### PR TITLE
New Dialog to Setup Data Entry dialogue

### PR DESCRIPTION
**Pull request by N-thony**
@lloyddewit @dannyparsons this is an empty dialog requested in issue #6401 that needs to be merged. Thanks

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet are you happy to approve and merge? thanks

**Comment by shadrackkibet** [comment]
@N-thony is this a sub-dialog? if yes then the naming should start with sdg...

**Comment by N-thony** [comment]
> @N-thony is this a sub-dialog? if yes then the naming should start with sdg...

@shadrackkibet it is a dialog.

**Review by shadrackkibet — APPROVED** [review]
Thanks for confirming.

**Pull request merged**
