### PR TITLE
Added import options for .dat file types

### LINKED ISSUE #6431: Importing multiple DAT file types
@rdstern says

> I think there is another issue on the File > Open.  We have data from 153 stations.  The files are actually csv files, but they have the extension dat.  Reading in as dat, you don't get the options to change the missing value code.  I thought things like this were always assumed to possibly read in as csv?  If not, then could you add dat files to be csv ones.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #6431.

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
I have added import options for DAT files. The DAT files will be read as csv when importing multiple files. The options are not available for single files because this was not previously implemented.

**Comment by lloyddewit** [comment]
@Patowhiz Thank you for working on this issue. 
I understand that this PR:
- only affects the behaviour when all the files in a directory are imported
- assumes that any `.dat` files in the directory are CSV formatted

Some questions:
- can we always assume that `.dat` files are CSV?
- what is the reason not to update the functionality for importing single files?
- for single file import, the code processes `.dly` files the same as `.csv` files; but it processes `.dat` files in a separate way. Is this correct?

Thanks for clarifying

**Comment by rdstern** [comment]
It is still not quite what is needed:  Here is the screen with a single file:
image

Now I need to change the default missing value code to -99999.  It is actually a csv file so this was all possible when I renamed the file to change the extension to csv.

This is being use for different countries on our AIMS Cameroon course.  Of course they can all change the extension, so I am seizing this opportunity to add to the flexibility of importing.

**Comment by Patowhiz** [comment]
> @Patowhiz Thank you for working on this issue.
> I understand that this PR:
> 
> * only affects the behaviour when all the files in a directory are imported
> * assumes that any `.dat` files in the directory are CSV formatted
> 
> Some questions:
> 
> * can we always assume that `.dat` files are CSV?
> * what is the reason not to update the functionality for importing single files?
> * for single file import, the code processes `.dly` files the same as `.csv` files; but it processes `.dat` files in a separate way. Is this correct?
> 
> Thanks for clarifying

@lloyddewit thanks for the questions.

> can we always assume that .dat files are CSV?
 yes we can assume that .data files are csv.

> what is the reason not to update the functionality for importing single files?
I see no reason, I think this is a good feature that went unnoticed. @rdstern recommends to have it done.

> for single file import, the code processes .dly files the same as .csv files; but it processes .dat files in a separate way. Is this correct?
yes, that is what is happening right now. I think this was done due to issues raised in closed issue #3433 back in 2017. I think it was anticipated that in future a reading .dat files will be implemented differently, though I'm not sure.

@dannyparsons has convinced me why its preferable to read the `.dat `files as `.txt` files. So I'll go ahead and implement this for single and multiple .dat files and also include its file type in the open file dialog. I'm also enabling the import options.

**Comment by Patowhiz** [comment]
@rdstern this is now ready for you.

**Review by rdstern — APPROVED** [review]
@Patowhiz great
@lloyddewit over to you.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
