### PR TITLE
Changing the package for natural splines in Climate>Compare>Seasonal Plot

### PR DESCRIPTION
**Pull request by mmulahvictor**
Fixes issue #5911
@africanmathsinitiative/developers this is ready for review
@shadrackkibet Can you look at this.

### CODE REVIEW

**Comment by N-thony** [comment]
> Fixes issue #5911 @africanmathsinitiative/developers this is ready for review @shadrackkibet Can you look at this.

@mmulahvictor I think to have done something similar on #6955. Please take a look.

**Review by rdstern — APPROVED** [review]
Looks fine

**Comment by lloyddewit** [comment]
@mmulahvictor @N-thony Should this be merged? or is it a duplicate of Pr #6955 ?
Please could you clarify and make a recommendation? thanks

**Comment by mmulahvictor** [comment]
@lloyddewit this seems to be a duplicate of PR #6955. I am closing this PR so that @N-thony can do the changes

**Comment by N-thony** [comment]
> @lloyddewit this seems to be a duplicate of PR #6955. I am closing this PR so that @N-thony can do the changes

@mmulahvictor you can leave it open and wait for @rdstern 's view.

**Comment by shadrackkibet** [comment]
Fixed in #7124

**Pull request closed without merging**
