### PR TITLE
View labels And Levels

### PR DESCRIPTION
**Pull request by shadrackkibet**
@africanmathsinitiative/developers this fixes display of output into the browser. Fixes part of #4324
This is ready for review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
Checking

**Comment by shadrackkibet** [comment]
@Patowhiz ?

**Comment by Patowhiz** [comment]
@africanmathsinitiative/developers this is ready to be merged. The change fixes the output.

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons @africanmathsinitiative/developers 
We had an extensive discussion with @shadrackkibet  and we had a few concerns / enhancements about this dialog. 
For instance checkbox **Show Variables Labels**, I think it will be less confusing if it were to be **Show Value Labels**. This will also make it consistent with dialog output.
@shadrackkibet has fixed the output window not showing up but the column generated for checkbox **Show Numeric Values** is simply stated as **Values**, this can be less confusing if it was stated as **Numeric Values** .

Looking further to the issue of labels, we also found in the column metadata grid, the column supposed to show the _labels of the values_ of a column was stated as **Labels** , I think it will be less confusing if its stated as **Value Labels**.

The images below illustrate what we thought could be a good addon: 

dlgviewlabels

dlgviewlabels output

column metadata

**Comment by rdstern** [comment]
On the main point, then if that is what it means, I am happy to change it to **Value labels**.  But if you look at the output, then there is also a column for the **Variable labels**, only you don't have any in this data set, and that is what I thought it referred to.  So before you change the name, can you check exactly what it does refer to?

**Comment by Patowhiz** [comment]
@rdstern  What is meant by **Variable labels** . Does it mean the labels of the variables(the columns of a data frame)?

In the output there is also a column which is named **Label** that refers to what I think is meant by **Variable Labels**

**Comment by rdstern** [comment]
That's right.  Each variable has a name, and also (possibly) a label.  In a survey the name is usually short and the label often then gives the survey question for this variable, e.g. Livstk as the name and "Does your household have any livestock?" as the label.  

Then (in the special case of factor columns they may have labels corresponding to each level.  For example None, Few, Many.  These are called Value labels.

So a question on a course might have a variable label "How did you find the length of this workshop?, to which the value labels could be Much Too Short, Too Short, OK, Too Long, Much Too Long.

They are both useful, but different.  In our data selector, if you hover over a column it shows the Variable label for that column.  SPSS allows you to choose whether you use the name or the Variable label.

**Comment by Patowhiz** [comment]
Exactly!, that's why we thought, changing 

**Show Variables Labels** to **Show Value Labels** for the view labels dialog
**Values** to **Numeric Values** for the view labels dialog output
**Labels** to **Value Labels** for the column metadata

Will make more descriptive and less confusing.
Then we can stick to such a naming convention in the entire Rinstant App where

Label will refer to this : 

> That's right. Each variable has a name, and also (possibly) a label. In a survey the name is usually short and the label often then gives the survey question for this variable, e.g. Livstk as the name and "Does your household have any livestock?" as the label.


And 
Value Labels will refer to this:

> Then (in the special case of factor columns they may have labels corresponding to each level. For example None, Few, Many. These are called Value labels.

Currently we have dialogs that are using the Label to refer to Value Label or Variable(Column) Label and this might be unclear to some until they are clear.

**Comment by Patowhiz** [comment]
Okay. That can be left the way it is.

**Comment by shadrackkibet** [comment]
@dannyparsons this is ready for merging.

**Comment by maxwellfundi** [comment]
@dannyparsons  this looks good too and its just simple changes.

**Pull request merged**
