### PR TITLE
Corrected the Import Dialog Auto-size setting

### LINKED ISSUE #7112: Import from File dialog is too wide
This has got wider from other changes. It needs AutoSize of the dialog set to False then it will be the correct size again.

@africanmathsinitiative/developers Can someone take this up?

### PR DESCRIPTION
**Pull request by Gioche6**
Fixes #7112

@africanmathsinitiative/developers , This is ready for review.
 @dannyparsons , I have set the Auto-size to false as you advised. Kindly review. Thank you.

### CODE REVIEW

**Review by shadrackkibet — DISMISSED** [review]

**Comment by lloyddewit** [comment]
@dannyparsons I tried to test this but I could not see any difference between the size of the Import Dataset in this branch and the master branch. You wrote issue #7112 so I assume that you know the background, please could you test/approve?
Thanks

**Comment by rdstern** [comment]
I also agree with @lloyddewit that I don't see any difference now from 7.3.1.  But also that it could still lose a bit of width.
image

Could you take the width back so this box just fits.  Check, though that there is no control that needs to be wider than this.  If there is, then leave the width as now.

**Review by rdstern — CHANGES_REQUESTED** [review]
comment made suggesting it be narrowed a bit still.

**Comment by Gioche6** [comment]
@rdstern I have checked and noted there's no control at the extra space. I have resized the width to get rid of the extra space. Kindly test thank you. 
@lloyddewit , this is ready for review.

**Review by rdstern — APPROVED** [review]
Looks good

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
