### PR TITLE
Bug fixed on the data frame selector control to select current data frame

### LINKED ISSUE #7371: Minor bug on the selector data frame control to remember the current data frame
The selector data frame control seems to not remember the current data frame, when you open the a dialogue when there is not dataset loaded in the dataview, and reopen the selector dataframe doesn't select the current dataframe by default or when you have different datasets `data1`, `data2`, and `data3`, with `data1` as current data in the `Data View` then open any dialogue, the selector dataframe for the first time will select `data1` by default then close the dialogue, delete `data1`, the current data may probably be `data2` or `data3`, then reopen the dialogue, the selector will not select the current data.
@rdstern @Patowhiz this is the issue I found with the selector and I'm trying to fix in PR #7370, it is not the same with issue #4712 which probably needs discussion before implementation or not.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7371 
@rdstern I have written the corresponding issue to this PR since it was not corresponding to issue #4712
@africanmathsinitiative/developers this is ready for review. Thanks.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@N-thony @rdstern  is this PR meant to make the dialogs automatically change to the selected sheet in the grid? 
That's how I seem to understand the issue. Not unless I'm mistaken.
I peeked at you code and I saw you have only changed `ucrReoGrid` . I would expect the change to include another data frame control.

**Comment by N-thony** [comment]
> @N-thony @rdstern is this PR meant to make the dialogs automatically change to the selected sheet in the grid? That's how I seem to understand the issue. Not unless I'm mistaken. I peeked at you code and I saw you have only changed `ucrReoGrid` . I would expect the change to include another data frame control.

Okay, thanks, it is probably not what I found, I will write an issue that is relative to this PR then.

**Comment by Patowhiz** [comment]
@N-thony @lloyddewit I'm looking into issue #7288 and #4712 which is related to issue #7371 that this PR intends to fix. I have a different approach which partly includes delinking the control from the `RLink` and making it use the data book structures.

**Comment by Patowhiz** [comment]
I'll also consult @N-thony regarding the same.

**Comment by rdstern** [comment]
@Patowhiz on this issue, and as someone who has often done the analysis on the wrong data frame, because I had forgotten to change it, I still roughly repeat my comment from #4712.  This is that I also like our simple rule that the dialogue "remembers" its previous settings.  They include the original data frame when it was last used.
Of course, if that data frame has been deleted, (or renamed?) then things might be different.  But otherwise I am ok that it remembers.
I sometimes look at a dialogue without a dataframe present.  Then I open a data frame.  Then I return to the dialogue, and there is no data frame there, because there wasn't the first time.  I am even happy with this.
But I would quite like to be alerted when my current data frame that I am looking at, is different from the one I last used in the dialogue.  Currently we alert users to the presence of a filter (or select) by putting row numbers in red.  Perhaps we could do the same with the data frame name?  Or, just put it in bold, or italic, or something?

**Comment by Patowhiz** [comment]
> @Patowhiz on this issue, and as someone who has often done the analysis on the wrong data frame, because I had forgotten to change it, I still roughly repeat my comment from #4712. This is that I also like our simple rule that the dialogue "remembers" its previous settings. They include the original data frame when it was last used. Of course, if that data frame has been deleted, (or renamed?) then things might be different. But otherwise I am ok that it remembers. I sometimes look at a dialogue without a dataframe present. Then I open a data frame. Then I return to the dialogue, and there is no data frame there, because there wasn't the first time. I am even happy with this. But I would quite like to be alerted when my current data frame that I am looking at, is different from the one I last used in the dialogue. Currently we alert users to the presence of a filter (or select) by putting row numbers in red. Perhaps we could do the same with the data frame name? Or, just put it in bold, or italic, or something?

@rdstern yes. That is exactly what I've been looking into.

**Comment by N-thony** [comment]
> @N-thony @lloyddewit I'm looking into issue #7288 and #4712 which is related to issue #7371 that this PR intends to fix. I have a different approach which partly includes delinking the control from the `RLink` and making it use the data book structures.

@Patowhiz I was thinking to look at it with @ChrisMarsh82 since he is around, but happy to discuss it together.

**Comment by N-thony** [comment]
> @N-thony @lloyddewit I'm looking into issue #7288 and #4712 which is related to issue #7371 that this PR intends to fix. I have a different approach which partly includes delinking the control from the `RLink` and making it use the data book structures.

@Patowhiz I was thinking to look at it with @ChrisMarsh82 since he is around, but happy to discuss it together.

**Comment by N-thony** [comment]
> @N-thony @lloyddewit I'm looking into issue #7288 and #4712 which is related to issue #7371 that this PR intends to fix. I have a different approach which partly includes delinking the control from the `RLink` and making it use the data book structures.

@Patowhiz I was thinking to look at it with @ChrisMarsh82 since he is around, but happy to discuss it together.

**Comment by Patowhiz** [comment]
@N-thony I have made the required changes in PR #7404.
Kindly review my changes. Thanks

**Comment by N-thony** [comment]
This is fixed in #7404

**Pull request closed without merging**
