### PR TITLE
Fixed bug related to reordering of data frame tabs in Data View

### PR DESCRIPTION
**Pull request by N-thony**
Fixes (partially) #7550
@rdstern I have made the change here that fixes the bug you are facing in the workshop, this will allow the reordering only when we do it. Please test it.
@lloyddewit please have a look.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@N-thony thanks for looking into this.
This PR addresses my https://github.com/africanmathsinitiative/R-Instat/pull/7508#issuecomment-1151038792  but does not address this [comment ](https://github.com/africanmathsinitiative/R-Instat/pull/7508#issuecomment-1151023372) when you use the reorder the dialog.
I'm happy that the critical problem has been addressed and we can use this in the short term. 
In the long term(later) we can refactor the approach used here after implementing the initial structures needed.

**Comment by N-thony** [comment]
> @N-thony thanks for looking into this. This PR addresses my [#7508 (comment)](https://github.com/africanmathsinitiative/R-Instat/pull/7508#issuecomment-1151038792) but does not address this [comment ](https://github.com/africanmathsinitiative/R-Instat/pull/7508#issuecomment-1151023372) when you use the reorder the dialog. I'm happy that the critical problem has been addressed and we can use this in the short term. In the long term(later) we can refactor the approach used here after implementing the initial structures needed.

Exactly

**Comment by lloyddewit** [comment]
@rdstern If you can test/approve, then we can merge, thanks

**Review by rdstern — APPROVED** [review]
As Patrick is happy I am approving

**Pull request merged**
