### PR TITLE
Added Trend keyboard and general changes to layout for the Hypothesis Tests dialog

### LINKED ISSUE #5816: Add trend keyboard to Model > Fit Model > Hypothesis Testing Keyboard
This could be done in parallel with #5810, which is a large task.  There will also be at least 2 other keyboards soon, on the DescTools and the Rcompanion packages.  They are not so easy.  This one is quite easy, because the keys can be in alphabitical order and almost every function in the package can be included.

Check, but I think, in each case the command is trend::key.test, e.g. trend::bartels.test unless I have stated otherwise.  Check with the trend package.
Keys:
1) **_bartels_**, with tooltip: A rank version of von Neumann’s ratio test proposed by Bartels
2) br, with tooltip:  The Buishand range test for change-point detection of a normal variate
3) bu, with tooltip: The Buishand U test for change-point detection of a normal variate
4) cs, with tooltip: The non-parametric Cox and Stuart trend test
5) csmk, with tooltip: The seasonal Mann-Kendall test under the presence of correlated seasons
6) lanzante, with tooltip: The non-parametric Lanzante test for a shift in the central tendency of
a time series
7) mk, with tooltip: The Mann-Kendall Trend Test
8) mmk (command is mult.mk.test) with tooltip: The multivariate (multisite) Mann-Kendall test
9) pcor (command is partial.cor.trend.test) with tooltip: The partial correlation trend test
10) pmk (command is partial.mk.test) with tooltip:  The partial Mann-Kendall trend test
11) pettitt with tooltip: Pettitt’s test for change-point detection
12) rrod with tooltip: The Fligner-Pollicello robust rank-order distributional test for location
13) ssens (command is sea.sens.slope) with tooltip: The seasonal Sen’s slope for linear rate of change
14) sens (Command sens.slope) with tooltip: Sen’s slope for linear rate of change and corresponding confidence interval
15) smk with tooltip: Seasonal Mann-Kendall trend test (Hirsch-Slack test)
16) snh with tooltip: The standard normal homogeneity test (SNHT) for change-point detection of a normal variate
17) wm with tooltip: The Wallis and Moore phase-frequency test
18) ww with tooltip: The non-parametric Wald-Wolfowitz test for independence and stationarity

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5816 and #5814

@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by rdstern** [comment]
@wyclife - this is looking good.
a) On the keys from the third row there is `:::` (i.e. 3 colons) rather than just 2.  In the bottom row it rises to `::::`.
b) the tooltip for mk has `Trend Test`, rather than `trend test`.  (All the other seem consistent - great.)
c) Put the `Clear` button before (and on the left, next to the `Help`), rather than underneath it.
d) Move the Try control slightly left, so it is aligned with the check boxes above and then it can also move upwards so it is next to the bottom row of the symbol keys.  Move the other keys at the left so they all align and also so that the dialogue becomes less deep.
e) Finally something new that I need to check with @dannyparsons.  In some commands we need to include the data frame name in the command.  Currently this can't be done, i.e. you can't click and Add the data-frame name.  If this is easy it would be useful to add - otherwise it should not holdup the merging, but can become a new issue.

**Comment by Wycklife** [comment]
@rdstern I have fixed the first 4 points above. @africanmathsinitiative/developers Could someone have a look at these changes.

**Comment by rdstern** [comment]
@Wycklife you have fixed the first 3 - here is the 4th

d) **_Move the Try control slightly left_**, so it is aligned with the check boxes above (if aligned now, then move them all a bit left) and **_then it can also move upwards_** so it is next to the bottom row of the symbol keys. Move the other keys at the left so they all align and also **_so that the dialogue becomes less deep._**

Ignore the final point (e) above for now.  I have discussed with @dannyparsons and will make a separate issue.

**Comment by Wycklife** [comment]
@rdstern Done. Kindly check a gain.

**Comment by Wycklife** [comment]
@rdstern That's fine.

**Comment by lilyclements** [comment]
@Wycklife would you mind updating this branch from the master copy?

**Comment by Wycklife** [comment]
@rdstern I have merged the changes made by @lilyclements  into this branch. Could you please check if the designer is now okay.

**Comment by lloyddewit** [comment]
@maxwellfundi I reviewed, it looks good and I''m happy to approve. Please merge, thanks

**Comment by lloyddewit** [comment]
@rdstern You already approved this. Please could you approve again so that we can merge? thanks

**Comment by lloyddewit** [comment]
@rdstern You already approved this. Please could you approve again so that we can merge? thanks

**Pull request merged**
