### PR TITLE
Deleting labels in the new column created in Calculator and Transform Dialogues

### PR DESCRIPTION
**Pull request by N-thony**
Fixes (partially) #7274 
@rdstern @shadrackkibet could you test? Thanks.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@N-thony this seems to work fine.  Well done.  Good one for @shadrackkibet to confirm as I think it completes our work with the mixture of factors and labels.  
I am pleased and relieved that we have done this.  I suggest it is a feature of R-Instat that isd both useful and also unusual in standard use of R.

**Comment by N-thony** [comment]
@lloyddewit how about this?

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony In your top comment above, you reference #7274. However, this is a PR not an issue. Did you mean to reference issue #7249 ? If so, please could you update your comment? Is issue #7249 fully resolved now?

**Comment by N-thony** [comment]
> @N-thony In your top comment above, you reference #7274. However, this is a PR not an issue. Did you mean to reference issue #7249 ? If so, please could you update your comment? Is issue #7249 fully resolved now?

@lloyddewit yes, it is fully resolved.

**Pull request merged**
