### PR TITLE
Reorder data frames

### LINKED ISSUE #4557: Reordering data frames
This now works in reogrid - just the same as in Excel.  But I wonder if it works for us, i.e. in the Instat object? When you reorder using reogrid it is just in the front end.  Does it also reorder in the metadata?  

Is this feature going to be a blessing or a curse?

### PR DESCRIPTION
**Pull request by shadrackkibet**
fixes  #4557

@rdstern please test this once PR #6865 is merged.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Please note, only column metadata do not update at the moment. I am investigating the problem.

**Comment by shadrackkibet** [comment]
@dannyparsons @ChrisMarsh82 when I reorder data frames currently from the dialog it only works in the data frame metadata but not in data view and column metadata.  It used to work in data view and data frame metadata before the paging changes were merged.  Kindly look into this. Perhaps just some insights then I can try to fix it.

**Comment by dannyparsons** [comment]
I hope this is just another symptom of the refreshing issues and this will also be taken care of, but good to check this once Chris resolves them.

**Comment by dannyparsons** [comment]
@ChrisMarsh82 I think this part of the code below from GridLink may have got lost in the translation, which would detect if the order needed to be changed.
```vb
        If bFoundWorksheet Then
            fillWorkSheet = grdCurr.GetWorksheetByName(strName)
        Else
            fillWorkSheet = grdCurr.CreateWorksheet(strName)
            grdCurr.AddWorksheet(fillWorkSheet)
            iCurrPosition = grdCurr.Worksheets.Count - 1
        End If

        If iNewPosition <> -1 AndAlso iNewPosition <> iCurrPosition AndAlso iNewPosition < grdCurr.Worksheets.Count Then
            grdCurr.MoveWorksheet(fillWorkSheet, iNewPosition)
        End If
```

**Comment by ChrisMarsh82** [comment]
@dannyparsons ok will add that in

**Comment by dannyparsons** [comment]
I think this is easy to solve, but it would change a core part of the refreshing so suggest it's high risk just before the release.

@ChrisMarsh82 Can we discuss this early next week?

**Review by rdstern — CHANGES_REQUESTED** [review]
It partially works:
a) In the column metadata window reorder is enabled and takes you correctly to the dialogue.  It is still disabled in the data window.
b) When the frames are reorded this seems to work in the data frame metadata, and the dialogue seems to remember the new order.
But the column metadata and data windows don't change the order.  I assume this might be a "refreshing" problem, but haven't found how to do that?

**Comment by rdstern** [comment]
@shadrackkibet this has been quiet for almost 3 months.  It now has conflicts.  It would be useful, and I assume you will be getting back to it?  Is there a problem?

**Comment by rdstern** [comment]
@shadrackkibet can this be closed now @N-thony is doing #7508?

**Comment by shadrackkibet** [comment]
Yes, please.

**Pull request closed without merging**
