### PR TITLE
new dialogue

### PR DESCRIPTION
**Pull request by Patowhiz**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  This new dialog is ready to be merged now

**Comment by dannyparsons** [comment]
If this is going to be a dialog to create, edit and delete sets then I think a different name is needed. Something like VariableSets.

**Comment by maxwellfundi** [comment]
Okay great. @Patowhiz  Please rename this to VariableSets

**Comment by dannyparsons** [comment]
Great looks good now.

**Pull request merged**
