### PR TITLE
Qc Temperature

### LINKED ISSUE #2392: Including the QC from Rclimdex and Rclimdex extra in R-Instat
[Aguilar-Nanjing-2013-Presentation2 QC R-CLIMDEX.pdf](https://github.com/africanmathsinitiative/Instat/files/663948/Aguilar-Nanjing-2013-Presentation2.QC.R-CLIMDEX.pdf)
[Manual_rclimdex_extraQC.r.pdf](https://github.com/africanmathsinitiative/Instat/files/663949/Manual_rclimdex_extraQC.r.pdf)

The quality control in R-Climdex is fairly clearly shown in the presentation, which is the first of the files above.  It is by Enric Aguilar, who works in this area.  It produces a whole set of files for each station, for users to examine.  It also calculates the 27 indices from WMO.

These indices are a separate dialogue for us.  They use the climdex-pcic package that is in CRAN.  I strongly suggest we make use of this package, even if we can produce those indices ourselves.  This is also the recommendation from one of the original authors, from Canada.

In contrast, the qc procedures are written in R, but are not a CRAN package and were written a long time ago.  I wrote to Enric (who visited Reading earlier and I also met in a subsequent workshop.) to ask his advice.  His reply was also sent to Patrick Parrish, from WMO, who we will meet in Reading in January.  It is below:

"First (suggestion from me) ) is to keep the results within the same software environment, rather than writing output files. : this is the way it should go. 100% agree. RClimdex was written 15 years ago (time flies); it started as Climdex, with excel files, and then the "R" was added, so there was a story of using external excel files. Besides, we were ensuring that computers with limitted resources could work. The extra-qc was a plugin done very quickly and I had no time to think of a better interface.

A couple years ago, I wrote a piece of code called quickqc.R, to extend the capabilities of extra-qc to whole networks and add a few more capabilities. I have a descriptive power point, only in Spanish, but I know this is not a problem in your capable team." 

[QUICKQC.pptx](https://github.com/africanmathsinitiative/Instat/files/663982/QUICKQC.pptx)

"Second is to broaden the checks to examine all climatic elements.

We did some attempts to do so for the UERRA project. I coded some QC for pressure data. There is no way you can use it, as it needs very specific data, but I am attaching it, as it can give you some ideas about what to look at. I know some other colleagues also coded QC for wind. I know that the guys at the SMN Argentina (Dr. Maru Skansi, mms@smn.gov.ar) did a tremendous work on this."

[quickqc_v2.0.zip](https://github.com/africanmathsinitiative/Instat/files/663985/quickqc_v2.0.zip)

So that is the basis for my suggestions below

### PR DESCRIPTION
**Pull request by shadrackkibet**
Fixes #2392

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is now ready for review and testing. Fixes #2392

**Comment by shadrackkibet** [comment]
@rdstern  Here is the screenshot of this dialog.
image

**Comment by rdstern** [comment]
Looks nice.  
I wonder about the New Column Name field.  I think I would have "New Column Prefix", because won't you usually have a number of columns you are generating, e.g. qc_diff, qc_same, etc?

**Comment by shadrackkibet** [comment]
If i have qc_diff, qc_same, etc? as defaults what would be the default name when more than one checkbox is checked? 
I am currently using an input textbox for saving like other climatic dialogs so this is not the prefix. This is also discussed here #4111

**Comment by rdstern** [comment]
That's the whole point.  When I use the dialogue I usually have more than one checkbox selected and then will be generating multiple logical columns.  That's why (at least for now) I would be giving them these fixed names.  So I would not mind if you didn't have that name field for now.  If the names are to be changed, (and hence not overwritten the next time the dialogue is used), then we need to change the column name in the data frame, once the dialogue is executed.

**Pull request merged**
