### PR TITLE
ANewDataFrameError

### LINKED ISSUE #4276: New Data Frame Error
I could not create a new data frame of more than 1000 rows in R-Instat 0.4.9. The attached error popped up 

newdataframeerror

### PR DESCRIPTION
**Pull request by Patowhiz**
@africanmathsinitiative/developers this is ready for review.
@dannyparsons conflicts with the other the other branch had been fixed but it still showed me a non fast forward change error so I have to create a new branch to fix it.

Relates to #4322 pull request.
Fixes #4276 issue.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
You dont need to create a new branch, when you get that error it means that you are pushing your commits to a more recent version  so you need to pull the incoming commits and then push your changes.

**Comment by Patowhiz** [comment]
@maxwellfundi okay I'll go ahead and close this one.

**Comment by maxwellfundi** [comment]
Am not sure you want to close this if you had copied your changes here. Just wanted to let you know how to circumnavigate the fast forward error in git

**Comment by Patowhiz** [comment]
Closed it because there is no need to have a new pull request for the changes. Your suggestion merged with my local repo and the new changes I had were committed succesfully.

**Comment by maxwellfundi** [comment]
Great, well done :-)

**Pull request closed without merging**
