### PR TITLE
Added option in Column Selection dialog to copy column selection into a separate data frame

### PR DESCRIPTION
**Pull request by shadrackkibet**
fixes #

This PR adds an option to copy column selection as a separate data frame.

image

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@shadrackkibet which issue does this PR fix? I'm assuming it also relates to issue #7196 as part of the Copy Special.

**Review by rdstern — APPROVED** [review]
Looks good and another useful facility.  I hope @lloyddewit can approve, so the next tasks with selects can be undertaken

**Review by lloyddewit — APPROVED** [review]
@shadrackkibet all looks good to me,  thanks

**Comment by lloyddewit** [comment]
> @shadrackkibet @rdstern which issue does this PR fix? I'm assuming it also relates to issue #7196 as part of the Copy Special.

@Patowhiz thank you for the comment.
@shadrackkibet @rdstern Please could you clarify how much this PR is related to issue #7196 , and if we can close this issue? thanks

**Comment by shadrackkibet** [comment]
As far as I know, this PR is adding a different feature into the Column Selection dialog. The Copy and Copy Special features in #7196 are some other features desired in R-Instat. As to whether they use the same function is a subject for assessment and discussion. Therefore #7196 should remain open.

**Comment by Patowhiz** [comment]
@shadrackkibet @rdstern so I'm assuming that this PR relates to an issue not created on GitHub but probably discussed elsewhere.
If so, I'm guessing it involves a user copying selected columns(entire rows of the columns, both visible and invisible) and pasting them to a new data frame within R-Instat. And I'm guessing partly from the PR title and the code done here.

@rdstern If so, it would be useful to know the menu item for this dialog and whether that menu item somehow should relate to issue #7196.

@lloyddewit @shadrackkibet I would suggest in future to tag related functionalities (issues) in GitHub, in my experience this helps a lot with implementation and reusing same functions(in this case R scripts) to achieve similar functionalities. The developers tagged on those issues can easily work together to design functions that can be used in related issues, hence better code quality and efficiency.

**Comment by rdstern** [comment]
It is item e in issue #7192.  I am not sure why #7196 is mentioned for this.

**Pull request merged**
