### PR TITLE
Updated the Prepare>Data Reshape>Merge title to Merge (Join)

### LINKED ISSUE #6904: Dialog names to change for consistency with Tidyverse
I have been looking at the dialogs in the "Data Reshape" sub-menu to check for consistencies with Tidyverse.
Some dialogs have names inconsistent with Tidyverse and the functions used.

1. `Prepare > Data Reshape > Merge` uses the set of `mutate-joins` functions in the `dplyr` package.
@rdstern would it make sense to change this dialog name to "Join" instead of "Merge"?

2. `Prepare > Data Reshape > Append` uses `bind_rows` from the set of `bind` functions in the `dplyr` package.
@rdstern would it make sense to change this dialog name to "Bind Rows" instead of "Append"?
(Additionally, the default naming structure for this dialog is currently calling a new data frame "Append_1". Elsewhere in the software we use lower case letters throughout so "append_1")

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #6904
@lloyddewit thanks for the quick call. As discussed I have updated the database and changed the dialogue text as requested in the corresponding issue from `Merge` to `Merge (Join)`. I have at the same time clearly demonstrated to @EstherNjeriLiberatta how to make such a change in the database and the required tool which `DB Browser for SQLite` for manipulating our database. This PR replaces PR #7108. Please take a look.

image

### CODE REVIEW

**Comment by lloyddewit** [comment]
@N-thony Thank you for helping @EstherNjeriLiberatta with this.
This PR only seems to fix part of issue #6904, so I changed your text above to 'Fixes (partially) #6904' so that the issue is not closed when this PR is merged.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern @EstherNjeriLiberatta @N-thony Should the menu option be consistent with the new dialog title?

image

**Comment by N-thony** [comment]
> @rdstern @EstherNjeriLiberatta @N-thony Should the menu option be consistent with the new dialog title?
> 
> image

@lloyddewit yes, and thanks for reminding me in #7118 to add the change here for Find/Replace dialogue.

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit @N-thony  Thank you.

**Comment by N-thony** [comment]
> > @rdstern @EstherNjeriLiberatta @N-thony Should the menu option be consistent with the new dialog title?
> > image
> 
> @lloyddewit yes, and thanks for reminding me in #7118 to add the change here for Find/Replace dialogue.

I have also changed the menu text
image

**Comment by N-thony** [comment]
@lloyddewit I resolved your comment. Please take a look. Thanks.

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit I'm very grateful. I wanted to also mention the second part of the issue seemed to be done already. 
We have checked on the database and found that Append has already been named to Append (Bind Rows) and dialog is currently calling a new data frame in lower case letters. Thanks.
image

image

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony @EstherNjeriLiberatta Thank you, good work. In your view, is issue #6904 now totally complete? Please confirm.
If yes, then you can change the first comment in this PR to 'fixes #6904' so that it closes automatically when this PR merges.

@rdstern Please could you test?

Thanks!

**Review by rdstern — DISMISSED** [review]
Looks fine

**Comment by N-thony** [comment]
@lloyddewit as you suggested, I have added the change requested in #7077, I changed the dialogue title on the form and in the database, same for then menu title to be consistent. I have made these with @Vitalis95 and explained how it works. Please take look. Thanks.
image
image

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern please could you test/approve again? thanks

**Review by rdstern — APPROVED** [review]

**Pull request merged**
