### PR TITLE
Improve Colour Option- for Ggplot2 Graph

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes partially #8282 
@rdstern , @N-thony  I added `Color Palette panel` in `colour tap` in `plot options`. Please can you have a look? I didn't work on part a) of this issue. I'm waiting for more explanation from @rdstern.

### CODE REVIEW

**Comment by rdstern** [comment]
@MeSophie that is starting to look really exciting.  I think I am assuming that there would be a Discrete and Continuous pull-down, in the same way as for the x-axis.  However, unless the detection can be made from the main dialog, Discrete would be the default, because that is much more commonly needed, compared to continuous.

Then, as with the x-axis tab, the rest of the colour tab would be different, depending on which option is used.  And I think that most of the palettes are for the discrete.

@N-thony maybe you can also help a bit with the code that is therefore needed, at least for the detection.  On my side there is a bit of "the blind leading the blind", because I am not sure I understand this aspect as well as I should.

**Comment by MeSophie** [comment]
@rdstern and I think @lilyclements  can also help on this. Here is a color tap in plot options sub dialog. After investigation i saw that for continuous options we can use `scale_fill_gadient`  or `scale_color_gradient` in **ggplot2** package and if we want to use the  **ggthemes** packages as the actual design we can use `scale_colour_gradient_tableau` or `scale_fill_gradient_tableau`. So are we keep the same ggthemes package for continuous option too?

Also can we change the checkbox **Use Fill/Color Palette** to two rdo **Use Fill Palette** and **Color Color Palette**? I think it is clearer this way.

**Comment by lilyclements** [comment]
@MeSophie interesting! I hadn't come across `scale_colour_gradient_tableau` or `scale_fill_gradient_tableau` before. This is really nice. What is the current suggestion under "Sequential"?
Are you suggesting we use `scale_colour_gradient_tableau` or `scale_fill_gradient_tableau` for the sequential tab now instead of what we currently use (for continuous only)? I think this looks really nice, and is a neat little option! I think it's a lot easier for the user too since they just have to pick which colour scale, instead of specifying a lower and higher (although that's nice too).

> Also can we change the checkbox Use Fill/Color Palette to two rdo Use Fill Palette and Color Color Palette? I think it is clearer this way.
I'm not sure what these options are currently meant to do, so I'll leave this one to @rdstern

**Comment by MeSophie** [comment]
@lilyclements when we have discrete value for Sequential, Diverging and Qualitative tab we use **scale_colour_brewer/scale_fill_brewer function** according to if you check the `UseFill/Color scale box` or not. the default value is unchecked and is passing **scale_fill_brewer function**. (reason why I think rdo button are better than the actual check box). The values of the palette are changing according to the tab you are. [Here](https://stackoverflow.com/questions/40290425/how-to-break-background-color-for-continuous-variable-in-ggplot2#:~:text=scale_fill_brewer%20is%20for%20a%20discrete%20scale%2C%20for%20a%20continuous%20scale,50%20scale%20as%20your%20data.&text=You%20can%20use%20RColorBrewer%3A%3A,brewer.) is the discussion about the function to use with the same palette for continous values. So for Continous I keep the same palette values and just change  **scale_colour_brewer/scale_fill_brewer function** to **scale_color_distiller/scale_fill_distiller**. Now my question is about the the function to use in the case we have` ggthemes tab and continous values`. I am going to design the  Fill Scale group box according to **scale_colour_gradient_tableau** if we will keep ggthemes package (we will still have ggthemes tab also for continuous ) or **scale_colour_gradient** that means we will change `ggthemes` package to `ggplot2` (the label of the `ggthemes `tab will change to `ggplot2` because scale_colour_gradient is a ggplot2 function) ?

**Comment by lilyclements** [comment]
@MeSophie thank you for explaining this all. 

About the rdo/checkbox - I agree that a radio button is less confusing for the user.
What currently happens if you want to apply it to both fill and colour? And what about if you want to apply one palette to colour, and another to fill?

## For the `ggthemes` option -
I'm going to just use the `*_colour_*` here, but this all applies to `*_fill_*` as well!

`scale_colour_gradient_tableau` is for continuous values as you correctly identified.
For discrete values the equivalent function is `scale_colour_tableau` -
* It has a `palette` which gives new palette options.
* This also has in it the options for `"regular"`, `"sequential"`, or `"diverging"` if we have a **factor** (regular = qualitative)
* It has the options `"regular"`, `"ordered-sequential"`, or `"ordered-diverging"` if we have an **ordered factor**. (regular = qualitative)
* The palettes are different depending on if we have a factor or an ordered factor!

There are two options we can do here, so @MeSophie I'll lay them both out to you and it would be great to know your opinion -

### Option One
We mix in the palettes that are in the ggplot2 package with the ggthemes package under each of the "Sequential", "Diverging", and "Qualitative" tabs.

Looking into `scale_colour_gradient_tableau`, the names of the palettes contain "sequential" or "diverging" (or neither, i.e., are for the qualitative) in them.
Then for `scale_colour_tableau` there's a whole set of different palettes and a `type` argument for qualitative, sequential, and regular (qualitative).

So we would be something like:

**Under Sequential**
We have a radio button which says "ggplot2 palettes" or "ggthemes palette"
If "ggplot2 palette" is selected, then we run what you currently have

If "ggthemes palette" is selected and it is **continuous**, then we can use the `scale_colour_gradient_tableau` function and offer only certain palettes (the ones that contain "sequential" in their name, e.g., "Blue-Green Sequential"

If "ggthemes palette" is selected and it is **discrete**, then we can use the `scale_colour_tableau` function, with `type = "sequential"` and offer the following palette options:
`Tableau 10, Tableau 20, Color Blind, Seattle Grays, Traffic, Miller Stone, Superfishel Stone, Nuriel Stone, Jewel Bright, Summer, Winter, Green-Orange-Teal, Red-Blue-Brown, Purple-Pink-Gray, Hue Circle, Classic 10, Classic 10 Medium, Classic 10 Light, Classic 20, Classic Gray 5, Classic Color Blind, Classic Traffic Light, Classic Purple-Gray 6, Classic Purple-Gray 12, Classic Green-Orange 6, Classic Green-Orange 12, Classic Blue-Red 6, Classic Blue-Red 12, Classic Cyclic.`

The same options would then be given for Diverging (`scale_colour_tableau(..., type = "diverging")`) and for Qualitative (for `scale_colour_tableau(..., type = "qualitative")`.

**However** the ggthemes option works for discrete only if the colour variable is **not an ordered factor**.
A different set of palettes is provided in R if it is an ordered factor.
I think this is too complex for now. @MeSophie If you disagree that this is too complex then that would be great to know, your opinion has much more value than mine, I'm just the "R-guy"!


### Option Two
Under "ggthemes", we keep using the `scale_colour_gradient_tableau` function for continuous variables, and offer all palettes for the user. 

If discrete, we offer the different functions and palettes within them. The discrete function options are given below. Some of these have additional palettes. I'm not sure if we want to offer these, or not! I've put a comment in for the ones with additional palette options - 

```
scale_color_calc
scale_color_canva # see canva_palettes for all 150 options! 
scale_color_colorblind
scale_color_economist
scale_color_excel
scale_color_excel_new # in the theme argument are lots of additional palettes
scale_color_few # palette = Light, Medium, or Dark
scale_color_fivethirtyeight
scale_color_gdocs
scale_color_hc # palette = "default" or "darkunica"
scale_color_pander
scale_color_ptol
scale_color_solarized
scale_color_stata # scheme = "s2color", "s1rcolor", "s1color", or "mono"
scale_color_wsj # palette	 = "rgby", "red_green", "black_green", "dem_rep", "colors6"
```

## Over to you!
@MeSophie what do you think? Hopefully I've understood the task and question. Your opinion here would be really useful - I've just laid out the R options, and how I think it can be fit in. Maybe you have another option to offer, or you have strong opinions on these! Thanks :)

**Comment by MeSophie** [comment]
Thank You @lilyclements very useful.
image
Here it will better to have two checked box than for the case where we can use the two functions.

And it is good to start with option two.
Concerning the list of functions available for discrete value do I need to include all of them in the dialog and let user to choose which function to use? because for now the discrete values are using **scale_color_colorblind and scale_fill_colorblind function**

**Comment by lilyclements** [comment]
> Here it will better to have two checked box than for the case where we can use the two functions.

@MeSophie I agree :) 

> Concerning the list of functions available for discrete value do I need to include all of them in the dialog and let user to choose which function to use? because for now the discrete values are using scale_color_colorblind and scale_fill_colorblind function

@MeSophie I think that's a good idea. So we can have them in a dropdown list, like "palettes", but instead they're the different functions for discrete (I'm not sure what we do about the palettes within the functions).

**Comment by MeSophie** [comment]
> > Here it will better to have two checked box than for the case where we can use the two functions.
> 
> @MeSophie I agree :)
> 
> > Concerning the list of functions available for discrete value do I need to include all of them in the dialog and let user to choose which function to use? because for now the discrete values are using scale_color_colorblind and scale_fill_colorblind function
> 
> @MeSophie I think that's a good idea. So we can have them in a dropdown list, like "palettes", but instead they're the different functions for discrete (I'm not sure what we do about the palettes within the functions).

Yes I think is the main challenge of this idea. Please I still need to understand how this palette values work. For example how know with palette use for color_colorblind ?
Then I can make a list of palette according to the  chosen function

**Comment by lilyclements** [comment]
> Yes I think is the main challenge of this idea. Please I still need to understand how this palette values work. For example how know with palette use for color_colorblind ?

@MeSophie good question. So some of these don't have any additional palette options, in which case you don't need to have any further options.
I imagine there being one drop down which takes the function from `ggthemes`, and then, when relevant, a second drop down taking the palette for that function.

The following have no additional palette options:
```
scale_color_calc
scale_color_colorblind
scale_color_economist
scale_color_excel
scale_color_fivethirtyeight
scale_color_gdocs
scale_color_pander
scale_color_ptol
scale_color_solarized
```

Then these do have additional palette options. This parameter name is usually "palette", but is a different name for some functions. I've given these below:


```
function name                   parameter name    parameter values

scale_color_few                  # palette        "Light", "Medium", or "Dark"
scale_color_hc                   # palette        "default" "darkunica"
scale_color_stata                # scheme         "s2color", "s1rcolor", "s1color", or "mono"
scale_color_wsj                  # palette	  "rgby", "red_green", "black_green", "dem_rep", "colors6"
scale_color_canva                # palette         write in R `ggthemes::canva_palettes` for all 150 options! 
scale_color_excel_new            # theme          "Atlas", "Badge", "Berlin", "Celestial", "Crop", "Depth", "Droplet", "Facet", "Feathered", "Gallery", "Headlines", "Integral", "Ion Boardroom", "Ion", "Madison", "Main Event", "Mesh", "Office Theme", "Organic", "Parallax", "Parcel", "Retrospect", "Savon", "Slice", "Vapor Trail", "View", "Wisp", "Wood Type", "Aspect", "Blue Green", "Blue II", "Blue Warm", "Blue", "Grayscale", "Green Yellow", "Green", "Marquee", "Median", "Office 2007-2010", "Orange Red", "Orange", "Paper", "Red Orange", "Red Violet", "Red", "Slipstream", "Violet II", "Violet", "Yellow Orange", "Yellow"
```

Does this make sense?

**Comment by MeSophie** [comment]
> > Yes I think is the main challenge of this idea. Please I still need to understand how this palette values work. For example how know with palette use for color_colorblind ?
> 
> @MeSophie good question. So some of these don't have any additional palette options, in which case you don't need to have any further options. I imagine there being one drop down which takes the function from `ggthemes`, and then, when relevant, a second drop down taking the palette for that function.
> 
> The following have no additional palette options:
> 
> ```
> scale_color_calc
> scale_color_colorblind
> scale_color_economist
> scale_color_excel
> scale_color_fivethirtyeight
> scale_color_gdocs
> scale_color_pander
> scale_color_ptol
> scale_color_solarized
> ```
> 
> Then these do have additional palette options. This parameter name is usually "palette", but is a different name for some functions. I've given these below:
> 
> ```
> function name                   parameter name    parameter values
> 
> scale_color_few                  # palette        "Light", "Medium", or "Dark"
> scale_color_hc                   # palette        "default" "darkunica"
> scale_color_stata                # scheme         "s2color", "s1rcolor", "s1color", or "mono"
> scale_color_wsj                  # palette	  "rgby", "red_green", "black_green", "dem_rep", "colors6"
> scale_color_canva                # palette         write in R `ggthemes::canva_palettes` for all 150 options! 
> scale_color_excel_new            # theme          "Atlas", "Badge", "Berlin", "Celestial", "Crop", "Depth", "Droplet", "Facet", "Feathered", "Gallery", "Headlines", "Integral", "Ion Boardroom", "Ion", "Madison", "Main Event", "Mesh", "Office Theme", "Organic", "Parallax", "Parcel", "Retrospect", "Savon", "Slice", "Vapor Trail", "View", "Wisp", "Wood Type", "Aspect", "Blue Green", "Blue II", "Blue Warm", "Blue", "Grayscale", "Green Yellow", "Green", "Marquee", "Median", "Office 2007-2010", "Orange Red", "Orange", "Paper", "Red Orange", "Red Violet", "Red", "Slipstream", "Violet II", "Violet", "Yellow Orange", "Yellow"
> ```
> 
> Does this make sense?

Yes @lilyclements  thank you.

**Comment by rdstern** [comment]
@MeSophie I get build errors.  Can you fix them?

**Comment by rdstern** [comment]
@MeSophie Many thanks.
My first test was to go to the scatterplot dialog.  This gives an error as follows:

image

I get the same error, whether, or not I have opened any data.
So I haven't checked further yet.

**Comment by rdstern** [comment]
@MeSophie as no answer, I tried again.  I used the diamonds and got a bar chart of 2 of the factors.  Reyturned and clicked on plot options and it crashed out.

**Comment by MeSophie** [comment]
> @MeSophie as no answer, I tried again. I used the diamonds and got a bar chart of 2 of the factors. Reyturned and clicked on plot options and it crashed out.

@rdstern Sorrry this branch has merge conflict. I created a new one I'm still working on it. I will let you know when it is ready to test

**Comment by rdstern** [comment]
@MeSophie many thanks for letting me know

**Comment by MeSophie** [comment]
image

@rdstern Please the detection here is according to which variable? X,Y Fill, or Color?

**Comment by rdstern** [comment]
@MeSophie please tell me when I can check the colours again.  I have tried from bar charts and then from line charts.  I get an error (and crash out) when I press for the plot options.
Do you need help from @N-thony or @Patowhiz ?

**Comment by Patowhiz** [comment]
@MeSophie what's the status of this, would be good to merge this for the next release. If it takes you more than a day, I'm on stand by this week for an online call to clarify any obstacles that are hindering you from making progress.
Thanks.

**Comment by MeSophie** [comment]
> @MeSophie what's the status of this, would be good to merge this for the next release. If it takes you more than a day, I'm on stand by this week for an online call to clarify any obstacles that are hindering you from making progress. Thanks.

@rdstern and @Patowhiz  It is almost done I just need some change from PR #8553. Now I can merge my branch with the branch of this PR.  I'm afraid to make a PR and have merge conflicts again sine I have also made Change on Plot Options sub-dialog

**Comment by rdstern** [comment]
@MeSophie the discrete option on the axes is now merged.  Can you now proceed to fix the conflicts here?

**Pull request closed without merging**
