### PR TITLE
Adding the compare column dialogue to the Climatic > Tidy and Examine menu

### LINKED ISSUE #6470: Two changes to the climatic menu on frm main
Could there be a new menu item in Climatic > File > Export to Climsoft.
It becomes the top of the 3 export dialogues and is ready for the dialogue to be written.  Perhaps the blank dialogue - for now - should also be included.
Then in Climatic > Tidy and Examine > Compare Columns.

This is simply another copy of the Prepare > Check Data > Compare Columns dialogue.  In the tidy and examine it is the 3rd menu item, so just below Daily Data Entry

### PR DESCRIPTION
**Pull request by mmulahvictor**
Fixes #6470
This PR adds the Compare Columns dialogue to the Climatic > Tidy and Examine menu. @africanmathsinitiative/developers this is ready for review
Related to #6723

### CODE REVIEW

**Comment by lloyddewit** [comment]
@mmulahvictor This PR has no changes. The normal process is to create a PR when you have changes that you want to push to master. Please could you ask @Ivanluv (or one of the other experienced developers) to help you follow the normal process?
Thanks

**Comment by lloyddewit** [comment]
@mmulahvictor Thank you for the commits, this Pr looks much better now.
Some requests:
- When you open a PR please add a couple of sentences describing what the PR does.
- Please state explicitly which issue(s) it tries to resolve (e.g. fixes issue #6470). The issue will then be closed automatically when the PR is merged
- Please also explicitly mention any PRs related to this PR (e.g. 'Replaces PR #6723.')

If you make the above changes, then I'll approve

@rdstern Please could you test? 

Thanks

**Comment by lloyddewit** [comment]
@mmulahvictor 'frmMain' has been changed by another PR so there are now merge conflicts. The easiest solution is probably to close this PR and make your changes in a new PR. Please let me know if you have any questions, thanks

**Comment by Ivanluv** [comment]
@mmulahvictor could you have this fixed .I also have the Pivot tables changes which contain form main changes

**Comment by lloyddewit** [comment]
Replaced by #6774

**Pull request closed without merging**
