### PR TITLE
Added facility to summarise sub-daily (hourly, synoptic, AWS) data to daily level

### PR DESCRIPTION
**Pull request by dannyparsons**
@africanmathsinitiative/developers this is ready for review

There's no specific issue. It adds a "Daily" button to the Climatic Summaries dialog in order to summarise sub-daily data to the daily level by summarising by date.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@dannyparsons this is great, so approved.  It has set us on a track we need to follow though.  This dialogue assumes a doy variable.  The dialogue that easily produces a doy variable only works currently with a Date variable, not a Date-time variable.  

I don't think any steps are difficult here, but we should take a few more soon - in the next couple of months?

**Comment by lloyddewit** [comment]
@dannyparsons I did not see @shadrackkibet 'c omment when I approved and merged (either my mistake or the PR was not refreshed). Do you wish to address his comment?

**Comment by dannyparsons** [comment]
It's sort of an existing issue but it should be fixed. I suggest another developer could take it up.

**Comment by lloyddewit** [comment]
> 
> 
> It's sort of an existing issue but it should be fixed. I suggest another developer could take it up.

Raise issue #6366

**Pull request merged**
