### PR TITLE
Made variables of class bigz or bigq to type S in the data view

### PR DESCRIPTION
**Pull request by N-thony**
Fixes (partially) #7493
@rdstern please have a look. Thanks

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
Looks fine to me

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony Thank you for the change.
I don't think that the PR title will mean anything to the user (in any case I didn't understand it!). So I assume this PR is an internal change that should not be in the release notes.
If you think this PR should be in the release notes, then please propose a user-understandable PR title.
Thanks

**Comment by N-thony** [comment]
Hi @ChrisMarsh82 @lloyddewit this PR was merged `Oct 6, 2022` but unfortunately the changes made here are not in the merged version. What could be the issue?

**Comment by lloyddewit** [comment]
> Hi @ChrisMarsh82 @lloyddewit this PR was merged `Oct 6, 2022` but unfortunately the changes made here are not in the merged version. What could be the issue?

@N-thony Thank you for spotting this.
I investigated. On 21 Oct, we merged PR #7924 which reversed the changes in this PR. This was an oversight, I don't think it was deliberate. It probably happened because PR #7924 replaced an older PR which was likely branched before PR #7894 was merged.

I suggest that we make a new PR and remerge these changes. What do you think?
thanks

**Comment by N-thony** [comment]
> > Hi @ChrisMarsh82 @lloyddewit this PR was merged `Oct 6, 2022` but unfortunately the changes made here are not in the merged version. What could be the issue?
> 
> @N-thony Thank you for spotting this. I investigated. On 21 Oct, we merged PR #7924 which reversed the changes in this PR. This was an oversight, I don't think it was deliberate. It probably happened because PR #7924 replaced an older PR which was likely branched before PR #7894 was merged.
> 
> I suggest that we make a new PR and remerge these changes. What do you think? thanks

@lloyddewit thanks for your investigation, I will open a new PR with these changes.

**Pull request merged**
