### PR TITLE
Prepare> Data Reshape> Unstack

### PR DESCRIPTION
**Pull request by shadrackkibet**
This PR doesn't address an existing issue. I explain the problem noticed and now fixed here. The automatic change of receiver focus is not working correctly on this dialog. That is because the Tab order is not sorted. @africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
- Also removed space between New data frame label and the save control.

**Comment by lloyddewit** [comment]
@Ivanluv  please could you review? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  this is ok

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Review by dannyparsons — APPROVED** [review]
Happy for this to be merged @lloyddewit

**Review by rdstern — APPROVED** [review]
Fine

**Pull request merged**
