### PR TITLE
Enhancing Windrose

### PR DESCRIPTION
**Pull request by maxwellfundi**
@rdstern I have fixed your issues on windrose except the color pallete one that seems to be taking bits of time. 
I am looking more onto it though. 

@africanmathsinitiative/developers this is ready for review for the #1908 issues that have been checked on the last comment on that issue by @rdstern

### CODE REVIEW

**Comment by stevenndungu** [comment]
reviewing this one

**Comment by maxwellfundi** [comment]
Great! Thanks @stevenndungu

**Comment by dannyparsons** [comment]
This looks good except you should be defining the speed cuts function on the main dialog, not the subdialog. Otherwise it doesn't exist outside the subdialog which is why you had to do the resetting in the subdialog. If you define it on the main dialog, pass it through to the sub dialog in SetRFunction, then everything will work in the same way as the wind rose function. The resetting with happen through setting the defaults on the main dialog.

**Comment by maxwellfundi** [comment]
@dannyparsons the issue is now fixed here

**Comment by dannyparsons** [comment]
Great, that looks much cleaner right!

**Comment by maxwellfundi** [comment]
Cool!

**Pull request merged**
