### PR TITLE
Mosaic plots dialog

### PR DESCRIPTION
**Pull request by dannyparsons**
@africanmathsinitiative/developers this is ready for review

Part of #4196

Note:
- You need to install `ggmosaic` package first. This will be added to package list in next release
- `Mosaic Plot Options` currently doesn't work as the geom is not yet added to our list of geoms. It will be added as part of #4196.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Testing this now.

**Comment by shadrackkibet** [comment]
Haven't been able to test this properly.  Using Dodoma dataset i filled up receivers as shown below. I click on mosaic plot options i get two this developer errors. When i click Ok and proceed the subdialog doesn't show any geom. If you proceed to click Ok i get a bug. Resetting the dialog after this, the dialog seems to work properly.

image

image

**Comment by rdstern** [comment]
It is good you are trying that on something like the Dodoma set.  It should work, so it is good you found that problem.  The results will be boring with the data as they stand.  

In this set of data try the logical calculation for rain days and then you have another factor.  You could use the date variable to get quarters of the year and try those instead of the months.  You could also get factors (or logical) by doing the same sort of calculation on the temperature data, i.e. splitting into 2 groups and on sunshine say > 5 hrs) in the day.

You could take the years and use the recoding of a factor into Early, Middle, Late.  

This will give you lots of factors to play with.

**Comment by maxwellfundi** [comment]
@shadrackkibet  thats because the layer options subdialog is not connected properly at the moment. I am working to adding the geom_mosaic on the list of geoms then that should be okay.

**Comment by shadrackkibet** [comment]
Aha! i see that. Thanks

**Comment by dannyparsons** [comment]
A survey type dataset with many factors would be better to test this with e.g. `efc` from R library or any of the procurement datasets, which was the motivation for getting this working now.

**Pull request merged**
