### PR TITLE
Further improvements to the front menu

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes issue #9058 
@rdstern this is ready for review, but I will also invite @rachelkg to check if this in now ok.

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@Fidel365 thanks for adding the Online bit.  
Now I'm not good at this spacing stuff and @N-thony .  But I would like this initial screen to look as professional as possible.
There seems to me to be a bigger space before the Advanced section, compared to the others.
And is the spacing between the 3 items in Advanced, the same as those between the Help items?  And the Paste data - is that exactly the same space below the items as the other?
@Fidel365 you  were really good at making the calculator keyboards much neater.  Can you have a similar go at the spacing here?
This is important, because it is going to be visible at the start every time anyone uses R-Instat.  And I'm keen that we give a really good initial impression.

**Comment by Fidel365** [comment]
@rdstern have a look at the recent channges.

**Review by rdstern — COMMENTED** [review]
@Fidel365 I think that looks much better now.  Many thanks.
A trivial point.  The `Restore Data from Backup...` needs the 3 dots.  And I take the opportunity to delete the `or Log`, so it is a simpler message.
@rachelkg could you also cast your critical eye over this, before it is merged - though changes could also happen later.

**Review by rdstern — APPROVED** [review]
@Fidel365 perfect - I like it.  @N-thony over to you to check and merge.  Maybe @rachelkg will comment before?, if not, then don't wait.  I am keen to have this new screen

**Pull request merged**
