### PR TITLE
Added nlog

### PR DESCRIPTION
**Pull request by ChrisMarsh82**
Added nLog for log files. 
Files will be dated within logs folder next to .exe
Logs will be kept for 5 days before being deleted
Currently, only one log is used ("R-Instat started")
We can edit the log config from individual machines if needed i.e. need to Trace an error.

### CODE REVIEW

**Review by lloyddewit — CHANGES_REQUESTED** [review]
@ChrisMarsh82 Thank you for this upgrade.
I'm happy to approve all the updates in the `instat` folder.
I assume that all the files in the `packages` folder are the result of installing `NLog` from NuGet.
Historically we have stored some 3rd party NuGet packages in our GitHub repo but this is bad policy because it bloats the repo.
Currently, when a PR requires a new NuGet package, we update the `.gitignore` file. There's an example in PR #7853.
If I misunderstood, then please let me know, thanks

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@ChrisMarsh82 Thank you for the changes.
this PR is vulnerable to merge conflicts. I'd like to merge asap.
Do you think it's safe to merge now? Or is there something that @rdstern could usefully test?
Thanks

**Comment by rdstern** [comment]
@ChrisMarsh82 or @lloyddewit when I synch the latest version I now get the following errors 

image

Should I worry?  Is there anything I should do?

I still seem to be able to start fine.

Roger

**Comment by ChrisMarsh82** [comment]
You will need to a nlog to your nuget packages.

**Pull request merged**
