### PR TITLE
Enabled viewing of multiple R help maximised windows in Import from Library dialog

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes @rdstern comment https://github.com/africanmathsinitiative/R-Instat/issues/8189#issuecomment-1685168424

@rdstern quoted comment 

> @Patowhiz I have just managed to crash R-Instat - but I was being a bit ambitious. I have a maximised window open and I decided to keep it open for later. Then I used File > Open From Library and the R-Help - which also uses the maximised window. It seems this isn't (yet?) possible?

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@Patowhiz I think this may be 50%, which is already good.  A major dialog I have been using is Help > Package Documentation.  That's partiocularly where I hoped I could use a back button, and hopefully not crash.  When I use it twice I still get the following error.

image

I suspect you may not yet have changed the window from here?

**Comment by Patowhiz** [comment]
@rdstern, I have now fixed the bug.

**Review by rdstern — APPROVED** [review]
@Patowhiz it is great now.  Perhaps I was missing this last time, but now anyway in the Package Documentation I can a) have multiple pages open and b) go back to the index, either from the bottom of the page, or right-clicking and using Back!

@lloyddewit I understand the wide data frames needs to be mergewd first.  These are good improvements.

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit this PR does not depend on any other PR. Thanks.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
