### PR TITLE
Enabled Climatic Data Entry menu

### PR DESCRIPTION
**Pull request by N-thony**
@maxwellfundi I have created this PR to enable the Climatic>Data Entry menu and avoid conflicts.

### CODE REVIEW

**Review by maxwellfundi — APPROVED** [review]

**Review by Patowhiz — APPROVED** [review]
This looks good

**Review by shadrackkibet — APPROVED** [review]
I am approving for merging so that @rdstern can test PR #6301

**Comment by dannyparsons** [comment]
We need to have other ways for testers to check new dialogs because we shouldn't be enabling and showing menu items in the master branch before a dialog has been tested and merged. These may creep in to released versions unknowingly which then look unprofessional in the software. The master branch should be a stable version of the software, which shouldn't have half-done features included.

I suggest we have a process for testers to access new dialogs by making a simple change to their local branch e.g. enable the menu item or temporarily change a toolbar icon to access the new dialog, for simplicity.

**Comment by shadrackkibet** [comment]
Can we have this as something to discuss with everyone during the meeting tomorrow? it doesn't only concern the developers it is for all. It's something I have also been thinking about.

**Pull request merged**
