### PR TITLE
Bug fix on try control giving unwanted warning in the output window

### PR DESCRIPTION
**Pull request by shadrackkibet**
@lloyddewit this is a fix to avoid a warning message in the output window when debugging. You might have noticed that there is a warning on the compilation as shown in the below screenshot.
image
 
Investigations show that this originates from a warning in `ucrTry` line 217.
image

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is ready for review.

**Review by lloyddewit — APPROVED** [review]
@shadrackkibet I am very happy to see this warning disapear :)
I tested with the calculator dialog:
- entered invalid calculation
- pressed try
- pressed '...' to view details
- pressed ctrl-enter to exit popup

Everything worked correctly

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Comment by lloyddewit** [comment]
> 
> 
> @africanmathsinitiative/developers this is ready for review.

no longer needed

**Comment by shadrackkibet** [comment]
> @shadrackkibet I am very happy to see this warning disapear :)
> I tested with the calculator dialog:
> 
> * entered invalid calculation
> * pressed try
> * pressed '...' to view details
> * pressed ctrl-enter to exit popup
> 
> Everything worked correctly

Thanks for testing.

**Comment by shadrackkibet** [comment]
@rdstern?[](url)

**Review by rdstern — APPROVED** [review]
Good

**Comment by Patowhiz** [comment]
Another relatex annoying warning is when opening the design view of some dialogs. This is caused by visual studio running commands even in design mode and finding nulls due to absence of connection to R. This could be addressed in another PR. It's more or less 2 lines of code being placed in strayegic places to detect whether the environment is in design mode or running mode.

**Comment by lloyddewit** [comment]
@shadrackkibet Thanks for adding the `bug` label and changing the title. I added the `skip-release-notes` label because I didn't think this fix was relevant for users. Your title was good, I just adjusted it to make it more consistent with other recent merge titles.

**Comment by lloyddewit** [comment]
> 
> 
> Another related annoying warning is when opening the design view of some dialogs. This is caused by visual studio running commands even in design mode and finding nulls due to absence of connection to R. This could be addressed in another PR. It's more or less 2 lines of code being placed in strayegic places to detect whether the environment is in design mode or running mode.

@Patowhiz Thanks for the suggestion. I rarely work on the dialogs so I don't experience this annoyance. If you think that the fix is simple enough to be worthwhile you could raise an issue.

**Pull request merged**
