### PR TITLE
Enhanced Climatic Boxplot

### PR DESCRIPTION
**Pull request by Muthenya**
@dannyparsons please let make get your take on the following changes.

### CODE REVIEW

**Comment by Muthenya** [comment]
@africanmathsinitiative/developers please review this.

**Comment by Muthenya** [comment]
@africanmathsinitiative/developers ?

**Comment by maxwellfundi** [comment]
Reviewing this @Muthenya

**Comment by Muthenya** [comment]
@maxwellfundi please have a look at this again.

**Comment by maxwellfundi** [comment]
@Muthenya This loos quite good now. However, When am on jitter, or Violin and close the dialog, when I reopen the dialog then the layer options button still says Boxplot options. You can see how i fixed that for the main boxplot dialog.

**Pull request merged**
