### PR TITLE
Sorted out a developer error when opening fill missing values dialog

### LINKED ISSUE #6924: developer error on Fill Missing Values dialog when opening the dialog the first time
This developer error appears just once on first opening:
image

@shadrackkibet Please assign to someone working on this as a high priority for the latest version.

### PR DESCRIPTION
**Pull request by Gioche6**
Fixes #6924

@africanmathsinitiative/developers , This is ready for review
@shadrackkibet , I have fixed the developer error. Kindly Review it.

### CODE REVIEW

**Comment by rdstern** [comment]
@Gioche6 which issue does this resolve?

**Comment by Gioche6** [comment]
@rdstern, I have Indicated the issue. Thank you for raising that concern.

**Comment by Gioche6** [comment]
@shadrackkibet . Kindly review, Thank you

**Review by shadrackkibet — APPROVED** [review]
@dannyparsons this is now sorted out. Over to you.

**Review by dannyparsons — APPROVED** [review]

**Pull request merged**
