### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@lloyddewit I am not assuming anything is needed from me on this?

**Comment by lloyddewit** [comment]
@rdstern Correct, nothing needed from your side for this PR. 
CrowdIn will push updates to this PR automatically. At a sensible point, we can merge this PR and I can make a new translations database for @berylwaswa to test.

**Comment by lloyddewit** [comment]
@N-thony As discussed, in dlgStringHandling, the new English text is just 'Count'.
Therefore CrowdIn should translate 'Count' to 'Compte'.
We should not change the translation of 'Word Count'.
Does this make sense?

image

**Comment by ChrisMarsh82** [comment]
@rdstern @dannyparsons do we want to merge this?

**Pull request merged**
