### PR TITLE
Empty clsPopup

### PR DESCRIPTION
**Pull request by Patowhiz**
@lloyddewit @maxwellfundi this is an empty `class` meant to hold the code that will be creating the popup used in several dialogs. 

Since I last created such a popup for the comment section, github issues have been created demanding more use of it (currently there is another dialog that needs this feature outlined by @rdstern in issue #5596 and possibly more will arise). Because of this we had discussed with @dannyparsons to have this as a reusable component that can be used in any dialog without much of re-implementation( and copy paste). Check out more about this `component` in issue #5876 . 

So I have added an empty class so that this can be merged quickly and avoid conflicts incase another item is added to the R-Instat `solution`. After this is merged I'll push the code needed to create the actual popup and demonstrate how this `class` can be used to dynamically create the `component`.

### CODE REVIEW

**Comment by Patowhiz** [comment]
I thought about this and realized that this will not have designer and resx. It's just a class that will dynamically create the GUI during runtime.  The size, controls of this "component" are only know by the callers of this class. That's why I used cls and not sdg,dlg,ctrl. I've actually already implemented it and pushed the commits on a separate PR.

**Comment by Patowhiz** [comment]
You can check out it's Implementation on PR #5878. I'm still happy to rename it though, if you still strongly think that the prefix should change.

**Comment by lloyddewit** [comment]
@rdstern or @maxwellfundi This is a placeholder and there's nothing to test here. Please could one of you approve so that this PR can be merged? Many thanks

**Comment by Patowhiz** [comment]
@lloydewit I don't know of any classes like this one In R-Instat no. If classes had been arranged into  packages(namespaces) I would have put it under the UI package.

**Pull request merged**
