### PR TITLE
DB Translation for Describe menu

### LINKED ISSUE #8053: French DB Translation Issues in Describe Menu
Pulls Requests will be made to fix issues relating to the incorrect translations for the describe menu. 
other areas will added as we move along. 

@N-thony, @lloyddewit is this ok for you

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes partly #8053
Database translation changes for Summary Tables
image

Database translation changes for Describe two variable Graphs
image

Database Translation for Bar and Pie Chart
image

### CODE REVIEW

**Comment by derekagorhom** [comment]
image
Database Translation for Recode Numeric Dialogue

**Comment by derekagorhom** [comment]
Database Translation for Recode Factor Dialogue
image

**Comment by lloyddewit** [comment]
@derekagorhom thank you for the changes. When you'd like to merge, just let me know, thanks.

**Comment by derekagorhom** [comment]
@lloyddewit you can merge this PR, i am currently working on the Transform keyboard for the calculator so i will make a new PR after that

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
