### PR TITLE
Added a new keyboard (Factor) to the calculator

### LINKED ISSUE #5504: Factor keyboard for the calculator
This is such a good idea that I am boldly suggesting it for Version 0.5.4, i.e. even by the time of the Cameroon AIMS course - though it certainly isn't vital!
I am also suggesting @Wycklife, because he has become expert in adding keyboards to the calculator.  But he may prefer different tasks?  In which case he could support whoever does the work.
We have a **_dates keyboard_** and a **_character keyboard_**.  I propose a **_factor keyboard_** be added.  I suggest it should go after Summary and before Strings (Character).  It should then go through the **_forcats package_** and will provide some very nice features.  Eventually we should also adapt the factor menu, but this should be quite quick and could be extremely useful.
Here is my proposed keyboard:

factor, anon, concat, collapse
cross, drop, expand, add_na
inorder, infreq, innum, lump
match, other, recode, relevel
reorder, reverse, shift, shuffle

This omits count, related, unify, and unique that don't (I think) return a single variable - at least of the right length.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5504 
@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by Wycklife** [comment]
@rdstern It's done. You may have a look at it. I'm happy to make any proposed changes.

**Comment by rdstern** [comment]
@Wycklife that's great.  I'll look later "today".  I am half-a-day behind you!

**Comment by Wycklife** [comment]
@rdstern Okay

**Comment by maxwellfundi** [comment]
@volloholic  great, merging it to master now.

**Pull request merged**
