### PR TITLE
Adding drop argument into facet_wrap and facet_grid - Plot options subdialog

### LINKED ISSUE #6083: Add drop parameter to facets on Plot Options subdialog
`facet_wrap()` and `facet_grid()` have a `drop` parameter: 

> If TRUE, the default, all factor levels not used in the data will automatically be dropped. If FALSE, all factor levels will be shown, regardless of whether or not they appear in the data.

This is a useful option to have, especially when filtering. I suggest this is added to the Facets tab on the Plot Options subdialog as a checkbox: "Drop empty factor levels". Default is checked as in R.

@africanmathsinitiative/developers can someone take this up? @maxwellfundi could also support this

### PR DESCRIPTION
**Pull request by shadrackkibet**
Fixes #6083 @africanmathsinitiative/developers this is ready for review. 

- Added handles on load subroutine
- Added drop checkbox, aligned controls and sorted Tab order
- Added `drop` argument into facet wrap/grid

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv please could you review? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  this is looking okay

**Review by dannyparsons — APPROVED** [review]
The change looks sensible to me. Assuming it has also been tested by someone by actually compiling and running the dialog then happy to approve.

**Comment by lloyddewit** [comment]
@rdstern Please can you test? thanks

**Review by rdstern — APPROVED** [review]
Great.  Seems to work fine

**Pull request merged**
