### PR TITLE
Small improvements to the Prepare > Check Data > Duplicates dialog

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes issue #7299
Small changes in the duplicates Dialogue

Selected Variables has become the first button, and hence the default when you first use the dialogue. The Data Frame is then second. The Successive values remains the last button.
And the pull down has the first entry as Index.

@Patowhiz  and I will make a new PR for the database changes recommended by @lloyddewit  in #7305

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
I really did think this was only a small task:
image
I am keen that the option titled Index Number of Duplicates should have Index as the default.  It still has Count.
I changed it to Index and it works fine.  Then the screen shot show what happens when I return.  It has changed back to Count.  It is supposed to remember the previous setting.
I notice you have changed Index to be the first of the 2 options, where it was Count before.  That's fine, but it isn't sufficient.

**Comment by derekagorhom** [comment]
Hello @rdstern i have done all these changes on the PR, but they do not show because of the database Translation, that is why we will make a PR for the database translation to correct this PR

**Comment by Patowhiz** [comment]
@lloyddewit @rdstern,  @derekagorhom and I have created PR #7363 that contains the required translation changes. Once merged this will be ready for review. 
Thanks

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom and @Patowhiz I don't understand why this change is causing so many problems.
image

In this option Count is still given as the default (Though Index is the first of the two options.
And if I change to Index, then it does it fine.  But when I return to the dialogue it still has returned to count.

If this continues, perhaps instead we should have a 4th option for the radio button.  But I really don't know why Index couldn't be the default, and why it can't remember the setting.  That's what we usually do?

**Comment by derekagorhom** [comment]
@rdstern sorry for the delay, PR #7363 will solve the translation issues with this PR

**Comment by Patowhiz** [comment]
@rdstern you may have to wait for the translation PR #7363 to be merged. @lloyddewit is aware of that too.

**Comment by derekagorhom** [comment]
@rdstern could you test this again, i merged the approved PR #7363 to this and it seems to work fine now

**Review by rdstern — APPROVED** [review]
Great!

**Review by lloyddewit — CHANGES_REQUESTED** [review]

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern I made a small change that should not affect the functionality. If you test/approve again, then we can merge.
Thanks!

**Review by rdstern — APPROVED** [review]
Great

**Pull request merged**
