### PR TITLE
Three Variable modelling Dialogue

### LINKED ISSUE #3088: Three-Variable Modelling Dialogue
I could not get to use the above-mentioned dialogue to fit a model with two predictors. After specifying both the first and second predictors, the dialogue fitted the second predictor only ignoring the first. I have tried this with several datasets including the ExperimentalSurveyData.RDS located in the Instat collection library. I was trying to fit village and variety to the yield.

### PR DESCRIPTION
**Pull request by stevenndungu**
@africanmathsinitiative/developers  this is ready for review. Fixes #3088

### CODE REVIEW

**Comment by stevenndungu** [comment]
While everything looked fine, there was a small issue with parameter positions. Such that the variables for the two receivers were set to the same position in the function. This led to overwriting second variable passed by the latter.
@jkmusyoka this sorts outs the problem you raised earlier.

**Comment by Lunalo** [comment]
@dannyparsons 

This ready for merging

**Comment by AlexSananka** [comment]
@stevenndungu great that you spotted this quickly,I have tested it and now works perfctly.
@dannyparsons this is ready for you.

**Comment by dannyparsons** [comment]
Great, well done for fixing this and thanks to those who are testing.

**Pull request merged**
