### PR TITLE
Added menu for Setup data entry dialog

### PR DESCRIPTION
**Pull request by N-thony**
@lloyddewit this PR adds a menu for Setup Data Entry dialog.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@lloyddewit this PR adds a menu item to frmMain. @rdstern and I need it to test and add to implementations done by @N-thony

**Comment by Patowhiz** [comment]
@lloyddewit it would be helpful if it could be merged before conflicts arise.

**Review by lloyddewit — CHANGES_REQUESTED** [review]
This menu option will currently open an empty dialog. Normally, we should not have this user behaviour on the main branch.
Please could you set the new menu option's visibility to false? You could then set the menu option's visibility to true in the branch where you implement the Setup Data Entry dialog. The chances of a conflict on `frmMain` should be small.
Does this make sense? if not, then I'm happy to discuss
Thanks

**Comment by N-thony** [comment]
> This menu option will currently open an empty dialog. Normally, we should not have this user behaviour on the main branch.
> Please could you set the new menu option's visibility to false? You could then set the menu option's visibility to true in the branch where you implement the Setup Data Entry dialog. The chances of a conflict on `frmMain` should be small.
> Does this make sense? if not, then I'm happy to discuss
> Thanks

@lloyddewit I would prefer to make it disable instead of visible false.

**Comment by lloyddewit** [comment]
@N-thony disabled is also OK

**Comment by N-thony** [comment]
@lloyddewit this is ready now.

**Comment by shadrackkibet** [comment]
Disabled gives an impression to the user that they have to do something for it to be enabled. I would prefer setting visibility to false.

**Review by maxwellfundi — APPROVED** [review]
@lloyddewit over to you

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
