### PR TITLE
Add Reducing Evaporation to the R-Instat Water Balance

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes Partially #8352 
@rdstern , @lilyclements  I added the reduicing evaporation for End of Rain Dialog. Please check it.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@MeSophie this is good progress I think.  I have sent a version of the dodoma data on skype, that you might like to try.
a) The function in the Transform dialog seems to work, but not if there are missing values.  It needs to be able to cope with the missing data, simply giving missing for the water column.
b) The result is produced in a way that is too accurate in the sheet.  you could round it to 2 decimals.  Otherwise, with the usual number of significant figures we get very small values, see below:

image


b) In the End of the season dialog there seem to be (at least) 2 problems.  The names of the columns are now giving end of the rains, when they seemed fine before.  Here is the dialog:

image




The calculations seems to work - at least without missing values, but giving the wrong answers.     The answers we want are easy to check, because I tried them on the data file after I had used the trainsform.  So I can see when (in each year) they drop below the limits I set.  I use about 5 typically as the end point, but try anything you like.

**Comment by MeSophie** [comment]
@rdstern  the dialog to check is just **End of Rain** dialog. I fixed the first problem concerning the checkboxes. I still need some R code from @lilyclements for transform dialog.
If the End of Rain dialog is giving the wrong answer, it means the code is not correct. So @lilyclements  Please can you check that the code I'm supposed to have is this? Specially line 2 and 4.

```
rain_min <- instat_calculation$new(type="calculation", function_exp="ifelse(test=is.na(x=rain), yes=0, no=rain)", result_name="rain_min", calculated_from=list("dodoma"="rain"))
wb_min <- instat_calculation$new(type="calculation", function_exp="Reduce(f=function(x, y) pmin(pmax(x + y - WB_evaporation(x, 0.5, 100, 5, y), 0), 100), x=tail(x=rain_min - 5, n=-1), init=0, accumulate=TRUE)", result_name="wb_min", sub_calculations=list(rain_min))
rain_max <- instat_calculation$new(type="calculation", function_exp="ifelse(yes=100, test=is.na(x=rain), no=rain)", result_name="rain_max", calculated_from=list("dodoma"="rain"))
wb_max <- instat_calculation$new(type="calculation", function_exp="Reduce(f=function(x, y) pmin(pmax(x + y - WB_evaporation(x, 0.5, 100, 5, y), 0), 100), x=tail(x=rain_max - 5, n=-1), init=0, accumulate=TRUE)", result_name="wb_max", sub_calculations=list(rain_max))
wb <- instat_calculation$new(type="calculation", function_exp="ifelse(test=(wb_min != wb_max) | is.na(x=rain), yes=NA, no=wb_min)", result_name="wb", sub_calculations=list(wb_min, wb_max))
conditions_filter <- instat_calculation$new(type="filter", function_exp="(wb <= 0.5) | is.na(x=rain)", sub_calculations=list(wb))
grouping_by_station_year <- instat_calculation$new(type="by", calculated_from=list("dodoma"="year"))
doy_filter <- instat_calculation$new(type="filter", function_exp="doy_366 >= 1 & doy_366 <= 366", calculated_from=calc_from_convert(x=list(dodoma="doy_366")))
end_season <- instat_calculation$new(type="summary", function_exp="ifelse(test=is.na(x=dplyr::first(x=wb)), yes=NA, no=dplyr::first(x=doy_366))", result_name="end_season", calculated_from=list("dodoma"="doy_366"), save=2)
end_season_date <- instat_calculation$new(type="summary", function_exp="dplyr::if_else(condition=is.na(x=dplyr::first(x=wb)), true=as.Date(NA), false=dplyr::first(x=date))", result_name="end_season_date", save=2)
end_of_season_combined <- instat_calculation$new(type="combination", manipulations=list(conditions_filter, grouping_by_station_year, doy_filter), sub_calculations=list(end_season, end_season_date))
data_book$run_instat_calculation(calc=end_of_season_combined, display=FALSE)
rm(list=c("end_of_season_combined", "conditions_filter", "wb", "wb_min", "rain_min", "wb_max", "rain_max", "grouping_by_station_year", "doy_filter", "end_season", "end_season_date"))
```

**Comment by lilyclements** [comment]
Line 2: `x=rain_min - 5` not `x = rain_min`

@MeSophie this is looking good. One comment on lines 2 and 4 is that you have

`x=tail(x=rain_min - 5, n=-1)`

But I believe that we want

`x = tail(x = rain_min, n = -1)`

The missing values problem is a good point. That is hopefully just something for me to fix in the `WB_evaporation` function

**Comment by lilyclements** [comment]
@rdstern is the issue with missing values occurring for the End of Season dialog as well? I cannot seem to replicate it.

(It should be that missing values are treated the same way regardless of the evaporation options, and so this new code doesn't "touch" that side).

**Comment by MeSophie** [comment]
@lilyclements  I didn't push any change Already I just solved conflicts on my branch. Please can you confirm that instead of  `x=tail(x=rain_min - 5, n=-1)` and `x=tail(x=rain_max - 5, n=-1)` we should have `x=tail(x=rain_min , n=-1)` and `x=tail(x=rain_max, n=-1).`

**Comment by lilyclements** [comment]
@MeSophie yes I can confirm that is the case _if_ the checkbox is checked

**Pull request closed without merging**
