### PR TITLE
Dlg jitter

### PR DESCRIPTION
**Pull request by lilyclements**

### CODE REVIEW

**Comment by stevenndungu** [comment]
Is this still in progress?

**Comment by lilyclements** [comment]
Yes. I will always say as soon as a dialog is ready for review. Thanks for checking.

**Comment by Lunalo** [comment]
@stevenndungu 

How far have are you with this ?

**Comment by lilyclements** [comment]
Update: I have been working on this and nearly got it working. However, there's a strange issue with rdo's and so it hasn't been a priority lately.

**Comment by Lunalo** [comment]
@lilyclements 

Can I get this and try fix it?

**Comment by lilyclements** [comment]
@Lunalo  Yes you can. I'll be in the office in 15 minutes and can run through the current written code via Skype if you have any issues.

**Pull request closed without merging**
