### PR TITLE
Disables maximum height for outputs in the output window

### PR DESCRIPTION
**Pull request by Patowhiz**
Temporarily disables the maximum height for outputs in the output window. 
This is because sometimes some graphs outputs are not scrollable when the picture box height is set.

@rdstern @lloyddewit this is ready for your review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@ChrisMarsh82 you may have to include this in the next release.

**Review by rdstern — COMMENTED** [review]
I still only get half the graph?

image

And the less than informative table - first-time round:

image

Maximise continues to work well!

**Comment by Patowhiz** [comment]
@rdstern retest this please.

**Review by rdstern — APPROVED** [review]
Does what it says

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@Patowhiz Happy to merge.
I set the label to `skip-releasenotes` because I assume this is a temporary change. If I misunderstood, then please let me know.
Thanks

**Comment by Patowhiz** [comment]
Yes. This is a temporary change. We had problems with the scrolling of images as outlined by @rachelkg comment in issue #7979.

**Pull request merged**
