### PR TITLE
Improvements on climatic boxplots (adding drop, vjust, hjust and xlab(NULL))

### LINKED ISSUE #6081: Climatic boxplots possible improvements
There is a date receiver on the climatic boxplots dialog but it doesn't seem to do anything. Is it needed?

### PR DESCRIPTION
**Pull request by shadrackkibet**
Fixes  #6081 @africanmathsinitiative/developers this is ready for review.

- Added `drop = FALSE` into facet wrap/grid by default.
- Added `vjust = 0.5` and `hjust = 1`  into `element_text()` when vertical x tick makers is active.
- Changed `ggplot2::xlab("")` into `ggplot2::xlab(NULL)`

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv Please can you review? thanks

**Comment by lilyclements** [comment]
@shadrackkibet 
1. If you update this branch, can you replace `as.factor` to `make_factor` (see #6095)
2. While exploring things for 1. I came across a bug (which occurs whether it is `as.factor` or `make_factor`).
On first opening, input a variable under "Date", "Element", and "Year". Keep the corresponding ucrInput for "Year" as "None", and do not input a variable under "Within Year". Click OK and there is an error since no parameter is read into the `as.factor` function (It is important that this is done on the first opening of the dialog since it doesn't occur if I change the ucrInputYear to "X Axis" and then back to "None").

```
Error in is.factor(x) : argument "x" is missing, with no default

The error occurred in attempting to run the following R command(s):
dodoma <- data_book$get_data_frame(data_name="dodoma")
last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=rain, x=as.factor())) + ggplot2::geom_boxplot() + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text(angle=90, hjust=1, vjust=0.5)) + ggplot2::xlab(NULL)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")
data_book$get_graphs(data_name="dodoma", graph_name="last_graph")
```

**Comment by shadrackkibet** [comment]
@lilyclements I am unable to reproduce the bug in 2 above. I did the following.

- Loaded Dodoma data.
- On opening the dialog the receivers are filled in as follows
image
- Cleared the within-year receiver so that I have the dialog as follows.
image
- Click Ok. No error produced.
- The code produced is as follows.
```
# Code generated by the dialog, Climatic Boxplot
dodoma <- data_book$get_data_frame(data_name="dodoma")
last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=rain, x=make_factor(""))) + ggplot2::geom_boxplot() + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text(angle=90, hjust=1, vjust=0.5)) + ggplot2::xlab(NULL)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")
data_book$get_graphs(data_name="dodoma", graph_name="last_graph")
```
Anything different in the above procedure?

This is not giving an error because `x=make_factor("")` and not `x=make_factor()`. I also notice that when I switch from "None" to "X-Axis" then back to "None" `x=""` which shouldn't be a problem.

**Comment by lilyclements** [comment]
@shadrackkibet the error only occurs for me if "Within Year" is never filled. Try with a data set that doesn't autofill the receivers and then only fill in "Date", "Element", and "Year".

**Review by rdstern — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@lloyddewit I would consider the second issue reported by @lilyclements here as a new issue because that was not introduced by changes made in this PR, therefore, we should have that as a separate fix. This is ready for you.

> @shadrackkibet
> 
> 1. If you update this branch, can you replace `as.factor` to `make_factor` (see #6095)
> 2. While exploring things for 1. I came across a bug (which occurs whether it is `as.factor` or `make_factor`).
>    On first opening, input a variable under "Date", "Element", and "Year". Keep the corresponding ucrInput for "Year" as "None", and do not input a variable under "Within Year". Click OK and there is an error since no parameter is read into the `as.factor` function (It is important that this is done on the first opening of the dialog since it doesn't occur if I change the ucrInputYear to "X Axis" and then back to "None").
> 
> ```
> Error in is.factor(x) : argument "x" is missing, with no default
> 
> The error occurred in attempting to run the following R command(s):
> dodoma <- data_book$get_data_frame(data_name="dodoma")
> last_graph <- ggplot2::ggplot(data=dodoma, mapping=ggplot2::aes(y=rain, x=as.factor())) + ggplot2::geom_boxplot() + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text(angle=90, hjust=1, vjust=0.5)) + ggplot2::xlab(NULL)
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="dodoma")
> data_book$get_graphs(data_name="dodoma", graph_name="last_graph")
> ```

**Comment by lloyddewit** [comment]
@shadrackkibet I documented this issue in PR #6185.

**Review by lloyddewit — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@lloyddewit many thanks.

**Pull request merged**
