### PR TITLE
Histogram plot

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes (partially) #7556
@N-thony , this PR is ready for review

### CODE REVIEW

**Review by N-thony — CHANGES_REQUESTED** [review]

**Comment by N-thony** [comment]
@Fidel365 add `Density Options` menu context and also `Frequency Polygon Options` menu context, then on line `344` add the two additional menu context in the handles
image

**Comment by Fidel365** [comment]
@N-thony I have made the changes requested

**Comment by N-thony** [comment]
> @N-thony I have made the changes requested

@Fidel365  reduce the space a bit under the Plot Options
image

**Comment by Fidel365** [comment]
@N-thony , I have reduced the space in the dialog

**Comment by N-thony** [comment]
> @N-thony , I have reduced the space in the dialog

@Fidel365 can you resolve the conflicts?

**Comment by Fidel365** [comment]
@N-thony , I'm closing this PR because Esther has worked on the similar changes

**Pull request closed without merging**
