### PR TITLE
Fixes the problem with the data selector with multiple columns

### PR DESCRIPTION
**Pull request by stevenndungu**
@africanmathsinitiative/developers 
This perfectly fixes issue #3725

### CODE REVIEW

**Comment by stevenndungu** [comment]
Note: I have chose to have the variables in the selector retain the Data Frame order

**Comment by dannyparsons** [comment]
This does solve the issue, though we lose some functionality that is nice. Having the focus on the receiver after adding is natural for tabbing etc. We might need a more complex solution. I will leave this open so we can discuss this after thinking about it more.

**Comment by Lunalo** [comment]
@stevenndungu  @dannyparsons 

How far?

**Comment by dannyparsons** [comment]
This needs some more thought. I think it would be still be good to fix for 0.4.1.

**Comment by shadrackkibet** [comment]
@dannyparsons  ?

**Comment by dannyparsons** [comment]
I don't think we have a good solution for this yet. I think we can close this as we have the issue still open, which I have set to 0.x milestone.

**Pull request closed without merging**
