### PR TITLE
Allow R script to contain '<' and '>' symbols; also allow line breaks in constant strings

### LINKED ISSUE #7095: Excel file that doesn't paste into R-Instat?
@Patowhiz I would like to "promote" your dialogue Edit > New Data Frame and include it in the File > New dialogue.

But I am sending you separately and Excel file that I am finding difficult with the Paste.

I also tried with other Excel files and they worked fine.  

This one - from our evaluation of R-Instat - imports easily into R-Instat - all sheets if needed.  But when I do Paste New Data Frame it says as follows:

image

### LINKED ISSUE #7377: Serious bug in calculations again
I was trying to test a new pull request - #7329 and fell over the same bug (I think) that was reported before, namely 
image

I have captured the dialogue that is the cause:
image

That's all I can do, because it crashes out of R-Instat.  

I think this is the same known bug that we found in a number of dialogues during our training workshop in February.  It is reported in issue #7095. And it is in the 0.7.4 released version.

a) @dannyparsons has said fixing it is not urgent.  I don't understand that.  We had bugs in Version 0.7.2 and 0.7.3 that were deemed serious enough to fix and an updated version was supplied.  I know @ChrisMarsh82 wants to discuss checks before release on his forthcoming visit.  This seems a good example.
b) Please could it be fixed.  @lloyddewit I think it is with you at least initially, or perhaps finally.  

Thanks

### PR DESCRIPTION
**Pull request by lloyddewit**
Ensured that RScript lib supports '<' and '>'symbols; and also line breaks in constant strings.

Fixes #7095 (the RScript parts)
Fixes #7377

The changes in this PR are also required by PR #7224.

@rdstern @Patowhiz Please could you test?
Thanks!

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
Great, that now seems to work ok.  I have tried on the climatic boxplots and on various calculations including #7377, and it seems fine now.
I hope @shadrackkibet can review the code and merge if he is ok.  He has not been very active recently, so perhaps @Patowhiz could check if there is no response from Shadrack soon.

**Comment by Patowhiz** [comment]
@lloyddewit issue #7377 seems to be fixed but the issues I found in my PR #7224 is not yet fixed, it throws the same error.
In addition, it would also be useful if we could handle such an error at R-Instat level just incase we get such errors in future.
Attached is the data set I used for testing.

[R GUI Comparison Table Colour Coded.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/8518634/R.GUI.Comparison.Table.Colour.Coded.xlsx)

**Comment by lloyddewit** [comment]
> @lloyddewit issue #7377 seems to be fixed but the issues I found in my PR #7224 is not yet fixed, it throws the same error. In addition, it would also be useful if we could handle such an error at R-Instat level just incase we get such errors in future. Attached is the data set I used for testing pasting new data frame.
> 
> [R GUI Comparison Table Colour Coded.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/8518634/R.GUI.Comparison.Table.Colour.Coded.xlsx)

@Patowhiz Thank you for the observation and download link.
- I opened the xlsx file in the PR #7224 branch. I saw that your changes convert the quote inside a string to `\"` (see example below). I think this is correct. I will change the `RScript` library so that it correctly interprets 'escaped' quotes, and let you know when I'm done.
- RScript takes any string as input and throws an exception if it can't process it. Therefore I agree that RInstat should handle RScript exceptions more elegantly. We should wrap calls to `New Rscript(...` inside a catch block, and then display an RInstat message dialog.

```
"data=clipr::read_clip_tbl(x=""Ease_of_Use" & vbTab & "Hides R by default to prevent \""code shock\""" & vbTab & "  1"", header=TRUE)"
```

**Comment by Patowhiz** [comment]
@lloyddewit I agree.

**Comment by lloyddewit** [comment]
@Patowhiz I added support for escaped quotes in constant strings (e.g. `"Hides R by default to prevent \""code shock\"""`)`.
Please could you test again?
Thanks

**Review by Patowhiz — APPROVED** [review]
@lloyddewit yes this fixes my issue. Thanks.

**Comment by lloyddewit** [comment]
@rdstern Please could you test/approve again?
@dannyparsons @shadrackkibet @ChrisMarsh82 I think one of you needs to approve before we can merge. It's already been tested/reviewed so I think you can just approve without reviewing.
Thanks

**Review by rdstern — APPROVED** [review]

**Review by ChrisMarsh82 — APPROVED** [review]

**Pull request merged**
