### PR TITLE
Adding x axis label angle to bar chart

### PR DESCRIPTION
**Pull request by Ivanluv**
in progress

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Ivanluv  Whats remaining on this?

**Comment by maxwellfundi** [comment]
@Ivanluv  Whats the status of this. @Muthenya  could you check and see if there is help needed here.

**Comment by Muthenya** [comment]
Ivan had to clone a new since he was having problems with his repository. We will have to begin work again. This should be ready today. We will close this and open a new pull request once we are through.

**Comment by maxwellfundi** [comment]
You dont need to begin work afresh.. you can pull from the pull request.
Regards
Maxwell Fundi
|| Phone :+254728508241||


Powered By  SalesHandy
<https://www.saleshandy.com/signup/?utm_source=gmail&utm_medium=emailfooter&utm_campaign=branding>

**Comment by Muthenya** [comment]
Okay. The only remaining thing here is linking the checkbox in the dialog to the checkbox in the sdgthemes. I'm not sure how to do this.

**Comment by dannyparsons** [comment]
@Ivanluv is there a new pull request for this now? Should this be closed?

**Comment by Muthenya** [comment]
@dannyparsons this wont need to be closed since from the cloning the branches were still retained.

**Comment by dannyparsons** [comment]
@Ivanluv @Muthenya this is essentially the same as what is now on the "common options" on the themes tab of the Plot Options subdialog.
If you look at the code related to the same control there, you should see everything that is needed for it to link correctly. If not then get in touch.

**Comment by Ivanluv** [comment]
@maxwellfundi please review this

**Comment by maxwellfundi** [comment]
@Ivanluv  I realize that the nud on the main dialog ans that on the sdgplots common themes options are out of sync. We can have a look at this together and find out whats happening, probaly setting rcode when you leave the subdialog for this nud

**Pull request closed without merging**
