### PR TITLE
Ensure that Single Receiver text not translated

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes issue #6519.

In issue #6519 @rdstern wrote:
> I agree that receiver text, for single and multiple receivers, should not be translated. They contain the names of variables and they need to stay in their "neat" form.

This PR ensures that Single Receiver text is not translated. 
In the current implementation, Multiple Receiver text is anyway not translated so no changes were required for this.

This PR also includes some other changes:
- Added back Portuguese translations (these were accidentally removed in PR #6513)
- Removed all tool tip **test** translations. These will be added back correctly (i.e. with real translations) when the JSON file in PR #6533 is translated in CrowdIn
- Correctly translated the 'View Last Graph' and 'Column Metadata' button tool tips (and closed PR #6540)

@rdstern Please could you test?
@shadrackkibet Please could you approve? The problem was solved in the database (my personal notes below), so there isn't much you can review.

----
Preventing translation of Single Receiver text:
- Each single receiver has a `txtReceiverSingle` property
- In the `forms_controls` table, for each Single receiver, I set this property to `DoNotTranslate`.

image

Correctly translating the 'View Last Graph' and 'Column Metadata' button tool tips:
- In the `forms_control` table, set `mnuLastGraph` and `mnuMetadata` to `ReplaceWithDynamicTranslation`

image

### CODE REVIEW

**Review by shadrackkibet — APPROVED** [review]

**Comment by Patowhiz** [comment]
@lloyddewit going by @rdstern analogy of receivers containing 'variables' text that shouldn't be translated. I think other controls could also have texts that are related to contents of data frames that shouldn't be translated(subject to @rdstern  correction). For instance, the drop downs for selecting the factor levels or file types, input text boxes that display file paths etc. Basically some custom controls can be used to display text related to something in the data frame that shouldn't be translated. 

@lloyddewit I haven't delved much into the translation implementation and the above examples could have already been factored in (in which case my concerns should be ignored!).

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit going by @rdstern analogy of receivers containing 'variables' text that shouldn't be translated. I think other controls could also have texts that are related to contents of data frames that shouldn't be translated(subject to @rdstern correction). For instance, the drop downs for selecting the factor levels or file types, input text boxes that display file paths etc. Basically some custom controls can be used to display text related to something in the data frame that shouldn't be translated.
> 
> @lloyddewit I haven't delved much into the translation implementation and the above examples could have already been factored in (in which case my concerns should be ignored!).

@Patowhiz Thank you for the comments. You are correct that many controls have text that should never be translated. Winforms allows us to add tags to controls. We were planning to use this feature to tag controls with 'do not translate'. This will be one of the next features we implement (see issue #3721).

**Comment by lloyddewit** [comment]
@rdstern Please could you test that that Single Receiver text is no longer translated? and approve if satisfied? thanks

**Comment by Patowhiz** [comment]
@lloyddewit thanks for the feedback. 
As a side note, I'm a bit skeptical on using the **winforms** `Tag` property for controls, because we already use it in other places for other functionalities(you probably are aware of this). I would generally lean towards adding a new property explicitly for this purpose.

**Review by rdstern — APPROVED** [review]

**Pull request merged**
