### PR TITLE
Correct Regular Sequence Dialogue

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes issue #6672
Moved the preview up in the dialogue to allow for room for the Position button to go after the main control
@maxwellfundi can you check if everything is in order

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@maxwellfundi @shadrackkibet @maxwellfundi If one of you could test/approve, then we can merge.
Thanks

**Comment by rdstern** [comment]
@derekagorhom could you please check which controls remember their previous settings and which reset to the original default.
image
 This example used the usual survey data I had just made a column at the start from 4 to 12 repeating each value 4 times, see below - first variable:

image


When I return the start is reset to 1 and the end to 36.  But the 4 remains.  Our "system" is for them all to remain.  Good to correct this.

Also good for testing to always:
a) Do something and then come back to the dialogue to check all is ok.
b) Then also change to another dialogue to check that nothing carries over from the previous one.  For example, after the survey, use dodoma.  I did not check that aspect yet.

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom I have added a point above I found, before merging is possible

**Comment by derekagorhom** [comment]
i will work on it please

**Comment by maxwellfundi** [comment]
@rdstern Thank you for your review. I think we can have this merged and tour comment written as an issue. What @derekagorhom  was doing at least for this PR was to swap controls around as a starter task.

**Comment by rdstern** [comment]
@maxwellfundi and @derekagorhom I am happy either way.  Either:
a) @derekagorhom writes the point above as a new issue.  Then I'll approve the current version for merging.  Or
b) @derekagorhom fixes the point above first and I'll check again.

Back to you to decide.

**Comment by derekagorhom** [comment]
Hello @rdstern 
i think i will go with the first one and treat your suggestion as a new issue rather, if that is ok with you

**Comment by rdstern** [comment]
@derekagorhom that's fine.  Please write the issue.

**Comment by derekagorhom** [comment]
Hello @rdstern 
Before i create the new issues, i did some testing with data from the R-instat library and everything seems to be working fine
Screenshot (366)

i used the sleeping data for students and it started from 1.

**Comment by rdstern** [comment]
@derekagorhom I found nothing wrong with the execution of the dialogue.  It was only in the "memory" of certain controls that is incomplete.  The idea in R-Instat is that, when you re-open a dialogue, the controls "remember" their previous setting.  It should be a trivial issue to write - or to fix in your current version.

**Comment by rdstern** [comment]
I am not using your branch, but the merged version.  Here is an example:
image
It is in a data frame of length 100 - anyone will do.
It works fine, though the file to be saved is not visible - I think that's a more general problem.

When I re-open the dialogue it has remembered the repeat values as 10.  But the other 3 controls have reverted to their defaults.  I think this may be the same in your branch.

image

**Comment by shadrackkibet** [comment]
@derekagorhom I see you are making good progress here.  I can help you understand the problem identified by Roger. Let me know if you would like us to jump into a quick skype.

**Comment by derekagorhom** [comment]
@shadrackkibet please can we have the skype meeting now?

**Comment by derekagorhom** [comment]
@rdstern i have been able to fix the controls but for some reason this PR is giving me conflict issues so want to close this PR and make the changes again if that is ok with you.

**Comment by rdstern** [comment]
@derekagorhom yes - please do.

**Pull request closed without merging**
