### PR TITLE
NCMP Climatic Dialogs

### PR DESCRIPTION
**Pull request by lilyclements**
@lloyddewit my apologies - does this also need to be merged before I can make any further changes? It's been a while since I added windows forms, and I forgot that editing the dialog adds a resources file.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@lloyddewit I am approving following this request from Lily for merging:
"Thank you for accepting the changes in #6132. It's been a while since creating empty forms on R-Instat so I accidentally forgot to create the resource files which I think also need to be merged in to avoid conflicts. These are in #6133. Would you mind accepting this PR too?
There's no rush - I have been able to do the code for the NCMP dialogs regardless. I've just saved the code elsewhere and will put it in a PR once #6133 is merged."

**Comment by lloyddewit** [comment]
@lilyclements thanks for the explanation.
I agree that the `.resx` files would normally have been included in PR #6132. I did not notice they were missing when I approved - sorry for that.
I see that, in this PR, you included the `.Designer.vb` files. These were also included in PR #6132.
The main branch currently builds without errors (even though the `.resx` files are missing). So the `.resx` files aren't essential for the build. Also the new dialogs aren't visible to the user so, from a user perspective, it doesn't matter if the `.resx` files are missing.

So the question is do we really need this PR?
- if, before your next merge, more than one person is likely to work on these dialogs (parallel work), then we should merge this PR
- if you are currently the only person likely to work on these dialogs then I think you can make a new PR when you're ready to merge the new functionality (and we can close this PR)

@lilyclements does the above make sense? do you have a preference?
@africanmathsinitiative/developers if you have anything to add then please let us know, thanks

**Comment by lilyclements** [comment]
@lloyddewit great thanks for the explanation. My main concern is that the Instat.vbproj file is edited. If this isn't a problem then I'll make changes to the dialogs on this branch.

**Review by lloyddewit — APPROVED** [review]
@lilyclements Thanks for the comments and Skype message. I'll approve and merge as suggested.

**Comment by lloyddewit** [comment]
@rdstern Please could you approve again (I don't think there's anything you can test)? thanks

**Review by rdstern — APPROVED** [review]

**Comment by dannyparsons** [comment]
Just for in future, it's good to include the resx and designer files in the original PR when creating dialogs so that we have less PRs which edit the vbproj file so less likely to conflict.

> So the question is do we really need this PR?
> 
> if, before your next merge, more than one person is likely to work on these dialogs (parallel work), then we should merge this PR
> if you are currently the only person likely to work on these dialogs then I think you can make a new PR when you're ready to merge the new functionality (and we can close this PR)

**Pull request merged**
