### PR TITLE
Updated R version & R packages

### LINKED ISSUE #5976: Packages for next version
- stringdist

@rdstern @lilyclements @africanmathsinitiative/developers any new packages that need to be added for newly created dialogs?

### PR DESCRIPTION
**Pull request by dannyparsons**
fixes #5976

To test this follow the instructions here https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers. First update R, use the script to install the required R packages then close R and run. Note that this process requires ~400MB download. Also note doing this process will change your default version of R and you may need to reinstall the older version of R to work with other branches. It may be easiest for me to walk through testing this with @lloyddewit or @rdstern to avoid issues.

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Review by maxwellfundi — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@dannyparsons I think you forgot to update this message when updating R version. It will be good to make this a variable like others?

line 258 ` MsgBox(ex.Message & Environment.NewLine & "Could not establish connection to R." & vbNewLine & "R-Instat requires version " & strRVersionRequired & " of R." & vbNewLine & "Note that R-Instat does not work with R below 3.5.0. We recommend using R " & strRBundledVersion & ".  Try reruning the installation to install R " & strRBundledVersion & " or download R " & strRBundledVersion & " from https://cran.r-project.org/bin/windows/base/old/" & strRBundledVersion & "/ and restart R-Instat." & vbNewLine & ex.Message, MsgBoxStyle.Critical, "Cannot initialise R connection.")`

**Comment by dannyparsons** [comment]
Thanks, that whole message in fact needs to change now because of the way we include R in the installation.

**Comment by shadrackkibet** [comment]
Also, some information about R on the download page on the website needs update.

**Comment by dannyparsons** [comment]
Can you discuss that with @maxwellfundi as he is redoing the website and also any other suggestions for improving the website?

**Pull request merged**
