### PR TITLE
 Made the Message text box non-editable on the Remove Unused Levels dialog

### LINKED ISSUE #7023: The Try textbox on the Calculator should not editable & Message Textbox on Remove Unused Levels
@africanmathsinitiative/developers Someone please take this up.

### PR DESCRIPTION
**Pull request by mmulahvictor**
@africanmathsinitiative/developers @shadrackkibet 
this partially fixes issue #7023 
This is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@rdstern Please can you test? thanks

**Comment by rdstern** [comment]
This now seems to work.  I can still go into the control and move about there, though I can't edit.  
But it does seem to have fixed this error.

I was about to approve, when I hit an annoying - possibly totally different problem.  I report it here because it was through this testing that it came about.  I decided to filter (using the standard survey data) and making fert > 0 as the condition, and then getting a subset.  It gave me this error repeatedly.

image

I had seen a similar looking error before when testing other things - I'll check further here.  

Aha I get it here too and have had it here before.  When I start, some data sets give this error.  here is an example:

image

I'll also make this into a separate issue, but it might be useful to look into it on this branch, before merging?

**Review by rdstern — COMMENTED** [review]
This feature seems to be fixed fine.  But I am getting an error on something that seems (to me anyway) totally unrelated.  I have reported that under this pull request.
I have also seen the same problem in another pull request.  I'll check again.  But it may be worth investigating with this branch.

**Review by rdstern — APPROVED** [review]
I am now approving, because the main feature I tested is working.
I still get the (possibly unrelated) error when doing a filter (say on survey, and just selecting 3 villages, so there is an unused level)  When I use the subset option it gives an error, (reported above) that I don't have in the current merged version.  I hope @shadrackkibet or @lloyddewit in the check of the code, can confirm this will be ok to merge.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
I modified this PR so that merging will not automatically close issue #7023 . Issue #7023  will be closed when PR #7055 is merged.

**Pull request merged**
