### PR TITLE
Sub Dialogue for Table Options 

### PR DESCRIPTION
**Pull request by john-bagiliko**
This is beginning work on #6770

### CODE REVIEW

**Comment by lilyclements** [comment]
@john-bagiliko how is this coming on?

**Comment by john-bagiliko** [comment]
> @john-bagiliko how is this coming on?

@lilyclements I am waiting for the meeting with you for clarification.

**Comment by rdstern** [comment]
Am I right that @anastasia-mbithe is (or has) taken over this branch?  Or @john-bagiliko has relatively little been done, so it should be closed and she should start a new branch?

**Comment by john-bagiliko** [comment]
You are right. She can either continue with it or close and start a new one, depending on what works best for her.

**Pull request closed without merging**
