### PR TITLE
Updating OnevarUseModel&OneVarCompareModel

### PR DESCRIPTION
**Pull request by AlexSananka**
@africanmathsinitiative/developers This is ready for review.
Here I have updated `dlgonevarusemodel `because we were running a bootstrap before click OK which isn't ideal for the current system.

### CODE REVIEW

**Comment by AlexSananka** [comment]
Note:The `panel `of the `subdialog `isn't resetting well yet but am still looking for a better way to handle this.

Just to make it more clear,When you open the `subdialog `and click on a different radio button from the default one then close the `subdialog `and reopen you realise that reset itself  to the default radio button.

**Comment by lilyclements** [comment]
That resetting problem I sometimes get on a main dialog when I close and reopen. It tends to be caused by not setting the r code for that control correctly. Could that be the problem here?

**Comment by AlexSananka** [comment]
@africanmathsinitiative/developers This is ready for review.

**Comment by stevenndungu** [comment]
Thhis looks good... make the I changes suggested to you, then it will be ready...

**Comment by AlexSananka** [comment]
Just to make it clear;the changes were deleting out some commented code.
I will do this once this is merged since am having issues with my branch.
@stevenndungu can it be merged on the current state?

**Comment by stevenndungu** [comment]
Yes this is ready for @dannyparsons it's working fine.

**Comment by dannyparsons** [comment]
Looks good nice code. I'll hand over to @rdstern for detailed testing and bug finding, if any.

**Pull request merged**
