### PR TITLE
Implementing delete in reogrid 

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes issue #7149 

implementing a delete option for cells or group of cells from the Dataframe through the Dataview by adding delete cell(s) to the 
Cell Context Menu Strip. 

@shadrackkibet can you test it to see if everything is working

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom well done getting this far.  I am not keen on adding this to the right-click menu.  Instead the main (possibly only) method is the Delete key, which is always there on the keyboard.
It currently says Delete is disabled.  Now it should say "This will replace the selected cells with missing values (NA).  Continue?"

**Comment by derekagorhom** [comment]
> @derekagorhom well done getting this far. I am not keen on adding this to the right-click menu. Instead the main (possibly only) method is the Delete key, which is always there on the keyboard. It currently says Delete is disabled. Now it should say "This will replace the selected cells with missing values (NA). Continue?"

understood, i will work on it

**Comment by derekagorhom** [comment]
@N-thony  can you check it please

**Comment by N-thony** [comment]
> @derekagorhom I tried to have a look too, but got build errors.

@rdstern this is still in progress and not yet for review. I have asked @derekagorhom to push the changes made so far for me to check on my side but I'm also facing a small issue of checking its branch. Once done, this will be ready for review. Thanks

**Comment by derekagorhom** [comment]
thank you @rdstern, i will update and open a new PR again

**Comment by N-thony** [comment]
> thank you @rdstern, i will update and open a new PR again

@derekagorhom are you not able to run on your side too?

**Comment by derekagorhom** [comment]
> > thank you @rdstern, i will update and open a new PR again
> 
> @derekagorhom are you not able to run on your side too?

Yes @N-thony  i am encountering build errors too

**Comment by N-thony** [comment]
> > > thank you @rdstern, i will update and open a new PR again
> > 
> > 
> > @derekagorhom are you not able to run on your side too?
> 
> Yes @N-thony i am encountering build errors too

Okay, it may probably be the problem on my side too. Let me know after opening another PR then we can continue with the remaining part.

**Comment by derekagorhom** [comment]
@N-thony i fixed the error, @rdstern can you check this

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom I checked as you requested.  The good news is that it now builds.
But there are so many things that don't work as expected, that I find it difficult to believe you checked yourself, before asking me.
It will be good, in the future, to mention what you have done to confirm that it works for you - then I can repeat that, before trying other things.
a) The delete cells is still there on the right-click.
b) I tried with the review data.  I deleted a block of cells.  It correctly gave a message.  This does need to be reworded now, because will soon have an undo!
c) Then it gives an error, saying it can't find the index.
d) Then it replaces the cells by a blank - not NA.
e) Then I tried deleting a single cell.  That didn't work either.
f) Then I tried typing NA into a cell.  That worked before, and now it doesn't work.
This is turning into a good example, for you to learn a lot about good working practices and about working to a high standard.  Also possibly getting your colleagues to check , i.e. to become early testers of each other's work.

**Comment by N-thony** [comment]
@derekagorhom any reason for closing this?

**Pull request closed without merging**
