### PR TITLE
developer error fix

### PR DESCRIPTION
**Pull request by shadrackkibet**
@dannyparsons  this is a minor fix.This is ready to be merged.

### CODE REVIEW

**Comment by dannyparsons** [comment]
What about the other input control?

**Comment by shadrackkibet** [comment]
The other input control doesn't bug.

**Comment by dannyparsons** [comment]
I think it should be non editable as well anyway, because it doesn't allow custom values?

**Comment by shadrackkibet** [comment]
i have changed both now.

**Pull request merged**
