### PR TITLE
Corrected the translations in the ExportToWWR Dialogue

### LINKED ISSUE #8668: Oddity on dialog could be a language issue?
@lloyddewit here is a little-used dialog we plan to show in the WMO course on Wednesday.

image

I don't really understand the dialog, but it has various oddities in the text in the items labelled 2, 3, 4 and 7.

I wonder if that's the language translation problem again?  If so, then is that something @N-thony can correct?

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #8668 
@lloyddewit @rdstern the three label controls 2, 3 and 4 had an issue with additional text with the translation all the languages we have except in French. I checked in the database and found the problem was in the translation table were I made the changes. It is now consistent with the texts in Crowdin. Have a look.
image

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@N-thony great.  Looks fine now - in both English and French.  @Patowhiz please can you merge.

**Comment by lloyddewit** [comment]
@rdstern @N-thony Thank you for fixing.
This resolves the issue but I still don't understand what caused the translation table to be incorrect in the first place.
When we make a new version of R-Instat that includes updated translations, we regenerate the translation table from the JSON files (instructions on Wiki). But I looked at the JSON files and they seem correct. So it's a bit of a mystery what went wrong.
I suggest that the next time we make a translation build, that @rdstern specifically checks this dialog to see if the translations are still correct.

**Comment by lloyddewit** [comment]
@N-thony thanks, interesting. Recreating the database is only a semi-automatic process so it's possible that there was some human error during the process. Or maybe there's a bug in the automated part. Next time we rebuild the database tables, we can pay special attention to these translations to see if it happens again.

**Comment by lloyddewit** [comment]
> @lloyddewit this PR contains change in the database, could we merge it to avoid conflicts?

I don't have this role any more. Could you merge it yourself or ask Chris or Patrick?

**Review by Patowhiz — APPROVED** [review]
@N-thony I have approved without looking into the PR as a user.
Request @rdstern to approve after he has looked at the translations as a user.

**Comment by Patowhiz** [comment]
@rdstern I can see you approved this last month. I'm now merging.

**Pull request merged**
