### PR TITLE
Small corrections to the Evapotranspiration dialog design

### LINKED ISSUE #7026: Correcting the dialogue title on Climatic > Prepare > Evapotranspiration dialogue
The current title is `Evapotraspiration ` but it should normally be called `Evapotranspiration `.

In addition, the `Wind Speed` groupbox is correctly spelled but the Receiver is not `WindSpeed`, it should be changed to `Wind Speed` and the checkbox is called `Wind`. Perhaps the checkbox should be called  `Wind Speed` and get rid of the label of the Receiver once checkbox checked the receiver will appear?

image

### PR DESCRIPTION
**Pull request by Gioche6**
Fixes #7026

@africanmathsinitiative/developers , This is ready for review. 

@N-thony , I have fixed the typos mentioned in the issue an also made a few design changes for the Solar, missing method and crop combo to have the same X point. I have additionally removed the label of the wind speed and renamed the which checkbox to windspeed to remove repetition. 

I have also changed the `PenmanMonteith `radio button  to `Penman-Monteith`, I have done some research in a few research papers and That is how it should be written as. 

The name of the dialog in vb has been `Evapotranspiration` as compared to what is appearing on runtime as `Evapotraspiration`. This could be because of Translation issue, Perhaps @lloyddewit  could help on this. 

Kindly review and let me know what you think?

### CODE REVIEW

**Comment by N-thony** [comment]
@Gioche6 the `Interpolate Missing Entries` checkbox is too wider till over its groupbox, I think this is like that for the French version. Can you just its size so that it will fit the French translation also not goes over its groupbox? Same fro Wind Speed checkbox. And the radio button text is still `PenmanMonteith ` this is due to the translation. I think it can be fix the same way with the dialog title.

@lloyddewit for the mispelling of the dialog title, could this change be directly corrected through the database?

**Comment by Gioche6** [comment]
@N-thony , I have fixed the the issues you raised. Kindly have a look.

**Comment by lloyddewit** [comment]
> @lloyddewit for the mispelling of the dialog title, could this change be directly corrected through the database?

Yes, you are correct, the error is in the database:

image

I will fix this in a new PR.

**Comment by lloyddewit** [comment]
@rdstern Please can you test? thanks

**Review by rdstern — COMMENTED** [review]
@Gioche6 and @lloyddewit this is still wrong here, but is ok in the merged version.  So I assume this can be closed?

**Comment by lloyddewit** [comment]
@Gioche6 

- [ ] I just noticed that I didn't update the database for the 'Penman-Monteith' button.

- [ ] For consistency, should the other radio button be 'Hargreaves-Samani'? Please can you fix in this PR?

I'll update the database for both of the above in a separate PR.

@rdstern The two name changes above can't be tested in this PR. When @Gioche6 has done the above, please could you approve? Thanks

**Review by rdstern — DISMISSED** [review]

**Comment by Gioche6** [comment]
@lloyddewit, @rdstern , I have added the hyphen for the second radio button for consistency.

**Comment by rdstern** [comment]
I will approve these changes, but then there is still more to do on the layout of this dialogue.  I think there is an issue that can be used - if not we should create one.  
image

I temporarily made my screen resolution 800 by 600 and then the dialogue is too big and cannot be used.  We need to make it shorter.  There is a lot of space that can be saved without changing the layout.  If that isn't enough, then we should change the layout as well.

**Review by rdstern — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
@Gioche6 I am approving this pull request.  But I would like you to check with @HawardKetoyoMsatsi and @N-thony about then who will be working on #7060 and #7061?  They both relate to the same dialogue.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
