### PR TITLE
Bar chart bug

### LINKED ISSUE #5409: Small bug in bar chart
This should be a simple one to fix!
In the bar chart one argument is called position.
The default is **stack** and that is fine and works.  The next option is what could be labelled **stack (reverse).**  Currently it is labelled position = position_stack(reverse =TRUE), which looks very odd and out of place there!  That's essentially the code, not the label.

But the bug is more what is what it produces in code, which is **position = position = position_stack(reverse=TRUE)**, i.e. the **position =** is repeated twice.

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes #5409 
@africanmathsinitiative/developers this  is ready for review

### CODE REVIEW

**Comment by maxwellfundi** [comment]
Am not sure how this was missed-  @Ogik99 could you check this to see its looking okay?

**Comment by maxwellfundi** [comment]
@Ogik99 could you have a review of this this morning?

**Comment by maxwellfundi** [comment]
Additionally here, these two files have been edited by two people, i suggest, when its reviewed then @Ivanluv merges his changes to @Ogik99 s branch with the changes on `ucrGeom` called `label_geom`

**Comment by Ogik99** [comment]
> Am not sure how this was missed- @Ogik99 could you check this to see its looking okay?

This now works well (there's no longer code repetition)

However, there is another unrelated issue (which is similar to an existing issue under #5358. Changes made to the bar chart options sub dialog for the position parameter do not get updated on the main dialog specifically for position_stack(reverse), Dodge2.
This is something I will be looking into.

**Comment by dannyparsons** [comment]
@Ogik99 if you run SetRCode when returning to the dialog controls will update based on the code and this should be fixed, good to notice this issue.

**Pull request merged**
