### PR TITLE
Improvement and bug fixes to the Three Variable Pivot Table dialogue

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes issues raised in PR #6634 ie

-  Having the Additional Variable receiver ,Table Input and Summary Input linked to the new` Numeric Variable (Optional): `checkbox
- Fixed the bug raised by the save control

@africanmathsinitiative/developers this is ready for review

### CODE REVIEW

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Please can you peer review? thanks

**Comment by rdstern** [comment]
This is looking good
@ivan the one trivial point is your message above, you say: "Having the Additional Variable receiver ,Table Input and Summary Input linked to the new `Numeric Variable (Optional): `checkbox.  Please make that the checkbox label.  Currently it just says Numeric:
Then we can merge, and also use it to replace the current pivot table dialogue under 2 variables.

**Comment by ivan** [comment]
I keep getting emails from this project because of the use of "@ivan". Please stop that, as I cannot make GitHub not send me emails when my @ is mentioned.

**Comment by rdstern** [comment]
Apologies.

We have @ivanluv in our group!  I must be more careful!

Thanks

Roger

**Review by rdstern — APPROVED** [review]
@Ivanluv please check carefully.
Add a space before the (Optional) and the top label is no longer visible

**Review by rdstern — CHANGES_REQUESTED** [review]
@Ivanluv Add a space before (Optional) and the top label is no longer so visible

**Comment by Ivanluv** [comment]
@rdstern  could you have a look again

**Comment by rdstern** [comment]
@Ivanluv thanks - will do

**Review by rdstern — CHANGES_REQUESTED** [review]
@Ivanluv looking pretty good now.
a) When I click on the Numeric, it correctly opens to control, but it should also pass the focus to that field.
b) Good to restrict the variables in the selector to numeric (or date, or logical) for that receiver.
c) Change the default statistic from Count to Average.  (With Count, it doesn't include the numeric variable.)

**Comment by Ivanluv** [comment]
@rdstern could you have a look again

**Comment by rdstern** [comment]
@Ivanluv I can't test it now I think.  The 3 variable option has gone from the menu.  Can you slot your code into the new 2/3 variable menu.  There is a pivot table dialogue there, which is no longer needed, because of your changes.

**Pull request closed without merging**
