### PR TITLE
Added Options subdialog to Two variables, Frequency/summary and Column Summaries dialogs

### LINKED ISSUE #7917: Link the Missing Options subdialog to specific areas required.
This is from a conversation I had with @N-thony.

The missing options sub dialog is currently linked to the Describe>One Variable> Summarise dialog under the Customised button.
Add the sub dialog to;
1. Describe > Two variables dialog when we have Omit missing values checkbox. The checkbox is visible when we have Numeric by Categorical and Numeric by Numeric summaries.
2. Describe > Specific Tables and graphs> Frequency/summary dialog in the summary option.
3. In Prepare > Data Reshape > Column Summaries dialog, change the already existing label for the sub dialog from Missing to Options.

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
Fixes #7917 
Added Options subdialog to Describe > Two variables dialog, Describe > Specific Tables and graphs> Frequency/summary dialog and Prepare > Data Reshape > Column Summaries dialog.

@N-thony, have a look at this and test it as well.

### CODE REVIEW

**Comment by N-thony** [comment]
@anastasia-mbithe I have tested the Summary Table dialogue, but there is an issue after adding the missing parameter from the sub dialogue which is fine when you unchecked `Omit Missing Values` the missing parameter is still there in the code.

**Comment by rdstern** [comment]
Well done @anastasia-mbithe for adding the option and @N-thony for that good spot!

**Comment by anastasia-mbithe** [comment]
@rdstern and @N-thony, this issue is now fixed.

> @anastasia-mbithe I have tested the Summary Table dialogue, but there is an issue after adding the missing parameter from the sub dialogue which is fine when you unchecked `Omit Missing Values` the missing parameter is still there in the code.

**Comment by N-thony** [comment]
> @rdstern and @N-thony, this issue is now fixed.
> 
> > @anastasia-mbithe I have tested the Summary Table dialogue, but there is an issue after adding the missing parameter from the sub dialogue which is fine when you unchecked `Omit Missing Values` the missing parameter is still there in the code.

@Vitalis95 can you review on this?

**Comment by Vitalis95** [comment]
@anastasia-mbithe , one small thing could you update the label for the sub-dialog in the database, it is still reads `missing`, @N-thony  if there is an open PR for the database could be done there

image

**Comment by N-thony** [comment]
> @anastasia-mbithe , one small thing could you update the label for the sub-dialog in the database, it is still reads `missing`, @N-thony if there is an open PR for the database could be done there
> 
> image

@Vitalis95 you can add it in your PR if it is still open or open a new one?

**Comment by lloyddewit** [comment]
@rdstern Please could you test? thanks

**Comment by rdstern** [comment]
@anastasia-mbithe 
a) the specific tables option seems to be working well.
b) There is a trivial change mentioned that still has to be done.  In the 2 variable and specific tables the button is called Options.  It is still called Missing in the Prepare > Data Reshape > Summarise dialogue.  Please change to Options for consistency.
c) I think you are using an old version of the Describe > Two Variables dialogue.  The code looks good, but it is not doing the options quite as it should.  I wonder where the new version of that dialogue is?  Aha it is #7920, which is now by Vitalis.  I am not sure what should be done therefore about order of merging?

**Comment by anastasia-mbithe** [comment]
@rdstern, comment b) on the Reshape> Column summaries was resolved in PR #7942

**Comment by rdstern** [comment]
@anastasia-mbithe thanks - I realised too late!

**Review by rdstern — APPROVED** [review]
Happy to approve now

**Review by lloyddewit — APPROVED** [review]
@anastasia-mbithe looks good, many thanks

**Pull request merged**
