### PR TITLE
Added a new keyboard (hydroGOF) to the calculator

### LINKED ISSUE #5663: New hydroGOF keyboard in the calculator
This is a keyboard to compare two numeric variables.  The functions are all taken from the hydroGOF package.  
There are 21 keys, so perhaps 3 across and 7 rows:
1) br2, cp, d
2) KGE,mae,md
3) me, mNSE, mse
4) nrmse, NSE, pbias
5) pbiasfde, rd, rmse
6) rNSE, rPearson, rSD
7) rsr, ssq, VE

Note - give them with the parameters as for the cor function, e.g. hydroGOF::br2(sim=, obs=)
Note - for pbiadfde include plot=FALSE.

Great if the help on this keyboard could link to the R package.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5663

@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by Wycklife** [comment]
@rdstern  Should the help for this goes direct to help package? or to our help?

**Comment by maxwellfundi** [comment]
This looks good. A quick one on this @rdstern, for the help of the hydroGOF would you like this to open the Help from the package or should this have section from our own help?

**Comment by rdstern** [comment]
It should go to the R package help

**Comment by maxwellfundi** [comment]
Great thank you @rdstern 

@Wycklife  now you need to run `help(package = "hydroGOF"  )` to open the package help.

**Comment by Wycklife** [comment]
@maxwellfundi okay

**Comment by Wycklife** [comment]
@rdstern Part c, the arguments for the keys are shown when you check the show parameters check box. Do you want them to appear in the default state?

**Comment by rdstern** [comment]
Yes - just as for the correlation and others you did recently.  So when there are parameters that are compulsory we help the user by giving them.

**Comment by Wycklife** [comment]
@rdstern I have made the changes kindly check.

**Pull request merged**
