### PR TITLE
Windrose#5965

### PR DESCRIPTION
**Pull request by Ivanluv**
Fixess #5965

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
This has started well.
The facets isn't working yet.  Could those labels change to Facet (Optional): and 2nd Facet (Optional):  
It should be easy to include.  The facet variable can be numeric or a factor.  Then it just sets the type = "facetvariable" argument if one variable and type = c("v1","v2") if 2 variables are selected.

I tried with the mydata supplied with the openair package.  When with a Togo dataset, then it gave an error, so I will investigate that in more detail next time.

**Comment by Ivanluv** [comment]
@rdstern I have added the facet options, could you look at this again.

**Review by rdstern — COMMENTED** [review]
There are some funny things going on with this function.  I was trying to test the facets, but finding that it sometimes works and sometimes gives odd errors.  

The errors are usually in the checkPrep function, which I think is called by many of the functions we will be using in different dialogues. (all part of openair) This seems to be related to the existence of a date (or datetime variable and possibly also to the default naming of arguments.

For example, when I use the mydata (default data) for a simple windrose, then it works.  But in my version, where I have changed the names of all variables, the same data gives an error in the dataPrep function.

Perhaps @shadrackkibet or @HawardKetoyoMsatsi could examine the puzzle.

**Comment by shadrackkibet** [comment]
My quick investigation shows that for some reason the function requires another parameter `pollutant`. By default `pollutant = "nox"`. Since from your "messed-up" data, there is no `nox` column the function bugs. I tried renaming `rename_nox` back to `nox` and that seems to work.

Possible solution is to pass in by default `pollutant = "ws"` where "ws" is the wind speed column name. Otherwise we have this an option in the dialog.

**Comment by Patowhiz** [comment]
@Ivanluv is this ready for review?

**Comment by Ivanluv** [comment]
@Patowhiz this requires more investigation and has been taken over by @HawardKetoyoMsatsi

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Please could you clarify the status of this PR? thanks

**Comment by HawardKetoyoMsatsi** [comment]
This PR is still in progress I am working on it alongside some other issues.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi did you manage to make any progress on this? please request support if needed, thanks

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit from my discussion with @Ivanluv and @rdstern this PR is supposed to be closed so that another PR to fix the same can be opened. 
@Ivanluv could you please close this PR.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Thank you for the update. When you open a new PR please reference this one so that other developers can see that the PRs are related.
If you want to build on the changes made in this PR, then I assume that you will first merge the commits from this PR to your local branch. In this case, we do not need to manually close this PR because it will close automatically when your new PR is merged.
If you want to start from scratch (and not merge the commits

**Comment by HawardKetoyoMsatsi** [comment]
Kindly close it because I will be starting from scratch, thank you.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi closed as requested

**Pull request closed without merging**
