### PR TITLE
Added initial Kiswahili machine translation to translation database

### PR DESCRIPTION
**Pull request by lloyddewit**
@rdstern , @shadrackkibet Please could you test and merge? thanks
Please note that much of the text will still be shown in English, this is only because it's not been translated yet, it's not a translation mechanism fault.
Do you know if Beryl is on Github?

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Yes @berylwaswa is here.

**Review by shadrackkibet — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
Looks good!

**Comment by lloyddewit** [comment]
@berylwaswa You can use this version of R-Instat to test the current Kiswahili translations. Please let me know if you have any questions, thanks

**Comment by berylwaswa** [comment]
Okay, I will.

Kind Regards,
Beryl Waswa,
Research Assistant,
INNODEMS.

**Pull request merged**
