### PR TITLE
dlgRatingScales

### PR DESCRIPTION
**Pull request by AlexSananka**
In progress

### CODE REVIEW

**Comment by AlexSananka** [comment]
@africanmathsinitiative/developers This is making a good progress

**Comment by dannyparsons** [comment]
@AlexSananka How is this going? It seems to have been open for quite a long time now. How far away from complete is it?

**Comment by Lunalo** [comment]
There is still some issue with developer errors and  passing of one parameter. We will have a look together early morning tomorrow

**Comment by AlexSananka** [comment]
@dannyparsons this is taking shape but still not ready for review,I was facing a challenge on changing base functions and setting the Rcode correctly,we will be making minor edits with @Lunalo tomorrow and hopely it will be ready.

**Comment by dannyparsons** [comment]
I see you have started using the new code for using multiple functions and parameters. It would be great if you can implement this on this dialog. You can use the one variable frequencies dialog that I did as an example.

**Comment by dannyparsons** [comment]
Are you still working on this?

**Comment by AlexSananka** [comment]
Just one more minor edit then you can pull my branch.

**Comment by AlexSananka** [comment]
@dannyparsons this dialog is somewhere,It has a developer error(which I can fix but it's taking a lot of time).One major issue on this dialog is the way it's updating the parameter values.Sometimes it does update on changing the function and sometimes it doesn't.Another issue which we need to clarify on is the use of the cat.neautral parameter?Do we need a checkbox?If yes how do we want it to work,am not sure.
You can pull my branch and have a look at it.

**Comment by stevekogo** [comment]
@AlexSananka what is the current state of this?

**Comment by AlexSananka** [comment]
@stevekogo This dialog is working partially fine and it's almost there, @dannyparsons was to work on it from there.

**Comment by dannyparsons** [comment]
Yes I will take a look at this today and try to resolve remaining issues.

**Comment by stevekogo** [comment]
@dannyparsons Did you manage to fix this?

**Comment by dannyparsons** [comment]
I will work on this now

**Comment by dannyparsons** [comment]
I just had a quick look at this and there seems to be a lot of issues. I think this was one of your first dialogs, I wonder if you relook at this now you'll see easy ways to improve it. Some of the issues I found are:

- I couldn't get the dialog to do a likert graph (or anything else) with any data. Probably because `catcount = 0` is always passed. Read the notes of the function carefully, and then I suggest we have a checkbox to specify number of categories, if not checked we don't need that parameter.
- Table and graph radio buttons are on the side. How about 3 buttons at the top: Likert Graph, Stacked Graph, Table (or better names)
- Issues with linking of Graph Type panel (but might be irrelevant if you implement above)
- Spelling errors in the Sort radio buttons
- Linking issue with the Neutral Level controls. Again, read the help on the Likert function and then I suggest this is also a checkbox to optionally specify it.
- The save control has the column names in the drop down, not the existing graphs

Quite a lot of issues, but hopefully, most will be easy to fix and you will see what progress you've made since March!

Once it's in a better state I'm happy to help with the developer error if it's still an issue, although I guess this might get resolved as you redo other parts of the dialog.

**Comment by AlexSananka** [comment]
This sounds great,lot's of ideas here I see.Let me have a go at the dialog again.
Thanks @dannyparsons

**Comment by AlexSananka** [comment]
@africanmathsinitiative/developers  This is ready for review
Note:The` sjp.stackfrq` function allows you to plot multiple variables that have the same categories length for example if one variable has : “never”, “sometimes”, “often” and “always” then the next variable must have exactly the same category lengths as your first category(not necessarily the same names).The plot then prints the stacked frequencies of all variables in a single plot.This is not possible if your variables in the receiver  have different categories length.I know this is a lot of restrictions but at least this is what we have for now.

Though this dialog needs some enhancement,we can work with this now.

**Comment by dannyparsons** [comment]
Thanks for explaining the further improvements needed. Could you copy that into an issue so we remember to do it later?

**Comment by AlexSananka** [comment]
@dannyparsons  This is ready to go in for now.

**Comment by stevenndungu** [comment]
Before it goes in, let  me have  a test of it

**Comment by AlexSananka** [comment]
1.This can change
2.I am also not sure why this isn't doing well,I'll check this with @dannyparsons 
3.We are doing this because of issue 1
4.I thought this is resetting well maybe I can counter check
5.I am not getting this error
6.I think this is what we need.

**Pull request merged**
