### PR TITLE
sdgSummaries/Proportions/Percentiles.

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers  this is ready for review.

**Comment by maxwellfundi** [comment]
@dannyparsons  this is ready for you.

**Comment by shadrackkibet** [comment]
fixes  #3845

**Comment by dannyparsons** [comment]
On the column summaries dialog, could you also swap the buttons around so that the summaries button is above the proportions one?

**Comment by dannyparsons** [comment]
Is this now done?

**Comment by shadrackkibet** [comment]
yes this is done!

**Pull request merged**
