### PR TITLE
Ensured output from Summary dialog is correct

### LINKED ISSUE #8104: Implement the New output system and fix existing bugs
@rdstern, After reviewing the `Describe `menu dialogs with @Patowhiz and @anastasia-mbithe, we identified the following issues that need to be addressed.

**Describe> One Variable** dialogs
- [x]  **Summaries dialog** 
- [x] - Adding save controls to save objects for all the options 

- [x]  **Frequencies dialog**
- [x] - For `Table` option, we remove the **Output option** i.e **Text & HTML** and add save control.
- [x] - For `Graph` Option, fixing the bug
- [x] - Disabling `Both` option for now.
- [ ] - Find a way for the `stem and leaf` option to save an output object.

- [x] **Rating dialog**
- [x] - Adding save control to `Table` option

- [x] **Describe> Two/Three Variables**
- [x]  **Correlation** dilaog
- [x] In `Multivariable` option;
- [x] - Changing save label name
- [x] - Design changes

- [x] **Two Way Frequencies**  dilaog
- [x] In `Table` option
- [x] - Adding save control 

- [x]  **Three Way Frequencies**  dilaog
- [x] In `Table` option
- [x] - Adding save control

**Describe> General**
- [x]  **Column summaries**  dilaog
- [x] - Investigating the `calculate summary` function
- [x] - Adding save options i.e `save table` & `save dataframe`

- [ ] **Describe >Multivariate**
- [ ]  **Principal Component Analysis**  dilaog
- [ ] - Fix a bug where the receivers does not allow  to add variables
- [ ] - Adding save model for the new output system

- [x]  **Canonical correlation**  dilaog
- [x] - Fixing the bug

- [ ] **Cluster Analysis**  dilaog
- [ ] - Reviewing the design
- [ ] - Adding the save control for the new out put window

### PR DESCRIPTION
**Pull request by Vitalis95**
Partially fixes #8104 
@rdstern , @Patowhiz , @lloyddewit - this PR adds save controls to save objects for all the options

### CODE REVIEW

**Comment by lloyddewit** [comment]
@berylwaswa if you can test first, then I can review, thanks

**Comment by berylwaswa** [comment]
@Vitalis95 the save control added to the summary dialog seems to be working okay, however, the okay button is not disabled when I have checked to save and there's no object name assigned to the summary table.

instat_BtCa85HlSI

**Comment by Vitalis95** [comment]
@berylwaswa , have look at it

**Comment by berylwaswa** [comment]
@Vitalis95 this looks fine now.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
