### PR TITLE
Added Choropleth Map dialog.

### PR DESCRIPTION
**Pull request by EstherNjeriLiberatta**
@shadrackkibet Please review this.

### CODE REVIEW

**Comment by EstherNjeriLiberatta** [comment]
Hello @shadrackkibet I've changed the code it should run okay in the script now.

**Comment by EstherNjeriLiberatta** [comment]
Hello @shadrackkibet @HawardKetoyoMsatsi, I've fixed some of the issues I was having but I'm having trouble linking the labels and the colour palette to their respective radio buttons. Please review my code.

**Comment by HawardKetoyoMsatsi** [comment]
Sure, @shadrackkibet let me get to her.

**Comment by EstherNjeriLiberatta** [comment]
Hello @rdstern @shadrackkibet This ready for review.
Fixes issue #6782 Adding the choropleth map dialog. I also added reorder controls to the heatmap I'm yet to code them.
The swap x and y control in the heatmap is working okay.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta I have been trying to review your work, but I am always blocked by files your changes say I have made.  I hope @shadrackkibet can test or you may like to skype and share your screen?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern I'm sorry to hear that. May I share with you on skype tomorrow? I would like you to review it before proceeding with anything else. It would be great if @shadrackkibet could test it too. Thanks.

**Comment by EstherNjeriLiberatta** [comment]
Hello @rdstern This is ready for review. 
I made most of the changes you suggested on issue #6665 and #6802.
i.) The heat map now has a` swap` button and you can` reorder` variables.
ii.) The labels automatically format the numbers with the round function. 
iii.) The multireceiver is now enabled. However, I wasn't able to add value to the fill control as the the code only allows for one receiver to have  `variable` in it.

**Review by rdstern — CHANGES_REQUESTED** [review]
This now seems to work, but I still need more instruction on how to use it to get good maps.
I did try labels.  It gave an error when I didn't have a fill completed.  Then, when I did include a fill it couldn't cope with a character variable.

I was interested in the data set you used, from that survey.  Where was that from?

**Comment by EstherNjeriLiberatta** [comment]
@rdstern I got it from a college.

**Comment by rdstern** [comment]
@EstherNjeriLiberatta is it an interesting study to be able to add into our library?  Do you know the details of the study?  Do you have the objectives, etc.

**Comment by EstherNjeriLiberatta** [comment]
Hello, @rdstern I think it is an interesting study. I don't know about the details or objectives but I can get them. However, it had some confidential information on the respondents' resident location which I had to remove.

**Comment by lloyddewit** [comment]
@rdstern I don't completely understand the current status of this PR. Do you still have open questions or is this PR now ready for review and test?
thanks

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit This is not ready for review yet. Thanks

**Comment by EstherNjeriLiberatta** [comment]
@shadrackkibet could I get some help from you with this?

**Comment by EstherNjeriLiberatta** [comment]
> This now seems to work, but I still need more instruction on how to use it to get good maps. I did try labels. It gave an error when I didn't have a fill completed. Then, when I did include a fill it couldn't cope with a character variable.
> 
> I was interested in the data set you used, from that survey. Where was that from?

Hello @rdstern there was an error when you tried labels but didn't have fill completed because the labels work when you have fill completed. 
I added the round function so that labels automatically format the numbers. When you included a character variable it gave an error because its not numeric.

**Comment by EstherNjeriLiberatta** [comment]
@rdstern This ready for review.

I have been able to create a map with the choropleth dialogue sorry this took so long. 
I added a group control in the choropleth map gotten from `geom_polygon(aes(group=))`. It didn't seem necessary at first but it has helped in creating a map. The group aesthetic determines which cases are connected together into a polygon. In order to create a good map you may need to have a dataset with a column that can act as group in some datasets the variable is named **Id** or **Group**.
I also fixed some of the errors that got introduced when I made the multireceiver in the heatmap dialogue enabled. 

I've added below a dataset you can use to test this.
[mydata.csv](https://github.com/africanmathsinitiative/R-Instat/files/7686790/mydata.csv)

**Comment by lloyddewit** [comment]
@EstherNjeriLiberatta Thank you for this PR. Unfortunately, due to other recent PRs, there are now merge conflicts.
Please could you resolve the merge conflicts and let us know when its ready again for test/review?
Thanks

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit Thank you for letting me know.

**Comment by shadrackkibet** [comment]
@EstherNjeriLiberatta could you sort out the conflicts?

**Comment by maxwellfundi** [comment]
@EstherNjeriLiberatta your conflicts are tricky because there is a resource file conflict too. The designer also has about 10 conflicts with the master. Some of the conflicts are easy to fix because they are an issue of some code of the same control pushed down with new additions. Others are tricky and might cause distortion of the dialogue. Therefore I suggest the following easier and more safe way to have this fixed

1- Update your master 
2- Create a new branch from the master 
3- Copy and paste the changes from the new branch 
4- Open a new PR that will have those changes.

**Comment by EstherNjeriLiberatta** [comment]
Thank you @maxwellfundi

**Comment by shadrackkibet** [comment]
@EstherNjeriLiberatta should we close this now? I see another PR #7143

**Comment by lloyddewit** [comment]
> @EstherNjeriLiberatta should we close this now? I see another PR #7143

@EstherNjeriLiberatta may we close this PR? thanks

**Comment by EstherNjeriLiberatta** [comment]
@lloyddewit Yes, Thank you.

**Pull request closed without merging**
