### PR TITLE
dlgUseDate Design

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready for review

Changes
- design amendments to decrease the depth of the dialog from 515x648 to 505x555

One of the dialogs discussed in #5835

### CODE REVIEW

**Comment by lilyclements** [comment]
New design:

image

**Comment by shadrackkibet** [comment]
Looks better now. 

- I was wondering about aligning **Numeric, Abbr and Name to the left**. 
- Should we also have colons at the end of each? Labels should always end with a colon.
- The starting month Combobox appears too wide to me, I think the size should be reduced.

**Comment by lilyclements** [comment]
Good points, and I agree. Updated it now

image

**Comment by shadrackkibet** [comment]
Looks good to me now. @rdstern  @lloyddewit up to you now to review and approve for merging.

**Comment by lloyddewit** [comment]
@rdstern Please could you approve (using the GitHub approve mechanism)? then we can merge, thanks

**Pull request merged**
