### PR TITLE
Solving Build errors caused by frequency Sub Dialog

### PR DESCRIPTION
**Pull request by Gioche6**
@africanmathsinitiative/developers , This is ready for review
@shadrackkibet , I have fixed the build errors caused by PR #6916. 
I agree they occurred while solving the merge conflict. I wonder why most PRs are getting merge conflicts. I have however fixed this one and runs okay now without affecting the performance of the dialog.
@lloyddewit , Could you test and merge if its okay to get rid of the build errors ? 
Thank you.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
Seems to work for me.

**Comment by maxwellfundi** [comment]
@Dennis Gioche ***@***.***> merge conflicts are common when
two people make changes to the same document. I suggest a practice of
frequently updating your branches from master to avoid conflicts.

**Comment by Patowhiz** [comment]
@lloyddewit @shadrackkibet could this be prioritized for review. We now have a 'broken' master which I had merged its changes, and I'm needed to look into issue #7006 urgently.

Thanks.

**Review by shadrackkibet — APPROVED** [review]
@maxwellfundi please approve and merge.

**Comment by lloyddewit** [comment]
@Gioche6 There have been lots of merge conflicts in the last days. I think because large numbers of files were changed for the new Linux version. I agree with @maxwellfundi that occasional merge conflicts are unavoidable.

**Comment by lloyddewit** [comment]
@shadrackkibet @maxwellfundi @Gioche6 @rdstern Thank you for resolving this so quickly.
The master branch should never be broken. To prevent this happening again, I suggest:

- The tester (normally @rdstern or his delegate) should always do a sanity check before approving a PR that was already tested/approved, but has since changed. The sanity check should include building the PR. I think it makes sense for the testers to do this check because the peer review is focussed on analysing the source code and won't always involve building the software.
- I also agree with @maxwellfundi 's comment in PR #6916 that we should normally never manually edit `.resx` or `.designer.vb` files.

**Comment by dannyparsons** [comment]
Thanks Stephen this is a useful process.

Related to this, Chris recently made a PR which changed all dialogs back to `Localizable = False`. This was previous used for the old translation system but now no longer needed. This now means that all designer details will be the designer file and the resx file will remain static. This should also avoid some conflicts and issues as there will only be 2 file changes per dialog. There are no software functional changes but from now on, or if any old ones are found, keep `Localizable = False` (the VB default).

**Pull request merged**
