### PR TITLE
Added new dialog for finding points in a polygon

### LINKED ISSUE #5422: Finding points in a polygon?
From where we are now, this would be very useful, but I don't know how to do this. 

Here is my problem.  In each country with climatic data we are being given the station data to draw on a map.  The station file needs checking - in each case.  Often, for example in Tanzania, the station file does not include the region, or the district variables.  It would be helpful if it did, both to support checking and also for the plotting.  I have the polygons from the gadm file and also the locations (lat and long from the station file.  

So I would like to do a sort of merge.  I think the answer is [here](https://gis.stackexchange.com/questions/282750/identify-polygon-containing-point-with-r-sf-package/318629#318629)?

If so, then it may be quite easy?  It would certainly be useful and appreciated!  Not just by me!

If it is really easy then I wonder where it should go in the menu system?  It is essentially a merge, but a pretty special one.  Perhaps it should go under the mapping, which would now have a map sub-dialogue and an Add Variables dialogue.

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #5422
@maxwellfundi , @rdstern @dannyparsons @shadrackkibet @lloyddewit  This is ready for review kindly take a look.

### CODE REVIEW

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern the changes e agreed upon have been made, kindly take a look.

**Review by rdstern — APPROVED** [review]
Great to see this working

**Review by shadrackkibet — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi This dialog needs to be now enabled from the frmmain.

**Comment by shadrackkibet** [comment]
Note that this dialog currently works with only `level-0` shapefiles i.e boundary. It is easy to enable other levels to work, we just need to use `sf::st_combine()` which will combine several feature geometries into one.  @rdstern would you like this addition?

**Pull request merged**
