### PR TITLE
Adding library(circular) function to before code

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes#5336

@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by dannyparsons** [comment]
I'm happy with this solution of loading the package, but the `circular` package only needs to be loaded for the circular distributions, otherwise the code will look confusing if I use a non circular distribution is used.

So instead of adding the library() function to the before codes in the defaults, you can just check when the distribution changes, if its circular, add it, if not, remove it.

**Comment by Wycklife** [comment]
@dannyparsons The condition has been set.

**Comment by Wycklife** [comment]
@dannyparsons Changes has been made.

**Comment by dannyparsons** [comment]
Great. Have you checked all the other distributions too. I wonder if any others depend on a package?

**Comment by Wycklife** [comment]
Yes, other distribution are working well without the library(), 
@stevenndungu Could you please review this.

**Comment by rdstern** [comment]
Good.  Please check the Extreme Value distribution.  That was another one that doesn't work currently.  That's in the extRemes package.  It may also have been fixed?

**Comment by stevenndungu** [comment]
Extreme value distribution has an error and apparently adding package extRemes does not solve the problem. The error is;
image


Hypergeometric distribution has this error.
image

The rest i find them to work work well

**Comment by rdstern** [comment]
The error in the extreme value distribution is odd.  An example of the command line is:

last_graph <- mosaic::qdist(dist="evd", p=c(0.5), shape=0, scale=0.5, loc=0)
So where has the code c(0,0.001, 0.999,1) come from?  Is it within the qdist code, or did we produce it?
Because I don't understand why we need that.  And it is the 0 and 1 in that line that has given the error.

**Comment by maxwellfundi** [comment]
@dannyparsons @Wycklife I am suggesting that, we have then temporarily hide the distributions that have issues if we can not find a quick fix for now- it will just be the Extreme value, which needed better defaults and hypergometric. The von Mises is okay. 

@rdstern would you be happy with this?

**Comment by rdstern** [comment]
ok by me.  I am disappointed with the extreme value distribution not working, but looked briefly and can see what's wrong, but not where it comes from!

**Comment by maxwellfundi** [comment]
great @Wycklife  If you could look at leving out these two on the distributions list would great!

**Comment by Wycklife** [comment]
@maxwellfundi I'm looking at it now

**Comment by dannyparsons** [comment]
Ok I'm happy with that

**Pull request merged**
