### PR TITLE
Implemented the drop unused levels checkbox in the Column Summaries dialog

### LINKED ISSUE #8730: Implement the Drop Unused Levels checkbox in the Column Summaries dialog
This is the second of three improvements in the R-Instat Summary system.  It also awaits a check with @volloholic.
The Drop unused levels checkbox is in the existing dialog, but disabled.  I suggest it be implemented - as long as it doesn't "open a can of worms".   
If it does, then the implementation remains on our to-do list, but the disabled option should have the checkbox ticked, because it currently does remove the unused levels.
My possible concern is that the current system works very nicely with a filter in operation and I want that to remain.  I hope it isn't dropping levels as its way of accomodating the filter.
There are perhaps 2 separate situations on the levels.  
a) A single factor could haved unused levels.
b) Each factor could be ok, but there are some zero frequencies in the combinations.  For example, in the survey data, Variety has 3 levels and Village has 4 levels, but only 10 of the 12 combinations are non-zero.  Currently we only give the 10 combinations.

Note that one way of getting the unused levels in the summaries would be to proceed initially with the summaries as now.  Then get the cross factor (forcats) with all levels and then merge with the data.  The only complication I forsee is that the cross factor would have to allow for a filter being in place.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #8730
@rdstern I made the change as requested for the drop unused levels checkbox. @lilyclements can now make the change in the calculation system.

### CODE REVIEW

**Comment by rdstern** [comment]
@lilyclements I am under the impression you have the change in R, but had "hard-wired it, in your version to test.  I hope it could now be included in this pull request, as the condition that the by variables have to be factors is now there.  The checkbox should be disabled if they are not.

**Comment by rdstern** [comment]
@lilyclements can you incorporate your new code in this pull request, so the option can be completed?

**Comment by rdstern** [comment]
@lilyclements are you ok to add your magiv here.  You said you had the solution, but "hardwired".  Note it will be needed again later in the Tables dialog.

**Comment by lilyclements** [comment]
> @lilyclements are you ok to add your magiv here. You said you had the solution, but "hardwired". Note it will be needed again later in the Tables dialog.

@rdstern as you pointed out the changes are in #8794 - thanks!

**Comment by rdstern** [comment]
@lilyclements I am unable to test changes just now (misplaced laptop!).  It would be great if this now works.  Could you test?

**Comment by rdstern** [comment]
@lilyclements has agreed to test this.  Then, or in parallel, could @Patowhiz check the code and merge.  This is an important new feature in the calculation system.  (It is also helping an improvement in the climatic dialogs.)

**Comment by rdstern** [comment]
@N-thony if I understand correctly, then the check unused levels should not be disabled.  Let me give an example to check the different options now are possible,
In the survey dataset, if you summarise yield by both the variety (3 levels) and village (4 levels), then you get a summary data frame with either 10 or 12 (3 times 4) rows.  

image

In the past there were always 10 rows, because 2 combinations have zero frequencies.  (NEW variety is only in 2 of the 4 villages.)  

image

Now, with the @lilyclements and your changes, the user can choose - depending on the state of the ``Drop Unused Levels ``checkbox.

So if you don't drop the unused levels then I think you should now get the following table.  

image

I suggest the 10 rows remain the default, so the Drop Unused Levels checkbox is checked by default.

**Review by lilyclements — APPROVED** [review]
@N-thony looks good! Approving now, @Patowhiz over to you

**Comment by rdstern** [comment]
@Patowhiz this is a small, but important improvement.  I'll explain when we meet.  It links to "your" tables too!  Hope the code is ok, so it can be merged.

**Comment by rdstern** [comment]
@Patowhiz I am back testing again and very happy with this new feature.  Over to you to check and merge.

**Review by Patowhiz — APPROVED** [review]
Thanks for reviewing this @lilyclements

**Pull request merged**
