### PR TITLE
Adding the three Variable functionality to the Describe> Two\Three Summary dialogue

### PR DESCRIPTION
**Pull request by Ivanluv**
This PR has implementation for the three variable functionality to match the  `Three Variable` radio button  option on the Describe> Two\Three Summary dialogue

This is still in progress

### CODE REVIEW

**Comment by rdstern** [comment]
@Ivanluv and @lilyclements this is useful to clarify what is needed from 3 variables.  
I suggest you include the 2 variables at the same time, and build on the one variable case that is now finished.
The usual survey data will do as an example.  
a) The **_One variable > Summarise > Customised_** has everything now (I think), except the `Format Table` button, which we can add later, once it is complete. 
b) The **_Two > Variables > Categorical (Many) by Categorical_** gives **_Frequency tables_**, and is also complete (I think) except for the `Format Table` button, to come later.
c) The **_Two > Variables > Numeric (Many) by Categorical_** gives **_Numeric Summaries_** and still needs to use the new table system.  
d) Then there is your 3-variable stuff, which is to use the new tabulation "system".  Of course there are 8 combinations here, but I am particularly interested in 2 way summary tables.  There are 2 possibilities here 
1. Numeric (many) by Factor, by Factor.  For example (yield, size, fert) by Village, by Variety.  This will give 3 two-way summary tables for each summary variable, e.g. mean, sd.
2. Factor (many), by Factor, by Numeric - which you have started.   For example Village, Variety, by Fertlevel, by Yield.  This will give 2 summary tables, namely Village by Fertlevel and Variety by Fertlevels for each of the mean yields, and sd of the yields.

e) For the 3-variable options we might include the box on the left for the 2 variables which has numeric by categorical, etc.  And (initially) just have numeric by categorical (2)  and categorical (2) by numeric as the only options allowed.  2-way summary tables are then what's provided!

f) And the top button might then (at least for now) have 3-variable summary - so it isn't everything for the 3 variables.

**Comment by Ivanluv** [comment]
```
survey <- data_book$get_data_frame(data_name="survey")
multiple_receiver_cols <- c("size","fert")
list_of_tables  <- survey %>% purrr::map(.x=multiple_receiver_cols, 
                                         .f= ~data_book$summary_table(data_name="survey", summaries=c("summary_count","summary_sum"), factors=c("variety"), columns_to_summarise=c(.x))) %>% purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) + mmtable2::header_left_top(variable="variety") +
                                                                                                                                                                                         mmtable2::header_top_left(variable='summary-variable'))

names(list_of_tables) <- multiple_receiver_cols

list_of_tables
rm(list=c("list_of_tables ", "survey", "multiple_receiver_cols", "names(list_of_tables)"))
```
@lilyclements I have tried modifying the **Categorical by Categorical** code we previously had and came up with the the above code ,for the Two > Variables > Numeric (Many) by Categorical  option. Is this code correct?

**Comment by Ivanluv** [comment]
> 1. Numeric (many) by Factor, by Factor.  For example (yield, size, fert) by Village, by Variety.  This will give 3 two-way summary tables for each summary variable, e.g. mean, sd.



```survey <- data_book$get_data_frame(data_name="survey")
multiple_receiver_cols <- c("size","fert","yield")
list_of_tables  <- survey %>% 
  purrr::map(.x=multiple_receiver_cols,
             .f= ~data_book$summary_table(data_name="survey",
                                          summaries=c("summary_count","summary_sum"),
                                          factors=c("variety","village"),
                                          columns_to_summarise=c(.x))) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_left_top(variable="variety") +
               mmtable2::header_top_left(variable="village") +
               mmtable2::header_top_left(variable="summary-variable"))

names(list_of_tables) <- multiple_receiver_cols

list_of_tables
rm(list=c("list_of_tables ", "survey", "multiple_receiver_cols", "names(list_of_tables)"))
```
Is this correct?

**Comment by lilyclements** [comment]
@Ivanluv this code looks good to me. Have you tried checking them in R?

**Comment by Ivanluv** [comment]
@lilyclements Thank you for looking at this. Both codes are working  in R  from my end. This is the output of the second piece of code from R
image

**Comment by lilyclements** [comment]
@Ivanluv great! I thought it might be just an issue my end so I didn't want to spend too long diagnosing it. I think it's just that an R package or two aren't installing. Thanks.

**Comment by Ivanluv** [comment]
The latest changes have the following improvements
- The Two > Variables > Numeric (Many) by Categorical are now Summary 
  Tables that use the new system
-  The Numeric (many) by Factor, by Factor are now 3 two-way summary tables  
- Factor (many), by Factor, by Numeric are now 2 way summary tables

I have also added the summary sub dialogue  for the summary table but am getting an error which @lilyclements  could help me with i.e

image
image
image
This also happens for the Three Variable Numeric by Categorical Option.  I think this might be as a result of having `columns_to_summaries=.x` .

**Comment by Ivanluv** [comment]
@lilyclements  when for the Three Variable ,Numeric by categorical option, I get an error when I have two similar columns for the last two receivers .For example 
image

image
image

**Comment by lilyclements** [comment]
@Ivanluv can you update from the master and see if that helps?

**Comment by Ivanluv** [comment]
> @Ivanluv can you update from the master and see if that helps?
 @lilyclements  Am still getting the errors after updating the branch

**Comment by Ivanluv** [comment]
@lilyclements  have you looked at this?

**Comment by rdstern** [comment]
I started with this:
image

When I leave it with just the Total N as the summary, it works, though I only seem to get one table.  If I add a summary, like the mean, then it gives 3 errors - did you check this?

image

Then I tried three way frequency tables, see below:
image

This gives the same error as above, as though it is still using the summaries from the example above?  Aha yes, if I reset, then it seems to work.  Great.  

The other combination of numeric by factor, by factor.  Again that gives an error if I ask for the mean.

**Comment by Ivanluv** [comment]
> I started with this: image
> 
> When I leave it with just the Total N as the summary, it works, though I only seem to get one table. If I add a summary, like the mean, then it gives 3 errors - did you check this?
> 
> image
> 
> Then I tried three way frequency tables, see below: image
> 
> This gives the same error as above, as though it is still using the summaries from the example above? Aha yes, if I reset, then it seems to work. Great.
> 
> The other combination of numeric by factor, by factor. Again that gives an error if I ask for the mean.

I was also getting the same error have requested for @lilyclements help with that

**Comment by lilyclements** [comment]
> @lilyclements when for the Three Variable ,Numeric by categorical option, I get an error when I have two similar columns for the last two receivers

@Ivanluv the issue here is that we use "variety" twice, but, the `summary_table` code makes it just one "variety" variable, and then `mmtable2` calls "variety" twice and is confused because `mmtable2` does not know the difference between the two "variety" variables.


```
... + mmtable2::header_top_left(variable = "variety") + mmtable2::header_left_top(variable = "variety") + ...
```

So our question is then what do we want to do about using the same variable multiple times?
1. We do not allow the user to use "variety x variety" on the dialog
2. We allow the user to use "variety x variety" on the dialog, and change the dialog code for `mmtable2` code to be that if the variable is the same in two receivers, then mmtable2 should only add it in once so we don't have
```
... + mmtable2::header_top_left(variable = "variety") + mmtable2::header_left_top(variable = "variety") + ...
```
But instead have
```
... + mmtable2::header_top_left(variable = "variety") + ...
```

I think option 2. is more suitable because it catches issues like if we have a whole set of variables in one receiver (or use the future "select" option!). @Ivanluv what do you think?

**Comment by lilyclements** [comment]
> I was also getting the same error have requested for @lilyclements help with that

@Ivanluv @rdstern I am not getting this error if I run in R. Can you give the script that is returned in R-Instat? Given the error and that it worked upon reset for @rdstern I'm wondering if the issue is that something isn't being added in the dialog code?

The script I'm trying in R

```
survey <- data_book$get_data_frame(data_name = "survey")
multiple_receiver_cols <- c("yield", "fert")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ data_book$summary_table(data_name = "survey",
                                            summaries = c("summary_count", "summary_mean"),
                                            factors = c("village"),
                                            include_margins = TRUE,
                                            margin_name = "All",
                                            columns_to_summarise = .x)) %>%
  purrr::map(.x = .,
             .f = ~ mmtable2::mmtable(data = .x,
                                      cells = value) +
               mmtable2::header_top_left(variable = "village") +
               mmtable2::header_left_top(variable = "summary-variable"))
```

**Comment by Ivanluv** [comment]
> > @lilyclements when for the Three Variable ,Numeric by categorical option, I get an error when I have two similar columns for the last two receivers
> 
> @Ivanluv the issue here is that we use "variety" twice, but, the `summary_table` code makes it just one "variety" variable, and then `mmtable2` calls "variety" twice and is confused because `mmtable2` does not know the difference between the two "variety" variables.
> 
> ```
> ... + mmtable2::header_top_left(variable = "variety") + mmtable2::header_left_top(variable = "variety") + ...
> ```
> 
> So our question is then what do we want to do about using the same variable multiple times?
> 
> 1. We do not allow the user to use "variety x variety" on the dialog
> 2. We allow the user to use "variety x variety" on the dialog, and change the dialog code for `mmtable2` code to be that if the variable is the same in two receivers, then mmtable2 should only add it in once so we don't have
> 
> ```
> ... + mmtable2::header_top_left(variable = "variety") + mmtable2::header_left_top(variable = "variety") + ...
> ```
> 
> But instead have
> 
> ```
> ... + mmtable2::header_top_left(variable = "variety") + ...
> ```
> 
> I think option 2. is more suitable because it catches issues like if we have a whole set of variables in one receiver (or use the future "select" option!). @Ivanluv what do you think?

I also prefer the second option. But won't this mean that we are producing a two way summary table within the three variable option?

**Comment by lilyclements** [comment]
> I am still getting the error after updating my branch. This is the code in the output window image Am also getting the error in Rstudio image could you maybe try updating your branch? The error occurs when I have any other summary apart from `summary_count`

@Ivanluv Did you try the R code I posted in my comment that I said worked for me?
In the future, I suggest you do try these things out as you can then run my script and your script adjacent to each other. This can help eliminate if the issue is due to the branches being different, or the code being different.
If you find the issue is in the code being different, you can compare line by line to work out what is working in script A that is not working in script B.
I have found the issue - the parameter name is misspelt in the dialog code. It is meant to be `columns_to_summarise`, not `columns_to_summaries`.
Since I was using a screenshotted version, I didn't pick up on the typo when copying the code into R. Can you in the future copy and paste the R script, or send a file containing the R script, and not give screenshots of the code?

**Comment by Ivanluv** [comment]
> 2\. The multiple receiver clears as I switch between buttons at the top

That's because the first radio button, `skim`, option uses variable of any data types while the two and three variables  options are restricted to numeric only or categorical only data types

> 4\. Under "Three variables" is "Numeric Variable (Optional)", but I can put a factor in, and it isn't optional. Can this be relabelled?

I have renamed this to `Third Variable :`.



> 3\. Under "Three variables" it says "numeric by categorical", but there are three variables here. Should it say "numeric by categorical by numeric" (if those are the classes I have, of course). What do you think?

I agree with you on this. But since the second variable will always be a categorical, for now, can I just add a  label with  `categorical` as the text?

> 1. Under "Two variables", if I put village and variety in the multiple receiver, I then can't put a factor variable in the "second variable" receiver

`fertgrp` should be available. I added the restriction of not having the factor variables selected in the first receiver available in the second receiver

**Comment by lilyclements** [comment]
> I agree with you on this. But since the second variable will always be a categorical, for now, can I just add a label with `categorical` as the text?

Sounds like a good solution to me.

> `fertgrp` should be available. I added the restriction of not having the factor variables selected in the first receiver available in the second receiver

Great!

@Ivanluv let me know when this is ready for re-review and I'll take a look :)

**Comment by Ivanluv** [comment]
@lilyclements could you have a look

**Review by lilyclements — COMMENTED** [review]
@Ivanluv looks good. There is an issue with the second receiver still.

* Click Two Variables
* Insert village, variety as first variables / field as second variable
* Press OK
* Reopen
* Press reset
* Only numeric variables are now allowed in the multiple receiver under "Two Variables"

**Comment by Ivanluv** [comment]
> @Ivanluv looks good. There is an issue with the second receiver still.
> 
> * Click Two Variables
> * Insert village, variety as first variables / field as second variable
> * Press OK
> * Reopen
> * Press reset
> * Only numeric variables are now allowed in the multiple receiver under "Two Variables

Looking at this now

**Comment by rdstern** [comment]
@lilyclements the changes a) and b) from #7589 are great.  The only error I could find was with date variables, when I asked for percentiles (p25 and p75).  I used the Dodoma data from the library.  It said:
image

By the way, the median works ok for dates.

As you say, items c) and d) are for @Ivanluv.  It would be great if he could include them.  I am liking both of them to be added and then described in the help (by me) and videos (by Beryl).

**Comment by Ivanluv** [comment]
> @Ivanluv looks good. There is an issue with the second receiver still.
> 
> * Click Two Variables
> * Insert village, variety as first variables / field as second variable
> * Press OK
> * Reopen
> * Press reset
> * Only numeric variables are now allowed in the multiple receiver under "Two Variables"

@lilyclements this occurs when I try restricting factor variables ,selected in the multiple receiver, from being available in the second receiver. This approach introduces more complications. Could we instead have messages to inform the user that they will get an error when two or more similar variables are selected in the the different receivers?

**Comment by lilyclements** [comment]
This is replaced by PR #7920

**Pull request closed without merging**
