### PR TITLE
Added Save Control to Transform Dialog

### LINKED ISSUE #6314: Add a position button to the New Column Name control in  Climatic>Prepare>Transform
I am going through the Transform dialog. I have a new column being added to the existing data frame. I would like to position this column without using the reorder columns method. Below is the screenshot what I was doing. I think it should be implemented for all the options.

image

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #6314 and item (m) in issue #6080.

This will only be ready for review once PR #6285 is merged. It contains changes from that PR.

### CODE REVIEW

**Comment by dannyparsons** [comment]
@Patowhiz I renamed the issue to something that's more release notes friendly, I hope I've captured the work in the PR.

**Review by rdstern — COMMENTED** [review]
@Patowhiz I assume this is still work in progress.  In Climatic > Prepare > Transform the Save label needs the colon and the save control should be closer.  I assume that will change once the Position part of the control is added.

**Comment by Patowhiz** [comment]
@rdstern yes. This PR will immediately be ready for review once PR #6285 is merged. All necessary changes have already been made.

**Review by rdstern — COMMENTED** [review]
@Patowhiz I only checked as far as noticing that the position control wasn't there for the Climatic > Prepare > Transform

So there is still a bit to do for next time I am afraid!

**Comment by Patowhiz** [comment]
@rdstern this is now ready for you.

**Review by rdstern — APPROVED** [review]
@Patowhiz great - looks fine
@lloyddewit for the final check

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
