### PR TITLE
DB Translation for Prepare > Column:Numeric

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes partly #8053

DB Translations for Transform dialogue
image

DB Translations for Random Sample dialogue
image

DB Translations for Permute/Sample Row dialogue
image

DB Translations for Reorder Levels dialogue
image

### CODE REVIEW

**Comment by lloyddewit** [comment]
@derekagorhom 
Thank you for this.
Please could you always indicate if a PR is ready to review/merge or is still ongoing. If it's ongoing, please set the PR to 'draft' (see below), thanks


image

**Comment by derekagorhom** [comment]
Sorry @lloyddewit i was not done with dlgReorderlevels, i will push the remainding changes soon

**Comment by derekagorhom** [comment]
DB translation for dlgReorderlevels
image

**Comment by derekagorhom** [comment]
@lloyddewit you can merge this now

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
