### PR TITLE
Taylor diagram bug when the same variable is used as group and type

### LINKED ISSUE #6062: Taylor diagram bug
When the same variable is used as a station and group as shown below then the dialog bugs!
image

Clearly, the function doesn't allow this from the error output.
image

The only way to avoid this error is to ensure that once a variable is in either of the two receivers then that is removed from the selector.

### PR DESCRIPTION
**Pull request by shadrackkibet**
Fixes #6062. @africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv please could you review? thanks

**Comment by lloyddewit** [comment]
@Ivanluv please could you review? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  this is looking okay from my end

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Review by dannyparsons — APPROVED** [review]
code changes look ok, happy if functionality has been tested

**Review by rdstern — APPROVED** [review]
ok

**Pull request merged**
