### PR TITLE
Modified the plot options in Mosaic Plot dialog

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes (partially) #7556,
Modifying the plot option control in Mosaic Options
@N-thony , this PR is ready for review

### CODE REVIEW

**Comment by lloyddewit** [comment]
@N-thony Can @rdstern test in parallel or is it more efficient for you to test/review first?
thanks

**Comment by N-thony** [comment]
@Fidel365 I'm not able to see the down arrow button
image

**Review by N-thony — APPROVED** [review]
@lloyddewit over to you

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge, thanks

**Review by rdstern — APPROVED** [review]

**Pull request merged**
