### PR TITLE
adding new files to the website

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons I have now updated the website files with the new ones with an the ones with a "facelift" from @derekagorhom and @mmulahvictor. Once we merge this then we have the "new" webiste. I think we can merge this and continually add things as needed over time.

**Comment by maxwellfundi** [comment]
@dannyparsons  @rdstern @lloyddewit  please approve this.

**Comment by dannyparsons** [comment]
Ok thanks, I think it needs a careful review then before we make this change to the website.

**Comment by maxwellfundi** [comment]
@dannyparsons  you are right. This can be reviewed from here  - https://maxwellfundi.github.io/New-R-Instat-website/index.html

**Comment by rdstern** [comment]
I saw I am listed to evaluate this pull request for @maxwellfundi.  So I looked at it today and immediately found so much to change.  And please can this pull request be written to help reviewers a bit more too. 

The last entry above is Nov 13.  Usually the successive entries say what has been done recently, so that we can see what to check.  So please can changes be described here.  

I looked at just one entry and that is the FAQ.  I find:
a) It is still the old set of FAQs, not the new ones.  They are for the old Instat, though they look as though they are for R-Instat
b) At the bottom it gives a link to the new set.  And the link doesn't work.

This seems all pretty poor progress for what is now over a year of work.  I thought @volloholic had a new plan that would come to fruition about now?  Is that somewhere else?

Anyway I suggest @rachelkg is a better reviewer of the forthcoming website than I am.  I also have not found any response yet to her e-mail message of 16 Nov.  Perhaps the replies can come here?

Here it is:
```
 I feel very unsure that this is an improvement on the old website. 

Here is an initial list of critiques:

•	The FAQ page does not seem to relate to the other pages, in look, colour or layout. 
•	The spacing and size of the clickable items on the resources and download page are odd and make it hard to see what is going on.  
•	The spacing and ratio of the fonts seems odd, the top items are smaller than the bottom...
•	The ratio of the big band at the bottom does not relate to the items in it. The items in the bottom band are all very close together.
•	The people's photos are oddly stretched.
•	The photos on the front page are boring and unappealing.
•	The colour scheme is unrelated to R-Insat.
•	Everything seems sort of squashed into a centre column on most of the pages and then too wide on the FAQ page. 
•	The resources button is not in line with the other items.
•	The dataset item doesn't work.
•	Home and R-Instat both go to the same place. 

My main concern though is that there does not yet seem to be any design about this site yet. 
I sent examples to look at last time. I feel as though these are possibly programmers. 
Therefore they should be able to build a website, but there needs to be a design element to their skill set. 
It isn't clear that the need for this key skill is recognised.
```

We have now just been reviewed and that made me look at the sites of some of our competitors - there are 8 of them!  As an example I found the jamovi site very tempting.  Once I looked at that site, I wondered why anyone should consider any other package.

**Comment by rachelkg** [comment]
I agree with your comment about the jamovi website! It looks great. Very clean, clear and well designed. https://www.jamovi.org/

**Pull request closed without merging**
