### PR TITLE
Added text on Json File and Minor Design on Correlation, New Data Frame Dialog and Data Options Sub dialog.  

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes issue #7647.
Fixes issue #7649.
Fixes (partially) #7679 
@N-thony Please approve the tanslation of  **PICSA Crops** that I made in Crowdin. And it look like there is not yet mechanism to translate this?

image

Fixes (partially) #7599 
For **Lits, Category, Lits:**, and **Try** , I think we @derekagorhom can solve it by adding controls? Because they are all in Crowdin

image

### CODE REVIEW

**Comment by MeSophie** [comment]
@lloyddewit , @N-thony In the new build **Adjust variable** (Describe>One Variable>Visualize Data) is still is not translate because this PR is not yet merge.

image

This minor Design Adjustment on Correlation dialog (Climatic>Compare>Correlation ) will be also solve with this PR.
image.

**Comment by lloyddewit** [comment]
@MeSophie I understand that we can merge when:
- @N-thony needs to review the translations
- @rdstern needs to test

Is that correct or do you still wish to make changes?
thanks

**Comment by N-thony** [comment]
> @MeSophie I understand that we can merge when:
> 
> * @N-thony needs to review the translations
> * @rdstern needs to test
> 
> Is that correct or do you still wish to make changes? thanks

@lloyddewit everything seems fine on my side.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge, thanks

**Review by rdstern — APPROVED** [review]

**Pull request merged**
