### PR TITLE
Added the tidy broom dialog to use model

### LINKED ISSUE #5647: Add broom to the Model > Use Model menu
Initially this is easy, but there will then - or in parallel - be more work to do!  This needs advice from @dannyparsons and David.
broom is designed to use models in a tidy way, so I suggest it becomes the first in the tab order of the packages.
a) There are just 3 commands, namely augment, glance, tidy.  They all work trivially, i.e. initially we just put them in as they stand.  Then, for example after an lm(yield~fert) in the Model > Model dialogue, each can just be used as it stand, 
broom::augment(last_model)
broom::glance(last_model)
broom::tidy(last_model)

The results go into the output window.  That's a good start.
But each produces a tibble (data frame) object.  So the next step will be to be able to save the data frame - as an object - which we can do - and then be able to see it in the grid as a tabble (data frame!)
The augment could hopefully be a separate data frame, or add variables to the data frame that produced the model - that's what broom is designed to do.

At the same time there are some minor edits to the Use Model dialogue:
a) It is too wide and that looks messy.  Let's make narrower.
b) It is too short, so the last row is cut off.  Make it a bit longer.
c) More difficult - the Help on General doesn't work - no package called General!  This is a bit more complicated, because there are multiple packages used here.  I am not sure what to do here - it needs a bit of discussion, partly because it should be done quickly!

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5647

This is working for a single model for now!

@africanmathsinitiative/developers  This is ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
This works, as far as it goes.  There are 2 next steps to undertake.  It needs to write to a new data frame.  The controls are there, but ignored by the command.

And it needs to be able to do this for multiple models.  Then I also suggest the dialogue could usefully move to the Compare Models section

**Comment by Wycklife** [comment]
@rdstern The changes are noted! But for the implementation for the data frame and multiple models, I will need @volloholic help.

**Comment by Wycklife** [comment]
@rdstern This is ready for you.

**Comment by Wycklife** [comment]
@rdstern  Done!

**Pull request merged**
