### PR TITLE
Added Penman Monteith Constants Sub dialog On Evapotranspiration Dialog.

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes partially #7060  
Fixes partially #7061
@lloyddewit ,  @Patowhiz,  @berylwaswa  Please can some one have a look on it?
@rdstern I added a Constants sub dialog on PM method. I also move all missing controls on one Sub dialog (So I created also one sub dialog for each method ). As you can see this branch didn't have **Priestley-Taylor method**. This is because i lose my last branch. I will  Add It may be today also.
I dont know if we have to add more on this Constants sub dialog. But all constants required for PM using **evapotranspiration** package are there.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@berylwaswa Please can you test? thanks

**Comment by lloyddewit** [comment]
@rdstern I discussed briefly with @berylwaswa . She looked at this and believes it is one of the PRs it is best for you to test.
Thanks for your understanding.

**Review by rdstern — COMMENTED** [review]
@MeSophie that is excellent progress.  Well done you and I assume @Patowhiz?  There is still work I am afraid, but I can now see the finishing line and I think it could be really nice. 

For reference I used the Bohicon data that has a single year and is from the Excel file in the climatic library.  I added a date variable - making it 1/1/2021 to 31/12/2021 (any non-leap year will do.  Then I defined it as climatic and was releived to see we now have all those elements in the definition.
 
a) Could you arrange for all elements to be filled automatically, once the data are defined as climatic.  See below:  @N-thony can help on this perhaps.
b) Check with @Patowhiz perhaps, and I will also check with @dannyparsonsI think you need a separate sub-dialogue for the locations.  I assume you will need this for all methods, so it can be a single `Locations` button. This should give the Locations part of your existing sub-dialogue.  It will have the usual selector and then 4 single receivers for Station, Latitude, Longitude,  Altitude.  I suggest we need to improve the Define Climatic dialogue to include these, and then - for climatic data - they would also be completed automatically.  But you could select those variables.  For now you could perhaps copy over largely the existing part of your dialogue, but not with the up-down for altitude.  (It will only work for one station now.)
c) Then I suggest you have a single Constants button with Tabs for each method.  So each method has the same 3 buttons. (Stations, Constants, Missing) You go automatically to the corresponding tab for each method.
d) Then I was relieved that it did work.  It should not produce any results in the output window.  And I only expected one variable, but haven't followed the full calculations enough yet.  It just gave NA for the Evap column?

**Comment by N-thony** [comment]
@MeSophie is this ready for review?

**Comment by MeSophie** [comment]
> @MeSophie is this ready for review?

@N-thony  Yes we can review it.

**Comment by N-thony** [comment]
> > @MeSophie is this ready for review?
> 
> @N-thony Yes we can review it.

@anastasia-mbithe can you peer review this?

**Comment by MeSophie** [comment]
@rdstern   I pull the new  changes of Define climatic on this dialog. Location can be now fill automatically.

**Review by anastasia-mbithe — COMMENTED** [review]
I have tested using the bohicon data and it looks & works well.

**Comment by N-thony** [comment]
> I have tested using the bohicon data and it looks & works well.

Good, can you check the code too?

**Review by anastasia-mbithe — COMMENTED** [review]
The code looks good

**Review by N-thony — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern Please can you retest? thanks

**Comment by rdstern** [comment]
@MeSophie I get build errors, which I hope you can resolve?  @jkmusyoka will be testing this pull request from Monday and we aim to merge during the sprint.

**Comment by rdstern** [comment]
@MeSophie I was verey pleased to hear you are continuing to work on this dialog this week.  I note there are related dialogs #8147 and #8118 to consider as well.  Remember you also have @jkmusyoka as a tester of these dialogs.  He has a busy week on the Mozambique course, but I hope is now ready to work with you on these dialogs.

**Pull request closed without merging**
