### PR TITLE
Fixed small bugs in Add Prepare > Data Frame > Add (Merge) Data dialog

### PR DESCRIPTION
**Pull request by N-thony**
Fixes (partially) #7777
@lloyddewit @rdstern this fixes part b) of the corresponding issue

### CODE REVIEW

**Comment by rdstern** [comment]
@derekagorhom and @N-thony am I correct in waiting for item a) to be fixed, before checking?

**Comment by N-thony** [comment]
> @derekagorhom and @N-thony am I correct in waiting for item a) to be fixed, before checking?

@rdstern I'm sharing this with @derekagorhom , for item b) this is ready for your test. Please test

**Review by rdstern — COMMENTED** [review]
@N-thony thanks and the bug is fixed.  But it is still giving an extra copy of the list variable from the x.  Perhaps that is a feature?  here is what I got.
image

It has correctly passed the binary data, and then also added another copy of the primes, which it has called list.x!

These are minor inconveniences so you may decide to abandon the problem for now?

**Comment by N-thony** [comment]
> @N-thony thanks and the bug is fixed. But it is still giving an extra copy of the list variable from the x. Perhaps that is a feature? here is what I got. image
> 
> It has correctly passed the binary data, and then also added another copy of the primes, which it has called list.x!
> 
> These are minor inconveniences so you may decide to abandon the problem for now?

@rdstern I suspect that you have done the operation twice i.e returning to the dialogue and clicking `Ok` again, it is only in that case you will have an additional `list` column otherwise you will only have `list.x` and `list.y`

**Comment by rdstern** [comment]
@N-thony I don't think so.  list is there from the start, and it seems another copy has been made into list.x, while from the other data frame it has correctly copied list.y.  But I will check.

**Review by rdstern — APPROVED** [review]
@N-thony I suggest there are more important improvements than this one for now.  
So I am approving.  I am happy that the issue is just partially done.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
