### PR TITLE
dlg/sdgCanonical rewriting

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is ready for review.

**Comment by maxwellfundi** [comment]
@stevenndungu  can you test and review this?

**Comment by lilyclements** [comment]
@stevenndungu @shadrackkibet I'm currently reviewing/making changes to this

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers ,@AlexSananka  took over this and is now working on it at #3624 .I am therefore closing this.

**Pull request closed without merging**
