### PR TITLE
Added new R geoms: geom_density_ridges, geom_density_ridges2 and geom_density_ridges_gradient

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
@africanmathsinitiative/developers @rdstern, this is ready for review
I added three geoms to ucrGeom.vb: 
1. geom_density_ridges, 
2. geom_density_ridges2 and 
3. geom_density_ridges_gradient.
This should be merged fast so that I can add ridge plots to the specific plots.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi that looks great for a start.  
a) Could they be added in the alphabetcal position, as with the other geoms
b) You only have 3 aethetics for each of them.  When I look at the instructions there seem to be many more.  It refers to geom ridgeline for the complete list.  Iwonder why you just give those 3?

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern the above has been fixed. I dded additional aethetics parameters to geom_density_ridges, geom_density_ridge, geom_density_ridge_gradient and also added geome_ridgeline and geom_ridgeline_gradient

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi great.  I'll check

**Review by rdstern — APPROVED** [review]
@HawardKetoyoMsatsi it looks much better now.  I have only looked and not tested in detail, but it seems ok from my side

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Thanks for the changes!

@shadrackkibet The new geoms seem to have been added in a standardized way so I'll go ahead and merge. But if you have any post-merge comments then let me know, thanks

**Pull request merged**
