### PR TITLE
Labelling issue with climdex dialogue

### LINKED ISSUE #7092: Small labeling issue with Climatic > Prepare > Climdex Indices dialogue
There is a small issue with the label text not showing correctly as shown in the screenshot below
image

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes #7092 
This PR was made to correct the previous PR #7093 
@N-thony can you please test this one .

### CODE REVIEW

**Comment by derekagorhom** [comment]
@shadrackkibet can you test this PR to see if it works

**Comment by N-thony** [comment]
> @shadrackkibet can you test this PR to see if it works

@shadrackkibet I have tried to test this but I couldn't, @derekagorhom was able to demonstrate to me and all was looking fine. Could you test it? Thanks

**Comment by shadrackkibet** [comment]
Great. I am just curious, what was the problem when you tried to test it?

**Comment by N-thony** [comment]
> Great. I am just curious, what was the problem when you tried to test it?

I was not able to see the change

**Comment by derekagorhom** [comment]
@N-thony and @shadrackkibet 
i tried cloning R-instat again last night but it seems i cloned the wrong repository.... i will try and clone it again and see what happens

**Pull request closed without merging**
