### PR TITLE
UcrFilePathControl

### PR DESCRIPTION
**Pull request by Patowhiz**
A new empty control aimed at solving issue #5606 and to be used and tested in PR #5873.
@africanmathsinitiative/developers this is ready for review.
@lloyddewit this is an empty control. It's design and logic code implementation will be added in PR #5873. So this has to be merged before it.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@rdstern This is an empty stub (needed by other PRs) and there's nothing you can test. Please could you approve? thanks

**Comment by Patowhiz** [comment]
@lloyddewit this is ready for you. Please note the code additions in the `ucrFilePath.vb` file are just placeholders meant to generate  a resource file, and thus no need to review in this PR. The actual code additions are in PR #5873.

**Comment by lloyddewit** [comment]
@rdstern Some more stubs were added. There's nothing you can test. Please could you approve again? Sorry for the inconvenience.

**Comment by Patowhiz** [comment]
@rdstern yep sorry for the  inconvenience.

**Pull request merged**
