### PR TITLE
Implementing Skimr Dialogue for Describe > Two variable > Summarise

### PR DESCRIPTION
**Pull request by derekagorhom**
partially fixes issues #7204 and #7213 

I did some discussions with @N-thony and @Ivanluv and the dialogue has been created but we are left with the Rcode for the Skimr package

can @shadrackkibet  and @lilyclements  help me with the displaying of the object produced by the skim package

### CODE REVIEW

**Comment by lilyclements** [comment]
@derekagorhom can you be more specific about the problem you are having with the skim package object?
For example, is it for help writing the R code, or displaying it in the output, or something else?

**Comment by derekagorhom** [comment]
> @derekagorhom can you be more specific about the problem you are having with the skim package object? For example, is it for help writing the R code, or displaying it in the output, or something else?

for displaying it in the output please

**Comment by rdstern** [comment]
@derekagorhom you clearly need help on this.  For example I notice that the rules for filling the multiple receiver are the same as for the other button.  You also need sensible rules for when Ok is enabled.  So there are also many details of the controls - even though there are only 2 - that you have to get right as well as the output.  Perhaps if you work with @Ivanluv or @N-thony or even @shadrackkibet things would go a lot faster.  Otherwise the other interns may also be able to help you.  They have done bits of this

Please note also 
a) You should be able to have any type of data mixed in the multiple receiver.  (That's an important way it differs from the other option.)
b) Ok should be enabled here even if the single receiver is empty.
c) So the single receiver could have an (Optional) added.
d) The single receiver is for groups, so could be restricted to factor (or logical) variables.  But it may work more generally.  You could check this first.
e) Later there could usefully be a second similar single receiver - that's for 3-variable analyses.
f) It is supposed to give "tidy" summaries.  So I assume the results could be saved into a new data frame.  (That's the sort of thing I had hoped you might have checked with your initial use of RStudio).  That can come later.

**Comment by derekagorhom** [comment]
> @derekagorhom you clearly need help on this. For example I notice that the rules for filling the multiple receiver are the same as for the other button. You also need sensible rules for when Ok is enabled. So there are also many details of the controls - even though there are only 2 - that you have to get right as well as the output. Perhaps if you work with @Ivanluv or @N-thony or even @shadrackkibet things would go a lot faster. Otherwise the other interns may also be able to help you. They have done bits of this
> 
> Please note also a) You should be able to have any type of data mixed in the multiple receiver. (That's an important way it differs from the other option.) b) Ok should be enabled here even if the single receiver is empty. c) So the single receiver could have an (Optional) added. d) The single receiver is for groups, so could be restricted to factor (or logical) variables. But it may work more generally. You could check this first. e) Later there could usefully be a second similar single receiver - that's for 3-variable analyses. f) It is supposed to give "tidy" summaries. So I assume the results could be saved into a new data frame. (That's the sort of thing I had hoped you might have checked with your initial use of RStudio). That can come later.

Ivan and I have worked on the dialogue and the changes have been made now...

**Comment by derekagorhom** [comment]
Hello @rdstern  please can you review the changes made to the PR

**Comment by derekagorhom** [comment]
Hello @rdstern  please can you review the changes made to the PR

**Comment by rdstern** [comment]
@derekagorhom and @Ivanluv thank you for getting skim to work now.  Here are the results for the survey data.  This is for all variables, by the variety as a factor:
```
-- Data Summary ------------------------
                           Values     
Name                       Piped data 
Number of rows             36         
Number of columns          8          
_______________________               
Column type frequency:                
  factor                   2          
  numeric                  4          
________________________              
Group variables            `"variety"`

-- Variable type: factor -------------------------------------------------------
# A tibble: 2 x 7
  skim_variable n_missing complete_rate ordered n_unique
* <chr>             <int>         <dbl> <lgl>      <int>
1 village               0             1 FALSE          4
2 fertgrp               0             1 FALSE          3
  top_counts                       `"variety"`
* <chr>                            <chr>      
1 NAN: 14, SAB: 10, KES: 7, NIK: 5 variety    
2 >2c: 17, .5-: 10, 0cw: 9         variety    

-- Variable type: numeric ------------------------------------------------------
# A tibble: 4 x 12
  skim_variable n_missing complete_rate  mean    sd    p0    p25   p50   p75
* <chr>             <int>         <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl>
1 field                 0             1 10.7   7.63   1    4       8.5 14   
2 size                  0             1  4.49  3.15   1.5  2.5     4    5   
3 fert                  0             1  1.44  1.03   0    0.375   1.5  2.12
4 yield                 0             1 40.6  11.9   19.1 30.4    40.5 48.8 
   p100 hist  `"variety"`
* <dbl> <chr> <chr>      
1  28   <U+2587><U+2586><U+2583><U+2582><U+2582> variety    
2  20   <U+2587><U+2582><U+2581><U+2581><U+2581> variety    
3   3   <U+2587><U+2582><U+2585><U+2586><U+2586> variety    
4  62.1 <U+2585><U+2582><U+2587><U+2583><U+2585> variety    
```
I am now confused as to what to do with them?  I guess they may display better once we have html working for the output window.  The curious symbols at the end are supposed to be a sort of histogram.  We should also be able to save them, but I had expected a better display of the by factor.  I think this must be a clear difference perhaps between a tibble and a data frame.  

What do each of you think now?  Perhaps @shadrackkibet has some ideas.  For me, now I am inclined to disable the Skim button for now and wait for the html output and then come back to this code?

**Comment by derekagorhom** [comment]
Hello @rdstern sorry for the late reply. 
i went back again through R-studio and realized the `by factor` is not working the way it is supposed to be. i have contacted @Ivanluv  on this issue and i am hoping to fix it soon. 
also i think maybe the html window might make the display look better.

**Comment by rdstern** [comment]
@derekagorhom that's great.  I also looked [here](https://stackoverflow.com/questions/9847054/how-to-get-summary-statistics-by-group).  That included the following example which looked good with a by:

```
library(dplyr)
library(skimr)

starwars %>%
  group_by(gender) %>%
  skim()

#> ── Data Summary ────────────────────────
#>                            Values    
#> Name                       Piped data
#> Number of rows             87        
#> Number of columns          14        
#> _______________________              
#> Column type frequency:               
#>   character                7         
#>   list                     3         
#>   numeric                  3         
#> ________________________             
#> Group variables            gender    
#> 
#> ── Variable type: character ──────────────────────────────────────────────────────
#>    skim_variable gender    n_missing complete_rate   min   max empty n_unique
#>  1 name          feminine          0         1         3    18     0       17
#>  2 name          masculine         0         1         3    21     0       66
#>  3 name          <NA>              0         1         8    14     0        4
#>  4 hair_color    feminine          0         1         4     6     0        6
#>  5 hair_color    masculine         5         0.924     4    13     0        9
#>  6 hair_color    <NA>              0         1         4     7     0        4
#> # [...]
#> 
#> ── Variable type: list ───────────────────────────────────────────────────────────
#>   skim_variable gender    n_missing complete_rate n_unique min_length max_length
#> 1 films         feminine          0             1        9          1          5
#> 2 films         masculine         0             1       24          1          7
#> 3 films         <NA>              0             1        3          1          2
#> 4 vehicles      feminine          0             1        3          0          1
#> 5 vehicles      masculine         0             1        9          0          2
#> 6 vehicles      <NA>              0             1        1          0          0
#> # [...]
```

**Comment by derekagorhom** [comment]
yes please that was what we expected to happen, I am looking through to find out where we went wrong

**Comment by derekagorhom** [comment]
@rdstern  we found where the problem came from.
this is the original code for the output 

```
mydata <- data_book$get_data_frame(data_name="mydata")
mydata %>% dplyr::group_by("subregion") %>% skimr::skim(c("murder","assault","urbanpop","rape"))
rm(mydata)

```
As you can see in `dplyr::group_by("subregion")` the factor column was in quote  which provided a different output from what was originally intended for the `by factor` . this has been fixed with the new commit i just added.

**Comment by rdstern** [comment]
@derekagorhom great - I'll check.

**Comment by derekagorhom** [comment]
hello @rdstern 
i did some work on R-studio and found a suitable output for the skimr dialogue 

```
iris %>%
  dplyr::group_by(Species) %>%
  skim_without_charts()
```
This removes the histogram from the output code but i could not find a way to remove the `complete_rate` since it appears in other data types and not only in numeric

**Comment by derekagorhom** [comment]
Here is the result on using the above mentioned function 

```

> iris %>%
+   dplyr::group_by(Species) %>%
+   skim_without_charts()
-- Data Summary ------------------------
                           Values    
Name                       Piped data
Number of rows             150       
Number of columns          5         
_______________________              
Column type frequency:               
  numeric                  4         
________________________             
Group variables            Species   

-- Variable type: numeric ------------------------------------------------------------------------------------
# A tibble: 12 x 11
   skim_variable Species    n_missing complete_rate  mean    sd    p0   p25   p50   p75  p100
 * <chr>         <fct>          <int>         <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
 1 Sepal.Length  setosa             0             1 5.01  0.352   4.3  4.8   5     5.2    5.8
 2 Sepal.Length  versicolor         0             1 5.94  0.516   4.9  5.6   5.9   6.3    7  
 3 Sepal.Length  virginica          0             1 6.59  0.636   4.9  6.22  6.5   6.9    7.9
 4 Sepal.Width   setosa             0             1 3.43  0.379   2.3  3.2   3.4   3.68   4.4
 5 Sepal.Width   versicolor         0             1 2.77  0.314   2    2.52  2.8   3      3.4
 6 Sepal.Width   virginica          0             1 2.97  0.322   2.2  2.8   3     3.18   3.8
 7 Petal.Length  setosa             0             1 1.46  0.174   1    1.4   1.5   1.58   1.9
 8 Petal.Length  versicolor         0             1 4.26  0.470   3    4     4.35  4.6    5.1
 9 Petal.Length  virginica          0             1 5.55  0.552   4.5  5.1   5.55  5.88   6.9
10 Petal.Width   setosa             0             1 0.246 0.105   0.1  0.2   0.2   0.3    0.6
11 Petal.Width   versicolor         0             1 1.33  0.198   1    1.2   1.3   1.5    1.8
12 Petal.Width   virginica          0             1 2.03  0.275   1.4  1.8   2     2.3    2.5
```

**Comment by Ivanluv** [comment]
@derekagorhom  I have added the second factor receiver in the Dialogue for the skimr functionality ,could you pull the changes from my branch `Derrick_skimr` into this branch. @rdstern this changes look okay from my end

**Review by rdstern — APPROVED** [review]
@derekagorhom very well done for continuing your work on this feature.  It now seems to work and I suggest we approve if the code is ok.
@Ivanluv has already had a look and also added a key new feature and approved.  So I suggest:
a) Could @shadrackkibet also check and approve, so we merge.  Then I suggest a further issue to include options on which summaries are displayed and b) to investigate taking advantage of html, once that is available in the output window.

**Comment by shadrackkibet** [comment]
Some points to report while testing.

1.  The Tab order isn't sorted.

2. While testing I got this messed up design. Not sure what exactly I did, I was moving from Skim to Customize etc

image
3. Then immediately I click reset and then put some variables into the receiver then click Ok then boom! a bug!
image
```
# Code generated by the dialog, Describe Two Variables
dplyr::group_by(village, fertgrp) %>% skimr::skim_without_charts(c("size","variety"))
```
4. Why is it that when I have a variable in the Multiple receiver then I switch between top radio buttons then it is cleared?

I will review the code once you fix these errors.

**Comment by rdstern** [comment]
@derekagorhom and @shadrackkibet , this is an ooops on my part - as I accepted it.  (I am keen to move on and there remains much to do on the other parts of this dialogue.  

But good we have 2 people reviewing.  @Ivanluv, you sort of accepted this before, as I did.   Could you also help Derek with these and look at the code with him, while doing that.  I suggest Derek fixing the bugs and then @shadrackkibet checking the code at the end will take longer than if Derek and Ivan could examine the code while fixing the bugs.  Ivan, like me, was clearly too accepting before.

**Review by rdstern — COMMENTED** [review]
@lilyclements could you look at this one too.  
I can't repeat @shadrackkibet problems.  I assume it does no harm and could be merged?  
I also assume the should have an option later (like your corrr) to put the tibbles into new data frames?  Should we add that now, or perhaps merge what we have first?

**Comment by lilyclements** [comment]
> I can't repeat @shadrackkibet problems. I assume it does no harm and could be merged?

@rdstern this dialog looks good. However, I believe @Ivanluv is working on the same dialog (different tab) in #7343. Merging this would cause conflicts with his work, so perhaps if we can merge @Ivanluv's PR today, then we should fix conflicts on this PR later.

> I also assume the should have an option later (like your corrr) to put the tibbles into new data frames? Should we add that now, or perhaps merge what we have first?

@rdstern yes this is straight forward to do. Can be created into a data frame by `as.data.frame(< skim object >)`

**Comment by Ivanluv** [comment]
@lilyclements  @rdstern  I have this changes in my PR #7343.So I think we can close this PR

**Comment by lloyddewit** [comment]
> @lilyclements @rdstern I have this changes in my PR #7343.So I think we can close this PR

**Pull request closed without merging**
