### PR TITLE
Added extra features to Climatic > Model > Extremes dialog

### PR DESCRIPTION
**Pull request by Tula1**
@rdstern, @lloyddewit, @N-thony, @lilyclements This PR does not fix any issue but is part of my work.

I have been working with @Vitalis95 and @Ivanluv on improving the extremes dialog. These are the improvements:

 i) Under the Bayesian fit method, prior parameters, Initial values and number of iterations was added to improve the model.
 ii) We added the confidence intervals tab that outputs the parameter and return level, with corresponding return periods, 
    confidence intervals.
 iii) We combined the fit method and display options sub dialogs into one sub dialog (Extremes Method) with separate tabs 
      ie fit method, Display Options and Confidence Interval to make it easier for the user.

@lloyddewit we have changed the ` Fitting Options` tab in the main dialog to `Options`. Could you update this in the database to avoid merge conflicts when executed from my side.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Tula1 Great to see you contributing to R-Instat. Welcome!

> @lloyddewit we have changed the Fitting Options tab in the main dialog to Options. Could you update this in the database to avoid merge conflicts when executed from my side.

Done in PR #7724

**Comment by Tula1** [comment]
@rdstern , Please have a look.

**Comment by rdstern** [comment]
@Tula1 that is a considerable improvement.  It will be good for you to explain, ready for testers, what you have done to test the new dialogue, before expecting others to check.  This to include which data you used, and what models you fitted.
a) I like the new Options sub-dialogue.  It is a good improvement.  Please tidy the bottom of the sub-dialogue, so the controls are centred and there isn't that large space.
b) I tested with the dodoma data (i.e. a single site).  I got the annual daily rainfall maximum which I used for the testing.

c) I tried the Bayesian fitting and it seems to work.   I don't quite understand all the Bayesian options, so didn't change from the defaults that you supplied.  Could you please give some descriptive details so I know what I can change.  (I was fitting a gev.)  I would like to alter aspects of the prior.

d) I then added the year so I am fitting a non-stationary model.  It didn't work.  I then found that the original didn't work either, and that's because it doesn't like missing values that are different for the dependent and independent variables.  (We do need to be able to filter out missing values in the data.)  This was easy in this case, as it was just the last 2 years.  So I deleted them.

e) Then I tried again.  I found the Bayesian doesn't work now.  Possibly something needs to change in the priors.  The ordinary MLE works fine.  Please could you check this.

**Comment by Tula1** [comment]
@rdstern The issues raised above have now been sorted. Attached is a description of how the added parameters in the dialogs work. I have used the Dodoma Dataset to test the dialogs.

Please have a look at it.

[Testing the Extremes Dialogs..docx](https://github.com/africanmathsinitiative/R-Instat/files/9784822/Testing.the.Extremes.Dialogs.docx)

**Comment by rdstern** [comment]
great - thanks

**Comment by lloyddewit** [comment]
> great - thanks

@rdstern Will you approve or should @Tula1 still make changes? thanks

**Comment by N-thony** [comment]
> > great - thanks
> 
> @rdstern Will you approve or should @Tula1 still make changes? thanks

@rdstern would you like to approve or they are still do here?

**Review by rdstern — APPROVED** [review]
@lloyddewit and @N-thony I see I sort of "dropped the ball" on this one!).  It is now a considerable improvement on the existing dialogue and it would be good to have it merged for the next release.  I hope the code is ok or that either of you could make it ok, given @Tula1 has finished her internship.  
I have copied the main points from here into an issue, so we can continue with the discussion by using the dialogue, once this is merged.

**Pull request merged**
