### PR TITLE
Climatic transform dialog

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
This is work in progress

**Comment by stevekogo** [comment]
This is partially working with part of the dialog disabled. Reviews are welcome.

**Comment by stevekogo** [comment]
@africanmathsinitiative/developers This is ready for review

**Comment by stevekogo** [comment]
This dialog is still fragile. If need be, I recommend that it should not be merged into today's version unless it is necessary.

**Comment by dannyparsons** [comment]
How fragile? Can it do something useful fairly easily yet and without completely crashing out of the software? If not then probably you're right.

**Comment by stevekogo** [comment]
It does not crash the software but reset does not work properly and you need to manually change the new column name since it is not a prefix.

**Comment by dannyparsons** [comment]
I think that is ok to at least put in for now as long as other non functioning parts are disabled.
If someone agrees with this after testing then I'll merge.

**Comment by dannyparsons** [comment]
@stevenndungu agrees. There are big issues still but it is usable for someone to look at at least.

**Comment by lilyclements** [comment]
@stevekogo Are you continuing work on this today? I would like to make design changes but would like to wait until you've got a more stable version.

**Pull request merged**
