### PR TITLE
DB Translation

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes partly #8053
DB changes so far.....
1. One variable > Visualise Data
2. Two/Three Variable > correlations
3. Graphs
4. Graphs > Bar chart, Histogram, Lineplot, Boxplot and ScatterPlot
5. LinePlot > Line, Smooth, Dumbbell, Slope
6. Bar Chart > Frequency, Value
@lloyddewit, @N-thony can you have a look

### CODE REVIEW

**Comment by derekagorhom** [comment]
Screenshot (543)
Screenshot (544)

@N-thony , @lloyddewit Here are the changes

**Comment by lloyddewit** [comment]
@derekagorhom Thank you for the database updates.
I found the comments above a bit confusing. I had to work hard to reconcile the text and screen shots.
For future database updates, please could you provide a screenshot with the changed lines highlighted? 
I accept that if there are too many changes, then this may not be practical.

Can we merge this PR now or do you expect more changes to come?

**Comment by derekagorhom** [comment]
@lloyddewit this is the final changes
Screenshot (547)

**Review by lloyddewit — APPROVED** [review]
Thanks @derekagorhom

**Pull request merged**
