### PR TITLE
New dialog

### PR DESCRIPTION
**Pull request by bethanclarke**
Created a new blank dialog, in preparation for Evapotranspiration dialog

### CODE REVIEW

**Comment by dannyparsons** [comment]
Can you give it the correct name of the new dialog? Otherwise there will be conflicts when you want to rename it.
I think you need to add one control, like the base buttons as well so that the resource file is also created. @shadrackkibet would know about this better.

**Comment by shadrackkibet** [comment]
When you create an empty dialog there should be a resource file automatically without adding any control.
check that you have the following files all pushed here. ;
```
designer.vb
.resx
.vb
.vproj 
```

Please don't forget to change following properties always!
```
StartPosition - Centerscreen
FormBoarderstyle - FixedToolwindow
MinimiseBox=False
MaximiseBox=False
```

**Comment by dannyparsons** [comment]
You'll want to add something to the dialog code since that isn't included here.

**Comment by bethanclarke** [comment]
@danny I’ve added bad buttons to the dialog in my pervious commit

**Comment by dannyparsons** [comment]
I think you need to open the dialog code file and add anything like a comment, because it's not included here.

**Comment by shadrackkibet** [comment]
@dannyparsons please merge this so that i can proceed with this dialog.

**Comment by dannyparsons** [comment]
Looks like this dialog exists now from the changes

**Comment by shadrackkibet** [comment]
Great, so this can be merged now.

**Comment by dannyparsons** [comment]
Most of the changes are deletions so I'm not sure you want it merged.

**Comment by shadrackkibet** [comment]
Great, i am going to create an empty dialog , then we will have to close this.

**Comment by dannyparsons** [comment]
The empty dialog seems to already be there from another pull request, this one is now just edits.

**Comment by shadrackkibet** [comment]
I think this can now be closed!

**Pull request closed without merging**
