### PR TITLE
dlgCumulativeGraph design

### LINKED ISSUE #5799: Cumulative/Exceedance graph dialog
**Describe the bug**
This is a designer question. Is there any reason why the top radio button design look like this? This is not consistent with what we have for top radio buttons. 

There is also an issue with the controls at the bottom, clearly, they are not aligned properly, labels, size, the distance between controls etc

image

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready for review

Fixes #5799 

Changes:
* ucrSave aligned with comment input box
* Controls on right hand side aligned
* Top buttons no longer overlap
* First letter capitilised for items in combo box
* Tab order

(for "Before" see pull request). After:

image

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Looks better now. However, I would retain the first alignment of receivers with Combobox and Nud below but with their respective labels left-aligned shown in above screenshot.

image

**Comment by lilyclements** [comment]
@shadrackkibet sorted:

image

**Comment by shadrackkibet** [comment]
Sorry for not making my explanation above clear. This is what I meant.

image

**Comment by lilyclements** [comment]
Apologies. Sorted - I hope:

image

**Comment by lloyddewit** [comment]
@rdstern over to you for final approval, then we can merge, thanks

**Pull request merged**
