### PR TITLE
Enabled and showing the two dialogs(Tidy and Augment) form the formmain

### PR DESCRIPTION
**Pull request by Wycklife**
@africanmathsinitiative/developers Get these changes first before testing the dialogs

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Wycklife Please could you provide some extra information for this pull request? It would be helpful to know if/how it is linked to pull requests #5752 and #5753. Thanks

**Comment by Wycklife** [comment]
@lloyddewit @rdstern These are formmain changes. The dialogs were (Tidy and Augment) they were disabled from the formmain before I started working on them. For the testing get the changes from these three pull request #5752 ,#5753, #5754 into one branch. These changes are related. 
This is my first dialog after pulling these changes to a branch called TEST.
image

**Comment by Wycklife** [comment]
@lloyddewit @rdstern This is my second dialog

image

**Comment by Wycklife** [comment]
I'm closing this pull request since it has conflict.

**Pull request closed without merging**
