### PR TITLE
Fixed Minor problems where Split By input keeps resetting back to "Comma ," in the split dialogue

### LINKED ISSUE #6532: Minor problems with the split dialogue
[data to split.zip](https://github.com/africanmathsinitiative/R-Instat/files/6651387/data.to.split.zip)

These data need to be split:
Here is the dialogue in Prepare > Column: Text > Split

Note I have masse the prefix into x and am using a space to split the components.
a) The first time I ran this, it worked - well almost:

Here is the command it generated:

```
# Code generated by the dialog, Split Text Column
V1 <- data_book$get_columns_from_data(data_name="data", col_names="V1", use_current_filter=FALSE)
split <- stringr::str_split(string=V1, pattern=" ", n=Inf, simplify=TRUE)
data_book$add_columns_to_data(data_name="data", col_name="split", col_data=split, use_col_name_as_prefix=TRUE, before=FALSE)
```
It correctly identified the pattern = " " , but it ignored my request for the prefix geing x and insisted it still be split.  So it generated columns split1, to split8.

b) I deleted the variables and ran again.  

The dialogue still looks as shown, but now, although space is shown in the dialogue it has another bug.  The code now is as follows:

```
# Code generated by the dialog, Split Text Column
V1 <- data_book$get_columns_from_data(data_name="data", col_names="V1", use_current_filter=FALSE)
split <- stringr::str_split(string=V1, pattern="Comma ", n=Inf, simplify=TRUE)
data_book$add_columns_to_data(data_name="data", col_name="split", col_data=split, use_col_name_as_prefix=TRUE, before=FALSE)
```

It now says pattern = "Comma " in the code,  i.e. Comma + <space> and so doesn't now work well at all!

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #6532
@rdstern @africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@HawardKetoyoMsatsi greast - seems to be fixed.
@shadrackkibet if ok with you, then maybe it can be merged?

**Review by shadrackkibet — COMMENTED** [review]
The only change I see is that the name of the control changed from `ucrInputPattern` to `ucrInputSplitByPattern`. Was this causing the bug? Otherwise, I couldn't see how the bug is fixed in the code.

**Comment by HawardKetoyoMsatsi** [comment]
Yea I realized there was a problem  that with the control I had to change the name which fixed the issue. I it however appeared a little strange to me.

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet I have looked at this issue together with @Ivanluv and it seems to be more complicated for us to fix. I would like someone to take over the problem and give a fix better than the temporary fix suggested in this PR.

**Comment by shadrackkibet** [comment]
Thanks for the response. I will discuss this further with @lloyddewit when he comes back.

Please move on to another task.

**Comment by lloyddewit** [comment]
> 
> 
> Thanks for the response. I will discuss this further with @lloyddewit when he comes back.
> 
> Please move on to another task.

I also looked at the code changes, and I can't see anything that would fix this bug. It's possible that:
- The bug is intermittent
- The bug has been resolved since the issue was created (as a side-effect of another change)

@rdstern Please could you try and recreate the bug using the latest master? If you can recreate the bug, then please could you perform the exact same steps on this branch to see if there is a difference?

Thanks

**Comment by rdstern** [comment]
For me there remains a problem, but it seems now slightly different to before.  I use the same dataset given in #6532.
I change the character to a space, and the prefix to x.  It seems to run ok.  Here is the command generated:
```
# Code generated by the dialog, Split Text Column
V1 <- data_book$get_columns_from_data(data_name="data", col_names="V1", use_current_filter=FALSE)
x <- stringr::str_split_fixed(string=V1, pattern=" ", n=2)
data_book$add_columns_to_data(data_name="data", col_name="x", col_data=x, use_col_name_as_prefix=TRUE, before=FALSE, adjacent_column="V1")
```

I now realise the initial strin g is wider than I thought.  The new string x is Ok, but x1 (the other string in the split) still has some spaces remaining.

I return to the dialogue.  I now split x1.  Here is the dialogue.  It has now kept the space in the dialogue - which I don't think it did before.  So that's good.
image

I run this to give x2 and x3.  This doesn't work.

I examine the code.
```
# Code generated by the dialog, Split Text Column
x1 <- data_book$get_columns_from_data(data_name="data", col_names="x1", use_current_filter=FALSE)
x <- stringr::str_split_fixed(string=x1, pattern="Comma ", n=2)
data_book$add_columns_to_data(data_name="data", col_name="x", col_data=x, use_col_name_as_prefix=TRUE, before=FALSE, adjacent_column="x1")
```

So, although the dialogue said Space it now used Pattern = "Comma" in the command.

(If I press Reset, then it works OK - just once.  It then gives me x4 and x5 correctly with space as a split.  I then continue, because there are still more spaces in the remaining string.  But - although space( ) is now in the dialogue, it goes back to its default and puts a comma in the code.

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit @shadrackkibet , Please how do we go about this?.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi I think this is all done and ok now

**Comment by maxwellfundi** [comment]
@lloyddewit  this too needs your review :-)

**Comment by lloyddewit** [comment]
This PR solves the issue by renaming the `ucrInputPattern` control. This has the side effect of bypassing the translation database. This is not the best way to solve this issue. The issue is best solved by updating the database and its associated 'ignore' file.
Therefore, I will close this PR and solve this issue in PR #6621 .

**Pull request closed without merging**
