### PR TITLE
Minor code changes

### PR DESCRIPTION
**Pull request by Ivanluv**
@dannyparsons  I've made the changes for the ucrReceiverStation here.Related to #5698

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great, and does this do the climatic summaries correctly still with a station column?

**Comment by Ivanluv** [comment]
yes,its working correctly

**Comment by maxwellfundi** [comment]
@Ivanluv this looks like it has been addressed by another PR and merged and the PR closed?
Is this still relevant?

**Comment by shadrackkibet** [comment]
This looks okay. Can this be merged?

**Comment by rdstern** [comment]
This works in the sense that the summaries are now given correctly by station.  However there is a problem with the dialogue not providing the variables.  I illustrate with a slightly awkward data set with 2 stations.  Here it is:
[ghana_2_gof.zip](https://github.com/africanmathsinitiative/R-Instat/files/4621201/ghana_2_gof.zip)

This file does have some problems with the dialogue.  We would like the dialogue to work even without the data defined as climatic.  So the Station field (with the data as read in) should show all factor variables.
Currently it shows nothing.  
The Date field won't work, because the variable is not defined as a date type.  So I made it a Date variable using Climatic > Date > Make Date (default format).  Then it should appear in the dialogue.

I then used the Use Date dialogue and added doy and day in month.  I then defined as climatic and used Reset in the climatic summary dialogue and all is now fine.  But we would like the dialogue to work without anything being filled automatically, as long as the variables are in the file, i.e. without needing to define the data as climatic.

**Comment by rdstern** [comment]
Oh, just a minute - the current version 6.1 does not have the deficiencies.  It has "been done".  So I am not entirely sure what the change was that Ivan has done.  It was merged and closed before - what exactly has changed?

**Comment by Ivanluv** [comment]
It was working though the code changes were done incorrectly done.These are the  required code changes

**Comment by rdstern** [comment]
Then I suggest it can be merged - perhaps @dannyparsons or @lloyddewit may want a very quick look soon.  Then I hope it doesn't affect the other recent changes in the dialogue.  I guess it won't.

**Pull request closed without merging**
