### PR TITLE
 Implemented the regex sub dialog under Prepare > Column:Text > Find/Replace Dialogue

### PR DESCRIPTION
**Pull request by N-thony**
Fixes (partially) #6893
@africanmathsinitiative/developers @rdstern this replaces PR #7062 due to the build errors. Please take a look.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
Now builds fine and all seems ok

**Comment by rdstern** [comment]
@N-thony a bit different, but (perhaps with the translation?) I am still keen for the first option to just say Count and not Word Count?

**Comment by N-thony** [comment]
> @N-thony a bit different, but (perhaps with the translation?) I am still keen for the first option to just say Count and not Word Count?

@rdstern you are right. This was supposed to be solved in PR #7070 but unfortunately, I missed one step from @lloyddewit explanation. I will do it in a separate PR.

**Comment by lloyddewit** [comment]
> > @N-thony a bit different, but (perhaps with the translation?) I am still keen for the first option to just say Count and not Word Count?
> 
> @rdstern you are right. This was supposed to be solved in PR #7070 but unfortunately, I missed one step from @lloyddewit's explanation. I will do it in a separate PR.

@N-thony I looked at the master branch and this seems to be partially implemented.
The `translationsManuallyEntered.csv` is updated and the correct translation is in the database:

image

However, the `r_instat_not_menus.json` file, `dlgStringHandling.designer.vb` and the `form_controls` table in the database all show the incorrect text:

image

image

As you suggested, please fix the above in a new PR. You're currently changing the database in PR #7122 so you'll need to wait for PR #7122 to be merged first.

**Comment by N-thony** [comment]
> > > @N-thony a bit different, but (perhaps with the translation?) I am still keen for the first option to just say Count and not Word Count?
> > 
> > 
> > @rdstern you are right. This was supposed to be solved in PR #7070 but unfortunately, I missed one step from @lloyddewit's explanation. I will do it in a separate PR.
> 
> @N-thony I looked at the master branch and this seems to be partially implemented. The `translationsManuallyEntered.csv` is updated and the correct translation is in the database:
> 
> image
> 
> However, the `r_instat_not_menus.json` file, `dlgStringHandling.designer.vb` and the `form_controls` table in the database all show the incorrect text:
> 
> image
> 
> image
> 
> As you suggested, please fix the above in a new PR. You're currently changing the database in PR #7122 so you'll need to wait for PR #7122 to be merged first.

I have now updated the database for dlgStringHandling
image

**Comment by N-thony** [comment]
@lloyddewit I found that `Count` in the database is not preceded by space, to make it consistent, I will remove the space from the id_text and on radio button text, `Count` exists already in `r_instat_not_menus.json` file
image

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
