### PR TITLE
Added a machine learning dialogue

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
I added a machine learning dialogue.
Keyboard and a few controls need to be added/fixed.

### CODE REVIEW

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet Kindly take a look at the Regression and classification models in this PR

**Comment by N-thony** [comment]
> I added a machine learning dialogue. Keyboard and a few controls need to be added/fixed.

@HawardKetoyoMsatsi which issue is this for?

**Comment by EstherNjeriLiberatta** [comment]
@HawardKetoyoMsatsi there is a problem when trying to run some of the models, some either take long to load and some bring an error message. Kindly have a look again.

**Comment by N-thony** [comment]
There is a developer error when opening the dialogue
image

**Comment by N-thony** [comment]
- Make the method input combo on the line with its label.
- Change the saving control text name to the appropriate text name.
- Make the rest of the controls work properly
- Make the space between control on the right side consistent

image

**Comment by N-thony** [comment]
@HawardKetoyoMsatsi I confirm that it takes too long when trying to run. I have simply tried the knn method and it was running more than 2 minutes.

**Comment by HawardKetoyoMsatsi** [comment]
@N-thony and @EstherNjeriLiberatta We had some discussion with @shadrackkibet he needed this dialogue he texted me via skype he hasn't looked at it yet and we haven't finalised or discussion yet. Let me try and look at it with @rdstern if @shadrackkibet is not available soon then we can fix the issues and open it for further review. Most methods require additional packages to be installed and I have been knocking out methods that take extremely long to run. as for the `knn` I think it should be running fine by now.

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet please take a look at this. The dialog has been improved and I guess we could remove the predictor model and only have predictor variable.

**Comment by rdstern** [comment]
1) I notice the response and predictor only allow variables.  Also include factors in either.
2) Why not allow a model formula?  I am (as usual) using the survey data.  Why can't I include interaction terms - which is easy with a model?
3) I noticed it said bootstrapping 25 reps.  How can I dictate the number of reps?
4) The Train size goes in steps of 0.05.  I suggest 0.01 instead.  I made it 1 and it complained.  If so, then make 0.99 (or 0.999) the maximum?  And I could also make it 0, and it complained again, so 0.01 could be the minimum.
5) The save control isn't given.  It still says checkbox 1.
6) Can any more results be given?

**Comment by shadrackkibet** [comment]
> 1. I notice the response and predictor only allow variables.  Also include factors in either.
> 2. Why not allow a model formula?  I am (as usual) using the survey data.  Why can't I include interaction terms - which is easy with a model?
> 3. I noticed it said bootstrapping 25 reps.  How can I dictate the number of reps?
> 4. The Train size goes in steps of 0.05.  I suggest 0.01 instead.  I made it 1 and it complained.  If so, then make 0.99 (or 0.999) the maximum?  And I could also make it 0, and it complained again, so 0.01 could be the minimum.
> 5. The save control isn't given.  It still says checkbox 1.
> 6. Can any more results be given?

@HawardKetoyoMsatsi what is the state of this PR?

**Comment by lloyddewit** [comment]
@rdstern @shadrackkibet @N-thony Who would be a good person to take over this PR? any ideas?

**Comment by N-thony** [comment]
> @rdstern @shadrackkibet @N-thony Who would be a good person to take over this PR? any ideas?

@anastasia-mbithe would you like to take this over? I discussed with @lilyclements and she is happy to support you on this.

**Comment by anastasia-mbithe** [comment]
@N-thony  yeah, I'll take over.

**Comment by rdstern** [comment]
@lloyddewit I agree we should close this pull request for now.  @lilyclements I was wondering if the Turing work might have implied it would be good to continue with this, but that is over now, and all seems quite on the machine learning front.

**Comment by lloyddewit** [comment]
@rdstern Thanks, may we close PR #7562 also?

**Comment by lilyclements** [comment]
@rdstern this is interesting. Serifat was showing some interest in Machine Learning dialogs. We can have a discussion with her perhaps if she is interested in supporting anyone over the next few weeks?

**Pull request closed without merging**
