### PR TITLE
French layout review Aug3

### PR DESCRIPTION
**Pull request by rachelkg**
In this pull request I have redone changes to dialogs that had conflicts and addressed comments about my previous pull request. I will be working on this again Tuesday the 10th, so please merge by then if possible. 

Thanks, 

Rachel

### CODE REVIEW

**Review by shadrackkibet — DISMISSED** [review]
@lloyddewit let's also merge this soon to avoid conflicts.

**Comment by lloyddewit** [comment]
@shadrackkibet , @rachelkg unfortunately there are now conflicts in this PR, probably because we just merged PR #6558 and PR #6580.
PR #6543 is also waiting to be merged, and could cause further merge conflicts with this PR. I suggest that we first merge PR #6543 and then resolve the conflicts in this PR (and then merge this PR asap).

@N-thony As discussed, please resolve the compilation errors in PR #6543 so that we can roll back the conflicts, test and merge.
Thanks

**Comment by lloyddewit** [comment]
@rachelkg Sorry, I needed to remove some conflicting files, you'll have to make these updates again in a new PR. From this point on, the risk of merge conflicts should be significantly less.

I removed the conflicting files from this PR with the git commands below.

$ git merge-base pr/6661-french-layout-review-aug3 master
506bdbdce4ae9d0ba1d5ccca9f699f847a30dd92

$ git checkout 506bdbdce4ae9d0ba1d5ccca9f699f847a30dd92 --  dlgOneVariableGraph.resx dlgOneVariableSummarise.resx dlgOneWayFrequencies.resx sdgDataOptions.resx sdgFiltersFromFactor.resx sdgOneVarGraph.resx sdgSummaries.resx ucrAxes.Designer.vb ucrAxes.resx ucrSaveGraph.resx

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern @shadrackkibet Please could one of you approve and merge? thanks

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
