### PR TITLE
Fix bug in Tidy Climatic Data year columns option

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by rdstern** [comment]
Great @dannyparsons , thanks

**Comment by rdstern** [comment]
@dannyparsons That bug is fixed, I just checked with the Kurunegala data that gave the problem before.  However there is another minor change from before:  It now says:


```
# Code generated by the dialog, Tidy Daily Data
kurunega <- data_book$get_data_frame(data_name="kurunega")
data_book$tidy_climatic_data(x=kurunega, format="years", stack_cols=c("y1950","y1951","y1952","y1953","y1954","y1955","y1956","y1957","y1958","y1959","y1960","y1961","y1962","y1963","y1964","y1965","y1966","y1967","y1968","y1969","y1970","y1971","y1972","y1973","y1974","y1975","y1976","y1977","y1978","y1979","y1980","y1981","y1982","y1983"), element_name="rain", new_name="kurunega_tidy1")


There are: 26 measurement values on invalid dates.

*** Invalid dates ***

# A tibble: 26 x 3
   year    doy  rain
   <chr> <dbl> <dbl>
 1 1950     60  9988
 2 1951     60  9988
 3 1953     60  9988
 4 1954     60  9988
 5 1955     60  9988
 6 1957     60  9988
 7 1958     60  9988
 8 1959     60  9988
 9 1961     60  9988
10 1962     60  9988
# ... with 16 more rows
There are: 26 measurement values on invalid dates. Correct these or specify ignore_invalid = TRUE to ignore them. See output for more details.

```

It used to give all the invalid observations and that is important in this context.  We currently don't have any other way to find those.

**Review by lloyddewit — COMMENTED** [review]
@dannyparsons FYI, I reviewed but have no comments

**Comment by lloyddewit** [comment]
> It used to give all the invalid observations and that is important in this context. We currently don't have any other way to find those.
@rdstern This PR did not change this functionality, Does the comment above refer to a different PR?

**Comment by dannyparsons** [comment]
Thanks. I fixed the extra comment from Roger here https://github.com/africanmathsinitiative/R-Instat/pull/6125

**Pull request merged**
