### PR TITLE
Added counts with percentages option to summary function in Describe > Specific Tables/Graphs > Summary Tables dialog

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers @rdstern this is ready to review.

This PR adds a parameter to include counts with percentages in summary function called `include_counts_with_percentage` as discussed in #7621.
This is default `FALSE`, but when `TRUE`, includes the counts when percentages are chosen.

E.g.

```
survey <- data_book$get_data_frame(data_name="survey")
multiple_receiver_cols <- c("village", "variety")
list_of_tables  <- survey %>% purrr::map(.x=multiple_receiver_cols,
                                         .f= ~ dplyr::select(.data=data_book$summary_table(data_name="survey", percentage_type="factors", perc_total_factors="fertgrp",
                                                                                           include_counts_with_percentage = TRUE,
                                                                                           summaries=c("summary_count"), include_margins = TRUE, factors=c("fertgrp", .x)), c(1, by_var=2, 3, 4))) %>% purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) + mmtable2::header_top_left(variable='by_var') + mmtable2::header_left_top(variable="fertgrp"))
```

gives:
image

Whereas 
```
survey <- data_book$get_data_frame(data_name="survey")
multiple_receiver_cols <- c("village", "variety")
list_of_tables  <- survey %>% purrr::map(.x=multiple_receiver_cols,
                                         .f= ~ dplyr::select(.data=data_book$summary_table(data_name="survey", percentage_type="factors", perc_total_factors="fertgrp",
                                                                                           summaries=c("summary_count"), include_margins = TRUE, factors=c("fertgrp", .x)), c(1, by_var=2, 3, 4))) %>% purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) + mmtable2::header_top_left(variable='by_var') + mmtable2::header_left_top(variable="fertgrp"))
```
gives:
image

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge
@lilyclements is there an R developer who should peer review this PR?
Thanks

**Comment by lilyclements** [comment]
@N-thony who do you suggest should peer review this PR?

**Review by N-thony — APPROVED** [review]
@lloyddewit even though  I'm not strong in R but I did a quick look of this with Lily and I'm convinced everything is okay. Over to you.

**Comment by lloyddewit** [comment]
@N-thony thank you for the review.
@rdstern if you can test/approve, then we can merge, thanks

**Review by rdstern — APPROVED** [review]
@lloyddewit I am happy to approve if the code is ok, but I can't check, until the dialogue is changed to allow more than one of these summaries to be included.  @lilyclements I wonder who will do this - perhaps choose someone at the workshop this week?

**Comment by lloyddewit** [comment]
@lilyclements what's the reason you closed this? do you plan to implement in a new PR? thanks

**Comment by lilyclements** [comment]
> @lilyclements what's the reason you closed this? do you plan to implement in a new PR? thanks

@lloyddewit Ah was an accident when deleting old branches! Thanks for pointing this one out!

**Pull request merged**
