### PR TITLE
Renaming filters and calculations using Rename objects dialog

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Fixes #5792. I moved changes from #5797 and #5804 because of many files changes after trying to fix conflicts.

**Comment by shadrackkibet** [comment]
@lloyddewit I have moved the changes here as it was not easy to refix indentation changes from #5804.

**Comment by lloyddewit** [comment]
@shadrackkibet This looks very good. Thank you for taking the trouble to correct the indentation, it'll be more maintainable for the next developer and we also have a clearer record of the changes made to the R code.
Approved from my side.

@rdstern if you can quickly retest/approve from your side then @maxwellfundi can merge.

**Comment by rdstern** [comment]
Happy to approve.  @maxwellfundi this is ready to merge

**Pull request merged**
