### PR TITLE
Rewriting dlgRecodeFactor

### PR DESCRIPTION
**Pull request by Lunalo**
Working on this now

### CODE REVIEW

**Comment by Lunalo** [comment]
@africanmathsinitiative/developers 

This is now ready for review

**Comment by lilyclements** [comment]
@Lunalo reviewing and making edits to this now

**Comment by lilyclements** [comment]
@dannyparsons this is ready to review

**Comment by lilyclements** [comment]
@Lunalo I think before this is merged, could you add in the option for the default column name to be the name of the current column, then "_recode"? What do you think?

**Comment by Lunalo** [comment]
@lilyclements  That is a brilliant idea. I have added the option when the receiver is not empty 

Please have a look

**Comment by lilyclements** [comment]
@Lunalo reviewing this now, may make edits too so make sure all your commits are in

**Comment by lilyclements** [comment]
@dannyparsons this is ready to review

**Pull request merged**
