### PR TITLE
Added editor tabs to Script window

### LINKED ISSUE #8071: Allowed multiple R scripts to be opened and managed as tabbed windows
This issue was created automatically from one of the check boxes in issue #7989.

### LINKED ISSUE #8133: tidy up file open/save/save-as functionality
This issue was created automatically from one of the check boxes in issue https://github.com/africanmathsinitiative/R-Instat/issues/7989.

### LINKED ISSUE #8134: ensure commands on R-Instat 'Edit' menu work as expected in script window
This issue was created automatically from one of the check boxes in issue https://github.com/africanmathsinitiative/R-Instat/issues/7989.

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes #8071
Fixes #8133 
Fixes #8134
This PR allows multiple R scripts to be opened and edited. The scripts are shown in tabbed windows. Tabs can be added and removed.
If the user loads/saves a file into/from a tab, then the name of the tab is set to the associated file name.
The Cut/Copy/Paste commands in the main edit menu can also be used with the script window tabs.

### CODE REVIEW

**Comment by lloyddewit** [comment]
This PR is ongoing. It is not yet ready for test/review.

**Comment by lloyddewit** [comment]
@rdstern 
I think that the tab functionality is generally working correctly now.
I still need to:
- tidy up the tab indexes (ensure that user can hit the tab key and navigate through the dialog controls in a rational order)
- review/refactor the source code
- ensure that the script window is fully translated (e.g. into Russian)
- update tool tips
- fix merge conflict
- fully test

You are welcome to do some beta testing if you wish, but it's not essential.

**Comment by lloyddewit** [comment]
> happy to examine, once the merge conflict is resolved

I resolved the conflict, you're welcome to beta test (but only if you wish)

**Review by rdstern — COMMENTED** [review]
@lloyddewit I had a quick look and it all seems very nice.  
I only used the To Script button.  And twice from different dialogues.
a) When there is information in a window then it adds to that - fine.
b) So if I want it in a new window I just have to make the blank window first. 
c) I was happy that Copy/Cut/Paste worked.
d) The only change I would like is with the remove it is  immediate.  If it is a blank tab, then that's fine, but I would prefer it to prompt - like the Clear button - otherwise.  Perhaps after saving it (and also clear) doesn't prompt.  Otherwise it does.
e) Almost everything can be done from the buttons, but not Save and Load.  They are on the right-click and I noticed that Save there was correctly disabled when I had a blank tab.  Could Save and Load buttons be added?  And perhaps Clear could me moved to be next to Remove?
f) For discussion I note that the buttons are different to those from Chris with the output window.  I don't have a particular problem with that, but wonder?

**Comment by lloyddewit** [comment]
@rdstern excellent suggestions, thank you, I'll work on these

**Comment by lloyddewit** [comment]
> d) The only change I suggest is with the remove. It is immediate. If it is a blank tab, then that's fine, but I would prefer it to prompt - like the Clear button - otherwise. Perhaps after saving it (and also clear) shouldn't prompt. Otherwise it does.

Done (I still need to work on parts e) and f) above)

**Comment by lloyddewit** [comment]
> f) For discussion I note that the buttons are different to those from Chris with the output window. I don't have a particular problem with that, but wonder?

Yes, the script and output windows have overlapping functionality but the buttons, right-mouse-button menus and script appearance are all different (see screenshots below). I view the output window as a script window that includes the results of the R commands. Some things will need to be different but the majority of the output window should look and behave the same as the script window. This should include:

- the script font and syntax highlighting
- adding, removing, (re)naming of tabs
- the buttons at the top (or at least partially)
- the right-mouse-button menu (or at least partially), note that the output window doesn't currently have a right-mouse-button menu

I don't think this work is urgent, but it is something we should think about. I added a note to issue #7989.

image

image

image

**Comment by lloyddewit** [comment]
@rdstern I finished implementing the tab functionality, please could you test? thanks
Note: When this PR is merged, I will do the language translations in a separate PR.

**Comment by rdstern** [comment]
@lloyddewit it really looks good, so I would like to see it merged as soon as possible.
a) The one item that I would like is for the Load and Save to remember the previous directory.  I tried your Load and it works fine.  But it isn't quite the same as the Load from File > Open.  That one returns to the previous directory, whereas yours goes always back to a default.  Could they be consistent?
b) Opening the script window.  Perhaps this may be on a separate pull request?  I can go (back) to your script windows now in 3 ways.  The first is by the `To Script` button on each dialogue.  Or from the Script/Log icon on the toolbar.  Or from the View > Script Window.  If I go from the To Script button on the dialogue, then the toolbar icon doesn't get its tick - though the View > Script Window is ticked.
c) I wonder on your plans for the log window now - or later?  It is currently rather pain and boring looking!  And I remain annoyed that the toolbar icon still seems to think it is more important than your bright-new script windows!  

I now tried a "program".  I report, but I think this is working fine.  It is from [here](https://www.tidytextmining.com/tidytext.html)  from section 1.3.

Copied into the script window it looks like this:

image

And it runs fine - but doesn't show me the results, of course.
If I add the line:

`data_book$import_data(data_tables=list(data=original_books))`

Then I can run the line and I get the data frame in an R-Instat data book.  All very satisfactory.  (If I run the same code from the File > New dialogue I have to make a small change and then it adds the last line for me.)

I am happy to approve now if you wish, or the small directory edit could be made first?

**Comment by lloyddewit** [comment]
@rdstern Thank you for the testing.

> a) The one item that I would like is for the Load and Save to remember the previous directory. I tried your Load and it works fine. But it isn't quite the same as the Load from File > Open. That one returns to the previous directory, whereas yours goes always back to a default. Could they be consistent?

Done. Please could you test?

> b) Opening the script window. Perhaps this may be on a separate pull request? I can go (back) to your script windows now in 3 ways. The first is by the To Script button on each dialogue. Or from the Script/Log icon on the toolbar. Or from the View > Script Window. If I go from the To Script button on the dialogue, then the toolbar icon doesn't get its tick - though the View > Script Window is ticked.

Good spot. This is related to the Script window, but not this PR. I opened issue #8153.

> c) I wonder on your plans for the log window now - or later? It is currently rather pain and boring looking! And I remain annoyed that the toolbar icon still seems to think it is more important than your bright-new script windows!

Happy to promote the script window! Covered in issue #7989.

@rdstern If you're happy with the above, then we can merge, thanks!

**Review by rdstern — APPROVED** [review]
Looks great

**Comment by lloyddewit** [comment]
@N-thony Please could you peer review? thanks

**Review by N-thony — APPROVED** [review]
@lloyddewit looks good to me

**Pull request merged**
