### PR TITLE
If error thrown when retrieving data frames from R, then handle error and display user message

### LINKED ISSUE #7374: A csv file that File > Open has trouble with?
[TTC 1981-2018.zip](https://github.com/africanmathsinitiative/R-Instat/files/8478380/TTC.1981-2018.zip)

I was able to read it, by opening in Excel and then saving as xlsx.  But opening as csv gave an error

Perhaps @Patowhiz or @N-thony could examine?

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #7374

@africanmathsinitiative/developers this is ready for review.

This PR is meant to prevent R-Instat from breaking if there is a problem with retrieving data frame form R. This prevention was already there in the old version of R-Instat.
Changes include;
1. Refactoring code
2. Adding a warning that was there in the old version. 

error old

To test it, you can  use the data file in the issue.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit please note, this should be tested and possibly merged before PR #7380.

**Comment by rdstern** [comment]
@Patowhiz thanks - will do.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Please could you review? thanks

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit Yes, I will review it, thanks.

**Review by HawardKetoyoMsatsi — COMMENTED** [review]
This looks fine to me.
@lloyddewit over to you.

**Review by lloyddewit — CHANGES_REQUESTED** [review]

**Review by lloyddewit — APPROVED** [review]
@Patowhiz Clean/readable code. Liked the comments. Thank you

**Comment by lloyddewit** [comment]
@rdstern If you can test, then we can merge, thanks

**Comment by Patowhiz** [comment]
@rdstern please note the data you can use to test this is in issue #7374. When loading the csv, R-Instat was breaking. This PR is meant to make user that never happens should we have a similar issue in future.

**Pull request merged**
