### PR TITLE
New Filters from factor subdialog

### PR DESCRIPTION
**Pull request by shadrackkibet**
@maxwellfundi this a new empty subdialog, please merge.,

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet I don't completely understand the reasons for adding an empty subdialog. Is this related to a specific issue? Please could you add some explanatory text?

@maxwellfundi Please could you wait until @rdstern and I approve before merging this, thanks

**Comment by shadrackkibet** [comment]
Sorry, I forgot to link this to an issue. It is #4800 which I am starting work on and might take a substantial amount of time to finish. 

Generally, we always want things that touch on frmmain and vbproj merged in quickly so that we avoid having conflicts on these files. New dialogs/subdialogs touch on these. There is nothing as such to review here, I would expect @maxwellfundi to review, but happy if someone would like to look at it.

**Comment by lloyddewit** [comment]
@shadrackkibet Thank you for the explanation and the follow-up WhatsApp exchange. I now understand the situation and approve from my side.

@rdstern This merge won't affect the user in any way so there's currently nothing in this PR for you to test. I suggest you approve for merging.
If you'd like to steamline the process for this type of merge request then we can discuss.

**Comment by rdstern** [comment]
Happy to approve.

Roger

**Pull request merged**
