### PR TITLE
Added 12 keys, tooltips for some of the keys and also rectify some of the proposed changes to the Probability Keyboard 

### LINKED ISSUE #5549: Tooltips and improvements to the calculator probability keyboard
Here is the second keyboard for the tooltips. At the same time I suggest some improvements and the correction of an error.
1. **_The errors first._**  In the existing keyboard the pF key actually delivers the pchisq function.  Correct this to give pf.  And the pchi key gives pt! So change that to give pchisq.  Then change pF and qF keys to **_pf_** and **_qf_** (which corresponds to the function names.) 
2. There are currently 18 keys in the keyboard, but they are not in logical and clear positions.  I propose an improved layout together with the addition of 12 more keys.  So there will be a 5  by 6 array of keys.  As follows:

Row 1: pnorm, pt, pchisq, pF, pgamma
Row 2: qnorm, qt, qchisq, qF, qgamma
Row 3: pbeta, pbirth, pbinom, ppois, pnbin
Row 4: qbeta, qbirth, qbinom, qpois, qnbin
Row 5: fact, choose, beta, gamma, digamma
Row 6: lfact, lchoose, lbeta, lgamma, trigamma

Note, if need be, then some of the keys can be shortened to fit, e.g. pbin could be instead of pbinom.  

The distrbutions are all described in [this page](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Distributions.html). For example pbirth is the birthday problem, function pbirthday and qbirthday.  That distribution is a useful idea in teaching. 

Next the tooltips for these keys.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes  #5549

This replaces pull request #5550 
@africanmathsinitiative/developers Someone to review this.

### CODE REVIEW

**Comment by rdstern** [comment]
I am able to go into this branch.  But when I use Prepare > Column: Calculations > Calculate it gives the following error:
image

**Comment by Wycklife** [comment]
@rdstern I'm currently working on the three calculator pull requests since all the branches have conflict. All are being being done on one branch. I will close the three pull requests on the calculator.

**Comment by rdstern** [comment]
@Wycklife That sounds good.  I'll wait for that.

**Comment by rdstern** [comment]
There is one new addition for the Wakefield keyboard.  The n =  argument should be completed for each key.  It is n = nrow(<data_frame>).

**Comment by Wycklife** [comment]
@rdstern Okay, I will do that.

**Pull request closed without merging**
