### PR TITLE
Ensured logical layout and correct toggling of Script, Metadata, Data and Output windows

### PR DESCRIPTION
**Pull request by Patowhiz**
When you start R-Instat, there is a layout oddity as shown in the image below. 
This PR fixes the oddity and also comment https://github.com/africanmathsinitiative/R-Instat/pull/8465#pullrequestreview-1588370215 
@africanmathsinitiative/developers this is ready for review.

Layout oddity screenshot

### CODE REVIEW

**Comment by Patowhiz** [comment]
This can only merged after PR #8465 has been merged. It contains changes from that PR.

@rdstern I have now fixed the layout oddity you saw in PR #8465 when you now open the column metadata.

**Review by rdstern — DISMISSED** [review]
FRom what I could see, this looks fine.  @lloyddewit please note Patrick's message that the other pull request needs to be merged before this one.

**Comment by Patowhiz** [comment]
@lloyddewit agreed.

**Review by rdstern — DISMISSED** [review]
@Patowhiz this looks good.  I note it also incorporates the extra information on the number of variables in a multiple receiver.
However, this number is not visible if the sheet name is long.  I wonder if you do an abbreviation of the sheet name.  I don't suppose the R abbreviate function can be used here, but just giving say the first 8 characters, or perhaps 6 followed by dot, dot, dot, if there is an abbreviation, might be enough.  The data-frame is anyway on the left in the data selector, so it isn't vital that the full name is repeated. 

Happy to approave, but not sure of the oder that the rewlated pull requests should be merged.  I think in ascending number.

**Comment by Patowhiz** [comment]
@rdstern yes we can look into how to solve long data frame names in a separate PR. Thanks.

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit this is now ready for review.

**Review by rdstern — APPROVED** [review]
@Patowhiz this looks much cleaner and more professional now.  Perhaps I imagine, but it also seems to load faster now?
One "curiosity" has been that sometimes the first time I load the library it closes the R-Instat window.  When I click on the icon in the taskbar it all returns and the library control is ready to continue.
I don't know if your changes affected that?  It happened the first time I started, but not afterwards?
I am approving.  @lloyddewit you were waiting until the wide data changes were merged.  I think that has now been done?

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
