### PR TITLE
Runtime warnings

### PR DESCRIPTION
**Pull request by Patowhiz**
This solves issue  #4275 Runtime Warnings.
I have removed the unused variables and initialised the uninitialised ones.
I'm still not sure why there is a reference to 'System.Net.Http' . I haven't been able to locate where its being used, so I haven't removed it. However for this reference to work then the path to it needs to be set up to point to System.Net.Http.dll. 

@africanmathsinitiative/developers anyone who could quickly point to me where and why this reference was added to the project.

### CODE REVIEW

**Comment by dannyparsons** [comment]
I remember solving that issue before and it was something to do with matching the reference with the correct .NET version. I'll try to find the solution again.

**Comment by Patowhiz** [comment]
Yeah 4.5 and above have removed the System.Net.Http . To reference it you will have to manually add the  System.Net.Http.dll . But am still skeptical where this is being used in RInstant.

**Comment by dannyparsons** [comment]
I believe it's required by other reference, but I'm not absolutely sure. It's easy to check - if you remove the reference and it's needed in the project, you will get an error.

**Comment by Patowhiz** [comment]
@dannyparsons I removed it and there was no error in my project during runtime

**Pull request merged**
