### PR TITLE
File Export Dialogs - design 

### LINKED ISSUE #5879: File > Export dialogs. Minor tidy up.
The File > Export dialogs need a minor tidy:

* The save label is far from the receiver and too close to the edge
* The receiver can be lined up with the comment text box.

image

image

image

image

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready for review

Fixes #5879 

Minor design changes to the "File > Export" dialogs:
* Tab order
* Receiver/Browse button aligned with ucrBase
* "Export File" label moved.

To see "before" screenshots, see #5879 

image

image

image

image

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet Please could you peer review this one? thanks

**Comment by shadrackkibet** [comment]
This looks good to me. @rdstern @lloyddewit over to you.

**Comment by Patowhiz** [comment]
> Could the click even to go into that field be the same as pressing the Browse button.

@rdstern I made a PR( #5872 ) that could now enable such a control do exactly that. If merged then the click feature can easily be implemented.

**Comment by lloyddewit** [comment]
@Patowhiz PR #5872 and PR #5874 are now merged. Does this help to resolve @rdstern 's comment?

**Comment by lilyclements** [comment]
This does not resolve @rdstern 's comment (unless I am doing something wrong!)

@Patowhiz how do I implement the click feature? I thought the current below code would suffice given the updated merged code

```
    Private Sub ucrInputExportFile_Click(sender As Object, e As EventArgs) Handles ucrInputExportFile.Click
        cmdBrowse_Click(sender, e)
    End Sub
```

**Comment by rdstern** [comment]
I would be happy for this to be merged as it is, and then pass the remaining task to @Patowhiz .  It is much more his domain.  @lloyddewit should I approve?

**Comment by Patowhiz** [comment]
> This does not resolve @rdstern 's comment (unless I am doing something wrong!)
> 
> @Patowhiz how do I implement the click feature? I thought the current below code would suffice given the updated merged code
> 
> ```
>     Private Sub ucrInputExportFile_Click(sender As Object, e As EventArgs) Handles ucrInputExportFile.Click
>         cmdBrowse_Click(sender, e)
>     End Sub
> ```


@lilyclements thank you for your good question. The code you've outlined above couldn't work because in VB.NET,  `childrens'` `click` events are not propagated to their `parents` (`parent` here meaning the control that contains other controls, and `children` meaning the control contained inside another control). In this case, `ucrInputExportFile` contains a `textbox` control, which is the one that is receiving the `click` event. This `textbox` `click` event is not propagated to its` parent` hence `ucrInputExportFile` click event is not raised, what's being raised is just the `textbox` `click` event.

To solve that, we have to listen to the custom event that I implemented in PR #5872. This custom event will be raised whenever a `click` event is raised by the controls contained in `ucrInputExportFile` (which is a `ucrInputTextbox`, the code changes in the PR #5872 explains this concept much better). Of course the alternative will be listening to the internal control (textbox) of `ucrInputExportFile` but that is bad practice!  

So to answer your question on what code will suffice, the below code  will do the job.

```
 Private Sub ucrInputExportFile_Click() Handles ucrInputExportFile.ControlClicked
        cmdBrowse.PerformClick()
    End Sub
```

The good news is, I have added this functionality in PR #5873 .

**Comment by lloyddewit** [comment]
@Patowhiz Thank you for the comments. I understand that @rdstern 's request will be resolved automatically when PR #5873 is merged, but that this PR should be merged first (see comment in PR #5873). No additional changes are needed from @lilyclements . Is that correct?

**Comment by Patowhiz** [comment]
@lloyddewit that's correct.

**Comment by lloyddewit** [comment]
@rdstern Based on your previous comments, I think you can approve this PR now. Your remaining request will be resolved automatically when PR #5873 is merged (but this PR has to be merged first).

**Pull request merged**
