### PR TITLE
Replaced splines::ns with new splines2::naturalSpline in the Seasonal Comparison dialog

### LINKED ISSUE #6942: Replace `splines::ns` in Seasonal Comparisons dialog
Seasonal Comparisons dialog currently uses `splines::ns` for the Natural Splines option but the package has been removed from CRAN.

There may be an option for this in the `splines2` package or elsewhere. We need to find some kind of replacement.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #6942
@dannyparsons I have the replacement of splines::ns with new splines2::naturalSpline as suggested in the corresponding issue. Please take a look. Thanks.

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Review by dannyparsons — CHANGES_REQUESTED** [review]
Look good to me.

@N-thony I recently added intructions on how to add a requirement for a new R package https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers#how-to-add-a-new-r-package Can you add `splines2` to the list in the R file and add it in this PR?

@rdstern This looks good to me from the code side. Could you test it works ok in practice on the dialog?

**Comment by N-thony** [comment]
> Look good to me.
> 
> @N-thony I recently added intructions on how to add a requirement for a new R package https://github.com/africanmathsinitiative/R-Instat/wiki/Information-for-developers#how-to-add-a-new-r-package Can you add `splines2` to the list in the R file and add it in this PR?
> 
> @rdstern This looks good to me from the code side. Could you test it works ok in practice on the dialog?

@dannyparsons I have added `splines2` to the file `instat\static\InstatObject\R\install_packages.R `in the variable `pkgs`, please take a look. Thanks.

**Review by rdstern — APPROVED** [review]
@N-thony and @dannyparsons they look nice.  This is great!
I assume the other spline pull request is no longer needed?
I am happy for this to be merged.

**Review by shadrackkibet — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@N-thony could you sort out the conflict then we can merge?

**Comment by N-thony** [comment]
> @N-thony could you sort out the conflict then we can merge?

@shadrackkibet I have resolved the conflict. Thanks

**Review by rdstern — COMMENTED** [review]
@N-thony I wanted to approve, but still had build errors.

**Comment by N-thony** [comment]
> @N-thony I wanted to approve, but still had build errors.

Okay @rdstern , there is nothing much to change. I will close this and make a new one. Thanks

**Pull request closed without merging**
