### PR TITLE
Rewriting Non-Parametric one way ANOVA

### PR DESCRIPTION
**Pull request by stevenndungu**
@africanmathsinitiative/developers this is ready for review.
Few changes made

1.  The first receiver was not passing its variable ie, 
       `kruskal.test(formula=variable2, x=data)`
instead of 
       `kruskal.test(formula=variable1~variable2, x=data)` ....fixed this semantic error

2. Restricted variable1(Y-variate variable) to numeric variables only instead of all variables. This is how kruskal should work, ie, numeric vector vs a factor variable, in order it can compare medians across the different levels given by variable 2

### CODE REVIEW

**Comment by rdstern** [comment]
Can we have a discussion on the work on the dialogues that are "below the line" in the modelling menu.  My understanding is that they will all be incorporated within the dialogues above the line.  So this one is an example of a dialogue using 2 variables and is (or will be) put there.

**Comment by stevenndungu** [comment]
Yes we can have a discussion on this.

**Comment by dannyparsons** [comment]
This looks like it's still waiting for review @africanmathsinitiative/developers

**Comment by lilyclements** [comment]
On the google docs I put a "Ignore for now" next to this since it is listed here #2635 as a dialog to not update.
Happy to review later today if everyone agrees it should be.

**Comment by dannyparsons** [comment]
Since it's been updated, might as well review quickly. If it's going to be more work to get it ready then we leave it for now.

**Comment by stevenndungu** [comment]
@dannyparsons I have tested this...now that I had already re-written it. It can just be merged in.

**Pull request merged**
