### PR TITLE
Change form properties to correct display in Linux

### PR DESCRIPTION
**Pull request by ChrisMarsh82**
Updated auto-size properties so the dialogs display correctly in linux. This could be done within the user controls for the most part apart from where ucrSelector/descendants are used. This means anywhere it was used the autosize had to be set to true on the control in the dialog.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@ChrisMarsh82 This PR contains 480+ changed files. I don't think it's practical to peer review these changes, especially as they're mainly auto-generated, and I trust that you've tested. Therefore I approved. I suggest that either @shadrackkibet or @rdstern also approve so we can merge.
Thanks

**Review by rdstern — APPROVED** [review]

**Comment by dannyparsons** [comment]
The conflicts look fairly simple to solve hopefully. I suggest we merge this asap once resolved to avoid further conflicts.

**Comment by ChrisMarsh82** [comment]
@dannyparsons @lloyddewit updated merge conflicts

**Review by dannyparsons — APPROVED** [review]
I've checked it out locally and it seems to run fine so approving and merging.

**Pull request merged**
