### PR TITLE
Extended the PCA dialog

### LINKED ISSUE #6686: PCA Options subdialog, Save Tab Empty
Hi All, 

I have noticed that the PCA Options subdialog, Save Tab Empty. Is it waiting to be filled or should it be removed. 

Thanks, 

Rachel 

PCA Options

### LINKED ISSUE #7318: Extend the PCA dialogue
Looking in more detail this should be a reasonably easy improvement.
We currently already use the factominer package.  
Here is the current dialogue:
image

The factominer package says:
```
Description
Performs Principal Component Analysis (PCA) with supplementary individuals, supplementary
quantitative variables and supplementary categorical variables.
Missing values are replaced by the column mean.
Usage
PCA(X, scale.unit = TRUE, ncp = 5, ind.sup = NULL,quanti.sup = NULL, quali.sup = NULL, row.w = NULL,col.w = NULL, graph = TRUE,axes = c(1,2))
```
These are exciting additions, particularly:
a) Multiple receiver for additional numeric variables.  Suppl. Numeric
b) Multiple receiver for additional factor variables.  Suppl. Factors
c) Receiver for Additional individuals - a filter for us! 
In the examples it seems to code them numerically.  I assume we can use variable names?  I am not sure about c)
Then it is important that we get a pca object.  
There is a video, that then shows many alternative graphs from the pca object.
There is plot, predict, print and summary for the object.
There is a video, and it looks very nice.  How can we do that sort of investigation in R-Instat?

There is also fviz_pca and fviz_pca_var and get_pca from the factoextra package.

It looks as though (at least for multivariate, we want to get a pca object and then use it.  This is the parallel of our modelling ideas, i.e. fit and use, where we also have keyboards.  
We might even want to consider keyboards in multivariate, just as we have in the modelling???
We can possibly investigate by using the current modelling keyboard dialogues, before seeing if that could supply an "advanced" option for factoMiner to start with.  The fit keyboard could then not just be for pca, but for each of the methods?
 With dialogues we can start with Principal Components

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #7318 
Fixes #6686 
Replaces PR #7654 due to conflicts
@rdstern @lloyddewit @lilyclements , have a look at it

### CODE REVIEW

**Comment by rdstern** [comment]
@Vitalis95 is this the new PCA dialogue?  It looks like the old one (so just a single receiver) and gave a problem with a simple example as well.

**Comment by lilyclements** [comment]
@rdstern are you sure you synced your branch? I can see the changes on my version

@Vitalis95 I get the following bug if I fill the boxes in and press OK

image

**Comment by rdstern** [comment]
@Vitalis95 @lilyclements was correct I wasn't using the right branch.
I got the same error as above. 
I also tried with the diamonds data and there was too much printout.  So I chose not to get the eigenvectors and that was much better.  I suggest not having the eigenvectors could be the default.

Then I tried the other plot options and only the scree plot seems to work.  The others all failed.  

From the presentation with this package there seemed to be many plotting options.  Are these updated yet to permit all that is possible from the new system, particularly those with the added variables. 

With the new output window perhaps @Patowhiz can also advise.  We are currently limited to a single graph at a time.  Will that limit still be there, or could we get multiple graphs now?

**Comment by Patowhiz** [comment]
I still need to design for multiple outputs. Essentially, we need to detect when an R object has multiple outputs when printed. Once that's possible we can trivially have the output window display them.

We can do that once we are done with the new way of processing R objects.

**Comment by Vitalis95** [comment]
@rdstern, to avoid the bug, I have excluded the variables from the  selector once added to Explanatory Variable receiver to avoid using them also in Suppl.Numeric Receiver . I did wrote an email to Francois Husson the author of `FactoMineR` package to inquire if it is possible to use the same  variable(s) in active variables  as well as in quantitative supplementary variables, he responded that he doesn't  have any example where a variable already used as active could be also used as illustrative (quantitative supplementary variables). 
From the documentation it says these supplementary variables  have no influence on the principal components of the analysis but they help to interpret the dimensions of variability-they are not taken into account in the PCA computations.

**Review by lilyclements — APPROVED** [review]
Looks great! @rdstern this is ready for you review

**Review by rdstern — APPROVED** [review]
@Vitalis95 this is looking really good now and I am approving.
Later we could revisit, or you could explain - as we write the help.  I am still not sure how we plot the options with the extra variables and factors.  That can be come later though!

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
