### PR TITLE
Bug fixes in the append to variable metadata function

### LINKED ISSUE #9208: Library data file doesn't open in latest 0.8.0 version
I'm using version 0.8.0 and trying to open the efc data from the sjstats (or sjplot, or sjmisc) packages:

image

I get the following error message:

image

O've tried a few other files from the library - other packages - and the other dataset here.  They all seem ok?

Perhaps others could try on their installations?  Oddly, when I return to the merged version it opens fine there!

### LINKED ISSUE #9209: Transform to factor gives error message in Version 0.8.0
This is the same dataset efc that I report a problem on importing in #9208 

This is when I right-click to make into a factor:

image

I am not sure what is happening, because it then works!  In the error message the length is then the number of levels in the resulting factor.

I get the same error message with other data sets.

As in the earlier issue, it works fine in the merged version?

### LINKED ISSUE #9211: Another error in 0.8.0 that is ok in the merged version?
@N-thony I am getting increasingly puzzled about these errors in the test version that are on standard operations.  Thankfully none - so far - are in the mergec version.  What is going on?

This is the Prepare > Data Reshape > Column Summaries dialog, with the diamonds data.

image

I get the count and mean as the summaries.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #9208
Fixes #9209
Fixes #9211
@rdstern this fixes the bug when trying to convert a column or importing the efc data and also the one in `calculate_summary`. Have a look.

### CODE REVIEW

**Comment by rdstern** [comment]
@N-thony in preparation I wanted to check that I do get this problem in the merged version now.  (Because I didn't before updating to R 4.4.1.)  I do get it, so I can't now import efc, until your bug fix.

I notice, at the same time, there are still packages missing from the merged version.  In particular I had to add sjlabelled earlier today.  And sjmisc, sjplot, etc are not yet there.  

In the set of packages with datasets the last one in the alphabetical list is tidyr.  In version 0.8 there are 20 packages after that.  So we are missing a lot!

**Review by rdstern — APPROVED** [review]
@N-thony well done.  That's a relief.  @Patowhiz can you approve and merge.

**Comment by Patowhiz** [comment]
@rdstern this is quite advanced R changes on functions used by different data book R functions. Considering @lilyclements has been looking at documenting the data book and summary R functions, I recommend her to review and approve.

I'm happy to merge but I can't reliably check what other areas may be affected.

**Review by lilyclements — APPROVED** [review]
@Patowhiz thanks. @N-thony happy to approve

**Pull request merged**
