### PR TITLE
Dlg Jitter Bug Fix on change of data frames

### PR DESCRIPTION
**Pull request by stevenndungu**
@africanmathsinitiative/developers  this is ready for review
The parameter `n` could be updated wgen you changed from one data frame to the other.
image

### CODE REVIEW

**Comment by shadrackkibet** [comment]
i am going to test this now.

**Comment by stevenndungu** [comment]
Please do.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers I have been testing this dialog but i didn't understand how the dialog works.could someone  explain how jitter works?

image


I noticed that when the input textboxes on the group box are empty TeskOk is  still enabled and i was wondering whether the output on teskOk click  is right.

**Comment by dannyparsons** [comment]
The dialog takes a numeric column and adds a random component to it. The input controls allows you to specify the maximum amount that will be added/subtracted from the column.

This is useful when you have confidential data. For example, if you have a latitude column for someone's house and you want to make the data public, you might not want to give the exact location of a house because it could be used to identify the people who live there. One option is deleting the column, but you could also just add a random component to it. So that now the latitude column is slightly different so it doesn't identify the house, but still gives an idea of where it is roughly located (which could be useful for analysis) if you specify the maximum to be small.

The reason it is called jitter is because you jitter the column i.e. make small changes to the values of the column.

**Comment by shadrackkibet** [comment]
This is a good example to understand the use and importance of jitter dialog. So it is okey for TestOk to be enabled when input textboxes on the group box are empty because it appends a column which is different from the original column.

**Comment by shadrackkibet** [comment]
@dannyparsons this is ready for you.

**Pull request merged**
