### PR TITLE
Describe two Variable graph

### LINKED ISSUE #3323: Describe > Two Variable > Graph Improvements
> This needs improvements to bring it to the level of the one variable. 
> There is no Coord Flip. 
> Then the options added to the one variable, like violin plots and jitter need to be added so the dialogues are consistent.
Improvements need from @rdstern. Any more can be listed here.

### PR DESCRIPTION
**Pull request by maxwellfundi**
Fixes #3323 

Added features

1. Flip cordinates on main dialog
2. Adding more geom options on categorical by numeric and numeric by categorical

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@lilyclements  could you help review this?

**Comment by maxwellfundi** [comment]
@lilyclements here are more enhancements for the dialog

**Comment by maxwellfundi** [comment]
Bugs fixed here
Ready to go in

**Comment by dannyparsons** [comment]
@lilyclements anything to add here?

**Comment by lilyclements** [comment]
If I get a chance to later, I'll review this?

**Comment by maxwellfundi** [comment]
@lilyclements tested this and is good now for you @dannyparsons

**Pull request merged**
