### PR TITLE
Updated refresh of data from the databook

### LINKED ISSUE #6912: Data View Window not clearing contents after trying to delete a dataset that is loaded.
I loaded a dataset from the library and realised it was the wrong one. I decided to delete it but it didn't clear. I also tried to close the data book but it didn't clear as well.

To reproduce the bug
1. Try and import any dataset either from the library, creating a new one, or from a file.
2. Once data is loaded, right-click on the tab at the bottom and click on `delete`.
3. See error.
4. You could also go to File and scroll down to `Close Data Book` and click on that.
5.  You will notice nothing happens on the Data View window.

What is expected is the data view window to have cleared its contents after clicking on delete or clear form.

Note: Once you click on delete/ close data book and try importing a new dataset, it automatically replaces the one you had even if it was not cleared from the data view window.

### PR DESCRIPTION
**Pull request by shadrackkibet**
fixes #6912

@ChrisMarsh82 I just copied the code you provided [here](https://github.com/africanmathsinitiative/R-Instat/issues/6882#issuecomment-953742432). It seems to work. However, the status label below is still there and the flash screen we had is lost.

@dannyparsons this is also an improvement from what we have in the master branch. I suggest we merge.

### CODE REVIEW

**Comment by dannyparsons** [comment]
@shadrackkibet Which bug should this fix so I can check it carefully?

**Comment by shadrackkibet** [comment]
**Close Data Book** under File menu should now work partially.

**Review by ChrisMarsh82 — CHANGES_REQUESTED** [review]
Separated out deleteAlldataframes to make the code more readable.

**Comment by ChrisMarsh82** [comment]
@shadrackkibet  I may have done this wrong in GitHub but tried to commit a suggestion of how the code could be written. Split up the code into another procedure to make it more readable.

**Comment by dannyparsons** [comment]
@ChrisMarsh82 The commit worked. Could you look into why the Start screen panels have disappear when the data book is closed? It looks like when `grid.AddWorksheet(fillWorkSheet)` runs in `AddAndUpdateWorksheets()` in `ucrDataView` when the data frame is first loaded then the panels get hidden. I can't see a line of code explicitly hiding them though, and it didn't do this before. Maybe related to a change in the designer?

The Start panels could always be visible because they are under the grid so there's no need to hide them when there's data in the grid.

**Comment by shadrackkibet** [comment]
> @shadrackkibet I may have done this wrong in GitHub but tried to commit a suggestion of how the code could be written. Split up the code into another procedure to make it more readable.

This worked fine Chris. I like your idea of splitting the code.

**Comment by ChrisMarsh82** [comment]
Added an update for the dataframe meta data that was not getting reset. 
@dannyparsons I've sorted the issues with the start screen however had to do it in #6919

**Review by dannyparsons — APPROVED** [review]
This fixes the deleting of data frames and closing the data book issues. Still some refreshing of status and info bar needed that should be in other PR

**Pull request merged**
