### PR TITLE
Adding icons to project. 

### PR DESCRIPTION
**Pull request by maxwellfundi**
@dannyparsons  this is a strange thing that i would not have expected. I added the proper icon everywhere its needed but only the resource file for the main form changed... I would not understand whats on the resource file as its strange code really but it works well.

### CODE REVIEW

**Comment by dannyparsons** [comment]
Can someone test this on their machine by cloning the branch. I thought it would need the icon file to be uploaded but maybe it doesn't work that way.

**Comment by shadrackkibet** [comment]
Testing this now.

**Comment by shadrackkibet** [comment]
I think the icon is already added to the project. This can be closed.

**Comment by maxwellfundi** [comment]
@shadrackkibet  great the issue seem to have been closed already so i close this too.

**Comment by dannyparsons** [comment]
Yes I did add the icon to frmMain which still had the old one set.

**Pull request closed without merging**
