### PR TITLE
Bug Fixes in PICSA Rainfall graph

### PR DESCRIPTION
**Pull request by derekagorhom**
This PR fixes the bugs recently found on the PICSA rainfall graph dialogue. 
@N-thony @Vitalis95 can you test. 

There seems to be an issue with the dialogue. 

1. In the Single variable; when using either Line or Point Options the user has to automatically select the variable it wants to use as the Y variable. (I tried correcting that but it created more problems that solutions). 
to show proof: 
When using the dialogue without Line/Point options:
ghana <- data_book$get_data_frame(data_name="ghana")
last_graph <- ggplot2::ggplot(data=ghana,` mapping=ggplot2::aes(y=as.numeric(x=rainfall), x=month_abbr)) `+....

When using the Dialogue with Line/Point options:
ghana <- data_book$get_data_frame(data_name="ghana")
last_graph <- ggplot2::ggplot(data=ghana, `mapping=ggplot2::aes(y=rainfall, x=month_abbr))` +...

And finally when using the dialogue with the multiple variable: 
ghana <- data_book$get_data_frame(data_name="ghana", stack_data=TRUE, measure.vars=c("min_temperature","max_temperature"))
last_graph <- ggplot2::ggplot(data=ghana, `mapping=ggplot2::aes(y=as.numeric(x=value), colour=variable, x=month_abbr))` +....

### CODE REVIEW

**Comment by lloyddewit** [comment]
@derekagorhom Will this PR fix Issue #7534 ? if so can you state this in the PR description so that the issue closes automatically on merge?
Thanks

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review?
@rdstern Please could you test?
Thanks

**Comment by rdstern** [comment]
Sorry @derekagorhom I get build errors

**Comment by derekagorhom** [comment]
> @derekagorhom Will this PR fix Issue #7534 ? if so can you state this in the PR description so that the issue closes automatically on merge? Thanks

This PR will not fix issue #7534... but rather the bugs reported by Antoine and Vitalis

**Comment by derekagorhom** [comment]
@lloyddewit and @rdstern i am closing this PR due to build errors

**Pull request closed without merging**
