### PR TITLE
QC Temperature.

### PR DESCRIPTION
**Pull request by shadrackkibet**
In Progress!

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@rdstern  i am thinking of adding another checkbox for Range in this dialog. Here is a screenshot i suggest. What are your suggestions?
image

**Comment by shadrackkibet** [comment]
@rdstern ?

**Comment by rdstern** [comment]
I like the new layout:
a) Space in labels before (Tmax) and (Tmin)
b) Could make the defaults for Tmax 10 to 50 and 0 to 30 for Tmin.
c) Jump I would make the default 10mm
d) Difference the default is 0.
e) Outlier is default of 2.5 and it isn't mm.  Make it **multiplier**.  There could be a tooltip to say **"Values that are further than this number of IQRs from the corresponding quartile."**

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers  This is ready for review.

**Comment by dannyparsons** [comment]
There should be a space after Range on the checkboxes. Also not sure why it is **Range (Element 1) Tmax**. I don't think the **Tmax** part is needed.

The Range options also confused me when I first used the dialog as I wasn't sure if it was a range for acceptable or unacceptable values. Can the label be changed to **Acceptable Range** instead?

Also, just to confirm the condition for range should be `!(Element1 > 0 & Element1 < 50)` i.e. show me all the values outside (0, 50) range. I may have specified this wrong in the issue so just checking this is what's implemented.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers  this is ready for review.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers ?

**Comment by Patowhiz** [comment]
@shadrackkibet I'm reviewing this too

**Comment by shadrackkibet** [comment]
@Patowhiz  are you still reviewing this?

**Comment by Patowhiz** [comment]
@shadrackkibet 
1 )
This is more of a question and a suggestion .
In the **Define Climatic Data** dialog we have **Minimum Temperature** and **Maximum Temperature** , is it possible to have them pre filled by default to **element2(Tmin)** and **element1(Tmax)** respectively ? I can see the **Station** and **Date** are being pre filled by default or has that been omitted on purpose? especially after the user has defined the climatic data.

2) 
In the **Acceptable Range (Element1)** and **Acceptable Range (Element2)**  , I presume the "mm" after their respective `ucrNud` controls are unit of measurements. Is "mm" a  correct unit of measurement for this dialog? Or does it refer to something else other than millimeter. I presume the same applies to **Jump** and **Difference**. Temperature measurement are recorded in Kelvin or Celsius.

3)
This is more of design. @rdstern  now that we according to the current dialog design Element1 will always be **Tmax** and **Element2** will always be **Tmin**, why can't we just name Acceptable Ranges checkboxes to **Acceptable Range(Tmax)**, **Acceptable Range(Tmin)**. And also remove the naming **Element1(Tmax)**, **Element(Tmin)**  to remain with just **Tmax**, **Tmin** as labels of their respective receivers? I think that will make the design much simpler and straightforward.

4)
 @rdstern  Still on labelling from my understanding, we are using **Acceptable Range** to mean that we don't want values of **ElementX** _from_ .. _to_ ... . I find that a bit confusing cause in that case we are simply defining **Unacceptable/Undesired Range** (any of its antonym) , which clearly expresses the intention.

5)
@shadrackkibet I can see the default lowest and highest values for **Tmax** range  is **-50** to **65** 
 respectively . But for **Tmin** its **-50** to **50**. Is that intentional? I thought they are to be the same.

6)
From my understanding of Difference, its meant to get the difference between Tx and Tmin, if that's is its true purpose then I think it's odd to have its highest value set as 5. I could want to have a difference of 10.

7)
Currently a new data frame is created with data after the "filtering" has been done. The naming is done automatically, @rdstern I think it will be much better if we had a ucrSave control for a user to get control over the naming of the new data.

8)
The` GMetData2.RDS` (Ghana_Data) has its **Tmax** and **Tmin** data in 1 decimal place **(float values)** yet the filter ranges(ucrNuds  controls used here) only accept whole values (integer values). Is this meant to to clearly tell the user that you can't get ranges and difference in decimal numbers. For instance if I didn't want values that are in a range of 21 to 22.4 probably because I want to assume 22.4 as 22 and 22.5 as 23 . This won't be possible.

**Comment by Patowhiz** [comment]
https://github.com/africanmathsinitiative/R-Instat/issues/2392

**Comment by shadrackkibet** [comment]
@Patowhiz  thanks for testing this.
Since there is no major bug in this dialog, I suggest we have this changes in the issue since it is still open then we can have more discussion and input from others and we can then agree on what to do and what not to.I think this can go in for today's release since we have better functionality compared to what we have now in the master.

**Comment by Patowhiz** [comment]
I agree.

**Comment by shadrackkibet** [comment]
Could you please move the above comments to issue #2339.

**Comment by Patowhiz** [comment]
Done

**Comment by shadrackkibet** [comment]
great!

**Pull request merged**
