### PR TITLE
Improved dialog layouts for French text in Prepare menu dialogs (up to and including View Labels/levels)

### PR DESCRIPTION
**Pull request by rachelkg**
I have made updates to the layout of the prepare menu, up to and including View Labels/levels. I have kept a record of questions, changes I could not make, 
[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6712658/R-Instat.translation.changes.xlsx)
and translation issues to be resolved in Crowdin in the attached excel document. 

I feel kind of stumped by the calculator. They are mostly abbreviations, so I am not really sure about the correct translations. There are a number of items that do not fit but there doesn't seem much wiggle room for changing the size of anything. I am also not sure how to access the different layers. I wonder who would be a good collaborator for this?

### CODE REVIEW

**Comment by rachelkg** [comment]
I have now finished checking the prepare menu. I was unable to do the calculator, General Summaries or Define new filter. But otherwise I have rearranged the dialogs to fit the French translation. I have not yet updated all the translations but have kept a record of issues and questions in the attached excel document. 

[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6719290/R-Instat.translation.changes.xlsx)

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern please can you test? thanks

**Comment by rdstern** [comment]
In Prepare > Data Frame ok up to Filter.  In the Filter sub-dialogue the Filter to Factors seems ok, but the main Filter sub-dialogue has:
a) Add Condition button
b) All combined with & which changes to All combined with |
c) Delete condition
d) Name new filter
all cut off in the French

In Data Frame > Insert Columns/Rows the 3 controls with I, NA and X almost line up, but not quite.  Maybe they could, and perhaps that could be at the same point as the box for the controls above?

That was all in the first (Data Frame) menu

In Check Data
a) In Visualise Data, the Save Graph control needs to move over a bit.  I suggest changing the English text to Save the Graph (i,.e, add "the") to make the English a bit longer.
Second the French does not capitalise, so change the thanslation of Millions de Points de Donnees to get rid of the capitals.

b) Perhaps more for @lloyddewit is that in Compare columns (which was merged recently.  The radio buttons are not translated.

c) In boxplot the Save Graph control needs to be moved over.  Again perhaps it could be Save the Graph in English.  This must be in many dialogues?
 There is a lot still to do on the sub-dialogues.  I suggest this be done when the Describe dialogues aeew checked.

Similarly there could be a lot of work for the summaries.  (That's available from the One Variable Summarise.  I suggest we do this later in the prepare menu.  But I notice here the translation for the range - (maximum minus minimum)  I think that could be étendue?

Column: Calculate>  Row Summaries is badly translated in the Menu and in the dialogue.  I assume it may be Resume par Ligne?  This should then be repeated in the dialogue title.  Then the English is wrong where the multiple receive is labelled something like Row Summaries.  Just change (in English to Variables:

Also on this dialogue make the label longer for the checkbox Ignore missing values.  Currently manquant is missing.

Rank - Change the label in English to Column (not Columns) and omit Rank - that will change the French too.  It is a single receiver, and hence a single column!

Random samples the translation for random number seed I think is not graine.  What about `la suite aléatoire`?  In English should we say Set Random Number Seed?  Or perhaps just Random Number Seed.  (There is a checkbox, so if unchecked, then we don't set it?

For Permute Column we have the same.  I suggest Random Number Seed for both - in English.  With (possibly) La suite aleatoire in French?
In Prepare > Column: Factor Dummy Variable could be `Variable factice`  That's what the ISI translation says.

**Comment by lloyddewit** [comment]
> b) Perhaps more for @lloyddewit is that in Compare columns (which was merged recently. The radio buttons are not translated.

@rachelkg The most likely reason why these radio buttons do not translate is because the English text has not yet been translated in CrowdIn. If you can fix these issues as you find them, then this is likely to be the most efficient.
Your part would be:

-check the English JSON file
-if the English text is missing, then create a PR to add the missing English text
-in CrowdIn, translate to French

I could then do the remaining steps to update the translations database.
What do you think of the approach above? If needed, I'm very happy to run through the steps above in a Zoom call.

**Comment by rachelkg** [comment]
@rdstern Thanks for the feedback I will check all of this over tomorrow. 
@lloyddewit I think that sounds fine. I will add this to my list of translation issues. I intend to do all of the translation issues at once as a separate task after I finish checking the menus over. A call to go over the process at that time would be brilliant. If you think it is a bad idea to separate the two tasks please say so? 

Thanks, 

Rachel

**Comment by lloyddewit** [comment]
> 
> @lloyddewit I think that sounds fine. I will add this to my list of translation issues. I intend to do all of the translation issues at once as a separate task after I finish checking the menus over. A call to go over the process at that time would be brilliant. If you think it is a bad idea to separate the two tasks please say so?
> 

@rachelkg That sounds like a good approach

**Comment by rachelkg** [comment]
**I have rectified those points that I could. Below are those that I cannot do:** 

In Visualise Data, the Save Graph control needs to move over a bit. I suggest changing the English text to Save the Graph (i,.e, add "the") to make the English a bit longer. **(I do not know how to change the english text in checkboxes (in visual studio it just shows up as checkbox @stevenndungu might you be able to tell me how? )**

Column: Calculate> Row Summaries is badly translated in the Menu and in the dialogue. I assume it may be Resume par Ligne? This should then be repeated in the dialogue title. Then the English is wrong where the multiple receive is labelled something like Row Summaries. Just change (in English to Variables: **(@rdstern I think I have done this correctly, it shows up as Variables in English but it hasn't yet updated the translation in my version.)**

Rank - Change the label in English to Column (not Columns) and omit Rank - that will change the French too. **(@rdstern I think I have done this correctly, it shows up as Variables in English but it hasn't yet updated the translation in my version.)**

Random samples the translation for random number seed I think is not graine. What about la suite aléatoire? In English should we say Set Random Number Seed? Or perhaps just Random Number Seed. (There is a checkbox, so if unchecked, then we don't set it? **(I do not know how to change the english text in checkboxes (in visual studio it just shows up as checkbox @stevenndungu might you be able to tell me how?)**

For Permute Column we have the same. I suggest Random Number Seed for both - in English. With (possibly) La suite aleatoire in French?

**Review by rdstern — DISMISSED** [review]
@shadrackkibet approved as explained in the pull request for the file menu

**Comment by shadrackkibet** [comment]
Similar case here. See https://github.com/africanmathsinitiative/R-Instat/pull/6580#issuecomment-890485191

**Comment by lloyddewit** [comment]
@rachelkg @shadrackkibet  I removed the unecessary handler subs that were accidentally added to this PR. I used the commands below. For more explanation, please see PR #6557 

$ git merge-base master pr/6558-french-translation-updates-prepare-menu-up-to-view-labels-levels
f14c0f83e1b4592b83fe06270bc7cc5dcafd48be

$ git checkout f14c0f83e1b4592b83fe06270bc7cc5dcafd48be -- dlgAddComment.vb dlgColumnStats.vb dlgCompareColumns.vb dlgInfill.vb dlgRandomSample.vb dlgRandomSubsets.vb dlgRank.vb dlgRowSummary.vb dlgVisualizeData.vb sdgCalculationsSummmary.vb sdgCreateFilter.vb

**Review by rdstern — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rachelkg I'm afraid that you'll have to implement your changes to the conflicting dialogs and subdialogs again.
I suggest that you first review the changes you made to the affected dialogs in this PR. You may want to take some screenshots. When you've done this, please let me know. I will then remove the conflicting files from this PR and merge this PR.
Please make a new PR for your new updates.
If you have any questions, then please let me know.
Thanks and sorry for the extra work.

Future considerations:
I understand that you mainly work on Fridays. If possible, each Friday, you could try and make a new PR, that's ready for review. We could then merge it very quickly. This would reduce the risk of merge conflicts.

The (sub)dialogs affected are:

- dlgBoxPlot (also updated in PR #6580 ?)
- dlgVisualizeData
- sdgCalculationsSummary
- sdgCreateFilter
- sdgDataOptions
- sdgFiltersFromFactor
- sdgMissingOptions  (also updated in PR #6580 ?)
- sdgSaveColumnPosition
- ucrFilter

**Review by rdstern — DISMISSED** [review]
@lloyddewit can this be merged now?  Or have we misunderstood what needs to be done.  @rachelkg is happy to redo all the dialogues that were causing conflicts.

**Comment by rachelkg** [comment]
Hi @lloyddewit and @shadrackkibet,

Thanks for all your work on this.. Sorry it have got so messy. I have made a note of the dialogs and subdialogs that need to be redone and will do those this week. Please feel free to go ahead with the merge.

re: "Future considerations: I understand that you mainly work on Fridays. If possible, each Friday, you could try and make a new PR, that's ready for review. We could then merge it very quickly. This would reduce the risk of merge conflicts." Thanks for this suggestion I will do this moving forward. I am going to try to work on Tuesdays and Wednesdays over the summer so will make PRs on Wednesdays.

Thanks,

Rachel

**Comment by lloyddewit** [comment]
I removed the conflicting files from this PR with the following git commands:

$ git merge-base master pr/6558-french-translation-updates-prepare-menu-up-to-view-labels-levels
$ git checkout f14c0f8 -- dlgBoxPlot.designer.vb dlgBoxPlot.resx dlgVisualizeData.Designer.vb sdgCalculationsSummmary.resx sdgCreateFilter.resx sdgDataOptions.resx sdgFiltersFromFactor.resx sdgMissingOptions.Designer.vb sdgSaveColumnPosition.Designer.vb ucrFilter.Designer.vb ucrFilter.resx

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet Please could you approve and merge? thanks

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
