### PR TITLE
Further improvements to Output Viewer

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes some items in issue #7852
PR makes some changes to the following dialogs;

1. Prepare > R Objects > View
2. Describe > Use Graph
3. Describe > Combine graph
4. Describe > View Graph
5. Model > Fit Model > One Variable
6. Model > Use Model > One Variable.

It aims to demonstrate how such dialogs and other remaining similar dialogs can use the new output system.
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@rdstern this is ready for you. I have detailed the dialogs to test in the above [comment](https://github.com/africanmathsinitiative/R-Instat/pull/8014#issue-1492138159).

**Review by rdstern — CHANGES_REQUESTED** [review]
@Patowhiz a lot seems now to be working, which is great, and a big relief.
You mentioned the One Variable dialogues and they seem to produce an appropriate object. 

But I then tried with 2-variable (that you imply still needs work).  To me it is just the same.  So I am unsure what remains to be done.

The resulting objects seem also all to "work" in the Prepare menu.  So I can list them in View, and also look at their structure.  I can also rename them and reorder them and delete them.  All good so far.

Also possibly very good.  When I save the file with some new objects, including a graph.  Then opening again and the objects seem still to be there - and including the graph.  That's exciting.

Oh no.  When I stop R-Instat and then start it again, I have lost the graph.  But that is what we had before.  



But when I try to use them on the Model > Use Model > Use Model keyboards I ger the following error:

image

I get this whether it is from a dialogue you say you have adjusted, and also one that you say you haven't worked on yet.  I get this evan if I ask for the structure (i.e. str(object) which seems to work from the Prepare > View Object dialogue.

So I am not clear exactly what remains to be done to complete the work?  I suggest it will be good if @Patowhiz could check the Use Model problem above and perhaps also specify what remains to be done.  Could wither @lloyddewit or @ChrisMarsh82 also look at the code.  Once this is working I am ready for the new release.

**Comment by rdstern** [comment]
I have now tried again and used View Graph, which seems to work fine (in the current session).  But the R-viewer is disabled and I wonder why?  It is enabled in the toolbar and seems to work fine.

Also here is the dialogue:

image

Also in the options:
a) Get rid of the `Display in` each time.  There is the overall title, so that phrase is redundant.
b) Add `(plotly)` to the second option, i.e. `Interactive Viewer (plotly)`
c) Re-instate the R-Viewer.
d) The first option also isn't the output window, but is the maximised window.  So there could be 4 options.  namely Output Window, Maximised Window, Interactive Viewer (plotly), R-Viewer.
I hope this is easy to do?

**Comment by Patowhiz** [comment]
@rdstern thanks for the review.
I noticed the translations system affected the way the I had labelled the radio buttons in the above comment. I have now temporarily disabled translation. I have also changed the labels to what you have suggested.

I have disabled R viewer temporarily because; it sometimes fails to display when called through the dialog. I haven't been able to know why. I'll investigate more with time.

I have fixed the model dialog. I insist that all model dialogs are not well done, most fixes I did are just patches to code that is inconsistent. More discussions are needed on the same. In addition, it was not clear to me which keyboard functions don't work with 1 variable models in the use model keyboards dialog.

@anastasia-mbithe after this PR is merged kindly change the translations of this dialog accordingly then create a new PR.

**Comment by rdstern** [comment]
@Patowhiz I am not sure what you have changed here.  On the Use Model > Use Model keyboard I still get the same error as noted above, i.e. attempt to apply a non-function.

And you say you have changed the labels - I assume on the View Graph dialogue, but they seem to be the same as before.

**Comment by rdstern** [comment]
@Patowhiz there are now some build errors to fix.

**Review by rdstern — APPROVED** [review]
@Patowhiz seems all to work now.  Great relief.  I am approving.  @lloyddewit I hope this can be checked and then merged.  It is the one item that (for me) was holding up this release.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
