### PR TITLE
Ensured that Stem and Leaf plots work correctly in Describe > One Variable > Frequencies dialog

### PR DESCRIPTION
**Pull request by Fidel365**
fixes partially issue #7980 
For part two of the issue, an error occurs when we replace the single receiver with a multiple receiver ; 'x must be a numeric value', this occurs when we use 2 or more variables in the multiple receiver.
@rdstern , this PR is ready for review

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@Fidel365 this now seems to work - at least with a single variable.  I am approving and would be happy for this to be merged as it is.  

Maybe you can also leave the issue open, in case it is not too difficult to include the multiple receiver.  It will need someone to change the R-code.  Could you ask @EstherNjeriLiberatta first to see if she can do it easily.  Emphasise that she should not spend more than 15 minutes on it - it will depend a) on her R skills and b) If it really is easy.  Then I hope @lilyclements can check her suggestions.  If it is difficult, then we leave it.  But I think it may be easy, and also instructive.

**Comment by lilyclements** [comment]
@Fidel365 let me know when this is ready for me to check and we can go through together

**Comment by Fidel365** [comment]
@rdstern , this PR is ready for  a re-review
But, we have to filter variables for the stem and leaf to be numeric and not for the Table and Graph; Hence when we set a datatype, we do not have a way of removing it; If we filter for numerics in stem and leaf the change applies also to Table and Graph, there should be an issue addressing this; i'll create one

**Review by rdstern — COMMENTED** [review]
@fidel, this is looking pretty good now, and I really like the way you are explaining some of the limitations you have found.
a) In the old version - when it was a single receiver - it did just what you wanted, namely only the numeric variables are available below for stem and leaf, but not for the other options.  Why is that so difficult now?

image

And here is the output in Version 0.7.6 - so from a year ago.

image

Could we return and have that same, nice clean, output now - ideally still for multiple (numeric variables, but without the line numbers and the quotation marks?  Maybe check with @Patowhiz.

However, I note that the 0.7.6 output does not say which variable it is summarising.  It would be good to add that, particularly now that multiple variables are bing processed.
.

**Comment by Fidel365** [comment]
@rdstern , the issue with the quotes in the stem and leaf has been fixed, but not for the line numbers, @lilyclements says it's not possible

**Comment by Fidel365** [comment]
@rdstern , this PR is ready for a re-review

**Review by rdstern — DISMISSED** [review]
@Fidel365 and @lilyclements I am really sorry I suggested this.

It is important we have a working stem and leaf, but the earleir one variable at a time was ok.  I just assumed it would be a minor change to be able to have a multiple receiver there!

How wrong I have been!  There are now 2 problems, 
a) We can't restrict to just numeric - which we had with one variable
b) The output is acceptable, but messier than with one variable.

image

I am approving, because it is working ok now.  But, I am very soory to say that changing back to the one variable is a lesser of evils.  

I hope that it doesn't take @lloyddewit too much time, so this can be merged for now.  Then my suggestion is to revert to single variable, neat output, and just numeric!

**Review by lloyddewit — CHANGES_REQUESTED** [review]
Thanks, looks good. Only 2 small suggestions.

**Comment by lilyclements** [comment]
@rdstern there's a bit of an issue with this function, and that's that it prints the item rather than stores it. It wasn't picked up on before, but this has always been an issue. @Patowhiz looked into it to find a way to "store" it, and unfortunately that's why the output is not as "clean" now. By storing it, we are enabling it to be viewed later on under bits like "View Objects".
So we have a choice: Would we rather have it as an object, and so viewable later on and stored within R-Instat
Or would we rather just have it print now, and un-saveable?

Maybe to help show, then run this:

```
# if we save it as an object (here "hello") it still runs the code! This is not like how R usually works!
hello <- stem(x = 1:100)

#  The decimal point is 1 digit(s) to the right of the |
#
#  0 | 123456789
#   1 | 0123456789
#   2 | 0123456789
#   3 | 0123456789
#   4 | 0123456789
#   5 | 0123456789
#   6 | 0123456789
#   7 | 0123456789
#   8 | 0123456789
#   9 | 0123456789
#  10 | 0
#
```
If I then call my object, I get no output, just `NULL`:
```
hello
NULL
```

**Comment by rdstern** [comment]
@lilyclements and @Fidel365 my main interest now is to finish this task using the minimum of your time.  So we can exist with the current printout - so it is stored.

Should we return to the single receiver so we can restrict the variables to numeric?

**Comment by lilyclements** [comment]
@rdstern great - @Fidel365 is working on it now. Thanks :)

**Comment by Fidel365** [comment]
@rdstern , this is ready for review
The multi receiver for stem and leaf now only picks numerics

**Review by rdstern — APPROVED** [review]
@Fidel365 well done.  @lloyddewit over to you

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
