### PR TITLE
Plot Residuals

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@rdstern  please test this. Currently, it only works in General Fit model. Once this is tested I will replicate it across other modelling dialogs.

**Comment by rdstern** [comment]
This is broadly working ok.  I have tried the different graphs.  I have also tried using data with and without missing vallues.  I have confirmed that the saving also works well still.
There is one problem.  It throws an error for each graph saying last_residplot not found - see below.

Once this is fixed it should be merged.  I am afraid this may change again once we implement broom - sorry - but that would be in a good cause!


image

**Comment by dannyparsons** [comment]
We need to identify the bug that @rdstern was getting but others are not getting.

**Comment by shadrackkibet** [comment]
@rdstern I have tried to push all my changes again please test this again.

**Comment by shadrackkibet** [comment]
This is now working in all modelling dialogs.

**Comment by dannyparsons** [comment]
Let's find these issues first before merging.

**Comment by maxwellfundi** [comment]
@dannyparsons did you guys get to know the cause of  this error? This looks like it's been approved but your review is pending.

**Comment by dannyparsons** [comment]
Still pending review.

**Comment by shadrackkibet** [comment]
@rdstern please test this again.

**Pull request merged**
