### PR TITLE
Rename data frame

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes#5210
@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by Ivanluv** [comment]
@Wycklife  please review this

**Comment by Wycklife** [comment]
This works well from my review

**Comment by dannyparsons** [comment]
This change will only effect the dialog on reopening. It doesn't look like it will do what I was suggesting:

> when I change the data frame, the new name should default to the current name.

Instead of running `SetDefaults()` on load, you could modify `CheckAutoName()` to always update the data frame name, regardless of whether the user has typed or not.

**Comment by Ivanluv** [comment]
@dannyparsons  is this fine?

**Comment by dannyparsons** [comment]
I think that looks ok. Can someone re-test to confirm it does update all the times we want?
You could then delete the commented lines.

**Pull request merged**
