### PR TITLE
Backup manager

### PR DESCRIPTION
**Pull request by Patowhiz**
@africanmathsinitiative/developers this is ready for review.
Solution to issue #4184
@dannyparsons  we are yet to discuss on the menu where this dialogue will fall under.
Below is a sample code of how the dialogue will be opened from the frmMain inside the menuitem click event
` dlgBackupManager.AutoSaveDataFolderPath = strAutoSaveDataFolderPath
        dlgBackupManager.ShowDialog()
        If dlgBackupManager.SelectedDataFilePath <> "" Then
            clsRLink.LoadInstatDataObjectFromFile(dlgBackupManager.SelectedDataFilePath, strComment:="Loading auto recovered data file")
        End If`
@dannyparsons the above code executes well and the data is loaded to the R-instant object. However, the dataview doesn't show the data or rather doesn't show up until when I do another kind of operation on the data like say Text Transform. I expect it to behave just like the way the autorecovery dialogue does after loading the data. What could be the issue?

Functionality of the form,

- Shows all backed up files

- Can delete multiple data files

- Can open ONLY one file at a time

- Can save ONLY one file at a time

This is how UI is like this 

backup

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Testing this.

**Comment by Patowhiz** [comment]
@shadrackkibet @maxwellfundi @dannyparsons  My expectation is when I load that into the rinstant object, the gridview should be refreshed to display the data. This does not happen, I still don't know why but am investigating it.

**Comment by Patowhiz** [comment]
@africanmathsinitiative/developers  @shadrackkibet  this dialogue is supposed to solve the issue raised in  #4184 . 
This is how it works:- Before loading it you are **SUPPOSEDto** set its  `AutoSaveDataFolderPath`  property.
This can receive its value from `strAutoSaveDataFolderPath  ` of  `frmMain `(It contains the path to the default folder for temporary backup files). This is done under the menuItem click event of `frmMain` as shown below

  ```
Private Sub mnuBackupmanager_Click(s As Object, e As EventArgs) Handles mnuBackupmanager.Click
      dlgBackupManager.AutoSaveDataFolderPath = strAutoSaveDataFolderPath 
      dlgBackupManager.ShowDialog()
      If dlgBackupManager.SelectedDataFilePath <> "" Then 
              clsRLink.LoadInstatDataObjectFromFile(dlgBackupManager.SelectedDataFilePath, 
                                                                                strComment:="Loading auto recovered data file") 
       End If
    End Sub
```
Please NOTE, to see the listview of the dialogue might appear empty because there is no currently backup data(they are currently being deleted once you launch the application and only saved after 10 mins ). To view the data file you can reduce the backup time in the Tools>Options dialogue (Data View) to 1 min.
Then let the application be idle for around **1 min** so that the `Application_Idle `and `Timer.Tick` event can coordinate and prompt an autosave. Once that is done the `dialogueBackupManager `will show the data file.

**Comment by shadrackkibet** [comment]
**Just a few things i have noted.**

This is how the dialog appears for me.
image

1. The dialog appears to me as too small. Perhaps you could increase the size?
2. The buttons **save,open,delete etc** at the bottom are too small.I think they should be the same size as our usual ucrButtons.
3. I noticed that this dialog is not shown when i reopen using our usual button to **edit last dialog.**.
4. Help doesn't lead me anywhere It is just enabled and when i click at it nothing happens.
5. In the listview i click on the item and click outside the list view, i found that **ok,delete,etc** is now enabled yet nothing is selected on the listview.
6. when i close R-Instat and then run it again.On coming back to the dialog i find my buckup file.When i click at it it doesn't load it in the data view window.

**Comment by dannyparsons** [comment]
I like all these comments for improvements. 
6. I will try to look into the reason for.

**Comment by dannyparsons** [comment]
You've deleted the branch here. You need to restore it and reopen this pull request

**Comment by Patowhiz** [comment]
@shadrackkibet @dannyparsons I had to create and continue this pull request in another branch .
You can check the changes here #4240 Dialog Backup manager pull request

**Pull request closed without merging**
