### PR TITLE
Added Label on Scatter Plot Dialog.

### LINKED ISSUE #8128: Label feature in Scatterplot not working
While performing **data visualization** of the murders data from the dslabs package, I realized that the Scatterplot option has a label feature but it does not impact the graph output. 

The path I used to **load the data** is;
File-> Import from Library-> Load from R-> from package (dslabs)-> Data(murders)-> Ok

The path to get to the **scatterplot** for analyis:
Describe-> Graphs -> Scatterplot

The pictorial below is the pop up window to input the variables.

image

The **output** does not include labels for the data points

image

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes #8128 
 @N-thony , @lloyddewit  I fixes the issues with Label on Scatter Plot dialog. Please can you have a look?

### CODE REVIEW

**Comment by rdstern** [comment]
@MeSophie and @COLIEWO I am not sure what to expect, or what is different here.  I still don't get the state label displayed in the output window, or the maximised output.
It does display in plotly, when youi hover over the point.  If that is all we can do, then perhaps the information on it, should be explained in a tooltip on that receiver.

**Comment by MeSophie** [comment]
> @MeSophie and @COLIEWO I am not sure what to expect, or what is different here. I still don't get the state label displayed in the output window, or the maximised output. It does display in plotly, when youi hover over the point. If that is all we can do, then perhaps the information on it, should be explained in a tooltip on that receiver.

@rdstern As @COLIEWO  explained in the reported issue #8128, when filling in the `Label Variable` receiver you would expect to see label on each point depending on the parameter chosen. but this was not the case.

image

image

So I added in this PR the function allowing to have this information on the graph.

image
image

@rdstern to test this you need to see if effectively when you fill the `Label Variavle` you have the label on your graph.

**Comment by rdstern** [comment]
@MeSophie many thanks.  I'll check again, but I didn't get the labels like that in the plot in the output, or maximised window.  I'll try again.

**Comment by rdstern** [comment]
@MeSophie and @COLIEWO I now get the same result that you did.  
It could be merged, but I wonder about further improving these labels?  Here is my adaptation:
image

I get this by changing `ggplot2::geom_text()` into `ggrepel::geom_text_repel()` .  That does not show all the labels, but it does show all that can be read?  What do you think?

And in the Plot Options button could you also add either text, or text_repel to the set that can be located.

**Comment by rdstern** [comment]
By the way, in my plot above I then changed the x-axis limits and that now labelled quite a few more points.  Useful:

image

**Comment by MeSophie** [comment]
@rdstern I changed `ggplot2::geom_text()` into `ggrepel::geom_text_repel()` .

**Comment by MeSophie** [comment]
@COLIEWO and @rdstern  You can test the label variale now.

**Review by rdstern — APPROVED** [review]
@MeSophie that's a great improvement.  Thanks
@lloyddewit another one to merge when the code is ok.
Also not a dangerous one to include in the February release if there is to be another build.  But can easily wait for March

**Review by lloyddewit — APPROVED** [review]
@MeSophie looks very good, thank you

**Pull request merged**
