### PR TITLE
One var fit fixes

### PR DESCRIPTION
**Pull request by lilyclements**
Still to do:

* Sort last_likelihood bug
* Checkbox is checked upon reopening
* OK is disabled upon reopening
* Error if I run a factor with the wrong distribution (e.g. Normal)

### CODE REVIEW

**Comment by stevenndungu** [comment]
@lilyclements  is this ready for review?

**Comment by lilyclements** [comment]
@stevenndungu sorry my comment was unclear. I've made it clearer now. This is not ready to review as I have to make those four bullet point changes/fixes still.

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is ready to review

**Comment by AlexSananka** [comment]
sorry am still experiencing this bug  `last_likelihood bug`

**Comment by dannyparsons** [comment]
Are you checking on the latest version?

**Comment by AlexSananka** [comment]
Yes but it seems I can't replicate it.

**Comment by AlexSananka** [comment]
Yes I am using the latest version,I don't know if anyone of you have across this bug

**Comment by AlexSananka** [comment]
This bug is now fixed on #3707

**Pull request merged**
