### PR TITLE
Implementing the Find In Variable and Filter Dialogue

### LINKED ISSUE #7950: Add a simple Find dialogue into the Edit menu?
I would like to see the Edit menu "completed".  I am including @Patowhiz in this issue, just to get his take on the suggestions below.  Also it may prompt him to advise on how the Copy > Paste features can be completed - I think there is still a bit to go here.  Then @N-thony could advise, but this might be a simple task for Derrick or Victor, once agreed.

I would like to be able to use reogrid a bit more as it is possible in Excel.

Here is an example - it is the statquotes data, from File > Open from Library > Statquotes package
image

I wanted to find a particular quote - the one about `liars`.

This is a common problem.  But it isn't as general as in Excel, because almost always there is a single variable that I need to examine.  So I would be quite happy with a `Find ` that brings up a simple dialogue that just searches in one variable.  
And, of course, we already (sort of) have the dialogue in the Prepare > Column Text > Find/Replace 

image

So I would be quite happy with just a simple copy of this as a new dialogue.  
a) The usual selector on the left 
b) Single receiver on right  (meant for strings, but can take anything)
c) Pattern field
d) Ignore case
e) Include Regular Expressions (is also available.)

It then uses the stringr command to locate the first occurrence of the pattern.
The difference is what it does then.  It should mark that row, or text in some way. and go there. 

It should work on what's visible - so if a filter is in place, then it just searches the visible text.  I think that will be automatic.

Initially I am quite happy if it always starts at the top.  Later we could permit it perhaps to start from a particular line - that's not so trivial when the data are filtered perhaps.  Perhaps it would be easy to have a control 
From (Visible) Row and then an up-down control?  If so, then it could perhaps start on the current row of the data frame, when the dialogue is opened, or re-opened.  

One use of this dialogue is that the help could direct users to the other text options.  Perhaps this Find dialogue  could even have label saying `Use Prepare > Column: Text > Find/Replace for more options`

We could also perhaps implement `Find Next`, fairly trivially.  It would be disabled if there is no Find text.  It is enabled if there is, and there is a short-cut - perhaps <ctrl>,shift>F?  It doesn't give a dialogue, just goes to the next occurrence.

Then I propose we delete the Replace and Cut items from the menu.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7950
@rdstern following your comment in the corresponding issue, I have implemented the find into different pages. Could you have a look? The find in Filter is disable for now.

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
So that's a bit better, but not great as a general find yet.
Try with the diamonds data and caret and pattern 3. - there are about 35 of those in the record.  But I have to step manually down.  

I don't know how you are doing it, but could ytou use R to find them all on all pages and then be able to step down.

It will also be good to have a From Row... but you need to be able to find on all pages first.  Maybe also try with the filter?

**Comment by N-thony** [comment]
@ChrisMarsh82 I have made some changes to find rows with R. Can you have a look? They are still some minor things I need to fix but so far this seems to work.
@rdstern could you also test quickly and give the feedback? Probably will make the changes once.

**Comment by rdstern** [comment]
@N-thony that's looking good.  It seems to work fine.
a) I tried some values that don't exist and it gave a message.  That could improve.  I wonder if it should be a popup or within the dialogue?
b) It goes round, and when you start a new text, it always starts at the top.  Could you add a Find Next button below, which starts from the current place - even for a new Finf pattern or variable and just goes to the end.  (So the Find option for a new variable, or pattern) always starts at row 1 and goes round, while Find next always starts from the current row and only goes down?
c) Can you add a regex option/keyboard as you have added in the ordinary dialogues, and possibly an ignore case option?

d) Oh here is a slight inconvenience:

image

It doesn't have the same pages anymore.  And I sometimes want to see the observation in context, so I wanted here to scroll up.  Can you keep the ordinary paging at 1000?

e) I like the green cell being marked.  But could you perhaps add a radio button, if easy, with Show (O) Cell (O) Row.  (You can see in the example shown I made a logical variable for rain > 100 and searched for when that is true.  

f) So, in addition maybe the pattern could have a drop down with suggestions.  The obvious ones are TRUE and FALSE.

Roger

**Review by rdstern — COMMENTED** [review]
@N-thony I had a quick look though you are still working on it.  I used the dodoma data.  When I started ar the top and looked for day 31 it went to the next page and gave me row 1035.  Then went to the next page?
I notice the line option isn't working yet..

**Comment by N-thony** [comment]
@rdstern you can test this.

**Comment by rdstern** [comment]
@N-thony I got build errors

**Pull request closed without merging**
