### PR TITLE
Added Priestley Taylor rdo in Evapotranspiration Dialog. 

### LINKED ISSUE #7060: Reading data from the evapotranspiration package
The evapotranspiration dialogue has an issue with the data.  The last dataset - processed data can't be read.  I wonder why not, and can we do anything about that.  It is the example used in the evapotranspiration package, so I assume it reads ok with rstudio?
You may also like to look briefly at the reading of the constants data, which inputs into 37 separate data frames with one cell in each.  That isn't a real problem, because Append works fine and turns them into a single data frame with 2 variables and 37 rows.

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes partially #7060

@N-thony , @lloyddewit , @rdstern  I have Added Priestley Taylor method on this branch for Evapotranspiration Dialog. So I will close PR #8020 since the branch has some issue.

I also adjust the size of `ucrChkAddLine` on Line Plot Dialog such that the french translation can be well display.

### CODE REVIEW

**Comment by MeSophie** [comment]
> Partilly fixes #7060
> 
> @N-thony , @lloyddewit , @rdstern I have Added Priestley Taylor method on this branch for Evapotranspiration Dialog. I added the Extraterrestrial Radiation Receiver for the Hargreaves Samani I not sure that it will be helpful because **evapotraspiration** package don't require it.  So I will close PR #8020 since the branch has some issue.
> 
> I also adjust the size of `ucrChkAddLine` on Line Plot Dialog such that the french translation can be well display.

**Comment by lloyddewit** [comment]
@MeSophie thanks for the PR. Small point: it's important to write 'Fixes partially #7060'. If we write 'Partially fixes #7060', then the issue will close automatically when this PR is merged. I corrected this in the opening comment above.

**Comment by lloyddewit** [comment]
@MeSophie is this PR ready for test/review? thanks

**Comment by MeSophie** [comment]
> @MeSophie thanks for the PR. Small point: it's important to write 'Fixes partially #7060'. If we write 'Partially fixes #7060', then the issue will close automatically when this PR is merged. I corrected this in the opening comment above.

@lloyddewit Well received with thanks.

**Comment by MeSophie** [comment]
@lloyddewit , @N-thony , @Vitalis95  Please can some of you help me to review this PR? Thank you.

**Review by Vitalis95 — APPROVED** [review]

**Comment by Vitalis95** [comment]
If this can be merged so that @MeSophie  can proceed with improvements in PR #8114

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Comment by rdstern** [comment]
@MeSophie @jkmusyoka will be testing this pull request next week.  Please can you suggest examples of data that he can use for the testing.

**Comment by rdstern** [comment]
@MeSophie this is ready to be tested by @jkmusyoka .  Can you suggest data sets he could use for the testing?

**Comment by MeSophie** [comment]
> @MeSophie this is ready to be tested by @jkmusyoka . Can you suggest data sets he could use for the testing?

@jkmusyoka I send the Bohicon data that I used to you. Please check your email. I let me know when you are available. Thank you.

**Pull request closed without merging**
