### PR TITLE
Fit model calculator design

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready for review

Changes:
- design amendments to decrease the width of the dialog
- fixed buttons to be more consistent sizes/positions across tabs

One of the dialogs discussed in #5835 (see point (d))

Before:
image

After:
image

### CODE REVIEW

**Comment by shadrackkibet** [comment]
**Display Options** is opening a new dialog so it should have `...`?

**Comment by lilyclements** [comment]
Good spot. Sorted that now - 
image

**Comment by shadrackkibet** [comment]
Looks good for me now. I just wonder how it looks when you select different options on the R package Combobox. But the stats keyboard is the largest so I assume the other keyboards fit well and that the buttons are also aligned like the stats keyboard shown.

@rdstern @lloyddewit up to you now to review and approve for merging.

**Comment by lilyclements** [comment]
Upon reading the old issue #5008 I believe that the options button should not have an ellipsis so have re-removed it. This seems to be consistent with other dialogs with an options button

**Comment by shadrackkibet** [comment]
I believe we need `...` for buttons that open a dialog to distinguish it from those that do not open any dialog like for **Try** button and **help** buttons in the calculator and elsewhere. If we decide to remove it then I know we need to do that in other places.

**Comment by lloyddewit** [comment]
@rdstern Please could you approve (using the GitHub approve mechanism)? then we can merge, thanks

**Comment by lloyddewit** [comment]
@rdstern Please ignore my previous comment. Maxwell formally approved so we can now merge (you already gave written approval for this PR).

**Pull request merged**
