### PR TITLE
Added a label text to export dialog

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes  #5585

@rdstern This now works well

### CODE REVIEW

**Comment by rdstern** [comment]
Here is the dialogue now:
image

I like the comment - which was the main reason for the change.  But:
a) Why the extra space below the OK buttons
b) Why the extra space to the right - after the browse button
c) Why is the browse button larger than before
d) Why the incomplete "box" for the filename

This was supposed to be such a simple change.  It seems to go on forever?

**Comment by Wycklife** [comment]
@rdstern I have resolve the problem. The designer is now working fine.

**Comment by Wycklife** [comment]
@rdstern Done.

**Comment by shadrackkibet** [comment]
Can we change the colour of this label to alert the user on clicking OK? perhaps make it red?

**Comment by rdstern** [comment]
I'd be happy with that change.  It would make the label stand out.

**Comment by shadrackkibet** [comment]
Good to also improve the design of this dialog. The **Export File** label is far from the corresponding control.  Align the label with the textbox.

**Comment by Wycklife** [comment]
@rdstern I have changed the color of the text to red.

**Comment by shadrackkibet** [comment]
You should do the same on the save dialog.

**Pull request merged**
