### PR TITLE
Shapefiles

### PR DESCRIPTION
**Pull request by jackykemboi**

### CODE REVIEW

**Comment by jackykemboi** [comment]
@maxwellfundi  kindly merge this

**Comment by maxwellfundi** [comment]
@jackykemboi  Did you check that all these can be distributed?

**Comment by dannyparsons** [comment]
This clearly says redistribution is not allowed which we would be doing by putting them in R-Instat so we would need their permission to do this. There may also be alternative sources which are free to distribute.

**Comment by maxwellfundi** [comment]
Okay, then I suggest we could write to them and say we would like to use shape files from them in our software so that they can allow us to. As far as we know, this this among the best places to get shape files. 
Meanwhile we are suggesting to disable the From Library Button.

**Comment by dannyparsons** [comment]
I've done a very quick search and there seems to be many places that provide geographic data and shape files freely. There's long lists of places in these links, have you checked any of them? They might not all provide shape files or have free distribution but I'd be surprised if there wasn't something useful here or by looking elsewhere.

https://gisgeography.com/best-free-gis-data-sources-raster-vector/
https://wiki.openstreetmap.org/wiki/Shapefiles
https://www.statsilk.com/maps/download-free-shapefile-maps
https://freegisdata.rtwilson.com/

**Comment by jackykemboi** [comment]
@maxwellfundi @dannyparsons Rwandan outline (polygon) we can get it from ArcGIS Hub. It's free to redistribute: https://hub.arcgis.com/pages/open-data.

 Rivers and towns shape files can be sourced from Humanitarian Data Exchange which give licence to redistribute data: https://data.humdata.org/about/license

**Comment by jackykemboi** [comment]
@dannyparsons  I have gone through most of the site that we can download free shape files. all the shapefiles are free to download but one isn't allowed to redistribute. However, the Humanitarian Data Exchange: https://data.humdata.org/dataset/rwanda-water-courses# allows one to redistribute the shape files if  you give appropriate credit, provide a link to the license, and indicate if changes were made.
 
What do you think? should we go with this?

**Comment by jackykemboi** [comment]
I contacted the HDX about the redistribution of the shapefiles and this is what they responded: 

> Dear Jackline;
> 
> You are free to use the dataset for your project. You are also free (if you wish to) to indicate a link to HDX as the host of the shapefiles
> As HDX team we are happy to see you using the dataset for your project and we wish you all the best.

**Comment by dannyparsons** [comment]
That's good to know. Did you ask specifically about redistribution or use for your project? Could you send your first email maybe?

**Comment by maxwellfundi** [comment]
@jackykemboi Am closing this issue now because we are no longer getting these on the library.

**Pull request closed without merging**
