### PR TITLE
Dlg MakeDate Bug Fix

### PR DESCRIPTION
**Pull request by stevenndungu**
We had developer errors since the parameters of the ucrinputs were not set properly after the changes made recently in the ucrCore on setrcode. @africanmathsinitiative/developers this is ready for REVIEW. 

Note: On Reopen  the controls of the respective radio button do not appear until you change the radio button.Can someone help. Line 255 causes it- Not sure how to fix that quickly

### CODE REVIEW

**Comment by stevenndungu** [comment]
@AlexSananka if you have time, you can have a test of this now...Above mentioned issue sorted is sorted as well

**Comment by AlexSananka** [comment]
While you were away I already started  reviewing this,I hope all your commit are now in.

**Comment by stevenndungu** [comment]
Great! All the changes are aready in. Note Usedate dialogue bug fix are also included

**Comment by AlexSananka** [comment]
I have tested this and it's really working fine.
@dannyparsons This is ready to go in.

**Pull request merged**
