### PR TITLE
Layout changes in Stack (Pivot) Dialogue

### LINKED ISSUE #7794: Layout issues with french version of Stack (Pivot) dialog
Hello @N-thony, 

This one looks too complicated for me to feel confident changing it. Please could you do it? 

I have circled the layout issues in red. The Nouveau nom....issue is a recurring issue with the Save.urc which affects many dialogs so it would be great to finally have this solved. 

There are also some database issues as a number of items are not translated, what would you like me to be doing about these?  

Thanks, 

Rachel

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes  #7794

This PR is ready for review

@N-thony can you test this and approve

### CODE REVIEW

**Review by N-thony — CHANGES_REQUESTED** [review]
@derekagorhom this is what happened when I check `Save Table` the Factor Levels receiver overlap the save control
image

**Comment by N-thony** [comment]
> @derekagorhom this is what happened when I check `Save Table` the Factor Levels receiver overlap the save control image
 This is `Pivot Table` Dialogue, you can make this small change in this PR too.

**Comment by derekagorhom** [comment]
Screenshot (467)
@N-thony i made the changes... i don't know why it is not displaying on your machine

**Review by N-thony — DISMISSED** [review]
Good, @lloyddewit over to you

**Review by lloyddewit — DISMISSED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge, thanks

**Comment by rdstern** [comment]
@lloyddewit and @derekagorhom am I doing something wrong, as this dialogue still looks messy in French.
Here it is when I start:
image
As you see, there is quite a lot still wrong here.

Now I click on the Empiler option and that gives this picture:
image

Now I click on the Unnest button at the top:
image

There it is neat.  Almost nothing is translated, but that might come later.  However I now click to go back to Pivot Longer and:
image

Now, as you see there is another control visible.  It wasn't there with the multiple option before.  I wonder which is correct.

I assume perhaps I am doing something wrong here?

**Comment by derekagorhom** [comment]
@rdstern and @lloyddewit, this is how the stack (Pivot) looks from the master when i updated it
Screenshot (468)

it looks different from yours, maybe if @lloyddewit can confirm because it have updated and your looks different from mine
thanks

**Comment by rdstern** [comment]
@lloyddewit I have done my check through a skype where Derrick shared his screen.  He now has a few small puzzles to resolve.  Then I suggest we merge, and see what's then translated.  Then he may have a bit more to do later?

**Comment by derekagorhom** [comment]
@rdstern and @lloyddewit i have fixed the problem with the drop prefix check box. please can you check and review. 
Thanks

**Comment by derekagorhom** [comment]
@N-thony and @lloyddewit i made the final changes can you review and approve. 
thanks

**Comment by rdstern** [comment]
@N-thony you are better at this language stuff than I am.  So I assume it can be merged if you and @lloyddewit are happy.

But, please note that there is a second pull request with this dialogue, because the Expand option is being added in #7967.  Perhaps that should be merged first?

**Comment by lloyddewit** [comment]
> But, please note that there is a second pull request with this dialogue, because the Expand option is being added in https://github.com/africanmathsinitiative/R-Instat/pull/7967. Perhaps that should be merged first?

@derekagorhom I'm afraid that @rdstern is corrrect. The changes to `dlgStack` in PR #7967 are more complex than in this PR. So I think we should merge PR #7967 first. This may trigger merge conflicts in this PR. Sorry for the inconvenience.

**Comment by derekagorhom** [comment]
> > But, please note that there is a second pull request with this dialogue, because the Expand option is being added in #7967. Perhaps that should be merged first?
> 
> @derekagorhom I'm afraid that @rdstern is corrrect. The changes to `dlgStack` in PR #7967 are more complex than in this PR. So I think we should merge PR #7967 first. This may trigger merge conflicts in this PR. Sorry for the inconvenience.

ok i understand

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@derekagorhom Thank you!
@rdstern If you can test/approve, then we can merge, thanks

**Review by rdstern — COMMENTED** [review]
@lloyddewit and @derekagorhom I don't see what has changed here?  

image

Look at the lhs with `Supprimer le`  or the rhs with `Colonnes a`  They remain incomplete.  I wonder what is going on?  Will it only take effect after merging?

**Comment by derekagorhom** [comment]
@rdstern , @lloyddewit i have made the changes

**Comment by rdstern** [comment]
I take the opportunity to comment more generally on the language changes in this dialogue.  This is because @derekagorhom will soon be working closely with @N-thony .  Perhaps together they can sort out the langue changes to the dialogue, together with a few further options.

image

1. I wonder about the translation on this menu.  There is Depiler twice, and I wonder if that is the translation for Unstack - and we just have something like Piler for stack.  Over to you Antoine.

2.  There are still some oddities in the French in the dialogue here:

image

I noted 4 places where the French is incomplete here.  
And also lots of bits that remain in English?  Will they be fixed when something else is updated?

3. When you click for multiple, it gets worse!

image

4. The other options seem still not to have a translation?

image

And:

image


We seem to be spending ages on translation-related aspects, while not really getting closer to the end??  Can there also be discussions on how we could become  more efficient?

**Comment by derekagorhom** [comment]
image
@lloyddewit , @N-thony  the new commits fix most of the translation issues that were still on the dialogue. 
the ones not translated are not in the database.

**Comment by lloyddewit** [comment]
> We seem to be spending ages on translation-related aspects, while not really getting closer to the end?? Can there also be discussions on how we could become more efficient?

@rdstern 
Sorry for the incomplete translations. I understand that this is annoying and frustrating. Some of the missing translations above are fixed in PR #8087 but not all. We cannot fully automate the translations and we will always need to fix things by hand. We don't have the resources to fix everything (and even if we did new issues would appear when we merge new PRs). Therefore we time box and we do the best we can in the time we have.
Can we be more efficient? Yes I think we can. For the next translation session we have, I can look to see if I can automate more of the database updates. This should make the team's work easier.

We haven't planned any more translation improvements for the next few weeks. Are you comfortable approving this PR or are there still changes you would like?

Thanks for your understanding.

**Comment by N-thony** [comment]
@derekagorhom can you resolve the conflicts?

**Comment by derekagorhom** [comment]
@N-thony , @lloyddewit i am closing this PR due to the merge conflicts

**Pull request closed without merging**
