### PR TITLE
Adding Logical option on Right clicks & Convert Columns dlg.

### PR DESCRIPTION
**Pull request by shadrackkibet**
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by dannyparsons** [comment]
you've got changes to sizes of lots of controls in the designer to plot region dialog and sub dialogs here?

**Comment by shadrackkibet** [comment]
I noticed the changes on plot region dlg and sdg dialogs. On the last commit i reverted this changes.

**Comment by shadrackkibet** [comment]
I see other changes, sorry i am going to revert this.

**Comment by shadrackkibet** [comment]
@maxwellfundi please test this.

**Comment by shadrackkibet** [comment]
@dannyparsons seems you caused a conflict in two files here. You worked on the two user controls here:#3952

**Comment by dannyparsons** [comment]
Oh yes, sorry about that, I forgot there were changes on this pull request. I have resolved the conflicts manually, hopefully that is ok now.

**Comment by shadrackkibet** [comment]
yep this is ok. @africanmathsinitiative/developers  this is still ready for review.

**Comment by shadrackkibet** [comment]
@dannyparsons this is ready for you to review.

**Comment by dannyparsons** [comment]
Looks good, well done

**Pull request merged**
