### PR TITLE
Removing filters from row names dialogue

### PR DESCRIPTION
**Pull request by Ivanluv**
disabling the use of filters in the row names dialogue #5608

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Ivanluv This seems okay. I wonder if @rdstern  point about on #5608  this being more general was discussed. I am happy for this to be merged really is its not urgent for other places. is that okay @rdstern ?

**Comment by lloyddewit** [comment]
@rdstern I peer reviewed the code change and it looked good. 
This PR links to issue #5608. This issue asks for some small additional changes:
>the first option says Copy Row names into First Column. Delete the First.
>Move the options box over, and make the dialogue smaller

Should these changes also be implemented in this PR or can they be ignored, and this PR and issue closed? Thanks

**Comment by Ivanluv** [comment]
@lloyddewit  the minor changes were already implemented

**Comment by lloyddewit** [comment]
@Ivanluv OK thanks for the clarification. Do you know which PR implemented the minor changes? Should this PR also be referenced in issue #5608?

**Comment by Ivanluv** [comment]
@lloyddewit  I dont know the pull request that  fixed the changes .However from the master the changes are fixed

**Comment by lloyddewit** [comment]
@Ivanluv OK, thanks for the clarification. No further comments from my side.

**Pull request merged**
