### PR TITLE
I have added Help on R-instat windows

### LINKED ISSUE #5041: Help on the R-Instat windows
The right-click in the script window has a (disabled) Help option.  Also the log window.

There are 6 windows in R-Instat.  I have an entry in the help file for each of them and am starting to add some information ready for the next release.  

The context numbers are as follows:
R-Instat Windows: 539  (This is the overall one with the 6 windows as children of this entry)
Spreadsheet (Data View) 134 - this is already available from **Help > Spreadsheet** .  Should that entry change to **Data View (Spreadsheet)**?  Should the Right-click - perhaps the bottom one - also have a Help)
Output: 540 (This has a small right-click menu, but without Help there for now)
Log: 541  (This has a disabled Help on the right click)
Script: 542 ((This has a disabled Help on the right click)
Column Metadata: 543  (This has no direct call to help currently.  It has the same right-click as the spreadsheet, but not yet a right-click at the bottom. 
Data Frame Metadata: 544

The ways of calling the help from the Windows seems currently to be a bit of a "hotch-potch".  What should we do?

I suggest:
1) We have a new **Windows** entry in the Help file, which has the help context 539.  It is just above the Menus and Dialogues entry and just below the horizontal line.
2) We change the position of Spreadsheet in the Help file, so it is below the new Windows entry and name it **Data View (Spreadsheet)**. 
3) We add a Help on the bottom of the Output Window right click - just as there is one on Log and Script.
4) We activate the Script and Log windows help.
5) For consistency we add a right-click link to the Help in the Data view window - just the one in the cells, i.e. the right-click when you are in the middle of the window - as in the log and script windows.  This right-click is currently quite short now.  It also has a line above it - just as in the Script and Log.
6) We add a very simple right-click in the middle of the Column Metadata and Data Frame Metadata window.  Nothing is there now.  Currently it just has the Help call. 

I suggest that will do for now?  At least it is consistent.

### PR DESCRIPTION
**Pull request by Wycklife**
This fixes #5041. This is ready for review @africanmathsinitiative/developers

### CODE REVIEW

**Comment by Muthenya** [comment]
This looks good.

**Comment by Wycklife** [comment]
As i was adding Help on the various windows on R-instat , i realized that some of the names given to the menu items are not consistent. I was thinking on whether to make them consistent.

**Comment by Muthenya** [comment]
> As i was adding Help on the various windows on R-instat , i realized that some of the names given to the menu items are not consistent. I was thinking on whether to make them consistent.

@dannyparsons should thisbe done here or on a separate pull request?

**Comment by dannyparsons** [comment]
In a separate pull request, but very good to go through the names and improve the consistency.

**Pull request merged**
