### PR TITLE
Minor edit on geom contour bin width parameter

### LINKED ISSUE #5402: Adding geom_contour to list of geoms
could we add a geom for contour plots potentially for the new mapping.  I think this is just geom_contour?

The geom exists and so please check it out, comment the code and test it.

### PR DESCRIPTION
**Pull request by Ogik99**
fixes #5402

### CODE REVIEW

**Comment by Ogik99** [comment]
#5405

**Comment by dannyparsons** [comment]
@Ogik99 what about the issue with `position` and `stat` parameters from here? https://github.com/africanmathsinitiative/R-Instat/pull/5405#discussion_r302473773
At least if we don't have other options for them then they need to be editable boxes.

**Comment by Ogik99** [comment]
I have made changed to geom_tile, tufteboxplot, polygon, density2d and contour. This should be okay now.

**Comment by maxwellfundi** [comment]
I have looked into this and the changes made here okay as expected.

**Pull request merged**
