### PR TITLE
Adding the facet receiver and TestOk changes to the Climatic Stations Maps dialog

### LINKED ISSUE #5084: Option of Not Using a fill when Creating Maps
**Describe the bug**
You are not able to make a map without selecting a variable to fill (Eg. using districts). It is currently made in such a way that it enforces to put a variable in the **fill** receiver. The **OK** tab is not made accessible to you if the  **fill** receiver is not filled 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Climatic >> Check Data '
2. Click on 'Station Maps'
3. Scroll down to the first data frame which should contain the shape file , adjacent to the receiver you will find the **fill** receiver and then find out the bug described above if you don't fill the **fill** receiver 

**Expected behaviour**
It should allow you create a map without a fill. This is doable if you remove the fill from the script  produced from the **To Script** button
**Screenshots**
**Not the Graph I want**
image

**The Graph I want**
image

**R script or commands**
```
# Code generated by the dialog, Climatic Maps
lso_bnd_admin1_wfp_co <- data_book$get_data_frame(data_name="lso_bnd_admin1_wfp_co")
Lesotho_metadata <- data_book$get_data_frame(data_name="Lesotho_metadata")
last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=lso_bnd_admin1_wfp_co, ggplot2::aes(fill=adm1_name)) + ggplot2::geom_point(data=Lesotho_metadata, ggplot2::aes(x=longitude, y=latitude)) + theme_grey()
data_book$add_graph(data_name="lso_bnd_admin1_wfp_co", graph=last_map, graph_name="last_map")
data_book$get_graphs(graph_name="last_map", data_name="lso_bnd_admin1_wfp_co")

```
**Correct Script**
```
# Code run from Script Window
lso_bnd_admin1_wfp_co <- data_book$get_data_frame(data_name="lso_bnd_admin1_wfp_co")

Lesotho_metadata <- data_book$get_data_frame(data_name="Lesotho_metadata")

last_map <- ggplot2::ggplot() + ggplot2::geom_sf(data=lso_bnd_admin1_wfp_co) + ggplot2::geom_point(data=Lesotho_metadata, ggplot2::aes(x=longitude, y=latitude)) + theme_grey()

data_book$add_graph(data_name="lso_bnd_admin1_wfp_co", graph=last_map, graph_name="last_map")

data_book$get_graphs(graph_name="last_map", data_name="lso_bnd_admin1_wfp_co")
```

**Details (optional):**
 - Windows 10
 - R-Instat Version [0.4.25]

### PR DESCRIPTION
**Pull request by Muthenya**
I've taken this up from @jackykemboi's pull request #5060.
This fixes #5084.
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers  this needs to be tested. @rdstern when you have sometime your feedback will be appreciated.

**Comment by Muthenya** [comment]
Thank you. I'm on it.

**Comment by Muthenya** [comment]
@maxwellfundi please have a look at this again. I have made the change.

**Comment by rdstern** [comment]
I am not helping here, except to say how happy I am that you continue with this dialogue.  You will remember, from Rwanda, how interested users will be in having some simple maps.  Next step will be to check with climatic data as an alternative to station labels etc.  I'll look as soon as this is merged.

**Comment by maxwellfundi** [comment]
@Muthenya  looks good here.  

@rdstern am merging this for you to keep testing now.

**Comment by dannyparsons** [comment]
Roger can now test pull requests through his VS so in future there's no need to merge to allow him to test.

**Pull request merged**
