### PR TITLE
Improving the Two Variables Graph

### LINKED ISSUE #7260: Further improve Two Variables Graph
@Ivanluv you have added the Pairs option to this dialogue.  Now to improve the (already good) By option.
a) I suggest the title could become `Two Plus Variables Graph`  can we improve on that?
b) Fix the bug, that the categories (e.g. numeric by numeric don't always display.  To see this, start (in the survey data) with 2 sets of factors, e.g. variety, village, by fertgrp.  There is now no group-box, below the Plot Options.  Now change the second (single receiver to yield.  Still no group box.  Press Ok.  Then return to the dialogue.  Lo and behold there is the group box!  
I think it is there for the other 3 options.  Is it there, and just not shown for the categoric by categoric?  If not, then make it there, even if there are currently no options.  (@Ivanluv I can show you this quickly on skype)
c) Now to possible improvements.  The single receiver is not quite in line with the multiple receiver.  I suggest that this could also move up slightly.  Then add a further single receiver with label `(More) Facets:`  This is just for a factor variable.  
(I need to check this option is the best way to add a third variable to the plots here?)
d) Whenever there are facets we could also add a checkbox, Include Margin in the group box below.  (This is either because there are multiple variables in the first receiver, or because the third receiver is used, or both.
e) When there are 2 facet variables, then add an option in the group box, `Swap Facets`.  Default unchecked.
f) If, as I suspect, there are currently no options for the factor by factor graph, then consider what can be added.  (They may be there now, but currently not visible.

I need to check some of these suggestions with @dannyparsons and @lilyclements before there is too much work.  But item b) at least, can be fixed immediately.

### PR DESCRIPTION
**Pull request by Ivanluv**
this replaces PR #7266 and fixes (partly) #7260 i.e

1. Changing the title of the dialogue to `Two Plus Variables Graph`
2. Hiding of the group box below the Plot Options button when having the categoric by categoric options (within the by radio button)
3. Aligning of the multiple and single receivers

### CODE REVIEW

**Comment by Ivanluv** [comment]
@shadrack after adding the labels controls am getting the following error, any ideas on how to fix this?
image
image
image

**Review by rdstern — CHANGES_REQUESTED** [review]
@Ivanluv I wonder if you have included the right bit of code from @shadrackkibet implementation in the full bar chart dialogue?  In the bar chart it works either for counts or for values (i.e. for summary data.).  It looks as though you are using the code for the values, when that for the counts is what you want.

**Comment by Ivanluv** [comment]
@rdstern from the discussion we had with @shadrackkibet I will be using counts

**Comment by Ivanluv** [comment]
@lloyddewit I have tried pulling the master and making the changes but still getting the conflict on the translation file. Is there a way I can fix this

**Comment by lloyddewit** [comment]
> @lloyddewit I have tried pulling the master and making the changes but still getting the conflict on the translation file. Is there a way I can fix this

I suggest that you pull the database file from the master again. This should solve the conflict but you'll lose your database changes. We can then approve/merge this PR without the database change and make the database change in a new PR.
Does this make sense or can you think of a better way?
thanks and sorry for the inconvenience

**Comment by Ivanluv** [comment]
@lloyddewit  I have created a new PR #7307 to replace this

**Pull request closed without merging**
