### PR TITLE
Renaming menu item: Climatic>File>Import from IRI Data Library

### PR DESCRIPTION
**Pull request by shadrackkibet**
@rdstern @dannyparsons @lloyddewit this is a small change in the frmmain as described in #3995. See the screenshot below for the latest change.
image

### CODE REVIEW

**Comment by dannyparsons** [comment]
Could you also add `...` to Climatic > Tidy & Examine > Visualise Data?

**Comment by shadrackkibet** [comment]
Added also  Climatic > Tidy and Examine > One Variable Frequencies

**Review by dannyparsons — DISMISSED** [review]
Great thanks. @lloyddewit could you double check?

**Comment by shadrackkibet** [comment]
Fixes #6031

**Review by dannyparsons — APPROVED** [review]

**Review by rdstern — COMMENTED** [review]
I am happy with this too.  I am just commenting, so @lloyddewit can do the final check and merge

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
