### PR TITLE
Added a new Structured menu to R-instat

### LINKED ISSUE #5839: Add a new Structured menu to R-Instat
This is from @volloholic and has grown from looking where to add time series analysis into the current menu structure in R-Instat.
The idea is to have a **_new Menu, called Structured,_** just after the Model menu, so before Climatic.
This would have the same general structure as the whole system, so Prepare, Describe, Model.  (I don't think we need File, at least initially.)
Currently I suggest the Menu as follows:
```
Structured
Define (dialogue moved from Prepare menu.  Only item currently in the Prepare section.)
-------
Describe
-------
Model
```
In the **_Describe_** section we either  have a submenu, perhaps initially as follows: 
```
Circular
Low-Flow
Survival
Time Series
```

Or we have **_Describe: Circular_** on the main Structured menu, etc

Similarly for the Model section.

We have (at least) four types of structured data.
1) **_Circula_**r is currently the only type of data in the **_Prepare > Define_** menu.  We are ready to define time series data (ts, xts, zoo).
2) We are also adding the lfstat package (for hydrology) and this has the **_lfobj_** object, which is usually created from a ts object.
3) The **_surviva_**l package defines a survival object
4) **_Time series_** may be ts, or xts, or zoo object.

I am including quite a number of people, simply so we discuss this issue and can proceed reasonably quickly.  It is quite a big change, but is growing on me.  It fits with the R principle of defining structures and these are all examples where there is a key variable, plus additional meta-data.  The extra data may be because of an additional variable, e.g. the censoring variable in survival or in information derived from the structure or additional variables, such as time series.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5839

@africanmathsinitiative/developers I have added a new menu called Structured with a list of items. Currently the items are doing nothing except for circular>Define which opens circular dialog. At this, there are still discussions on how to implement the items within the menu. @rdstern @dannyparsons @volloholic @lloyddewit

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Wycklife Thank you for the short discussion. I understand that this PR should not be merged yet as it still needs some work.

**Comment by Wycklife** [comment]
Structured

Here is the structure of the new menu.

**Comment by Wycklife** [comment]
> @Wycklife Thank you for the short discussion. I understand that this PR should not be merged yet as it still needs some work.

Yeah, I have made some edits to the pull request. Does that looks okay now?

**Comment by lloyddewit** [comment]
> Yeah, I have made some edits to the pull request. Does that looks okay now?

Yes, I saw that you removed the request to merge - thank you

**Comment by lloyddewit** [comment]
@Wycklife We briefly discussed this PR on 17 June. I understood that this PR was not ready to be merged. I don't see any new commits since then. Were you just waiting for @rdstern for Roger to assess the user impact and give his approval? Or were you still planning to make some additional code changes?
Thanks for clarifying.

**Comment by Wycklife** [comment]
@rdstern This branch now has conflicts, I have to work a fresh on this. So this should be added to the taiga

**Comment by Wycklife** [comment]
@lloyddewit Most of the implementation is still under discussion. It could be merged since it's a formmain work, it might bring conflicts when there is any work on the formmain. After the discussion then there will be more implementations later on.

**Comment by lloyddewit** [comment]
@Wycklife Thank you for the update. I suggest the following way ahead:
- You finalise the frmMain changes and resolve any conflicts
- @rdstern approves again (under the new GitHub configuration he has to formally approve before we can merge)
- I approve
- We merge and close this PR
- You complete the remainder of this enhancement under new PRs

Does this seem sensible to you? If you prefer a different approach then we can discuss, thanks

**Comment by Wycklife** [comment]
@lloyddewit I have done this a fresh since this branch has conflicts. I am now closing this pull request and creating a new one

**Comment by lloyddewit** [comment]
Replaced by PR #5856

**Pull request closed without merging**
