### PR TITLE
Adding the three Variable functionality to the Describe> Two\Three Summary dialogue

### PR DESCRIPTION
**Pull request by Vitalis95**
Replaces PR #7614 
@rdstern @N-thony , part a) and b) of the https://github.com/africanmathsinitiative/R-Instat/pull/7614#issuecomment-1239141364 is sorted
@lilyclements , could check on https://github.com/africanmathsinitiative/R-Instat/pull/7614#issuecomment-1277734379 for part c)

### CODE REVIEW

**Comment by lilyclements** [comment]
@Vitalis95 about the part c bit - 

There are **eight** combinations which we can have (even if some of them are not entirely sensible!).

Let "f" denote a factor, and "n" denote a numerical variable
(And "m" is if it is in the multiple receiver)

Our options our:
fff
ffn
fnf
fnn
nff
nfn
nnf
nnn

Let's go through all these combinations:

`multiple_receiver_cols` will **always** contain the variables in the multiple receiver.
**However, depending if the multiple receiver contains a factor or a numerical variable will alter where we place `.x` in the R code**.
This is because as a factor, we tend to put `.x` as the value for the `factors` parameter (with the exception of if we have only factors)
As a numeric, we tend to put `.x` as a value for the `columns_to_summarise` parameter.

```
factor_summary <- "summary_count"
numeric_summary <- c("summary_sum", "summary_mean")
```

**f(m) x f x f**
If we have all factors, we want to set `columns_to_summarise` as `.x`:
```
multiple_receiver_cols <- c("fertgrp", "village")
list_of_tables <- survey %>%
  purrr::map(.x=multiple_receiver_cols,
             .f= ~ dplyr::rename(.data=data_book$summary_table(
               "survey",
               summaries = factor_summary,
               columns_to_summarise=.x,
               factors=c("variety", "village"),
               j=1),
               by_var="village")) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_top_left(variable='by_var') +
               mmtable2::header_left_top(variable="variety") +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

**f(m) x f x n** or **f(m) x n x f**
 If we have a numerical variable introduced, then we want to set `columns_to_summarise` as the numerical variable, and **cycle around the factor** - so put `.x` in the `factor` (and in the `by_var`) values:

```
multiple_receiver_cols <- c("fertgrp", "village")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ dplyr::rename(.data=data_book$summary_table(
               "survey",
               summaries = numeric_summary,
               columns_to_summarise = "yield",
               factors=c("variety", .x),
               j=1),
               by_var=.x)) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_top_left(variable='by_var') +
               mmtable2::header_left_top(variable="variety") +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

**f(m) x n x n**
If we have two numerical variables, then it is the same as above (f(m) x f x n), but with both numerical variables in the columns_to_summarise parameter value:
In addition: The mapping will only have `by_var` in it, not any other variable because we only have one factor each time.

```
multiple_receiver_cols <- c("fertgrp", "village")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ dplyr::rename(.data=data_book$summary_table(
               "survey",
               summaries = numeric_summary,
               columns_to_summarise = c("yield", "size"),
               factors=c(.x),
               j=1),
               by_var=.x)) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_top_left(variable='by_var') +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

**n(m) x f x f**
If we are cycling around the numerical variable, then we put .x in the "columns_to_summarise". This is always the case.
Then depending if the two single variables are factors or numeric determines if they go as the `factors` value or the `columns_to_summarise` value:
We also do not need to use the `rename` function, or the `by_var`, anymore when we have numerical variables as we are not cycling around factors now:

```
multiple_receiver_cols <- c("yield", "size")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ data_book$summary_table(
               "survey",
               summaries = numeric_summary,
               columns_to_summarise = .x,
               factors=c("village", "variety"),
               j=1)) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_top_left(variable='village') +
               mmtable2::header_left_top(variable="variety") +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

**n(m) x n x f** or **n(m) x f x n**
```
multiple_receiver_cols <- c("yield", "size")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ data_book$summary_table(
               "survey",
               summaries = numeric_summary,
               columns_to_summarise = c(.x, "field"),
               factors=c("village"),
               j=1)) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_top_left(variable='village') +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

**n(m) x n x n**
Not that this makes the most sense for the user to run, but it is possible to do:

```
multiple_receiver_cols <- c("yield", "size")
list_of_tables <- survey %>%
  purrr::map(.x = multiple_receiver_cols,
             .f = ~ data_book$summary_table(
               "survey",
               summaries = numeric_summary,
               columns_to_summarise = c(.x, "field", "fert"),
               j=1)) %>%
  purrr::map(.x=., .f= ~ mmtable2::mmtable(data=.x, cells=value) +
               mmtable2::header_left_top(variable="summary-variable"))
list_of_tables
```

@Vitalis95 I am a bit hesitant to make this into one function. But, I appreciate you may need to spend some time on this to understand what is going on. I don't think it should be difficult to code, per se, because we just change the values of `columns_to_summarise`, `factors`, and whether `rename` is used? (and then change the layers in the `mmtable2` code.

@rdstern what do you think? If I make this into a function, we are drawing the user closer to our code which I would rather avoid, and would make it harder for the user to understand the code. However, it is a bit complex as it is so I'm not sure if a user would be reading this anyway! Plus, I feel it is privy to a good few bugs if we don't use a function.

**Comment by lilyclements** [comment]
@Vitalis95 here's a flow chart to summarise that above:

Note the "c_t_s" = "columns_to_summarise"
"any other factor/numerical variables" refers to the variables in the single receivers

image

Whenever `factors = .x`, then we run the `dplyr::rename` function around our summarise function, and set `by_var = .x`

**Comment by rdstern** [comment]
@Vitalis95 when I try to run this it says a merge is in progress and I have to delete conflicts?

**Comment by rdstern** [comment]
@Vitalis95 I am getting build errors

**Comment by Vitalis95** [comment]
@rdstern , I am closing this PR because of the build errors- Have a look at PR #7978

**Pull request closed without merging**
