### PR TITLE
Export to WWR dialog (2020 updates)

### PR DESCRIPTION
**Pull request by dannyparsons**
This builds on and replaces #6122

Addition to #6122:
- WIGOS identifier added
- Put elements in group box
- WMO Number no longer required
- Small changes to headers in text output

@africanmathsinitiative/developers this is ready for review. There are only minor changes from #6122 to incorporate the 2020 updates to the documentation as described here https://github.com/africanmathsinitiative/R-Instat/issues/6110#issuecomment-752185738. Could one of Shadrack/Roger/Lily test this?

### CODE REVIEW

**Comment by dannyparsons** [comment]
@Patowhiz you can now check here for whether the file control is needed. On the dialog the user selects a folder, not a file, as multiple files are created.

**Comment by lloyddewit** [comment]
@shadrackkibet This PR is based on PR #6122 which you have already peer reviewed. So I can do the peer review on this PR.

**Review by lilyclements — CHANGES_REQUESTED** [review]
Changes to make:

1. Tab order for the main dialog needs some minor amendments
2. Can you add a warning on the sub-dialog, similar to that of the sdg for the NCMP metadata (in PR #6133) so that it explains why OK is not enabled?

**Comment by dannyparsons** [comment]
Thanks @lilyclements I've fixed those two changes.

**Comment by lloyddewit** [comment]
@rdstern Please could you test (this PR replaces PR #6122, which you didn't test yet)? thanks

**Comment by shadrackkibet** [comment]
This now appears to have conflicts. I would like to test.

**Comment by dannyparsons** [comment]
Fixed conflicts now.

**Review by rdstern — APPROVED** [review]
@dannyparsons and @lilycI am not able totest, but propose it would be great if this and the NCMP could be merged today.  So I shouldn't, but trust you guys and am therefore approving for the formality

**Comment by dannyparsons** [comment]
I tested with a number of example data sets and compared the output to the template files. It will be good to get further testing once merged.

**Pull request merged**
