### PR TITLE
New Sub Dialog for Climatic Data Entry Dialog

### PR DESCRIPTION
**Pull request by N-thony**
@lloyddewit this is a new and empty sub dialog for Climatic Data Entry Dialog.
Could you merge this? It doesn't have any code. Thanks.

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet @rdstern @dannyparsons This is a new sub-dialog that does not currently affect anything else in R-Instat. It requires 2 approvals. Please could one of you approve and merge? thanks

@N-thony What's the reason for adding this subdialog as a separate urgent PR? please could you clarify? thanks

**Comment by N-thony** [comment]
> @shadrackkibet @rdstern @dannyparsons This is a new sub-dialog that does not currently affect anything else in R-Instat. It requires 2 approvals. Please could one of you approve and merge? thanks
> 
> @N-thony What's the reason for adding this subdialog as a separate urgent PR? please could you clarify? thanks

@lloyddewit  this is required in issue #6352 where we need to move some controls from the main dialog to this sub dialog.

**Comment by shadrackkibet** [comment]
@N-thony there are other properties we always want to change whenever we create a new form. 
- SizableToolWindow = FixedToolWindow
- Localizable = True
- StartPosition = CenterScreen
- MinimizeBox = False
- MaximizeBox = False

Then why are there no changes in ` instat/instat.vbproj`? did you omit it?

**Review by rdstern — APPROVED** [review]
@lloyddewit the current data entry dialogue currently has 3 options and there are more to come!  It is going to get very cluttered.  So much cleaner to put all these options together on a sub-dialogue.

**Comment by N-thony** [comment]
@shadrackkibet sorry, I omitted instat.vbproj. I added it now.

**Review by shadrackkibet — APPROVED** [review]
A approve with the assumption that you will consider changing the above properties while working on the sub dialog.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
