### PR TITLE
graphics layers bug fixes

### LINKED ISSUE #5321: Order of layers still swapping on ggplot
The plotting is holding up much better now, than previously.  And I have been producing many plots for the climatic guide.

But I have (at last) found a simple reproducible example where the order of the layers still swaps (and where it then again says the offending layer can't be edited, because it is on the base layer.

The graph below has 3 layers.  Main one is a boxplot and then the additional layers are a line plot and then a point plot.

image

The data are here:
[mooringsplottest.zip](https://github.com/africanmathsinitiative/R-Instat/files/3144139/mooringsplottest.zip)

Main plot is from Moorings and is a boxplot of cumsum against dekad_abbr.

Then add  2 more layers: first is line plot and is for the newyear data frame.  y  is cumsum and x is dekad
second is point plot with the same x and y.  Change the size of the points to 3.5 and the colour to blue.
You should now get the plot above.
(If not, then perhaps the filter needs to be set again for Moorings.)

Now go in and edit both the 2 additional layers and change the x variable to dekadoct.  Do it for both together (one at a time and it is ok).  Now do the plot again.

The blue points have now gone, the order of these layers is now changed and neither can be edited further.

I hope this helps!

### PR DESCRIPTION
**Pull request by dannyparsons**
fixes #5321 

@africanmathsinitiative/developers this is ready for review and will need much testing

@Ivanluv I have built on your attempt in #5426 to remove the message. Looking at the code of the control, it needed some reworking to work properly so I've made more substantial changes to the layers control and simplified it hopefully.

Also, see what I did on the boxplot dialog. One thing was to ensure all geom parameters have a position, so the layers order correctly. The second was to make variable for all the geom parameter names and then pass this list to the plot subdialog. This is to ensure that you can't delete main dialog layers from the sub dialog.
This will need to be done on every plot dialog to work correctly. Maybe you could look at this with @shadrackkibet?

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Testing this now.

**Comment by shadrackkibet** [comment]
I also remember there is this annoying bug we experienced at TMA with Plot options when It is used in Climatic Boxplots then you try to open it in other dialogs, facets are disabled. Resetting doesn't help,

**Comment by dannyparsons** [comment]
Yes thanks, I've fixed that one in another pull request that I will push shortly.

**Comment by shadrackkibet** [comment]
I did quick testing of this,  seems to be working well for me.

**Comment by rdstern** [comment]
It seems to be working well for me too.  This is a great improvement.

**Comment by shadrackkibet** [comment]
There is this Multiple receiver issue resetting back to a single receiver sometimes when you move to the sub dialog and back, I don't remember exactly how this happens. Right now when you activate multiple receiver and leave it empty then close the dialog and then reopen, it resets back to the single receiver unlike when you have a variable in.

**Comment by dannyparsons** [comment]
ok thanks, that will be good to look at in another pull request.

**Comment by Ivanluv** [comment]
> There is this Multiple receiver issue resetting back to a single receiver sometimes when you move to the sub dialog and back, I don't remember exactly how this happens. Right now when you activate multiple receiver and leave it empty then close the dialog and then reopen, it resets back to the single receiver unlike when you have a variable in.

I think the bug from activating  the multiple receiver and leaving it empty then on reopen it sets back to the single receiver is from the `setControlValue()` method in the ucrVariableAsFactor. This is because on reopen, the method is checking if the is any current  variables present and if true it is setting the receiver to Multiple otherwise its setting it to single

**Comment by shadrackkibet** [comment]
Are you able to fix it?

**Comment by Ivanluv** [comment]
I Think it requires  discussion to make any code changes

**Pull request merged**
