### PR TITLE
Added position_dodge2 to bar chart and box plot

### LINKED ISSUE #5147: New `position_dodge2` for ggplot
A comment from [this closed issue](https://github.com/africanmathsinitiative/R-Instat/issues/4804) that has not yet been addressed.

> New position_dodge2() provides enhanced dodging for boxplots. Compared to position_dodge(), position_dodge2() compares xmin and xmax values to determine which elements overlap, and spreads overlapping elements evenly within the region of overlap. position_dodge2() is now the default position adjustment for geom_boxplot(), because it handles varwidth = TRUE, and will be considered for other geoms in the future.

It may not need any action for boxplot but it might require general changes somewhere.

### PR DESCRIPTION
**Pull request by Ogik99**
fixes #5147 

@africanmathsinitiative/developers this ready for review

### CODE REVIEW

**Comment by Ogik99** [comment]
@Ivanluv kindly test this

**Comment by Ivanluv** [comment]
am on it

**Comment by maxwellfundi** [comment]
@Ogik99  I find that even histogram can have this position. this looks good for these two.

**Comment by maxwellfundi** [comment]
@Ogik99  Also if you could place this position after the original dodge would be great.

**Comment by Ivanluv** [comment]
@Ogik99 For the barcharts after changing the position option to dodge2,I get the following error message
image

**Comment by Ogik99** [comment]
Thanks @Ivanluv  I have also gotten the same error.
@maxwellfundi kindly assist with this

**Comment by maxwellfundi** [comment]
I have been looking at this and the positions have been added well. @dannyparsons  I think this is okay. 

@Ogik99 I did the bar chart from the general graphics dialog ans i was able to produce the bar chart without the developer error. 

`# Code generated by the dialog, General 
survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=Variety.)) + ggplot2::geom_bar(position="dodge2")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")`

**Pull request merged**
