### PR TITLE
Corrects the minor grid lines options label in the panel tab of the theme sub-dialog

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes Partially #8351 
@rdstern I correct the name of frame but I'm still investigating on the reason why the `"Minor Grid Lines"` is not working because the code in to script looks nice.

image

### CODE REVIEW

**Comment by rdstern** [comment]
@N-thony this seems odd.  Is this now back to you to check, or who might investigate further?  Does it await the sprint?

**Comment by N-thony** [comment]
@MeSophie let me know when you are ready then we can have a look together.

**Comment by rdstern** [comment]
@N-thony and @MeSophie how is this going?

**Comment by N-thony** [comment]
> @N-thony and @MeSophie how is this going?

@MeSophie can you report what we found last when trying to include the `panel.minor.grid` in the map?

**Comment by MeSophie** [comment]
@rdstern After investigation, we have discovered that despite the fact that the code is correct, the `panel.minor.grid` is still not visible and this only with the map dialogue and  at least since version 0.7.6 .

**Comment by Patowhiz** [comment]
@MeSophie what is the status of this PR?

**Comment by MeSophie** [comment]
> @MeSophie what is the status of this PR?

@Patowhiz It still partially solves issue #8351. Because  After investigation, we have discovered that there is no change when we modify the values for the `panel.minor.grid` in the map. So I don't know if @rdstern will  agree that despite that this pr can be merge.

**Comment by Patowhiz** [comment]
@MeSophie I'm not sure if I understand you correctly, are you saying that the script produced by the minor grid lines options don't cause any changes to the final output? Have you tested the scripts in R Studio as well?

**Comment by MeSophie** [comment]
> @MeSophie I'm not sure if I understand you correctly, are you saying that the script produced by the minor grid lines options don't cause any changes to the final output? Have you tested the scripts in R Studio as well?

Exactly @Patowhiz I Also asked help to @N-thony the result was the same.

**Comment by Patowhiz** [comment]
@MeSophie from your research, is this an issue in the R package itself or it's an issue in R-Instat. It's important you do these tests in R Studio as well. And also check online if others have encountered the same issue. We could then document why we have disabled the feature with concrete references.

**Comment by MeSophie** [comment]
> @MeSophie from your research, is this an issue in the R package itself or it's an issue in R-Instat. It's important you do these tests in R Studio as well. And also check online if others have encountered the same issue. We could then document why we have disabled the feature with concrete references.

@Patowhiz  Maybe the problem is in the package. We searched in R-Studio and online. Minor grid lines works everywhere else, except in the mapping dialog.

**Review by rdstern — APPROVED** [review]
I'm just approving!

**Pull request merged**
