### PR TITLE
Renaming sub-menu items in Describe, Prepare, Climatic and Option by Context menus and Right Clicks.

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixex #7297 
@rdstern @shadrackkibet ,this PR is ready for review.
@N-thony will make the database changes so that it will be visible on the runtime

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
Great as far as it goes.
In my suggestions, items a) and b) are done.
Item c) remains.  That's partly to clarify the Select and Filter items, and also to add the item @N-thony is working on - to Add (Merge) Data.
Please can @shadrackkibet check and merge.  Can he also comment on my suggestions for clafying the Filter and Select entries.  If agreed, then perhaps do them before merging, or make them a separate pull request.

**Comment by Vitalis95** [comment]
@rdstern @shadrackkibet 
I have changed the label to Duplicate Rows... in Climatic and Options by Context menus
Also Changed Filter to Filter Rows... and Column selection to Select Columns.. in all right clicks
@N-thony will update them in the database to be visible on the runtime

**Comment by Vitalis95** [comment]
@rdstern @shadrackkibet 
Have a look at it

**Review by rdstern — CHANGES_REQUESTED** [review]
It still says Filter... rather than Filter Rows...
And the Describe T> wo Variables should become Describe Two/Three Variables

**Comment by shadrackkibet** [comment]
@Vitalis95 could you send screenshots of the translation DB changes. Looks like GitHub cannot `diff` a binary file.

**Review by rdstern — DISMISSED** [review]
Great.  Perfect - for me anyway.
@shadrackkibet please also check and then good to merge

**Comment by Vitalis95** [comment]
@shadrackkibet here are the screenshots
image
image
image
image
image

**Comment by shadrackkibet** [comment]
@Vitalis95 why the changes on `instat/translations/rInstatTranslations.db-journal`? I can't seem to understand this.

**Comment by shadrackkibet** [comment]
Then you forgot the right in column metadata!

**Review by shadrackkibet — APPROVED** [review]
@rdstern if you approve then we can merge. Thanks

**Comment by shadrackkibet** [comment]
@Vitalis95 could you make this title a bit "specific"? which menu items changed? what else? Remember this title is used in the release notes therefore it should be informative to the user.
image

**Review by shadrackkibet — APPROVED** [review]

**Comment by shadrackkibet** [comment]
> @shadrackkibet I wonder about adding 2-Way Frequencies and 3-Way Frequencies first - see #7259 ., but also approve if you want to do that separately.

@Vitalis95 consider adding this on a separate PR.

**Pull request merged**
