### PR TITLE
Dlg Display of daily climatic data..

### PR DESCRIPTION
**Pull request by stevenndungu**
@Lunalo pick up from here on Display Daily Climatic Data

### CODE REVIEW

**Comment by stevenndungu** [comment]
Passed this on to @Lunalo  who is currently working on it.

**Comment by dannyparsons** [comment]
@Lunalo are you working on this on another branch? There is a conflict on this branch.

I also have the R code to do the tables part so I can send that to you.

**Comment by Lunalo** [comment]
I have pulled the changes from this branch. If you merged the r code. I can get the code from this and create a new branch.  I am editing r code for the graphs

**Comment by dannyparsons** [comment]
Ok so I'll close this now. I had already merged the R code for the table so you can use that as well.

**Pull request closed without merging**
