### PR TITLE
Adding R-Instat website files

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  These are the first website files that i have added to the docs folder. 

Could you please merge them, the we will have our site up.

**Comment by dannyparsons** [comment]
Thanks for spotting this. I had a check on the chuffed site but can't see a way of editing comments unfortunately so we'll have to leave it like that.

**Comment by maxwellfundi** [comment]
Was that a comment? I thought it was part of the update?

**Comment by dannyparsons** [comment]
You're right thanks, it's both. I can't edit on the comments but I can edit the update.

**Pull request merged**
