### PR TITLE
Improvements to Date Keyboard

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes part a to f of #5999
I have done the following;
Changed the name for the date keyboard toDates/Times
Added four keys namely; asdate, datetime, time and pm
Implemented the functionality of the keys.

@africanmathsinitiative/developers This can be reviewed

### CODE REVIEW

**Comment by Wycklife** [comment]
@dannyparsons Could please check whether the arrangement and the functionality of the keys is okay? Then we are to discuss the last part of the issue.

**Comment by rdstern** [comment]
@Wycklife yes please consider the discussion on g) with @dannyparsons.  Meanwhile:
a) You said you did a), but you only did it in one of the 2 places.
b) You omitted to do b).  To me that's minor, but also serious, because it implies you are still not testing what you have done.
c) Not what I asked, but I would like you to be making suggestions yourself. - the layout of the keyboard looks messy.  I suggest you make it 4 keys across - at this stage - and don't include the 2 keys that are not activated.

**Comment by Wycklife** [comment]
@rdstern Thank you for the comments. Honestly I forgot to implement part b. The arrangements was to be done once the last part is discussed. Otherwise I have resolve your comments above. For the last part of the comments above, I think I told you one of the keys you mentioned(date) already  exist in the keyboard, so what I added was as date, which now uses as_date function. The two keys are different.

**Comment by lloyddewit** [comment]
@Wycklife please could you confirm that you have resolved all of @rdstern 's comments? thanks

**Comment by Wycklife** [comment]
@lloyddewit I still have a discussion on this with @dannyparsons

**Comment by Wycklife** [comment]
@lloyddewit After discussing this with @dannyparsons, this PR should now be reviewed.

**Comment by lloyddewit** [comment]
@shadrackkibet please could you review? thanks

**Comment by lloyddewit** [comment]
@shadrackkibet If you get a chance, please could you review? thanks

**Comment by shadrackkibet** [comment]
Thanks for the reminder. I will review now.

**Comment by shadrackkibet** [comment]
I comment based on the reported issue and what has been done here.

>RDS: b) We already have an hour, minute and second function. The hours works fine, but the minutes and seconds should be corrected. lubridate::min should become minute and sec becomes second.

b) If I understand correctly. The following key labels should change too i.e Minute and Second respectively?

>RDS: c) There is a function lubridate::date. I am not sure of the difference between that and lubridate::as_date, - do we need both? If not, I suggest there be three top buttons lubridate::date or as_date (called date on the key), lubridate::as_datetime( ) (and called datetime on the key) and hms::hms( ) and called time.

c) On checking the functions documentation. I think `as_datetime` and `as_date` is the same.  Therefore one should be removed!

- Another point I noted is that the key in the last row (d_in_m) doesn't work. I think it should be days in month and use the function `lubridate::days_in_month()` . Also move this button so that it next to **day** button then **wday** @rdstern can confirm?
- I also note that you have another PR(#6087) editing the calculator.

**Comment by lloyddewit** [comment]
I received an email from @rdstern that stated that @Patowhiz will take over this PR, so I thought this decision should be added as a comment.
@rdstern, @Patowhiz if I misunderstood, then please let me know, thanks

**Comment by Patowhiz** [comment]
@lloyddewit yes. I've now taken over this task.

**Comment by dannyparsons** [comment]
@Patowhiz do you have a new PR for this work?

**Review by rdstern — APPROVED** [review]
@lloyddewit I am happy to see this merged.  I hope the code is ok.

**Comment by rdstern** [comment]
I would like it to be merged quickly and think it will not overlap with the other pull request from @Patowhiz using this dialogue.

Looking at @shadrackkibet query, his point c) remains and should be very quick for @Patowhiz to do.  So it is worth him taking it over quickly, for that.

**Comment by Patowhiz** [comment]
This is now continued in PR #6257

**Comment by maxwellfundi** [comment]
@HawardKetoyoMsatsi @Patowhiz  You can now go ahead and review this.

**Comment by Patowhiz** [comment]
@maxwellfundi  This is now continued in PR #6257

**Comment by shadrackkibet** [comment]
Closing since this has been continued (not branched) elsewhere.

**Pull request closed without merging**
