### PR TITLE
Changed underlying R function in dlgOneVariable Summarise > customised tab (from mmtable function to gt function)

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
This is a continuation of issue #8248 
@rdstern and @lilyclements, This is ready for review.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@anastasia-mbithe this is great.
a) I am not sure if you changed the skim option, but it now does seem to provide all the numeric summaries on a single line, which is great.  
b) It includes the Summaries button which I assume should be hidden.
c) On the customised could there be a group box with a label Rows:  Then I suggest the first (default) option might be Variables, see below.  The other two options are just as you have them now, namely Variables and (lastly) None.
d) Could there be another option Display Missing as: , with a drop down for options, and the facility to type youe own.  NA is the (visible) default followed by (blank) which ideally is written like that, but gives a blank.  Otherwise it is just spaces.  Then perhaps . is another option and --- might also be provided?

**Review by lilyclements — COMMENTED** [review]
@anastasia-mbithe this is looking great - I have nothing to add. Let me know once Roger's suggestions are implemented and I'll re-review. Nice one!

**Review by rdstern — COMMENTED** [review]
@anastasia-mbithe that's looking very nice now.
You are quite right - only an idiot (me) would say Rows when it should be Columns!
And a tiny detail - I can't see exactly whether the Options button is lined up with the Omit Missing Values checkbox, or is slightly low?

**Review by rdstern — COMMENTED** [review]
@anastasia-mbithe this is looking very nice now.  Here is an example, when I made fert into an ordered factor!  It shows that then there is a min and a max - which you don't have for an ordinary factor.  It even calculates the median - I didn't realise it could do that!

image


I hope it might now be easy to add 2 controls from the general summary tables dialogue

image

This would make it more useful, and it can also be a teaching tool.  What is a table?  How can we make it more attractive, and so on!

And could you also delete the As from the Display Missing As.  I think having the As there in English is sort of ok, but it could be tricky to translate.

**Comment by rdstern** [comment]
@lilyclements and @anastasia-mbithe could you please also check the code you are using?  It is all working swimmingly with my little survey which has 36 rows.  Howver, when I tried with Dodoma and then a trivial summary of one variable (carat) and default summary for the diamonds I always had to break out.  It never finished.

**Comment by anastasia-mbithe** [comment]
@rdstern, I have tested the dialog severally using Dodoma and Diamonds datasets, it gets to give an output, only that there is a lag for almost a minute, for the Diamonds data (maybe due to the dataset's size).
image

**Comment by rdstern** [comment]
@anastasia-mbithe working now ok

**Comment by anastasia-mbithe** [comment]
It's ready now, I just had to update the branch, for the sub-dialog functions to be consistent.

**Review by rdstern — CHANGES_REQUESTED** [review]
@anastasia-mbithe This development is exciting.  

a) I occasionally get the developer error when pressing the Format button

image

b) The Format code seems to be missing!  I don't get a change of theme, or a title, when I ask for them.

c) Could you make the 2 labels wider for the French text.  That's the Omit Missing Values and Save Summary.  (Come to think of it, you are making it into a table, so I wonder about Save Table instead?

d) I would very much like to merge this in the version this week.  If you are still waiting for the Missing options, then perhaps disable for now, so it can be merged.

**Review by rdstern — APPROVED** [review]
@anastasia-mbithe this is looking great now.  What a teaching tool we are getting towards!  @lloyddewit over to you

**Pull request merged**
