### PR TITLE
Linked sub-dialogs to their respective sub-help

### LINKED ISSUE #6967: Set Links for the sub-dialog Help so that  you are able to jump to a specified anchor point
First there are (at least for this task) 2 sorts of sub-dialogue.  If you look at Describe One Variable > Summarise and use the Customise button you will see there is an option Choose Summaries, for that sub-dialogue.  Now that is a sub-dialogue used by quite a number of dialogues, and Rachel has a special place in the Help for those.  The graph sub-dialogues is another example used by many dialogues.    

In contrast the Describe > One Variable > Graph has a Graph Options button and that is a sub-dialogue, just for that dialogue.  So then we jump to an anchor point in the Help for that dialogue.    

For that dialogue there isn't the proper help yet, but I have made the anchor point.  

Rachel has included 4 so far, that are used repeatedly, namely Data Options, Plot Options, Summaries and Save Column Position.  There may be more?  You could include those links in the code for now.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #6967

Since we were unable to link to specific anchor points in the help file, this PR links some of the singly used sub-dialogs to their respective sub-help in the help file.

@africanmathsinitiative/developers This is ready for review.

### CODE REVIEW

**Comment by Wycklife** [comment]
@rdstern Kindly have a look and leave a comment.

**Review by lloyddewit — DISMISSED** [review]

**Comment by rdstern** [comment]
@Wycklife it is really good that you are doing this.  To test I need you to report at least some of the specific dialogues where you have changed the help to go to the right place for the sub-dialogues.
I tried just one example, namely the Frequencies dialogue, and that sub-dialogue just went to the top.  I don't evben know if that is one that should go to the special sub-dialogue place for that dialogue or the more general place for sub-dialogues that are used with multiple dialogues.

**Comment by Wycklife** [comment]
@rdstern I will upload the excel sheet containing a list of the singly used sub-dialogs. Since we were unable to link to specific anchor points, this PR takes you to the top of the dialog containing  that particular sub-dialog(This is because of the .chm file I have).

**Comment by Wycklife** [comment]
I'm closing this PR since the branch has got conflicts. The changes are being done on a new branch.

**Pull request closed without merging**
