### PR TITLE
Minor bug fixed in the Merge Dialogue

### LINKED ISSUE #7414: Small Bug in the Merge Dialogue
While testing PR #7404, the bug in the screenshot below is expected, and this is not coming from the change made in PR #7404 but from the way the dialogue was implemented.
image

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7414 
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@N-thony Thank you for this PR.
I see that you have renamed some variables but I can't see what else has changed.
Which lines fix the bug?
Thanks

**Comment by rdstern** [comment]
@N-thony I assume this is the main prepare > reshape > merge dialogue, but I'm not sure what to do to check this is resolved?  What data and example gace that error before?

**Comment by N-thony** [comment]
> @N-thony I assume this is the main prepare > reshape > merge dialogue, but I'm not sure what to do to check this is resolved? What data and example gace that error before?

@rdstern while testing PR #7404 with the survey dataset, tried to open the Merge dialogue, you will get the bug that this PR attends to fix. To quickly avoid that bug in the merge version since it was easy to fix, I did the fix in this PR.
First test PR #7404 and in that same branch try to open Merge dialogue and you will get the bug.

**Review by rdstern — APPROVED** [review]
No problem with Merge here, which there was with the pull request @N-thony pointed me to.  I hope all will still work when both are merged.
Ok from my side now.  Over to @lloyddewit or @ChrisMarsh82

**Comment by lloyddewit** [comment]
> @N-thony Thank you for this PR. I see that you have renamed some variables but I can't see what else has changed. Which lines fix the bug? Thanks

I don't see any functional changes in the code, so I can't see how this PR has fixed a bug.
Am I missing something?

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
The functional change in this PR is that 'New' has been added to lines 22, 23, and 29.
This is a temporary fix for issue #7414 and part of #7438. 
The real issue is that an event handler in this dialog is called before `SetDefaults()`. This issue was introduced by PR #7404.
Another complication is that this PR was branched from master before PR #7404 was merged so we cannot fully test this branch.
@N-thony and I discussed. On balance, we decided to merge this PR and address the root cause of the problem in issue #7438.

**Pull request merged**
