### PR TITLE
Output Window

### PR DESCRIPTION
**Pull request by Patowhiz**
Addresses issue #4835
Hiding and showing of commands in the output window.
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by Muthenya** [comment]
I've tested this and it's working well. I just have a thought.

Is there a need to have the comment when the commands are hidden? I don't find it necessary. I think it is more logical when hiding and showing both.

image

**Comment by rdstern** [comment]
Good question.  That was discussed, because Patrick brought it up earlier.  We would still like to keep the comments - or at least keep the option of having comments and having R-commands separate.  I am hoping that soon users will not accept the default comments, but put in something more useful that reflects the output, rather than the commands.  I also like the bit of green being there to separate different parts of the output.

At this stage we are not even having the similar action for comments on the right-click.  So turning off comments is through Tools > Options.

But if you (and Patrick) still feel strongly, then perhaps we could have a similar right-click option for the Comments as we now have for the Commands?.

**Comment by Patowhiz** [comment]
@rdstern to be honest. I strongly feel that the comments we are sending to the output window look and feel more of log events than output comments. They fit well in the log window,knowing where the code came from etc. But I'd expect comments on the output window to simply describe the output and not necessarily if its coming from the dialog or from which event(The user already knows this and if he wants to confirm he can easily go to the log window). If we could improve the output window comments then having the 2 options;switching of commands and comments will seem logical. 

Probably I miss the goal of the output window, I'm open to correction. 

For now, if we have to retain this the way it is then adding an option for switching off the comments too will be a safe bet. I'll remember to discuss this design with students at AIMS.

**Comment by dannyparsons** [comment]
The option for comments is very different from the option to show/hide commands. Show/hide commands is purely an output window setting - the command always gets added to the log, or script, but might not be shown in the output window if the user wishes.

The option for displaying comments **by default** (since this is still an option on every dialog) determines whether a comment is associated with the code that is being run, this effects whether a comment is added to the output window, the log window and script window. So it's not an option of the output window it's more general, so I feel it shouldn't go on the Output Window right click.

**Comment by Patowhiz** [comment]
Yep. That's a good point. Now I understand this. @dannyparsons what about having a separate setting for the output comments, just like the commands. Then we can switch the comments on the output window separately.  Then on our right click menu we can combine the switching of commands and comments to one. Something like hide (future) commands & comments.

**Comment by Muthenya** [comment]
I agree Danny. My thought was more on the fact that the comment mentions the dialog or action that has generated the code yet in the event one has chosen **Hide (future) commands**, the comment is still there.

My thought now is if one wishes to hide the comments as well, they can just clear the comment from the dialog.

**Comment by dannyparsons** [comment]
It can be useful to have the comments displayed without the command. If your command produces no output you can tell that anything actually happened if both are not visible - users rarely have the log window open. If users want to turn off commands I would be encouraging them to keep comments on so that they do see what's happening in the Output.

We probably should have a way of turning comments off from output window only. But I don't easily see a way to do this that isn't confusing with 1. the global show comments by default option and 2. the comments option on each dialog.

I can see users getting confused if they have output comments turned off because they won't see any effect of the comments checkbox on each dialog. This is sort of a failure of how we've set up these options so far but I see it as a bigger job to fix this at the moment and not having the additional option would be clearer at the moment.

**Comment by Patowhiz** [comment]
I agree. @rdstern do you concur. If yes, then I think @dannyparsons this will be ready for your review.

**Comment by Muthenya** [comment]
I thought this was ready @dannyparsons.

**Pull request merged**
