### PR TITLE
Improved the appearance of the Language toggle button and added the tooltip text

### LINKED ISSUE #6588: Improve appearance of language toggle button on tool bar
The language toggle button in the R-Instat tool bar is currently labelled 'Lan'. 
Could the appearance of this button be improved?
Please review the discussion and suggestions in PR #6572.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #6588 
Improved the appearance of the Language toggle button on the menu bar with an image on the button, and added the tooltip text.
@africanmathsinitiative/developers @rdstern @rachelkg this is ready for review. Thanks.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@N-thony  - nice!

**Comment by lloyddewit** [comment]
@N-thony Great! thanks for adding this.

image

The other tool bar buttons are square. They either have no border or a thin dark blue border.
The translation button is rectangular and smaller. It has a thick grey border. The edges of the speech bubbles are lost.
Is it possible to make the translation button consistent with the others (shape, size, border) and also show the edges of the speech bubbles?

**Comment by N-thony** [comment]
@lloyddewit thanks for your comment above. I think it is resolved, please have a look.

**Review by rdstern — DISMISSED** [review]
That does look better!

**Comment by shadrackkibet** [comment]
@N-thony I have two suggestions below.

- I would suggest the use of ToolStripButton instead of the ordinary Command button.
- This control should remain disabled when the software is loading like other icons in the toolbar. This will require adding one line of code in the following subroutine in `frMain.vb` file
image

**Comment by N-thony** [comment]
> @N-thony I have two suggestions below.
> 
> * I would suggest the use of ToolStripButton instead of the ordinary Command button.
> * This control should remain disabled when the software is loading like other icons in the toolbar. This will require adding one line of code in the following subroutine in `frMain.vb` file
>   image

@shadrackkibet thanks for your suggestions, but I don't think we need to add it in this subroutine.
We can just use it like OpenFromLibrary is used.

**Comment by N-thony** [comment]
@shadrackkibet I have change the Lan button control as you suggested above. Please have a look. Thanks.

**Comment by shadrackkibet** [comment]
> > @N-thony I have two suggestions below.
> > 
> > * I would suggest the use of ToolStripButton instead of the ordinary Command button.
> > * This control should remain disabled when the software is loading like other icons in the toolbar. This will require adding one line of code in the following subroutine in `frMain.vb` file
> >   image
> 
> @shadrackkibet thanks for your suggestions, but I don't think we need to add it in this subroutine.
> We can just use it like OpenFromLibrary is used.

Does this mean it will remain disabled until when the software is loading?

**Comment by N-thony** [comment]
> > > @N-thony I have two suggestions below.
> > > 
> > > * I would suggest the use of ToolStripButton instead of the ordinary Command button.
> > > * This control should remain disabled when the software is loading like other icons in the toolbar. This will require adding one line of code in the following subroutine in `frMain.vb` file
> > >   image
> > 
> > 
> > @shadrackkibet thanks for your suggestions, but I don't think we need to add it in this subroutine.
> > We can just use it like OpenFromLibrary is used.
> 
> Does this mean it will remain disabled until when the software is loading?

Sure, see line 207 of in the subroutine.

**Comment by shadrackkibet** [comment]
If it does that then its fine

**Review by shadrackkibet — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
@shadrackkibet and @N-thony very nice and neat feature now.

**Comment by shadrackkibet** [comment]
The icon still appears fainted when enabled. We need to improve the appearance, I think if the borders of the logo are black/bright blue in colour and the circular logo inside also improved. 

I think this is sufficient improvement from the ordinary command button and therefore I merge.

**Pull request merged**
