### PR TITLE
added table containers to main windows (to have better positioning on screens that zoom) and corrected docking on receiver controls

### PR DESCRIPTION
**Pull request by dannyparsons**
@africanmathsinitiative/developers if I have done this well then you shouldn't see any change (almost). I have changed how controls in the main form are positioned. This links to #3864 where controls do not resize correctly on all screens. I can replicate this on my machine so I have been tested.
So hopefully this shouldn't affect the way controls display on normal screens like yours. If you do get any strange designer changes let me know. A small visible change is that there is now a small margin between controls within the main windows. It's hardly noticeable, I think it looks ok, but if it's preferred the other way without margins I can change that.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
I notice a blue margin on the output window.Is this what you mean here?

**Comment by dannyparsons** [comment]
Yes, that's one difference. There's now a thin margin between controls within each window. So there is now a small gap between the blue label at the top of each window and the controls below it, and a gap around the edge of the window, which is why you can now see the blue outline of the output text box. This is because I've put everything in a table container so it has default margins. If we want to go back to how it looked before I think we could set the margins to 0.

**Comment by shadrackkibet** [comment]
I notice a strange behavior, when you open any dialog the colour of the margin in the output window changes. Do you notice this?...

**Comment by dannyparsons** [comment]
I'm not getting this, is anyone else? I get the blue margin when I hover over the output window with the mouse. But nothing changes when I just open a dialog.

**Pull request merged**
