### PR TITLE
Removes script menu item from main form

### PR DESCRIPTION
**Pull request by Patowhiz**
This PR removes the  Edit > Script menu item that open the Insert Script dialog. The dialog will be opened from the script window once PR #8597 is merged.

@rdstern @N-thony this is ready for your review.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@Patowhiz looks fine.  The branch seemed to take a long time to load, for such a little change, but it did the job.  So fine from my point of view.

**Comment by Patowhiz** [comment]
@rdstern that's very odd. I'm not expecting any loss in performance. 
@N-thony kindly countercheck if the changes done here have affected performance.
Thanks.

**Comment by Patowhiz** [comment]
@rdstern can you try loading again. Thanks.

**Comment by rdstern** [comment]
@Patowhiz thanks - almost instantaneous now!

**Comment by Patowhiz** [comment]
@rdstern thanks. 
I can quickly merge this once you click on the Approve button. I also require @N-thony or @ChrisMarsh82 to click on the same button for me to merge because I'm the author of the changes.

**Comment by Patowhiz** [comment]
@N-thony if you approve these changes then I can merge to avoid conflicts.

**Pull request merged**
