### PR TITLE
Polynomial- Bug Fix

### PR DESCRIPTION
**Pull request by stevenndungu**
On rdo Centre, the receiver would reset automatically on reopen.

### CODE REVIEW

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers  this is ready for review.

**Comment by AlexSananka** [comment]
testing this

**Comment by AlexSananka** [comment]
This seems to still have a tiny issue with resetting on the panel,When I fill the receiver and click on rdocentered then the click OK.
Then reopen the dialog it resets automatically to rdosimple.

Only this one issue before it's  ready for @dannyparsons

**Comment by dannyparsons** [comment]
Remind me tomorrow to look into this if there's time, otherwise this is a known bug we include in release notes.

**Comment by AlexSananka** [comment]
Ok No problem

**Comment by stevenndungu** [comment]
Fixed the issue, @AlexSananka .This is now fully ready

**Comment by AlexSananka** [comment]
@dannyparsons This is ready for you.

**Pull request merged**
