### PR TITLE
View graph fix

### PR DESCRIPTION
**Pull request by lilyclements**
This is at a standstill until the issues I have mentioned in #3834 can be addressed

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  the issue #3834 needs to be addressed so that lily can finish up this. @lilyclements  does this work properly except for the issues in the #3834 ?

**Comment by lilyclements** [comment]
Yep this works fine asides from the final issue in #3834

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is fine (in my opinion) as it is so perhaps could be reviewed now?

There is still a bug which could be done on a new pull request. Otherwise, someone can take over this branch if you prefer.

The remain bug is that this dialog should only accept `ggplot` graphs, however, it is currently accepting
`gtable` `gTree` `grob` `gDesc` graphs (from the dialogs One Way Frequencies or One Variable Graphs (if you use combine)). These graphs do not work for any of the radio buttons so we need to fix this.

**Comment by maxwellfundi** [comment]
@dannyparsons  this is ready for you!

**Comment by dannyparsons** [comment]
I think the remaining issue from Lily is written up somewhere but can you check @maxwellfundi and write an issue if not?

**Pull request merged**
