### PR TITLE
Improvements on Import from Library Dialog

### LINKED ISSUE #7205: Three small improvements in File > Import from Library
@shadrackkibet these are pretty trivial - well 2 are, and the 3rd is optional, and only if you agree?
1. The menu item is now Import from Library.  So please change the title in the dialogue from `Open Dataset from Library` to` Import from Library`. 
2. There is a second Help button on the right of the dialogue, just below the list of files.  Change this from `Help` to `R Help`, so it is distinguished from the main Help button.  Alternatively it could be` Info`, but I think `R Help` will be fine.
3. I find I often do a double-click on a data set and expect it to work.  Now that is unusual in that we don't have any other dialogues that use double-click to implement Ok.  We do have double-click in the data selector to copy a selected variable to the receiver, so it is consistent with that.  I would certainly find it convenient.    Danny is Ok with the idea - at least not against it!

We will soon have a video on this dialogue.

### PR DESCRIPTION
**Pull request by Gioche6**
Partially Fixes Issue #7205

@africanmathsinitiative/developers , This is ready for review. 
@rdstern , I have fixed item 1, 2 and 3 in [7205`](https://github.com/africanmathsinitiative/R-Instat/issues/7205). 
I am currently working on item 4 on the comments. Kindly test it. Thank you

@shadrackkibet  Kindly test and review. 
@lloyddewit , could you update the Translation dialog for the renaming's in this PR, so that they can appear on the run-time?

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@Gioche6 you say you have fixed 1, 2 and 3.
3 - the double-click seems to work fine.
But there seems no change to the help label nor the title at the top?  Is it to do with thge language translations that the changes are not visible, or were they omitted?

**Comment by N-thony** [comment]
> @rdstern , once @lloyddewit solves the translations in this PR, the changes will be visible on the runtime.

Thanks @Gioche6, @lloyddewit @rdstern actually I have a PR open where I'm updating the database, I will add the translation requested here in my PR #7243.

**Comment by lloyddewit** [comment]
> > @rdstern , once @lloyddewit solves the translations in this PR, the changes will be visible on the runtime.
> 
> Thanks @Gioche6, @lloyddewit @rdstern actually I have a PR open where I'm updating the database, I will add the translation requested here in my PR #7243.

@N-thony Thank you!

**Comment by lloyddewit** [comment]
@Gioche6 Does this PR fully or partially fix issue #7205 . If partial then please change the text in your opening comment, otherwise the issue will be closed automatically on merge.

**Comment by Gioche6** [comment]
@lloyddewit , Thanks, I have changed the opening statement. I'll update it once I have done everything that fixes the issue.

**Comment by rdstern** [comment]
@Gioche6 or @N-thony is anything happening on the conflicts?

**Comment by shadrackkibet** [comment]
@Gioche6 left INNODEMS.

@N-thony I assume you are taking over this task.

**Comment by N-thony** [comment]
> @Gioche6 left INNODEMS.
> 
> @N-thony I assume you are taking over this task.

@derekagorhom is the one who will take over with my support all the tasks assigned to @Gioche6,

**Comment by derekagorhom** [comment]
> @derekagorhom I presume this PR has now been replaced with #7342 ?

yes please

**Comment by lloyddewit** [comment]
Replaced by PR #7342

**Pull request closed without merging**
