### PR TITLE
Added 12 keys, tooltips for some of the keys and also rectify some of the proposed changes to the Probability Keyboard 

### LINKED ISSUE #5549: Tooltips and improvements to the calculator probability keyboard
Here is the second keyboard for the tooltips. At the same time I suggest some improvements and the correction of an error.
1. **_The errors first._**  In the existing keyboard the pF key actually delivers the pchisq function.  Correct this to give pf.  And the pchi key gives pt! So change that to give pchisq.  Then change pF and qF keys to **_pf_** and **_qf_** (which corresponds to the function names.) 
2. There are currently 18 keys in the keyboard, but they are not in logical and clear positions.  I propose an improved layout together with the addition of 12 more keys.  So there will be a 5  by 6 array of keys.  As follows:

Row 1: pnorm, pt, pchisq, pF, pgamma
Row 2: qnorm, qt, qchisq, qF, qgamma
Row 3: pbeta, pbirth, pbinom, ppois, pnbin
Row 4: qbeta, qbirth, qbinom, qpois, qnbin
Row 5: fact, choose, beta, gamma, digamma
Row 6: lfact, lchoose, lbeta, lgamma, trigamma

Note, if need be, then some of the keys can be shortened to fit, e.g. pbin could be instead of pbinom.  

The distrbutions are all described in [this page](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Distributions.html). For example pbirth is the birthday problem, function pbirthday and qbirthday.  That distribution is a useful idea in teaching. 

Next the tooltips for these keys.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5549 
Added 12 keys
Added the tooltips for the proposed keys
Made some designer changes
@africanmathsinitiative/developers This is ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
@Wycklife that is looking great.  The keyboard is neat and so much clearer now.

a) The wrong functions from pf and pchisq are still there.  The pf key gives the command pchisq() and pchisq gives pt().
b) In the tooltips I suggest you delete up to the : .  You don't need to repeat the key name, because they are hovering there.  So qnorm tooltip should just say **_normal quantiles  For example...etc_**.  

Now I need to proceed and do more myself!

**Comment by Wycklife** [comment]
@rdstern Noted and working on them

**Comment by Wycklife** [comment]
@rdstern This is now complete, kindly have a look at it.

**Comment by Wycklife** [comment]
@rdstern I think comment (2) should be 4*3*2*1, which give the factorial of 4.

**Comment by Wycklife** [comment]
@rdstern Noted with thanks

**Comment by Wycklife** [comment]
@rdstern This is now okay.

**Comment by rdstern** [comment]
This is now giving an error when I try to test again.  @Wycklife could you check?

**Comment by Wycklife** [comment]
@rdstern Checking it now.

**Comment by Wycklife** [comment]
@rdstern I'm replacing this pull request with a new one.

**Comment by Wycklife** [comment]
@rdstern  I have resolve this on a new pull request. I'm closing this one.

**Pull request closed without merging**
