### PR TITLE
New verification dialog

### PR DESCRIPTION
**Pull request by shadrackkibet**
@maxwellfundi can you review, approve and merge this? Perhaps @lloyddewit would you like to check and approve it first? This is linked to #5843.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet Thank you for the commits. Please could you explain a bit more about your changes? Does this PR fix #4843 completely or just part of it? If the issue is not completely fixed, and you'd still like to merge, then please could you justify? Thanks

**Comment by shadrackkibet** [comment]
This has no relationship with PR #4843.

**Comment by lloyddewit** [comment]
> 
> 
> This has no relationship with PR #4843.

Sorry typo: #5843

**Comment by shadrackkibet** [comment]
This partially addresses changes that touches on frmmain from issue #5843.

I would like this merged because this will take a substantially amount of time to complete and I would not like to block anybody from working on the frmmain. Otherwise, that will cause conflicts.

**Comment by lloyddewit** [comment]
@shadrackkibet Thank you for the clarification, sounds sensible.
@rdstern This is just a placeholder for the new dialog so I don't think there's anything to test.
@maxwellfundi Please could you merge? thanks

**Comment by rdstern** [comment]
Great.  That was the reason for my quick skype request.  Happy it is resolved.

**Comment by shadrackkibet** [comment]
@lloyddewit I have just noticed we need a new sub dialog for the new dialog. So I have added it here.

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit I have just noticed we need a new sub dialog for the new dialog. So I have added it here.

@shadrackkibet Thanks for letting me know, I looked at the new changes and I'm still happy for @maxwellfundi to merge.

**Comment by shadrackkibet** [comment]
@lloyddewit I noticed I need to make a user control which will be used in other dialogs. So I have added it here.

**Comment by lloyddewit** [comment]
@maxwellfundi Thanks for the merge and quick discussion. I agree that the change was small and low risk, and that it was safe to merge. We deviated slightly from the process because the final commit was not formally approved before the merge was done. I understand that in future we'll follow the process more precisely and always formally approve a commit (even small ones) before the merge is done. 
I hope this is a simple approach which does not cause delays or extra work. However it's always a tradeoff between extra quality checks and efficiency. If you find this approach is slowing us down too much then we can adapt.

**Pull request merged**
