### PR TITLE
Adding column chart option to dlgBar and Pie chart

### LINKED ISSUE #5464: Adding a column chart button to the bar chart dialogue
I suggest this could be quite an easy addition.

The current Describe > Specific > Bar Chart dialogue has 2 buttons at the top.  I suggest a third button Column Chart after the Pie Chart.

This is the same as the Bar Chart, but with the stat="identity" as automatic.  It is alternatively geom_col which we have already.  So it can call geom_col.  
a) This is just the same as geom_bar, but with the stat="identity".  So in the properties of the geom I suggest we swap the order.  Currently the order is count, followed by identity - which is correct for geom bar.  I suggest it should be the other way round for geom_col.
b) On the main dialogue There should now be a new receiver.  I assume this should be the usual Y variable - which can therefore be Single/Multiple as for other graphics dialogues.  The existing single receiver is now the X-Variable.
c) Currently this x-variable can take numeric (as well as factors), though it is usually a factor.  Please keep this flexibility, i.e. don't restrict it to a factor.
d) While there, the pie chart option is restricted to a factor column.  Allow this to be (as for the ordinary bar chart) into numeric as well.
e) I suggest the third option could usefully also have the width of the bars on the main dialogue.  We will often want that to be much less than the default of 0.9.    If necessary that can come later.  

The issues of labeling are the same as in #5398 , except that labeling of an ordinary bar chart is just a count, while labeling here needs formatting decisions.  That can come later.

Here is an example of this third option:
image

### PR DESCRIPTION
**Pull request by Ogik99**
fixes #5464 

@africanmathsinitiative/developers this is ready for review

### CODE REVIEW

**Comment by Ogik99** [comment]
@Patowhiz you can check this now.

**Comment by rdstern** [comment]
It looks good.  I have checked that it seems to do all as before, and returns nicely to the dialogue on repeated occasions.  I have not checked the code itself.
@Patowhiz From what I have seen I would be happy for this to be merged.

Later a useful challenge for the graphics generally will be to be able to reproduce examples where the articles use the code.  Here is an example, called dot plots and bar charts from [Iowa University](https://homepage.divms.uiowa.edu/~luke/classes/STAT4580/dotbar.html).

**Comment by Ogik99** [comment]
@Patowhiz any final comments

**Comment by maxwellfundi** [comment]
@Ogik99 does this have improvements ready?

**Pull request merged**
