### PR TITLE
Adding threshold range plot into Extremes dialog

### PR DESCRIPTION
**Pull request by shadrackkibet**
Continuation of work in #5881. @rdstern this is ready for you to test. This is the implementation of the threshold range plot as discussed via skype earlier this week. Once this is reviewed and merged I will continue further with the "final" aspect i.e declustering.

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@shadrackkibet from my point of view this is working ok.  Good to merge.

**Comment by shadrackkibet** [comment]
@rdstern thanks for testing.

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review? 
@dannyparsons if you'd like to review the R changes before this is merged, then let me know
thanks

**Comment by Ivanluv** [comment]
@lloyddewit  the vb code looks okay from my end

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
