### PR TITLE
Improved smooth options in Line plot dialog.

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
@rdstern This is a continuation of the task started by @shadrackkibet in PR #6708. Could you kindly have a look at it.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
We discussed and there remain various options, particularly formula and family to add.  Then it is an exciting improvement to our system.

**Comment by anastasia-mbithe** [comment]
@rdstern Kindly have a look at the changes made and test them.

**Comment by rdstern** [comment]
Well done.  This is looking good already and I think all the options are all there.  Please now discuss the layout in detail with @shadrackkibet who is better than me on that aspect.  I describe below.  On substance, each of the controls Span, Formula, etc should have a checkbox, as they are all optional.  This would also apply to the R-code you generate.  Unless you click the checkbox you don't need that option in the code.  Then I think Shadrack said the default for span would be 0.75.

Then it is just the look of the dialogue.  I would prefer that the set of options for Smoothing is on a maximum of 2 "lines".  Include thinking about how close to the lhs you start the controls, and the Method label doesn't line yet with the control.  
Also put the se on the right i.e. after the formula and family and Span.  You might decide ona group box - perhpas called Smooth to help making it all neat!

**Comment by anastasia-mbithe** [comment]
I have added a group box for the Smooth options and also check box for the Span and Formula Options. @rdstern you can check if its okay now.

**Review by rdstern — APPROVED** [review]
Great.  Very happy to approve.

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
