### PR TITLE
Added more distributions to General Fit Model dialog

### LINKED ISSUE #6345: Improving the General Fit Model dialogue
**Describe the bug**
There is a developer error in the ucrDistributions that occurs on a modelling dialog when "Reset" is hit, if the response variable does not have a corresponding distribution. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload data (for example, `diamonds` in the `ggplot2` library
2. Open the `General Model` dialog (under Model > Fit Model > General...)
3. As the response variable, input a variable which does not have a corresponding distribution associated to it. For example, a factor variable (e.g. `cut` in the `diamonds` data set)
4. Click reset, and a developer error occurs
 "Developer error: Cannot set value of ucrFamily because cannot find a distribution matching the function and parameter given"

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #6345  

@rdstern @lilyclements @N-thony , we have added (@Tula1 and I) `glm.nb`, `polr`  distributions from `MASS` package and `multinom` from `nnet` package.
For the factor response variables, the dialog runs `car::Anova`  to the saved model (type-II analysis-of-variance tables for model objects)

### CODE REVIEW

**Review by lilyclements — COMMENTED** [review]
@Vitalis95 this looks good! One small issue I found:

Take the Survey data set
Put village in the y receiver
Put field in the explanatory variates
Check "convert to variate"
Uncheck "convert to variate"
Press OK

It runs the Ordered_Logistic model, but still tries to run `stats::anova`, so gives an error

**Comment by Vitalis95** [comment]
@lilyclements , could you have a look at it?

**Review by rdstern — APPROVED** [review]
@Vitalis95 I really like those additions.  I suggest @lilyclements does another check, before we merge, but I would like to see this included as soon as possible

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@lilyclements if you can test/approve, then we can merge, thanks

**Review by lilyclements — APPROVED** [review]
This looks good! Nice job @Vitalis95

**Pull request merged**
