### PR TITLE
Showmodeldialog updating 

### PR DESCRIPTION
**Pull request by Lunalo**
Still in progress

### CODE REVIEW

**Comment by dannyparsons** [comment]
Is this currently working in the latest version? If it is, then I don't think this should be a priority until after the testing version is released.

**Comment by Lunalo** [comment]
@dannyparsons 

It is basically working but ucrDistributions was not resetting.  If this is okay . I can just fix it later

**Comment by dannyparsons** [comment]
If it's quick to do then fine, otherwise there are probably more urgent bugs to fix or write up.

**Comment by Lunalo** [comment]
I have just got the code back to its initial state  and fixed the enabling of ok

I will look into the resetting of the ucrDistributions and I think this will be ready

**Comment by Lunalo** [comment]
@dannyparsons 

I have fixed resetting of the distributions. 
The distribution and parameters were not being set in the setdefaults .

This is ready  @africanmathsinitiative/developers 
This is ready for review

**Comment by AlexSananka** [comment]
Reviewing this now

**Comment by AlexSananka** [comment]
Can we change the call type of this to be 3?

**Comment by AlexSananka** [comment]
Apart from the known issue of typing  in non integer values and characters to `ucrInputTextbox` the dialog is working fine,It resets properly.

 If the above issue on call type is solved then this will be ready for @dannyparsons

**Comment by Lunalo** [comment]
@dannyparsons 

Should we go with @AlexSananka  suggestion of displaying graphs in the output window?

**Comment by dannyparsons** [comment]
yes they should have the same call type as other graph dialogs

**Comment by Lunalo** [comment]
@lilyclements 

@AlexSananka 

This now ready for brutal testing

**Comment by AlexSananka** [comment]
It's good that you now have confidence in this.

Maybe @lilyclements can have a final review.

**Comment by lilyclements** [comment]
Reviewing this now

**Comment by lilyclements** [comment]
@Lunalo I made some edits waiting to merge

**Comment by Lunalo** [comment]
@dannyparsons 

This is ready

**Comment by AlexSananka** [comment]
I have tested this and now works fine.
@dannyparsons  This is ready for you.

**Pull request merged**
