### PR TITLE
Refactors model dialogs to use the new output system

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes some items in issue #7852

### CODE REVIEW

**Comment by rdstern** [comment]
@Patowhiz so far so good.
I have quickly tried Fit Model 2 variables, and 3 variables and general with no problem.  Also Climatic > Extremes quickly.  All run ok so far.  Well done.

One variable the General case seems to run fine and I tried a Test and that was ok.
But the estimate t or normal gives me this error - I think not serious, as I explain below:

image

image

When I look at the results, they seem ok, but I don't have the R script in the output window.  Or the comment.  So that must be where the problem is?

**Comment by rdstern** [comment]
@Patowhiz I have been trying more things and (at last) found a real problem to fix!  A different one.
I think it is caused by using plotly when it can't be used - and perhaps doesn't know?
a) Open dodoma.  b) Do an inventory plot of the 4 variables. c) All the graphics options work except plotly.  I don't mind not having plotly, but it then freezes up and I have to break out of R-Instat.

Incidentally I also tried plotly for a combined graph on the describe.  It didn't give it - which it did for facets.  But it didn't freeze then?

**Comment by Patowhiz** [comment]
@rdstern it hangs because of the R process in the background taking too long to respond back. 
I tried this in R studio too, the R process hanged. 

I'm not sure why it also takes so long, probably because of the details of the plot. 
I tested the plotly option inventory plot with a smaller dataset of 100 rows. It worked fine. 

We can open a separate issue on ggplots that take long for plotly to render and the discuss with @dannyparsons @lilyclements on what we should do for such plots.

**Comment by Patowhiz** [comment]
The bug you have encountered in the 1 variable fit is an existing one. Let me look into it.

**Comment by rdstern** [comment]
@Patowhiz thanks for those replies.  Neither of them stop the new version being used on Monday.

**Review by lloyddewit — DISMISSED** [review]
@Patowhiz Thank you for the changes.
I am not expert on the R-Instat assignment but the code looks good to me.
No action needed from your side. I may do some small formatting things. After that, I will go ahead and merge.

**Pull request merged**
