### PR TITLE
Partially Fixes Duplicates Dialogue

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes (partially) issue #7299
Small changes in the duplicates Dialogue 

Selected Variables has become the first button, and hence the default when you first use the dialogue. The Data Frame is then second. The Successive values remains the last button. 
And the pull down has the first entry as Index.

@Ivanluv could you please test this to confirm

### CODE REVIEW

**Comment by lloyddewit** [comment]
@derekagorhom thanks for this PR.
If a PR only partially fixes an issue then please write 'Fixes (partially) issue ...' (not 'partially fixes issue ...'), otherwise the issue will close automatically when this PR merges.
Thanks

**Review by rdstern — CHANGES_REQUESTED** [review]
Good to have the change in order of the top buttons.
The top title and the menu item is still to change as is the order of count and index.

**Comment by derekagorhom** [comment]
Hello @rdstern  could you test this again?

**Comment by rdstern** [comment]
@derekagorhom almost.  I am not clear why this task is so tricky.
It now seems to work most of the time.  Index is first and seems to be the default.  But when I returned to the dialogue a second time, after selecting that option, then it had gone back to Count!

**Comment by derekagorhom** [comment]
@shadrackkibet i have added a commit, could you check and confirm if the dialogue is working properly again
thanks

**Comment by shadrackkibet** [comment]
@derekagorhom now you have conflicts in your PR.

**Comment by Ivanluv** [comment]
@shadrack @derekagorhom  and I are to create a new PR with this changes and some more additions

**Comment by Ivanluv** [comment]
I will tag this PR on the new one

**Comment by derekagorhom** [comment]
@shadrackkibet  could you test it again

**Comment by shadrackkibet** [comment]
What about this conflicting file? `instat/translations/rInstatTranslations.db`

**Comment by lloyddewit** [comment]
> > What about this conflicting file? `instat/translations/rInstatTranslations.db`
> 
> @Patowhiz could you have a look at this please

@derekagorhom The database file is binary so we can't resolve the conflict within this PR. To resolve this conflict, you could do one of the following:
- Close this PR and make a new PR
- Remove the database changes from this PR (by checking out the latest database file, from main, into this PR); get this PR approved/merged; and finally, make a new PR for just the database changes

The first option may be easiest for this PR.

**Comment by N-thony** [comment]
> > > What about this conflicting file? `instat/translations/rInstatTranslations.db`
> > 
> > 
> > @Patowhiz could you have a look at this please
> 
> @derekagorhom The database file is binary so we can't resolve the conflict within this PR. To resolve this conflict, you could do one of the following:
> 
> * Close this PR and make a new PR
> * Remove the database changes from this PR (by checking out the latest database file, from main, into this PR); get this PR approved/merged; and finally, make a new PR for just the database changes
> 
> The first option may be easiest for this PR.

@lloyddewit to avoid this it will be good to have someone doing that, I think as discussed with @Vitalis95 who is happy doing that, it will be  good thesr changes by @Vitalis95 in his PR #7324.

**Comment by lloyddewit** [comment]
> > > > What about this conflicting file? `instat/translations/rInstatTranslations.db`
> > > 
> > > 
> > > @Patowhiz could you have a look at this please
> > 
> > 
> > @derekagorhom The database file is binary so we can't resolve the conflict within this PR. To resolve this conflict, you could do one of the following:
> > 
> > * Close this PR and make a new PR
> > * Remove the database changes from this PR (by checking out the latest database file, from main, into this PR); get this PR approved/merged; and finally, make a new PR for just the database changes
> > 
> > The first option may be easiest for this PR.
> 
> @lloyddewit to avoid this it will be good to have someone doing that, I think as discussed with @Vitalis95 who is happy doing that, I suggest these changes to be done by @Vitalis95 in his PR #7324.

@N-thony yes, that sounds sensible
@Vitalis95 is this OK from your side?
@derekagorhom to remove the database changes from this PR, please see the info [here](https://github.com/africanmathsinitiative/R-Instat/wiki/GitHub-notes), let me know if you have problems.
Thanks!

**Comment by Vitalis95** [comment]
@lloyddewit it is Ok from my side.

**Comment by derekagorhom** [comment]
> > > > > What about this conflicting file? `instat/translations/rInstatTranslations.db`
> > > > 
> > > > 
> > > > @Patowhiz could you have a look at this please
> > > 
> > > 
> > > @derekagorhom The database file is binary so we can't resolve the conflict within this PR. To resolve this conflict, you could do one of the following:
> > > 
> > > * Close this PR and make a new PR
> > > * Remove the database changes from this PR (by checking out the latest database file, from main, into this PR); get this PR approved/merged; and finally, make a new PR for just the database changes
> > > 
> > > The first option may be easiest for this PR.
> > 
> > 
> > @lloyddewit to avoid this it will be good to have someone doing that, I think as discussed with @Vitalis95 who is happy doing that, I suggest these changes to be done by @Vitalis95 in his PR #7324.
> 
> @N-thony yes, that sounds sensible @Vitalis95 is this OK from your side? @derekagorhom to remove the database changes from this PR, please see the info [here](https://github.com/africanmathsinitiative/R-Instat/wiki/GitHub-notes), let me know if you have problems. Thanks!

Hello Lloyd i tried what you ask me to do and now i can't push the changes to the PR. 
error


so i am thinking the earlier suggestion is ok with me;
`Close this PR and make a new PR`

**Comment by derekagorhom** [comment]
@lloyddewit and @N-thony would it be ok if i just closed this PR and make a new PR?

**Comment by lloyddewit** [comment]
> @lloyddewit and @N-thony would it be ok if i just closed this PR and make a new PR?

@derekagorhom yes, a new PR sounds sensible. Not sure what went wrong here, sorry for any confusion.

**Pull request closed without merging**
