### PR TITLE
Design changes to the three variable dialogue

### LINKED ISSUE #5871: Three variable frequencies design
This dialog is unnecessarily wide when **Both** option is selected. I suggest the Graph Frequencies options be moved so that the dialog width is maintained when you are in any of the options at the top.

image

### PR DESCRIPTION
**Pull request by Ivanluv**
@africanmathsinitiative/developers  this is ready for review .Fixes #5871

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet please could you peer review this one? thanks

**Comment by shadrackkibet** [comment]
Yes, Happy to review this.

**Comment by shadrackkibet** [comment]
1) Why is the default radio button under graph frequencies group box hidden? 

2) Notice that Flip coordinates checkbox overlaps with the graph frequencies group box.

3) Sort out Tab order.

4) Use visual controls 
image
 to centre top radio buttons, make them the same size in the form. It appears not well aligned.

See below!
image

**Comment by Ivanluv** [comment]
@shadrackkibet  could you look at this again

**Comment by shadrackkibet** [comment]
The design looks better now. 

@rdstern I just wonder why **Flip coordinates** checkbox is visible when Table option at the top is selected. Can you flip a table?

**Comment by rdstern** [comment]
@shadrackkibet it does just what you would expect.  If you have a 3-way table it is made up of a set of 2-way tables.  Using flip simply swaps the rows and columns in each 2-way table.
I annoyance with this function is that it puts the results into a web browser only.  I am unsure what we could do in the output window, so putting the results there could become an option.  Perhaps @Patowhiz could investigate?  This should not prevent the current improvements being merged though.

**Comment by shadrackkibet** [comment]
Thanks for that clarification. Over to you and @lloyddewit to review approve and merge.

**Comment by lilyclements** [comment]
@Ivanluv just as a small other point, the ucrSave currently says "save graph". Usually this is capitilised so that it says "Save Graph". Very minor request, but can this be fixed?

**Pull request merged**
