### PR TITLE
Reading .DLY file type in Import datasets

### LINKED ISSUE #5788: Import file with an odd extension
[LIVING01_test.zip](https://github.com/africanmathsinitiative/R-Instat/files/4599826/LIVING01_test.zip)

This is a small file of the type sent by Zambia Met service.  It has the extension dly.  Currently the importing (using rio) assumes the format from the extension.  So if I change the extension to txt it works well.
But rio gives the option to override the default.  If I include the argument format =",", then it reads fine.  That's a bit odd to me, because this file isn't comma separated, but it works fine from the script window.  
Ideally it would check this earlier, so it can give a preview in our dialogue.

### PR DESCRIPTION
**Pull request by Ivanluv**
@africanmathsinitiative/developers  this is ready for review.Fixes #5788

### CODE REVIEW

**Comment by Patowhiz** [comment]
@Ivanluv can you sort the conflicts so that I'm able to test this from my side.

**Comment by maxwellfundi** [comment]
@Patowhiz  this is a big conflict thats quite risky to fix. You can keep working on your branch, and when you are done, add the sections with @Ivanluv  changes from this PR to your branch so that they can be merged together when you open your PR. 
cheers

**Comment by lloyddewit** [comment]
@Ivanluv This PR seems to be stuck because of merge conflicts. Please could you resolve the merge conflicts (make new PR?) so that Patrick, or one of the other developers, can test? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  this will be solved by @Patowhiz  pull request that works on the same dialogue

**Comment by Patowhiz** [comment]
Yes this is awaiting more feedback from @rdstern on the issue #5788. I made comments there, on how this can generally be approached. Once the PR #5738 is merged then I can work on this or @Ivanluv can take it up. Thanks

**Comment by lloyddewit** [comment]
@Patowhiz PR #5738 was recently merged. Are you able to work now on this PR? thanks

**Comment by Patowhiz** [comment]
@lloyddewit yes I would work on this PR as soon as PR #5738 is merged. Code needed is on the same form.

**Comment by rdstern** [comment]
I am just reading more dly files from Zambia and (of course) having the same problem as before.
So I made one of them into the same name.txt and it reads fine.
However the missing value is -99.0 and files with the extension .txt seem to ignore anything put into the missing field.  If (in the script file) I add na.strings="-99.0" then it works fine.
Does this link also with the possibility here also of allowing multiple missing value codes that @Patowhiz is working on?

**Comment by Patowhiz** [comment]
As I mentioned in [comment](https://github.com/africanmathsinitiative/R-Instat/pull/5738#issuecomment-591280974) in PR #5738, [comment](https://github.com/africanmathsinitiative/R-Instat/issues/5700#issuecomment-590719158) and [comment](https://github.com/africanmathsinitiative/R-Instat/issues/5700#issuecomment-648135811) in issue #5700, the missing values was only implemented for excel and csv.

I've taking your above comment and created it as a separate issue #5977.

**Comment by Patowhiz** [comment]
I've solved the issue that this PR was meant to solve in PR #5978. This PR can now be closed.

**Comment by lloyddewit** [comment]
Closed as requested by @Patowhiz

**Pull request closed without merging**
