### PR TITLE
Remembering Last Save In Closing Databook (NEW)

### LINKED ISSUE #6003: Small change to the File > Close Data Book option
I assume this will be quick to do. It is an obvious one for @Patowhiz and check back if it is not a small task.

It correctly gives a warning that all data will be lost.  If I don't want to lose any data, then I save, and then use this option.  But it still asks.  Most software would detect that the data have not been changed and only ask if there were changes.  Could this check be made here, so it does not ask if the data have not changed since the last save.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #6003
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv please could you review? thanks

**Comment by Wycklife** [comment]
@lloyddewit I have tested this and it seems to work from my end. The message doesn't pop up once the data frame is saved. Clicking on  Close Data Book option clears the data set.

**Comment by lloyddewit** [comment]
@Ivanluv please could you review (reminder)? thanks

**Comment by Ivanluv** [comment]
Reviewing this now

**Comment by Ivanluv** [comment]
@Patowhiz  If I have more than one dataframe open and  save  only one, closing the databook works ignoring whether the other dataframes are saved or not . Should it detect if all the dataframes are saved?

**Comment by Patowhiz** [comment]
@Ivanluv it should detect all data frames. I think they are saved as 1 rds file. So 1 single save user operation , saves all data frames.

**Comment by Ivanluv** [comment]
@Patowhiz  thank you for the clarification.  @lloyddewit the code looks fine from my end

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Review by rdstern — CHANGES_REQUESTED** [review]
It says my version of R isn't supported.  I think this is something at @Patowhiz end to update?

**Comment by Patowhiz** [comment]
@rdstern I had not updated this branch with the master. I have now updated it. You can now test it.

**Review by rdstern — APPROVED** [review]
seems fine

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
