### PR TITLE
Climdex2

### PR DESCRIPTION
**Pull request by Ivanluv**
@africanmathsinitiative/developers  this  is ready for review.Relates to issues on issue #5367

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@rdstern  please test this.

**Comment by rdstern** [comment]
@Ivanluv I assume the existence of #5699 and #5698 means I don't need to worry about this pull request?  Is that true?

**Comment by Ivanluv** [comment]
@rdstern  this is pull request deals with the climdex dialogue while #5699 and #5698 relates to the climatic summary dialogue.So no,this pull requests is not related to #5699 and #5698

**Comment by maxwellfundi** [comment]
@rdstern  This needs you to review. Cheers.

**Comment by maxwellfundi** [comment]
@Ivanluv  there seems to be additions to the `instat/static/InstatObject/R/Backend_Components/.Rhistory` file. Was this part of what was needed?

**Comment by Ivanluv** [comment]
@maxwellfundi No, additions  to the Backend_components were not needed

**Comment by shadrackkibet** [comment]
> @Ivanluv there seems to be additions to the `instat/static/InstatObject/R/Backend_Components/.Rhistory` file. Was this part of what was needed?

@maxwellfundi This file change is from my end. Is it possible to reverse these changes from your end? 

@rdstern  this pull request contains the fixes for climdex dialog. i.e 

- The **factor** conversion of the year column when producing indices.
- Shortened column names for the indices.

**Comment by maxwellfundi** [comment]
@shadrackkibet  Its quite hard to do that from my end at the moment. 

I suggest two things

1. @Ivanluv  to replace the that file with the file from the master by say copying it. then this will make the files even 

2. @Ivanluv  to update his master, create a new branch and add the required changes then open a new PR

**Comment by shadrackkibet** [comment]
@Ivanluv I think option 1 is easier. Anyway, feel free to go with either.

**Comment by maxwellfundi** [comment]
@Ivanluv  I have now removed the .Rhistory file. @rdstern this is ready for you to review.

**Comment by shadrackkibet** [comment]
I think this should be in the next version as well.

**Comment by rdstern** [comment]
Agreed.  It has been specifically requested by WMO so I would very much like to see it in 0.6.1.

**Pull request merged**
