### PR TITLE
Selector bug fix

### LINKED ISSUE #7437: Corrections needed in the new Tables dialogue
@Ivanluv in the (new combined) summary tables dialogue, I find the problem is likely to be caused by the changes in the selector control, and hence by @Patowhiz changes.

I think the selector control does not refresh when the receiver is changed, nor for other changes, like changing the class of data.  So this dialogue, and presumably others are not usable.

a) When I go to the summary button and the Variables receiver it only allows factors.  That's a change from version 7.4 and we need it to allow variables as I show in Version 0.7.4.
image

compare the above with your new version.
b) If I come back from Summary to Frequency after being in the Variables control no control seems to have the focus now.
c) Please check if there is more!

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #7437 and partly issue #7433.

@africanmathsinitiative/developers @rdstern this is now ready for review.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@Patowhiz phew.  Looks fine to me so am approving.  @Ivanluv could you also look quickly at the code, then we can perhaps get this merged soon.

**Review by Ivanluv — APPROVED** [review]

**Comment by rdstern** [comment]
@dannyparsons could you approve and merge?

**Comment by Patowhiz** [comment]
@rdstern @N-thony can you now test if this PR fixes issue #7433 selector issues. And also the duplicates [comment](https://github.com/africanmathsinitiative/R-Instat/issues/7438#issuecomment-1117061868)

**Comment by N-thony** [comment]
> @rdstern @N-thony can you now test if this PR fixes issue #7433 selector issues. And also the duplicates [comment](https://github.com/africanmathsinitiative/R-Instat/issues/7438#issuecomment-1117061868)

@Patowhiz for the Row Numbers dialogue, it is still adding key code as long as you reset the dialogue
image
and the issue in the Duplicate dialogue is still there
image

**Comment by Patowhiz** [comment]
@N-thony that's slightly a different issue relating to the dialog itself. Basically the dialog is not clearing the after codes on reset.
Let me quickly fix that for you in a separate PR.

**Review by rdstern — APPROVED** [review]
@Patowhiz I have checked the tables as before, and also the Row numbers/Names and the Transform dialogue.  All work fine for me.

**Comment by N-thony** [comment]
> @N-thony that's slightly a different issue relating to the dialog itself. Basically the dialog is not clearing the after codes on reset. Let me quickly fix that for you in a separate PR.

@Patowhiz remember, the issue with the `Duplicate Column` is the same with the one we found and fixed with the `Merge Dialogue`, to fix that in the Merge Dialogue we have initiated 'New RFunction` globally in the dialogue but normally this is is done in the `SetDefaults` which is also called in the Loading of the form but currently when you open the dialogue, it is the `ControlValueChanged` that is triggered out first before the `Load` of the form, that is why we are getting that bug.

**Comment by N-thony** [comment]
> > @N-thony that's slightly a different issue relating to the dialog itself. Basically the dialog is not clearing the after codes on reset. Let me quickly fix that for you in a separate PR.
> 
> @Patowhiz remember, the issue with the `Duplicate Column` is the same with the one we found and fixed with the `Merge Dialogue`, to fix that in the Merge Dialogue we have initiated `New RFunction` globally in the dialogue but normally this is is done in the `SetDefaults` which is also called in the Loading of the form but currently when you open the dialogue, it is the `ControlValueChanged` that is triggered out first before the `Load` of the form, that is why we are getting that bug.

Have a look of this, or I can demonstrate to make it more clear.

**Comment by Patowhiz** [comment]
> @Patowhiz remember, the issue with the Duplicate Column is the same with the one we found and fixed with the Merge Dialogue, to fix that in the Merge Dialogue we have initiated New RFunction globally in the dialogue but normally this is is done in the SetDefaults which is also called in the Loading of the form but currently when you open the dialogue, it is the ControlValueChanged that is triggered out first before the Load of the form, that is why we are getting that bug.


@N-thony yes correct. The `ControlValueChanged` will always be called before the `form load` event because the `control load` event is called before the `form load` event. That's why in many dialogs we have the `RFunctions` initilised before the `form load` event, even though the same is still done in the `SetDefaults()`. 

So to fix the bug we just need to always make sure the dialogs don't call on null objects.

**Pull request merged**
