### PR TITLE
Added Display as Dotplot checkbox to Histogram dialog

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
@africanmathsinitiative/developers This is ready for review. 
@Cal-Insta @rdstern This will fix the first part of issue #6615, in case we find options to add, that will be done in another PR.

### CODE REVIEW

**Review by Cal-Insta — COMMENTED** [review]
This works well.

**Review by Cal-Insta — COMMENTED** [review]
Some of the dotplot options I suggest we look at and add include: 
1. binwidth
2. method
3. stackdir
4. dotsize
5.stroke width
6. colour and fill

**Comment by HawardKetoyoMsatsi** [comment]
> Some of the dotplot options I suggest we look at and add include:
> 
> 1. binwidth
> 2. method
> 3. stackdir
> 4. dotsize
>    5.stroke width
> 5. colour and fill

@Cal-Insta I guess this should better be put under issue #6615 not this PR. I find it to be a continuation of the discussion on the issue.

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi @Cal-Insta that looks good so far.  But the y axis is different in the 2 cases.  It looks as though an option needs to be provided here, so counts can be given for the dot-plots.  At the same time, perhaps the current y-axis for the dot-plot could be given for the histogram option.

Also I assume the geom should change.  So when dotplots is checked, then the options should change from Histogram Options to dotplot Options?

@Cal-Insta has given a list of possible options.  This must go further and be much more precise as to hosk on the forthcoming dialogue.  Also, how many of those items will be just for the dot-plots and how many for both?

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern   I find the problem with the dot-plot giving inconsistent y-scale (kinda meaningless ) and one suggestion was to manually scale it to match the number of dots which depends on the data at hand.  
Could it be okay if we have it as it. Because if we manually scale it (as suggested by most people  [1](https://github.com/tidyverse/ggplot2/issues/1619) , [2](https://github.com/tidyverse/ggplot2/issues/2203) etc.), that cant be flexible to apply to different datasets?

**Comment by HawardKetoyoMsatsi** [comment]
> @HawardKetoyoMsatsi Is this PR ready again for test/review? thanks

@lloyddewit it is not yet ready, part of @rdstern  changes are yet to be made.

**Review by rdstern — APPROVED** [review]
@HawardKetoyoMsatsi ok, let's consider the scale with the other improvements that @Cal-Insta is - I think - going to make.  You are right that we need to move on!.

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit Please you can review this. The scale and suggestions by @Cal-Insta will be done in a new PR as described in issue #6615.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
