### PR TITLE
Removes redundant DataFrameChanged event in the data frame selector control

### LINKED ISSUE #7450: Redundant event in the data frame selector
Currently the only purpose of the data frame selector is to select and display data frames. Whenever a different data frame is selected it raises data frame changed event. This event is just a replacement of `ControlValueChanged` that all our custom controls use when their values change. 

I suggest replacing `DataFrameChanged` event with the `ControlValueChanged` for this control to be consistent with others

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #7450.

@africanmathsinitiative/developers this is ready for review.

This PR contains changes made in PR #7441. So PR #7441 should first be reviewed and merged before this can be merged.

@N-thony please have a look at this PR too.

### CODE REVIEW

**Review by lloyddewit — DISMISSED** [review]

**Review by N-thony — APPROVED** [review]

**Comment by Patowhiz** [comment]
@lloyddewit I think this now ready for you.

**Comment by lloyddewit** [comment]
> @lloyddewit I think this now ready for you.

@Patowhiz I'm uncertain how we can best test. There is no new functionality for @rdstern to test so we need to test regression. 
You have the best insight into the risks of this change. What type of regression tests do you think we need? Do you think that the regression testing you've done is adequate or should we still use an independent tester?
I appreciate that these aren't easy questions to answer, so thank you in advance!

**Comment by Patowhiz** [comment]
@lloyddewit thanks for you question.

As issue #7450 suggests, this PR basically replaces event `DataFrameChanged` with event `ControlValueChanged`. After my changes in PR #7404, those 2 events are technically the same. So this PR is simply 'swapping' the 2 events by removing the former.

Below is how this PR can be tested for regression.

Any dialog that has a data frame selector can be tested. Particularly whether the receivers or any input control that depends on the data frame selected clears and has their contents consistent with the data frame changed. I understand this can be time consuming so below are some of the dialogs that can be tested; 

1. Prepare > Column: Numeric > Regular Sequence. Testing should be focused on the data frame length control. To ensure it's contents reflect those of the selected data frame.

2. Prepare > Column: Factor > Recode Factor.  Testing should be focused on the receiver and factor control. To ensure their contents reflect those of the selected data frame.

3. Prepare > Column: Text > Find/Replace . Testing should be focused on the receiver and save control. To ensure their contents reflect those of the selected data frame.

4. Prepare > Data Frame > Reorder Columns.  Testing should be focused on the reorder column control. To ensure it's contents reflect those of the selected data frame.

The above regression test selection should cover all the files changed in this PR. Thanks.

**Comment by N-thony** [comment]
@Patowhiz @lloyddewit I did test with the above dialogues and some other dialogues randomly, it seems to work fine for me.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@Patowhiz @N-thony Thanks for the cooperation :)
Happy to merge

**Pull request merged**
