### PR TITLE
Changes on View Menu

### LINKED ISSUE #6602: Ticks in View menu not centered
Hello @shadrackkibet, 

I noticed that the ticks in the blue boxes of the view menu are not centered. They seem to be aligned to the top left. Would that be something that we could easily change? I think it would look much tidier. 

Thanks, 

Rachel 
View menu

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes #6602
This PR is ready for review

### CODE REVIEW

**Comment by derekagorhom** [comment]
@N-thony and @shadrackkibet  can you please test and approve

**Comment by N-thony** [comment]
> @N-thony and @shadrackkibet can you please test and approve

@derekagorhom looks good, can you do the same for the toolbar icon for Column Metadata and Data Frame Metadata?
image

**Comment by derekagorhom** [comment]
> > @N-thony and @shadrackkibet can you please test and approve
> 
> @derekagorhom looks good, can you do the same for the toolbar icon for Column Metadata and Data Frame Metadata? image also Script Window and Log Window? image

Done

**Review by N-thony — APPROVED** [review]
@lloyddewit over to you

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
