### PR TITLE
Small fix to the layout of the xtab in the Plot options dialog

### PR DESCRIPTION
**Pull request by rachelkg**
I noticed that the xtab had a layout issue whereby not all the text was visible so I extended the surrounding box to resolve this. 

Thanks, 

Rachel

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet @rdstern Please could one of you check/approve so we can merge? thanks

**Comment by shadrackkibet** [comment]
@rachelkg to quickly review such changes I suggest that in future you attach screenshots showing the previous look and the current look after designer modification. Thanks.

**Review by shadrackkibet — APPROVED** [review]
Looks better!

**Comment by rachelkg** [comment]
@shadrackkibet thanks for the suggestion, I will do that from now on.

**Pull request merged**
