### PR TITLE
Added circular tab for Prepare > Column: Reshape > Column Summaries

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes the first part of #5332 

In progress

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@Wycklife how far? do you need help on this?

**Comment by Wycklife** [comment]
@shadrackkibet Yes I need help, It's the issue I wanted to discuss with you

**Comment by maxwellfundi** [comment]
@shadrackkibet @Wycklife As you keep working on this, it has conflicts and it might need you change branches.

**Comment by shadrackkibet** [comment]
@Wycklife please close this and open a new pull request with the other changes we discussed.

**Comment by Wycklife** [comment]
I'm closing this puul request since the branch has conflict.

**Pull request closed without merging**
