### PR TITLE
Adding the pivot table dialogue to the Describe>Two Variable menu

### PR DESCRIPTION
**Pull request by Ivanluv**
@africanmathsinitiative/developers  this is ready for review.
The PR adds the pivot table dialogue to the Describe> Two variable menu

### CODE REVIEW

**Comment by rdstern** [comment]
@Ivanluv great - I am looking at that now.

**Comment by Ivanluv** [comment]
@rdstern  This contains the form main changes only which shouldn't work. I have the main changes in another branch but I need this merged first for me to make a PR from the other branch. This is to reduce form main conflicts

**Comment by rdstern** [comment]
@Ivanluv, then I am happy to approve, but would like @shadrackkibet to look quickly at what you have done first.  If it is just to get the blank dialogue, then I wonder if it should be limited to this one, or you might like to do the same for the 3 variable dialogue at the same time.  Up to you?  I am hoping that working on the 3-variable dialogue could perhaps be something for an intern, under your instruction, once the 2-variable has progressed.

**Comment by shadrackkibet** [comment]
@Ivanluv since you already have changes in another branch you could just open a PR since those changes do not affect frmmain. I will suggest you liaise with @rdstern on the testing before we enable it in the frmmain. We really don't want to encourage enabling of dialogs from the main form before they are tested and completed.

**Comment by Ivanluv** [comment]
okay am therefore closing this PR

**Pull request closed without merging**
