### PR TITLE
Edit keys and links

### PR DESCRIPTION
**Pull request by lilyclements**
@dannyparsons this is ready to merge. Made bug fixes for the Add Links/Keys dialogs.

### CODE REVIEW

**Comment by dannyparsons** [comment]
@Lunalo could you review this? These were your dialogs originally.

**Comment by lilyclements** [comment]
@Lunalo can you review this please?

**Comment by dannyparsons** [comment]
@Lunalo this was waiting for you to review for 16 days. I reviewed it myself instead now.

**Comment by Lunalo** [comment]
Sorry @dannyparsons 

I just forgot to review it on Friday.

**Pull request merged**
