### PR TITLE
Bug fixes: R-Instat crashes when clicked the Toggle Data View Open and Closed Icon

### LINKED ISSUE #8530: R-Instat Crashes when I use the Toggle Data View Open and Closed Icon
Hello @rdstern and @N-thony 

I am using the most up to date version through Visual Studio. Every time I use the Toggle Data View Open and Closed Icon 

 it crashes and I get this message:

Thanks, 

Rachel

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #8530
@rdstern @rachelkg have a look.
@ChrisMarsh82 can you check the code?
Thanks

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
Looks ok to me now.  I am also really keen that we chip away at these occxasional/rare bugs.
@Patowhiz I am approving and suggest this is a good one for you to look at the code?
At the same time, it would be great if you could approve and merge #8544

**Comment by rdstern** [comment]
@N-thony I can no longer crash it, and was about to report that I couldn't see a problem, when I suddently got this:

image

I was going to have one more try at deleting again, when I noticed there is now no tab at the bottom!  Is this the sort of thing you were finding?

**Review by rdstern — APPROVED** [review]
@N-thony it now looks fine to me.
@Patowhiz can you check again, and merge once you are happy

**Review by ChrisMarsh82 — CHANGES_REQUESTED** [review]
Adding RemoveOldWorksheets() into the dataframe loop will cause issues. If you close all of the dataframes there will be no dataframes in the loop so removeOldWorksheets will never be called. 
Why was this moved in the first place?

**Comment by ChrisMarsh82** [comment]
In `ucrReoGrid.RemoveOldWorksheets()` add an extra condition to if statement before `grdData.RemoveWorksheet(i) `
It should be possible to check here whether you are deleting the last sheet.

**Review by ChrisMarsh82 — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
Seems fine now

**Pull request merged**
