### PR TITLE
Clearing the previously selected columns on reopen in the sort dialog.

### PR DESCRIPTION
**Pull request by Wycklife**
This fixes issue #5048. @africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by dannyparsons** [comment]
@Wycklife Think also about the use of this dialog in other cases, not just from the column right click. It is also in the Prepare menu. With what you have implemented now, if I use the Sort dialog from the Prepare menu, open it and run it with some columns, then when I reopen the dialog again, it will be blank as the columns will have cleared. I hope you can see that this is inconsistent with how dialogs work in R-Instat. They should look the same when you reopen them again.

However, you are close with your solution. It just needs to be cleared only when we are filling in a default column from accessing the dialog in the right click menu.

**Comment by Wycklife** [comment]
@dannyparsons Thanks for the observstion, let me go through it and make the required changes.

**Comment by Wycklife** [comment]
This is ready for review @dannyparsons

**Comment by Wycklife** [comment]
This is ready for review @dannyparsons

**Comment by Wycklife** [comment]
This is ready for review @dannyparsons

**Comment by dannyparsons** [comment]
Great, looks good. Could you check other dialogs which do similar things from the right click menu to see if any have the same problem?

**Pull request merged**
