### PR TITLE
Corrected calculation for end of season

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@rdstern can you review this from here or should it be merged first?

**Comment by rdstern** [comment]
I can try, but why not merge?

**Comment by dannyparsons** [comment]
I can merge if that's easier.

**Comment by dannyparsons** [comment]
There are some issues with the two main checkboxes resetting here but I have not worried about this as they will soon be replaced with radio buttons at the top.
That will also give much more space on the dialog so the layout can be improved then too.

**Pull request merged**
