### PR TITLE
Fixes translation layout

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes (partially) #7650 
@N-thony @lloyddewit , this PR is ready for preview

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony @rdstern If one of you can test/approve this, then we can merge, thanks

**Comment by rdstern** [comment]
image

Just a few suggestions for now:
a) In the English, change the phrase to `Add the Fitted Line`.  This (I think) translates to `Ajouter la ligne ajustée`.
b) The Standard error is associated with that addition, so move it down to be on the same row as the add checkbox.  It should also be translated into `Ajouter l'erreur standard`.
c) Move the checkbox Add Valleys down slightly, so it is on the same row as the Add peaks.
d) Make the label for Save Graph wider, so there is enough space for Enregistrer le graphique.

**Comment by lloyddewit** [comment]
@Fidel365 
- did you intend to delete `dlgEndOfRainsSeason.vb`? should we restore it (will also solve resource conflict)?
- did you resolve all of @rdstern 's requests above? is this PR ready for review/test?
Thanks

**Comment by lloyddewit** [comment]
@Fidel365 I 'undeleted' `instat/dlgEndOfRainsSeason.vb`, I hope that's OK

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge (hopefully in time for the DRC release build), thanks

**Comment by Fidel365** [comment]
This PR has conflicts, iam working on all the requested changes in a new PR

**Review by rdstern — CHANGES_REQUESTED** [review]
I am not sure this has changed since my last comments that are in this pull request?

**Comment by lloyddewit** [comment]
> This PR has conflicts, iam working on all the requested changes in a new PR

@Fidel365 I don't see a replacement PR, so I assume you didn't open it yet.
When you open the new PR, please state that it replaces this one.
Thanks

tip: A PR title should clearly state which menu option(s) and/or (sub)dialog(s) have been changed; and explain what change has been made in language that a normal user will understand (i.e. no technical terms that only developers understand).
If you can do this, then it makes the review process more efficient and increases the quality of the release notes.
Thank you!

**Pull request closed without merging**
