### PR TITLE
Jitter

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by dannyparsons** [comment]
If this is easy, great. Otherwise, it's not the highest priority at the moment.

**Comment by maxwellfundi** [comment]
@stevenndungu  this has not been a priority for sometime. Could you have a look at it again now so that it gets to the master? Is it too much work still left here?

**Comment by Lunalo** [comment]
@dannyparsons 

I remember discussing with you on this dialog. We had agreed that the dialog needed more thoughts and possibly restructuring.  I would suggest the dialog's design to be restructured .

**Comment by dannyparsons** [comment]
Let's then merge this and disable the dialog on the main form so that it doesn't need to be complete. The form main edit can be done on a separate branch. Can someone do this?

**Comment by stevenndungu** [comment]
It is already disabled.

**Pull request merged**
