### PR TITLE
Quality control dialogs

### PR DESCRIPTION
**Pull request by bethanclarke**
Outliers:
-Coeff nud included 
-Skewed data checkbox removed for Rain dialog 
-Omit zero checkbox added 

I haven't included a checkbox for station for Outliers. 

One issue: on QC Temp, when Tmax is empty, Tmin receiver is not empty and Outlier is checked, OK button is not enabled.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@bethanclarke  Sorry, I didn't realize you also worked on the temperature dialog here. There are conflicts which need to be resolved as soon as possible. @dannyparsons  could you help resolve this if it is easy on you end?

**Comment by shadrackkibet** [comment]
It will be good if this is resolved as soon as possible so that i can work on the Rainfall dialog.

**Comment by dannyparsons** [comment]
@shadrackkibet It might be easier for you to manually add Beth's changes from `dlgClimaticCheckDataTemperature.vb` into your branch, and then for the designer changes check with Beth which controls have changed and then just add them again.
I could resolve the conflicts but it will likely lead to errors on the designer/resources file which would then be harder to fix.

**Comment by shadrackkibet** [comment]
@bethanclarke  i moved your changes on outliers for this forms. Please check that  in the master, then this can be closed.

**Pull request closed without merging**
