### PR TITLE
Ensured correct result from 3-way frequencies dialog

### LINKED ISSUE #7741: Please check possible error in results for 3-way frequencies dialogue
In writing the help for the Describe > 2/3 Variables > 3-way frequencies dialogue I suggest the R-commands are giving the wrong answers.  I hope someone can check this - possibly also using RStudio to confirm.

I have been using our usual rice survey data.  I have reordered the fertgrp factor, so it goes 0, 0.5-2, > 2, but that is not particularly relevant (I have also tried without that).

Here is a simple example:
image

Here are some answers:
image
 The numbers are all correct, but associated with the wrong villages!  The table shows that Nanda has 7 observations.  If you look at the data it is Kesent that has 7 and Nanda has 14 observations.

The graph option is also similarly wrong, i.e. in the villages associated with the frequencies.

If you try with a numeric sort of factor, then I think it is ok.  For example make fert the third variable above (and variety and village the first 2, then I think it is ok.)

Please can this be investigated - and quite urgently.  It could be our R-code, but I don't see how - here it is:

```
# Code generated by the dialog, Three Variable Frequencies
survey <- data_book$get_data_frame(data_name="survey", drop_unused_filter_levels=TRUE)
survey %>% dplyr::group_by(village) %>% dplyr::select(variety, fertgrp, village) %>% sjPlot::sjtab(show.summary=FALSE, digits=0, fun="xtab")
```

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7741
@rdstern please check if the result is now correct? Thanks
Probably you could play around with the dialogue and see if everything expected is correct?

### CODE REVIEW

**Comment by N-thony** [comment]
> Fixes #7741 @rdstern please check if the result is now correct? Thanks Probably you could play around with the dialogue and see if everything expected is correct?

@rdstern could you test?

**Comment by N-thony** [comment]
@derekagorhom can you peer review this?

**Review by derekagorhom — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]
@N-thony Thank you for the changes, looks good to me.
@derekagorhom Thank you for the peer review.

**Comment by lloyddewit** [comment]
@rdstern if you can test, then we can merge, thanks

**Pull request merged**
