### PR TITLE
Enabled Tmin and Tmax autofill automatically in Transform dialog

### LINKED ISSUE #7664: Minor bug in the Transform Dialogue
The Tmax and Tmin receivers should fill automatically tmax and tmin variables
image

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #7664 
@rdstern @lloyddewit @N-thony , this PR makes Tmin & Tmax update automatically for defined climatic data

### CODE REVIEW

**Comment by N-thony** [comment]
@Vitalis95 I tried with the rwanda dataset from the library but it didn't fill automatically
image

**Comment by N-thony** [comment]
> @Vitalis95 I tried with the rwanda dataset from the library but it didn't fill automatically image

You can follow `QC Temperature Dialogue` as an example

**Comment by Vitalis95** [comment]
> @Vitalis95 I tried with the rwanda dataset from the library but it didn't fill automatically image

I used Dodoma dataset to test it and it worked fine, I will check on it
image

**Comment by Vitalis95** [comment]
@N-thony , even for Rwanda dataset from Library, it works well from my side

image

**Review by N-thony — APPROVED** [review]
@rdstern could you test?

**Review by lloyddewit — APPROVED** [review]

**Review by rdstern — APPROVED** [review]

**Pull request merged**
