### PR TITLE
Net cdf

### PR DESCRIPTION
**Pull request by lilyclements**
In here I have combined and reviewed edits from #3068 and #3085 

1. I have found a bug which I'm not sure how to fix. If I run this and check the "Date/Time" checkbox, I get the following error:

> Error in ncdf.tools::convertDateNcdf2R(my_data$period, units = units,  : 
>   Unit months is not implemented.
> 
> 
> The error occurred in attempting to run the following R command(s):
> 
> InstatDataObject$import_NetCDF(main_data_name="ncdata", add_date_time=TRUE, loc_data_name="location_data", nc_data=ncdf4::nc_open(filename="C:/Users/Admin/Downloads/ncdata.nc"))
> 

@africanmathsinitiative/developers can anyone help with this?

2. Additionally, the receivers don't have to be filled for it to work. Is this intentional? Presumably it is!

### CODE REVIEW

**Comment by lilyclements** [comment]
@volloholic last we spoke about this, it needed a few changes to the r-code and you were going to have a look at this. Have you looked at this yet? What should I do about this dialog?
you mentioned removing the receiver and selectors and instead having checkboxes to offer the user to specify their name of their columns.

**Comment by volloholic** [comment]
This needs a more major overhaul. The underlying R code is simply wrong so we need to rethink it from the ground up. Importing NetCDF files is a high priority but I think we should disable this until 0.4.1 at the earliest.

**Comment by lilyclements** [comment]
Okay sure, what date are we planning to do 0.4.1?

**Comment by dannyparsons** [comment]
0.4.1 is August

**Comment by maxwellfundi** [comment]
@lilyclements  @volloholic  this now needs revisiting and rethinking for the suggested version 0.4.1 which is a few weeks from now.

**Comment by dannyparsons** [comment]
Yes, me and @volloholic are going to look into this.

**Pull request closed without merging**
