### PR TITLE
Added option to display menus in French.

### PR DESCRIPTION
**Pull request by lloyddewit**
Partially fixes issue #3721.
This PR replaces (and closes) PR #6343.

@dannyparsons Please could you review?

Note: The translation mechanism uses the TranslateWinForms library. I uploaded this library to NuGet so that it can be integrated into R-Instat in the standard way. The source code for this library can be found at:
https://github.com/lloyddewit/TranslateWinForm
We can move the library to the `africanmathsinitiative` GitHub site when it is stable.

### CODE REVIEW

**Review by dannyparsons — APPROVED** [review]
This works well. The first time I ran it complained about missing SQLite.interop.dll

After installing and uninstalling some packages it then worked. So there's a possible problem but not sure.

@rdstern or @shadrackkibet could you try out the branch and see if it works?

**Comment by rdstern** [comment]
I get the error you mentioned too, namely:

image

Do I have to load that dll.  If so, then where?

**Comment by dannyparsons** [comment]
Can you extract these two folders to `instat/bin/Debug` [dlls.zip](https://github.com/africanmathsinitiative/R-Instat/files/6223592/dlls.zip)

We're not yet sure why they don't appear automatically, but this should work for testing.

**Comment by shadrackkibet** [comment]
- First I got the same warning message.
image
- I extracted the files into the directory as shown above and the menu translation seems to work!

**Review by rdstern — APPROVED** [review]
Great

**Comment by lloyddewit** [comment]
I understand from @dannyparsons that if we make sure that `SQLite.Interop.dll` is copied in the bin folder when compiling the installer, then the R-Instat deliverable version should work fine for users.
Therefore I suggest that we merge this PR.

In parallel, we should also look for cleaner ways to manage packages within the R-Instat project. I raised issue #6356 for this.

**Pull request merged**
