### PR TITLE
Two var graph

### PR DESCRIPTION
**Pull request by lilyclements**
@dannyparsons this is ready to be merged
Minor edits:
- moved the label so that it is in a better position for the video
- added colon to the label
- removed the ellipsis from the Options button to be consistent across the software

### CODE REVIEW

**Comment by AlexSananka** [comment]
@lilyclements could you the change the icall type for this graph to be 3?

**Comment by lilyclements** [comment]
@AlexSananka I have now changed it and checked it. Thanks

**Comment by AlexSananka** [comment]
Ok great

**Comment by lilyclements** [comment]
@dannyparsons this is ready to merge

**Pull request merged**
