### PR TITLE
Delete on Right click

### PR DESCRIPTION
**Pull request by shadrackkibet**
@africanmathsinitiative/developers This is ready for review.

### CODE REVIEW

**Comment by Muthenya** [comment]
@dannyparsons this is ready for review.

**Comment by dannyparsons** [comment]
I actually prefer it as it was. When you say "Delete 3 columns" it's not saying which columns, which is why I liked simply "Delete columns". I think it's different to Insert because you're not referring to the selected columns there.

**Comment by shadrackkibet** [comment]
ok i see!. will now close this pullrequest.

**Comment by dannyparsons** [comment]
No problem, please keep making suggestions if you see something you think could be improved, it's always good to discuss.

**Pull request closed without merging**
