### PR TITLE
Fixed a bug when reversing y-axis order in Density/Ridges plot in Histogram dialog

### LINKED ISSUE #6978: Error trying to reverse y-axis order
I hope we can soon make progress on some of the outstanding issues on the plot sub-dialogue.  There are a lot of improvements needed, but now I have also a specific error that possibly hints to awkward code more generally.  The message is as follows and I explain below how I stumbled over it.
image

I understand the message.  However I then unticked the option (in Y axis) that produced the error, but the error persists - so possibly the code remains?

Here is the graph I had:
image

I decided to try reversing the Y axis, so the months would go down rather than up.  Slightly to my surprise I found reverse on the Y-axis tab - so tried it.

Here is the R-code generated:

```
# Code generated by the dialog, Histogram Plot
sadore <- data_book$get_data_frame(data_name="sadore")
Tmx <- data_book$get_columns_from_data(data_name="sadore", col_names="Tmx")
Mois <- data_book$get_columns_from_data(data_name="sadore", col_names="Mois")
last_graph <- ggplot2::ggplot(data=sadore, mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmn)) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::xlab(label="Tmin & Tmax") + ggplot2::scale_y_continuous(labels=scales::percent_format(), trans="reverse")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="sadore")
data_book$get_graphs(data_name="sadore", graph_name="last_graph")

``` 

I begin to see the problem.  When I untick it does change, but it still gives me the scale_y_continuous addition to the command, i.e.

```
# Code generated by the dialog, Histogram Plot
sadore <- data_book$get_data_frame(data_name="sadore")
Tmx <- data_book$get_columns_from_data(data_name="sadore", col_names="Tmx")
Mois <- data_book$get_columns_from_data(data_name="sadore", col_names="Mois")
last_graph <- ggplot2::ggplot(data=sadore, mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmx, y=Mois)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=Tmn)) + theme_grey() + ggplot2::xlab(label="Tmin & Tmax") + ggplot2::scale_y_continuous(labels=scales::percent_format())
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="sadore")
data_book$get_graphs(data_name="sadore", graph_name="last_graph")

```
So, the error message persists.

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #6978 
Replaces PR #7644 
@rdstern @lloyddewit @N-thony ,this PR fixes the error when trying to reverse y-axis order in Density/Ridges plot

### CODE REVIEW

**Comment by Vitalis95** [comment]
@lloyddewit, this the only change I made from my side (removing that line which is the one causing the bug). I never made any other change to this dialog.

**Comment by lloyddewit** [comment]
> @lloyddewit, this the only change I made from my side (removing that line which is the one causing the bug). I never made any other change to this dialog.

@Vitalis95 Thanks for the explanation. I'm not quite sure where the changes in the previous PR came from (parallel changes on the same file in master?). But these are reverted anyway so it's not important. I'm happy to approve.

@rdstern over to you for testing ...

**Review by lloyddewit — APPROVED** [review]

**Review by N-thony — APPROVED** [review]

**Comment by rdstern** [comment]
When I return to the dialogue I get (each time)
image

In addition, when I did reverse on the y-axis I got the following:
image

**Comment by Vitalis95** [comment]
@rdstern  the developer error is now sorted. The error "Discreet value supplied to continuous scale" is because `month_abbr` is factor

**Comment by N-thony** [comment]
> @rdstern the developer error is now sorted. The error "Discreet value supplied to continuous scale" is because `month_abbr` is factor

@rdstern please have look

**Review by rdstern — APPROVED** [review]
I think the code is now better, so I am approving.
At a later stage we do need to be able to complete the discrete scales.  However, I found the best way to reverse the months on the plot given in the issue is perhaps to reverse the levels in the factor first!

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
