### PR TITLE
Translate 'Code generated by dialog,' comment to the current language (e.g. French)

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes part f only of issue #7773 .

@N-thony Please could you peer review?

@rdstern
As requested, I added translation of the 'Code generated by the dialog,' comment. 

It turned out to be more complex than I expected because:
- In the options dialog, the comment can be changed manually by the user, or automatically when the language changes
- In each individual dialog, the comment can be changed manually by the user just for that dialog

So if the language changes, then under which conditions should we replace the current comment with the translated comment? 
I implemented the following approach:

- In the options dialog, if the user changes the language (e.g. to French)
    - If the user has previously manually changed the comment, then the comment is left unchanged 
    - If the user hasn't changed the comment, then the default comment for the new language is used
- In each individual dialog
    - If this is the first time that the dialog opens, then the dialog uses the options dialog comment
    - If the dialog reopens, and the comment has not been manually changed in the dialog, then the dialog uses the options dialog comment
    - If the dialog reopens, and the comment has been manually changed in the dialog, then the dialog uses the manually changed local comment

The general principle is that if the user has manually edited a comment, then this comment will never be overwritten automatically if the language changes. I hope this makes sense.

Please could you test? thanks!

Note: the current French translation of 'Code generated by the dialog,' is just temporary so that you can test this PR. When you approve this PR, I will remove the database change and instead follow the proper CrowdIn translation process via separate PRs. 

### Steps I used to test:

- open Describe / One Variable / Summarise dialog
    - dialog comment should be English default
    - change comment to 'changed in dialog'
    - close dialog
- open Describe / Two/three variables / Describe 2 variables dialog
    - dialog comment should be English default
    - close dialog
- open Tools / Options dialog
    - change language to French
    - instat options comment should change to French
    - click 'OK'
- open Describe / One Variable / Summarize dialog
    - dialog comment should be 'changed in dialog'
    - close dialog
- open Describe / Two/three variables / Describe 2 variables dialog
    - dialog comment should be French default
    - close dialog
- open Describe / General / Column summaries dialog
    - dialog comment should be French default
    - close dialog
- open Tools / Options dialog
    - change language to English
    - instat options comment should change to English
    - click 'OK'
- open Describe / One Variable / Summarise dialog
    - dialog comment should be 'changed in dialog'
    - close dialog
- open Describe / Two/three variables / Describe 2 variables dialog
    - dialog comment should be English default
    - close dialog
- open Describe / Multivariable / Correlation dialog
    - dialog comment should be English default
    - close dialog

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@lloyddewit thanks for undertaking it so carefully.  I hadn't thought of all the possibilities.  

I am happy to approve as it stands - if the following takes long, but wonder if the defaults are in operation, and you press the Lan button - could it go back to English?  I am being really gutty here I know!

**Comment by lloyddewit** [comment]
>  if the defaults are in operation, and you press the Lan button - could it go back to English?

@rdstern Thank you, good spot!
I think I resolved this, please can you test?

**Review by rdstern — APPROVED** [review]
Great - looks fine and a good improvement

**Comment by lloyddewit** [comment]
@N-thony If you can peer review, then we can merge, thanks

**Comment by N-thony** [comment]
@lloyddewit sorry for the delays now I see this branch has conflicts and I can't test.

**Comment by lloyddewit** [comment]
> @lloyddewit sorry for the delays now I see this branch has conflicts and I can't test.

@N-thony Thank you for looking at this. Don't worry about the merge conflict, this is just a temporary database to allow testing. I will remove the database before I merge the PR and this will solve the merge conflict. @rdstern already tested this PR. Please could you review the code changes I made?
thanks

**Review by N-thony — DISMISSED** [review]
@lloyddewit looks good. I did understand your code clearly.

**Pull request merged**
