### PR TITLE
Bug fixes on the File > New DataFrame > Lists

### LINKED ISSUE #8574: Odd serious bug with file-new data frame on some lists
@N-thony I think this may be one for you, because it may be tricky for the others.  But up to you.

With File > New Data Frame > Lists, most of the lists are given fine.

But a couple consistently crash out of the program.  Running on version 7.16 it gives the crash error.  When I continued the screen for the example was like this:

image

The data were going across rather than down!

The only 2 examples I have found of this are in the category geography

image

They are `US Airport codes` - result as shown above - and `venues`.

Here is the error in reogrid:

image

My guess is that these lists don't have any data?

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #8574
@rdstern this fixes the bug with `US Airport codes` and `venues`. Have a look

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@N-thony magic - it now works!

**Comment by Patowhiz** [comment]
@rdstern could you countercheck that the contents of the cells of LT column types in the data sheet are what you expect? If they match what was you wanted before.

@rdstern on as separate note do you have a example that works without getting the bug addressed by this issue? That would be useful in comparing the outputs brought about by the changes made here.

Thanks.

**Comment by Patowhiz** [comment]
@rdstern @N-thony excuse my ignorance,

Is it correct that if I have sample R contents like _list(Birmingham =  list(IATA = c("BHM", NA, NA, NA)))_ in the R data frame I should expect to see _Birmingham =  list(IATA = c("BHM", NA, NA, NA))_ in the data sheet cell? This should only happen if the column is of type LT? In summary, the end output removes _list()_  only in the contents of an LT column cells.

Thanks.

**Comment by rdstern** [comment]
@Patowhiz yes I am not sure what is happening with the airline codes example.  I don't find the example to be useful, so my only concerns were that it should not give a nasty error, and also should not take too much of the developer's time.

**Comment by Patowhiz** [comment]
@rdstern thanks for your feedback.

@N-thony I'm keen to hear your feedback on this [comment](https://github.com/africanmathsinitiative/R-Instat/pull/8583#issuecomment-1779292330) as well, I understand your changes have fixed the bug. But do they maintain the expected output as intended by the original code author? Given input _list(Birmingham = list(IATA = c("BHM", NA, NA, NA)))_ I was expecting to get output  _Birmingham = list(IATA = c("BHM", NA, NA, NA))_ , yet your new changes give output _"BHM", NA, NA, NA_

@rdstern the changes made here relate to getting the contents within the brackets of a list if the column is of type **LT**. I'm not sure why this feature is useful, I initially thought you are aware of this feature given it's impact on performance when it comes to long strings. If it's not useful to extract the contents with the brackets of a list, for instance in _list(.....content....)_, then we could easily fix this bug by removing the implementation entirely, this well ensure that the data viewer shows the same contents that the R data frame has, omit the bug entirely, improve performance and eliminate the additional complexity not needed(that means less developer time). If you are not sure about removing the feature, we could consult the original author to understand the intention and significance of the feature.

Thanks.

**Comment by rdstern** [comment]
@Patowhiz very happy if the change is made

**Comment by Patowhiz** [comment]
@N-thony thanks for the feedback . 
I understand the no harm bit, however it's important that we are aware of what the users will interact with, some of these details   may seem trivial but being aware of them and documenting them helps future maintenance.
From your end, I'm particularly interested in how you understood the significance of your changes, whether we understand the initial implementation and how the new change affects the initial intention.

**Comment by Patowhiz** [comment]
@rdstern for clarity, for reasons I mentioned in this [comment](https://github.com/africanmathsinitiative/R-Instat/pull/8583#issuecomment-1780483326), you are accepting that we remove this addition entirely? That means there will be no data transformation during it's display. Or we could comment out the lines responsible for the data transformation and reference this PR and it's issue for future reference on why the feature was removed.

@rdstern @N-thony on a separate note (that relates to how we are doing data transformations in the front end) I noticed something strange. The data viewer suggests that the data frame has 52 columns, yet the R viewer shows 3 columns. Notice how significantly different the data is represented as well. Is the difference intentional? or is it just not a significance issue? I do know we at times show contents in the data viewer in a different format compared to the R viewer, I've never seen a scenario where we allow the structure to be different as well.

Data viewer screenshot


R viewer screenshot

**Comment by Patowhiz** [comment]
I retract my second issue in the above comment. I noticed I didn't scroll horizontally!

**Comment by Patowhiz** [comment]
@N-thony after looking into this keenly, I now understand the expected output from the `GetInnerBracketedString()` function you made changes to. The function is meant to transform the sample input below to the output stated below.

**Sample Input**
_list(Birmingham = list(IATA = c("BHM", NA, NA, NA), ICAO = c("KBHM", NA, NA, NA)), Huntsville = list(IATA = c(NA, "HSV", NA, NA), ICAO = c(NA, "KHSV", NA, NA)), Mobile = list(IATA = c(NA, NA, "MOB", NA), ICAO = c(NA, NA, "KMOB", NA)), Montgomery = list(IATA = c(NA, NA, NA, "MGM"), ICAO = c(NA, NA, NA, "KMGM")))_

**Sample Output**
_BHM, NA, NA, NA, KBHM, NA, NA, NA, NA, HSV, NA, NA, NA, KHSV, NA, NA, NA, NA, MOB, NA, NA, NA, KMOB, NA, NA, NA, NA, MGM, NA, NA, NA, KMGM_

@rdstern this makes the data viewer consistent with what is seen in R Studio and the R Viewer. Which changes my mind from removing this feature if the bug can be fixed quickly.

@N-thony your code changes produce the following output.
_"BHM", NA, NA, NA_

Could you fix the bug in a way that maintains the expected output? Then I can review.

**Review by rdstern — APPROVED** [review]
@Patowhiz I am delighted with your detective work on this and @N-thony also delighted that your work on displaying lists in R-Instat is now consistent with the R viewer.  There will soon be more to do on lists.  It is potentially another selling point for R, that it is like a spreadsheet, but being able to handle lists should what an extraordinary spreadsheet it is.  @Patowhiz we already have a nice keyboard to manage numerical lists and we also need them for the new tables stuff!

This still looks to be working ok.

**Comment by Patowhiz** [comment]
@rdstern @N-thony this PR does not yet address my above [comment](https://github.com/africanmathsinitiative/R-Instat/pull/8583#issuecomment-1780588125). 

To save on time, I have created a PR #8607 that fixes the issue, retains the original functionality and improves the code.

Kindly check and let me know if we can close this PR.

**Pull request closed without merging**
