### PR TITLE
  Setting the enabled property of the difference checkbox in QC temperature

### PR DESCRIPTION
**Pull request by Ogik99**
Fixes issue #5013 
@shadrackkibet kindly review

### CODE REVIEW

**Comment by Muthenya** [comment]
Okay. I will have a look at it with them. Though I would also like Shadrack to have a look at it since I'm the one who took @Ogik99 through the changes.

**Comment by maxwellfundi** [comment]
@Muthenya thats fine but we need to have this tested

**Comment by Muthenya** [comment]
Okay. We have already tested it and we found a bug which I'll be resolving with Yvonne today.

**Comment by maxwellfundi** [comment]
@Ogik99  @Muthenya  was the bug found here resolved yet?

**Comment by dannyparsons** [comment]
Any update on this?

**Comment by Muthenya** [comment]
Sorry for taking long to respond to this. There is still a pending discussion on it's issue, that is #5013. This will depend on the outcome of the discussion.

**Comment by dannyparsons** [comment]
@Muthenya are you able to proceed now from Roger's response?

**Comment by Muthenya** [comment]
>The solution above, of keeping the difference checkbox enabled, but not allowing OK remains alright for now though. It may confuse some users, but not for long I think. There is so much else to do, that I am happy with this temporary solution.

@dannyparsons this is how the dialog is at the moment. So this means that no change is needed for now.

**Comment by dannyparsons** [comment]
Ok thanks, so can this be closed?

**Comment by Muthenya** [comment]
Yes.

**Pull request closed without merging**
