### PR TITLE
Fixing order of labels in the summary tables R code

### PR DESCRIPTION
**Pull request by lilyclements**
@rdstern @Ivanluv @dannyparsons this should fix the ordering issue outlined in the email from @rdstern 

@rdstern @Ivanluv - can you check this sorts the problem?

### CODE REVIEW

**Review by dannyparsons — APPROVED** [review]

**Comment by Ivanluv** [comment]
@lilyclements  I have tried this
image
  which produces the the following script 
image
 and the table does not seem to be ordered
image

**Comment by lilyclements** [comment]
@Ivanluv thanks! This should be sorted now.

**Comment by Ivanluv** [comment]
This is working okay from my end

**Comment by Ivanluv** [comment]
@rdstern @lloyddewit  could you review this so that we can have it merged?

**Comment by rdstern** [comment]
It is different, but I now can't get anything out!  For example for a simple table with the usual survey data:
image

And these were the commands:

image

**Comment by lilyclements** [comment]
@rdstern good point - this should hopefully now be fixed. Thanks!
(I am working from the office without my R-Instat laptop today so was not able to test this properly. Hopefully this is now fixed but do check!).

**Comment by rdstern** [comment]
@lilyclements sorry - still get the same error as above.

**Comment by lilyclements** [comment]
@rdstern how about now? It is working for me now !

I came across a bug which is that if we run mmtable2 without a factor and just one summary and one variable (and perhaps set as factor as FALSE only) then mmtable2 doesn’t work. I’ll write it up in an issue tomorrow.

**Comment by rdstern** [comment]
@lilyclements here is the table I have been aiming for!  Great.

image

**Review by dannyparsons — APPROVED** [review]

**Pull request merged**
