### PR TITLE
Renaming items and adding Three-Way Frequencies and Pivot-table(summaries) dialogs in Two/Three Variables sub-menu.

### LINKED ISSUE #7259: Incorporate Describe > Three Variables > dialogues into the current Two Variables dialogues
I propose that we change the Describe > Two Variables > dialogues into `Describe > Two/Three Variables >` dialogues, and then delete the Three Variables menu.
a) We currently have 4 items in the Three Variables menu.  The Summarise and Graph are disabled, so there are only two that have entries.  These are Frequencies and Pivot Table.  In each case the 3 variable is just a slightly more complicated dialogue, compared to the 2 variable.
1) Frequencies.  We could combine, by just having the 3 variable, and allowing it to be acceptable to just give the first 2 variables.  However the code is reasonably different for the graph (and table), so we could also keep them as separate dialogues?  Then they are called 2-way Frequencies and 3-way Frequencies.  That would be simple!
2)  The pivot table for Frequencies is 2 way.  Then the idea is that the 3-way is for Summaries.  Of course they can be added once the pivot table is established.  But it may also be sensible to keep them separate and have one as Pivot-Table (Frequencies) and Pivot-Table (Summaries)?
I welcome comments, particularly from @Ivanluv @shadrackkibet and @lilyclements .

We still need to include the 3-way (possibly also 4 way) in the summarise and graphics dialogues.  For the summarise I keep thinking that 3-way is often a simple summary table.  Whether that is a separate dialogue, or more options on the current 2-way dialogue is yet to be described.  And it may yet become `Two-Four Variables`!

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #7259 
@rdstern @shadrackkibet, in this PR which affects Two/Three variables sub-menu;
Renames Frequencies to Two-way Frequencies and also adds Three-way Frequencies. 
Renames pivot table to Pivot-Table (Frequencies) and also adds Pivot-Table (Summaries)
Also, here is updated database screenshot.

image

### CODE REVIEW

**Comment by rdstern** [comment]
@Vitalis95 this is almost there, and promising.
@Ivanluv has been working on the Pivot Table that is currently in the (now defunct) 3-way.  I think that is approved and merged, or just about ready. 
So delete Pivot Table (Frequencies)
Change Pivot Table (Summary) to just `Pivot Table`.
Check whether it looks better if there is a line above Pivot Table.  If so, add a horizontal line just above Pivot Table - which is a bit different.  That would make it stand out.
Make sure the Pivot table calls @Ivanluv new dialogue eventually.

Note also that as soon as it is ready, the Correlations option will call the new correlations dialogue you have been working on.  And the Summarise dialogue will be including the new version with skimr.

**Comment by Vitalis95** [comment]
@rdstern in this PR
I have added item `Add (Merge) Columns...` below Reorder Columns and also update the database for  `Duplicates... `to `Duplicate Rows...` in Prepare menu as requested by @N-thony in #7297 
I have also added a horizontal line just above Pivot Table and  deleted Pivot Table (Frequencies)

image

**Comment by Vitalis95** [comment]
@rdstern, since this PR isn't yet merged, I have changed the menu item `Data Object ` to `Data Book`, this partially fixes #7350 . I will add the Original Label control in separate PR.
Also, I have updated the label in the database
image

**Comment by rdstern** [comment]
@Vitalis95 that's great.  Is it the same pull request where you might add `Add (Merge) Columns` to the prepare > data frame menu, just after Reorder Columns? See 7029.  It is another copy of the same dialogue that is currently in Options by Context > Prepare.  @N-thony has a pull request that I've just approved.

**Comment by Vitalis95** [comment]
> @rdstern in this PR I have added item `Add (Merge) Columns...` below Reorder Columns and also update the database for `Duplicates... `to `Duplicate Rows...` in Prepare menu as requested by @N-thony in #7297 I have also added a horizontal line just above Pivot Table and deleted Pivot Table (Frequencies)
> 
> image

@rdstern  I have added that dialog in this PR below `Reorder Columns`. Have a look at it, thanks

**Comment by Vitalis95** [comment]
@rdstern @derekagorhom @lloyddewit , I have changed dialog name in Prepare>CheckData>Duplicates  to `Duplicate Rows` as suggested in PR #7305 
I had Changed the menu item to `Duplicate Rows` in this PR
image

**Review by rdstern — APPROVED** [review]
@Vitalis95 that's looking good.  Great.  Good with @lloyddewit or @shadrackkibet to get it merged

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
