### PR TITLE
Introduce AppImage build process

### PR DESCRIPTION
**Pull request by istride**
This PR introduces a mostly automated and cross-platform compatible process for packaging R-Instat into a single executable file that will run on Linux systems. The resulting package is an [AppImage][1]. See README.md for further details.

This work has come about due to a need to deploy R-Instat in a Linux environment for EUMETSAT. An initial attempt has been made to deploy R-Instat inside Docker containers, but it is awkward for GUI applications, for example, it is not straightforward to connect to the X server, and there is limited access to the host filesystem.  Packaging R-Instat as an AppImage will resolve these issues and simplify the installation process on Linux.

@dannyparsons and @ChrisMarsh82 have also been involved, thus far.

This PR is ready for review, but I am not able to assign a reviewer myself.

[1]: https://appimage.org/

### CODE REVIEW

**Comment by lloyddewit** [comment]
@istride Thank you for this.
To help other developers, please could you expand your comment above to include:
- a couple of sentences to describe what this PR does (you can still reference the ReadMe file for more info)
- the context
- who is involved
- what you expect the next steps to be (e.g. is this PR ready for review or still draft)?

Please could you also assign a suitable reviewer and tester?
Thanks

**Comment by istride** [comment]
@lloyddewit updated the description. I am not able to assign any reviewers myself. would you be able to help with that? cheers.

**Comment by lloyddewit** [comment]
@istride Thank you for the explanations.
@ChrisMarsh82 Please could you review?

**Comment by lloyddewit** [comment]
> @istride Thank you for the explanations. @ChrisMarsh82 Please could you review?

@ChrisMarsh82 please could you clarify the status? thanks

**Comment by ChrisMarsh82** [comment]
This looks fine although we may need to update what the install_packages.R looks at as we need to remember to keep this up to date with the current install_packages.R in the static folder. This may get a lot more involved as it is likely we need to update the docker file too as there may be other dependencies related to package.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
