### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by lloyddewit** [comment]
@dannyparsons I will update the French translations in the database and then merge this PR. 
Should I do that now or may I wait for further French translation changes, and then merge when we're ready to make a new release?

**Comment by dannyparsons** [comment]
I think @N-thony is still doing translations in CrowdIn and approving, which is why the commits keep updating here. So I think wait till he's done and then this can be merged to update the database.

**Comment by N-thony** [comment]
@lloyddewit this is ready now and can be merged. Thanks.

**Comment by lloyddewit** [comment]
@N-thony Thank you, this is fantastic! 
I cannot judge the actual language but I see that you have systematically and thoroughly reviewed several thousand translations. This should result in a big quality jump for R-Instat in French.
I copied the new files in this PR to PR #6469 and imported your changes into the database. I did this so that @rdstern will see your updated translations when he tests PR #6469; and so that the translation and database files are consistent in PR #6469.
I closed this PR to prevent additional updates from CrowdIn.
Any future changes to the French translations should be in a new PR.
Thanks again for the great work

**Comment by dannyparsons** [comment]
@lloyddewit I think we discussed this already, I can't remember, so I'll document here, I think we agreed in future to keep the CrowdIn changes in these auto PRs and to update the database separately. I'm just concerned that there are more chances for syncing issues if we update the non-English jsons outside of CrowdIn. In theory it works as well so I don't see an issue for the current files.

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit I think we discussed this already, I can't remember, so I'll document here, I think we agreed in future to keep the CrowdIn changes in these auto PRs and to update the database separately. I'm just concerned that there are more chances for syncing issues if we update the non-English jsons outside of CrowdIn. In theory it works as well so I don't see an issue for the current files.

Yes, as discussed, we should always approve and merge these CrowdIn PRs. If we don't, then CrowdIn will detect that the translations it has are different from the JSON files in the repo, and it will keep raising PRs until CrowdIn and the repo JSON files are consistent.

We will update the translations database in separate PRs.

**Pull request closed without merging**
