### PR TITLE
Improving the dlgInventory design

### PR DESCRIPTION
**Pull request by N-thony**
#5833

### CODE REVIEW

**Comment by N-thony** [comment]
I just made the design change and waiting for @lilyclements  for the code change.

**Comment by N-thony** [comment]
I'm waiting for the function from @lilyclements then I can add it.

> 
> 
> @N-thony this looks to be good so far. I expected it to add to the existing Inventory, so that would remain and give the graphical results, as it did before.
> I am not sure what is next? Are you waiting for the function from @lilyclements or should she add it in herself?

I'm waiting for the function from @lilyclements then I can add it.

**Comment by N-thony** [comment]
> 
> 
> @N-thony this looks to be good so far. I expected it to add to the existing Inventory, so that would remain and give the graphical results, as it did before.
> I am not sure what is next? Are you waiting for the function from @lilyclements or should she add it in herself?

I'm waiting for the function from @lilyclements, so I can add it.

**Comment by lloyddewit** [comment]
@N-thony Is this PR now complete and ready for review/test?

**Comment by N-thony** [comment]
> 
> 
> @N-thony Is this PR now complete and ready for review/test?

I had a problem with PR, the one I'm working on about dlgInventory is #5962.
Perhaps I will delete this one.

**Comment by N-thony** [comment]
This PR is superceded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Comment by N-thony** [comment]
This PR is superseded by #5962.

**Pull request closed without merging**
