### PR TITLE
Cumulative exceedance new branch

### PR DESCRIPTION
**Pull request by Ogik99**

### CODE REVIEW

**Comment by rdstern** [comment]
I have been trying this branch.  It tells me there are build errors?  Perhaps I am a bit early in trying to test it?

**Comment by Ogik99** [comment]
> I have been trying this branch. It tells me there are build errors? Perhaps I am a bit early in trying to test it?

Sorry for that Roger. I almost done with it

**Comment by Ogik99** [comment]
This can now be tested.

**Comment by rdstern** [comment]
@Ogik99 great it now works.
More comments soon, but can you start by getting @maxwellfundi to make the same changes on the polar stuff as in the other graphics dialogues - unless he also shared this with you.  Then we can get access to the Plot Options.

**Comment by maxwellfundi** [comment]
I already had got that done for this, not merged yet. But it's not a
problem will get that fixed automatically when both PR are merged

**Comment by rdstern** [comment]
So minor changes on the dialogue:
a) In the buttons at the top, Cumulative is centred, but Exceedance is on the left.  Could Exceedance also be centred.
b) There is a lot of vertical space round these buttons.  Good to compare with other dialogues (e.g. Prepare > Column: Text > Find/Replace.  So, reduce the space a bit, both above and below the buttons.
c) Similarly the From, To and In Steps of could usefully be centred with respect to the up/down control.
d) I tried changing the In steps of from 0.25 to 0.1 but nothing happened.  The y-axis steps still stayed as 0.25.
d) Currently the 0 and 1 is fixed.  So they could be text boxes, but disabled. 
e) I suggest that the **_:_** could also be so that you just type the number, rather than an up-down.  It could be checked that it is a positive number.  If you choose to type a silly number - say 25, then that's your problem.  The default remains 0.25.
f) If you are willing to become more ambitious, then the **_To:_** could usefully become a drop-down with alternative values of 1, 10, 100.  (Default is 1.) This will need a corresponding small change in the code of what is being plotted.  But check first with @dannyparsons first, because the stat_ecdf has fixed endpoints of 0 and 1.  See [here](https://stackoverflow.com/questions/28609547/in-r-ggplot2-include-stat-ecdf-endpoints-0-0-and-1-1).

**Comment by rdstern** [comment]
@Ogik99 those changes look very good.  The only one (I think) that remains is for the "In Steps of" to apply also to the exceedance graphs.  Currently the changes in the y-axis only applies to the Cumulative option.

**Comment by Ogik99** [comment]
Thanks Roger, working on it

**Comment by Ogik99** [comment]
This can now be reviewed

**Comment by rdstern** [comment]
@Ogik99 That's great that it now works.  I also like the idea that the fixed 0 to 1 changes to 1 to 0 when you move to exceedance.
However, I think the step can still be positive in both cases.  Then changing from cumulative to exceedance is just the button changing.

And I would slightly prefer that it starts with the actual default of 0.25.  (In both cases.)

Then it is ready for @dannyparsons to check on the code too.  It would be really good to get it merged.  Then @maxwellfundi can add the change for polar and we can check the dialogue with the sub-dialogue too.  

The one item missing is the date (in the year.)  But I hope that can be a general feature and therefore be done later within the sub-dialogue.

**Comment by Ogik99** [comment]
Managed to have the defaults as 0.25 in both cases. Currently working on having the steps as positive numbers only.

**Comment by maxwellfundi** [comment]
@Ogik99  This seems to have conflicts with the master. Could you try update it and I can help solve the conflict?

**Comment by Ogik99** [comment]
@maxwellfundi, I am unable to update the branch because of the same conflicts

**Comment by maxwellfundi** [comment]
@Ogik99  Okay let me help with the conflicts

**Comment by maxwellfundi** [comment]
@Ogik99  I have now fixed the conflicts with this. You can pull the new changes.

**Comment by Ogik99** [comment]
> @Ogik99 I have now fixed the conflicts with this. You can pull the new changes.

I have tried to update the branch but tells me there are no changes pull

**Comment by Ogik99** [comment]
@Maxwell could you kindly review the code

**Comment by Ogik99** [comment]
@Patowhiz any suggestions on the code

**Comment by maxwellfundi** [comment]
@Ogik99  You got nothing to pull because I updated your branch when I fixed the conflict. So you can keep working on this.

**Comment by Ogik99** [comment]
> Managed to have the defaults as 0.25 in both cases. Currently working on having the steps as positive numbers only.
@Patowhiz  any suggestions on this

**Comment by rdstern** [comment]
@Ogik99 great that you are working on this again.  I assume this is work in progress as I get build errors.  Tell me when you would like me to test.

**Comment by Ogik99** [comment]
> @Ogik99 great that you are working on this again. I assume this is work in progress as I get build errors. Tell me when you would like me to test.
@rdstern I am not getting any build errors from my end.

**Comment by rdstern** [comment]
@Ogik99 I must be doing something wrong then.  This is what it says now:
image

**Comment by Patowhiz** [comment]
@rdstern @dannyparsons after discussing with @Ogik99 about the issue of not displaying the negatives to the user when it comes to the `ucrNuds `controls. I'm convinced that we currently don't have such capabilities built into the control. For instance we want the control to have the value -1(the value which will be sent to R) but to display absolute value 1 to the user. 

@dannyparsons I think we may have to enhance the `ucrNuds `to be able to do this. If there's a different way of doing it please share otherwise I'm happy to quickly do PR addressing this so that @Ogik99 can finalise on this PR.

**Comment by Patowhiz** [comment]
@Ogik99 could you try and clean build before pushing for @rdstern to test. It could be why He is getting those compile time errors.

**Comment by Ogik99** [comment]
cum_vb
@Patowhiz , I have done the clean build. I didnt get any errors or changes that I could push.

**Comment by Ogik99** [comment]
> @rdstern @dannyparsons after discussing with @Ogik99 about the issue of not displaying the negatives to the user when it comes to the `ucrNuds `controls. I'm convinced that we currently don't have such capabilities built into the control. For instance we want the control to have the value -1(the value which will be sent to R) but to display absolute value 1 to the user.
> 
> @dannyparsons I think we may have to enhance the `ucrNuds `to be able to do this. If there's a different way of doing it please share otherwise I'm happy to quickly do PR addressing this so that @Ogik99 can finalise on this PR.

What's the final decision on this @Patowhiz  @dannyparsons

**Comment by rdstern** [comment]
@rdstern @dannyparsons after discussing with @Ogik99 about the issue of not displaying the negatives to the user when it comes to the ucrNuds controls. I'm convinced that we currently don't have such capabilities built into the control. For instance we want the control to have the value -1(the value which will be sent to R) but to display absolute value 1 to the user.

@dannyparsons I think we may have to enhance the ucrNuds to be able to do this. If there's a different way of doing it please share otherwise I'm happy to quickly do PR addressing this so that @Ogik99 can finalise on this PR.

What's the final decision on this?

I am forwarding to @volloholic to (at least) double the chances of a reply! @dannyparsons has had a "vow of slience" recently!

**Comment by Ogik99** [comment]
Polite follow up

**Comment by maxwellfundi** [comment]
@rdstern will merge this and other minor changes will follow.

**Comment by maxwellfundi** [comment]
@Ogik99 we have conflicts here. We should be able to fix this tomorrow, I can't easily do on the phone.

**Pull request merged**
