### PR TITLE
Adding Wakefield keyboard to the calculator

### PR DESCRIPTION
**Pull request by Wycklife**
This is still in progress.

### CODE REVIEW

**Comment by Wycklife** [comment]
@rdstern, I am adding the arguments for each variable, in the case where we have the arguments defined with values, should I ignore the values, for example; children(n, x = 0:10, prob = c(0.25, 0.25, 0.15, 0.15, 0.1, 0.02, 0.02,
  0.02, 0.02, 0.01, 0.01), name = "Children")

**Comment by dannyparsons** [comment]
If these are the defaults then keep them in. This is what we are doing for other functions so we need to keep consistency.

**Comment by Wycklife** [comment]
@maxwellfundi help me resolve this, then it will be ready for review.

**Comment by Muthenya** [comment]
@maxwellfundi kindly resolve this then I review.

**Comment by dannyparsons** [comment]
I've resolved the conflicts here.

**Comment by Muthenya** [comment]
@Wycklife I have come across this problem with the size of the dialog (the base buttons appear to be "cut").

image

Some resizing will do.

**Comment by Muthenya** [comment]
I have also observed a number of buttons whose names are not fully seen. Namely:
1. `internet_browser`
2. `wakefield_month`
3. `wakefield_upper`
4. `wakefield_year`
5. `sex_inclusive`

The buttons can be widened a bit to accommodate the longer names.

**Comment by dannyparsons** [comment]
Wider buttons or smaller font could be done. We should keep buttons the same size if possible.

**Comment by rdstern** [comment]
If it gets too difficult to fit, then we should consider Wakefield1 and Wakefield2, i.e. 2 keyboards.

**Comment by Muthenya** [comment]
@Wycklife what's the current state of this?

**Comment by Wycklife** [comment]
@dannyparsons We managed to make the changes together with Lazarus on his machine. When I pulled the branch containing the changes, I could not see the changes we made, what could be the problem and how do I resolve this?

**Comment by dannyparsons** [comment]
Do you know the name of the commits you made with Lazarus? They should appear in the list of commits on the pull request. You could first check that they appear there.

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons This is now finished. It works well. We would like you to test it to see if the outputs are what is expected.

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers I have managed to make the changes on Wakefield Calculator, and this is how it looks like
calculations

**Comment by dannyparsons** [comment]
The design looks good, but there are 414 file changes. Can you check why?

**Comment by maxwellfundi** [comment]
@dannyparsons  I have checked this and it appears that the files changes are many because he kept updating his branch and so it has file changes from other commits from other people.

**Comment by dannyparsons** [comment]
Yes something like this has happened because it is removing all of the recent changes that have been made.
In general there shouldn't be a need to update a branch you are working on, because the work is usually independent of recent changes, and it also can lead to issues like this.

I will close this so it doesn't get merged accidentally. I suggest moving the changes to a new branch.

**Pull request closed without merging**
