### PR TITLE
Updated Structured > Circular density Circular > 

### LINKED ISSUE #6060: Adding three plots dialogs from the circular package in Structur>Circular menu
These dialogs, Rose Plot (same as wind rose?), Density Plot and scatter Plot already have a placeholder under Circular sub menu in the structured menu. I have been comparing these plots from the circular package and reproducing the same using ggplot2 package. I find it efficient, consistent with our graphics and flexible to extend these plots using ggplot2 rather than those in circular package which uses base graphics. Since the circular package doesn't cope with multiple stations which is of interest to us, I therefore suggest we reproduce these graphics using the ggplot2 system. Initially I am going to proceed with implementation of these dialogs. @rdstern @dannyparsons  what  are your thoughts on this? I also had this discussion with @lilyclements elsewhere.

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #6060
@africanmathsinitiative/developers @rdstern @Wycklife this is ready for review but will require the review after PR #6220 is merged.
It implements ggplot options similar to the ones under Describe > Specific > Histogram.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet please could you review? thanks

**Comment by shadrackkibet** [comment]
I see conflicts in `instat.vbproj` file. @HawardKetoyoMsatsi do you need these changes?

**Comment by HawardKetoyoMsatsi** [comment]
I can see @Ivanluv also made changes affecting the file with conflicts let me confirm the changes he made to see whether I can accept them.

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet @lloyddewit I am closing this PR due to unresolved conflict. I will open another PR immediately.

**Pull request closed without merging**
