### PR TITLE
Duplicate rows translations changes

### PR DESCRIPTION
**Pull request by Patowhiz**
This PR contains translations changes needed for the duplicate rows dialog.
Related to issue #7299 and PR #7354.

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Patowhiz This is a binary file so there's no diff. Please could you list the database changes that you made? thanks

**Review by lloyddewit — APPROVED** [review]
@Patowhiz This is a binary file so there's no diff. 
I approved but I assume that, before @rdstern approves, he will want to know which text you changed.
Please could you list the database changes that you made? thanks

**Comment by Patowhiz** [comment]
@rdstern @lloyddewit 
The translations chnaged are, the dialog title and  I also set the database to not translate the dropdown menu mentioned in the issue.
We tested this with @derekagorhom .

**Comment by derekagorhom** [comment]
@rdstern could you approve this PR so that we can finalize the changes on PR #7354

**Review by rdstern — APPROVED** [review]

**Pull request merged**
