### PR TITLE
Ensured that menu translations in Portuguese are correctly capitalized

### LINKED ISSUE #8340: Lower case in Portuguese translation
@rachelkg thank you for your offer to check this in the database:

Here are the first 3 instances - `Climatic and Experiments` on the main menu and `Copy` on the Edit menu.

image

Contrasts on Factor menu:

image

Multivariate on Describe menu

image

date on thye climatic menu.

image

Experiments on the View menu.  There I notice that the English just says Experiments and could usefully be changed to Experiments Menu.

image

Windows on the Help menu:

image

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes #8340 
Thank you to @rachelkg for making the changes in CrowdIn.
@rdstern please could you test? thanks

### CODE REVIEW

**Comment by rdstern** [comment]
@lloyddewit and @rachelkg this seems improved, but 

image

The Experiments is now capitalised, but not climatic.

And I may have found more, though perhaps not for now?

Here is part of the above, now in English:

image

Notice each main word in English is capitalised, but not in the Portuguese?  I think perhaps in no other language than English?  Should we:

a) Leave these as they are - at least for now?
b) Capitalise the words in all languages - perhaps individually or through code?
c) Uncapitalise - is that a word - the English?

Roger

**Comment by lloyddewit** [comment]
> The Experiments is now capitalised, but not climatic.

I will fix this.

> Notice each main word in English is capitalised, but not in the Portuguese? I think perhaps in no other language than English? 

Good spot. It will be a lot of work to change this. Also, inconsistencies are likely to creep back in for each new release because the new machine translation will not follow our rules. Finally, different languages may have different norms regarding capitalization so standardization may not be appropriate. Is this a high priority? I suggest that we leave as is.

**Comment by lloyddewit** [comment]
@rdstern please could you test again? thanks

**Review by rdstern — COMMENTED** [review]
Great.

But I assume you want me to be "picky".
a) Edit > Copy
b) Climatic > date
c) Prepare > Factor > Contrasts

They are the only 3 I could still find that start in lower case.

**Comment by lloyddewit** [comment]
@rdstern Picky is just what I need, sorry I missed those.
Please could you test again? thanks

**Review by rdstern — APPROVED** [review]
@lloyddewit looks fine.
I noticed quite a number of language changes in Portuguese that I assume come from you.  There have also been a lot of Spanish changes and I wonder if they were made by Carla?  They still all appear to come from Danny.  Could that be altered easily to come from the person who made the change?

**Comment by lloyddewit** [comment]
@rdstern Correct, Portuguese changes are from me, Spanish changes are from Carla.
The PR always comes from Danny because he owns the automatic process that raises/updates the PR whenever something changes in CrowdIn (but there is no personal involvement from him).

**Pull request merged**
