### PR TITLE
Added the first Circular Plot (Density Plot dialog)

### LINKED ISSUE #6060: Adding three plots dialogs from the circular package in Structur>Circular menu
These dialogs, Rose Plot (same as wind rose?), Density Plot and scatter Plot already have a placeholder under Circular sub menu in the structured menu. I have been comparing these plots from the circular package and reproducing the same using ggplot2 package. I find it efficient, consistent with our graphics and flexible to extend these plots using ggplot2 rather than those in circular package which uses base graphics. Since the circular package doesn't cope with multiple stations which is of interest to us, I therefore suggest we reproduce these graphics using the ggplot2 system. Initially I am going to proceed with implementation of these dialogs. @rdstern @dannyparsons  what  are your thoughts on this? I also had this discussion with @lilyclements elsewhere.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #6060
I have added data selector
Two single receivers
Two buttons which opens  a subdialog each
Code Implementation is in the process.

@africanmathsinitiative/developers Still in progress.

### CODE REVIEW

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers This is now ready for review. @rdstern I have implemented this with ggplot2 package as well as added circular density function. The two buttons opening the sub dialogs are disabled for now. Could you please check if this is okay?

**Comment by Wycklife** [comment]
Before testing this, you either wait till the PR #6075 get merged or get the changes from this PR and PR #6075 into one branch. The two PR are related.

**Comment by lloyddewit** [comment]
@shadrackkibet please could you review? thanks

**Comment by Wycklife** [comment]
@lloyddewit I had a discussion with David over this, this PR is not therefore needed, I'm closing it. It's in progress but on anew branch.

**Comment by lloyddewit** [comment]
@Wycklife Thank you for letting me know. I'm not aware of any other open PRs for this issue so I assume that you'll open a new one. When you do this, please reference this PR, thanks

**Pull request closed without merging**
