### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@lloyddewit these are updates from CrowdIn. The menu translations should largely be the same as before. The non-menu items which were not translated before have now gone through a machine translation and are included here. 

These are the translations I propose for the initial French version. There will be some oddities, but this is the best we can do in the short time.

I've done a quick sanity check on the changes in the files by looking at individual items and it looks fine so I'm going to merge as there's no functional software changes. In case you notice anything odd let me know.

**Comment by lloyddewit** [comment]
@dannyparsons That's great, thanks.
I'll make a new translations database from these files and include it in PR #6413.

**Comment by lloyddewit** [comment]
@dannyparsons I made a new translations database. The menus and the static text translates correctly. Some of the dynamic translated text (e.g. some Checkboxes and buttons with dynamic labels) do not translate (see screenshot below).
I traced the problem to PR #6382. In the`en/r_instat_not_menus.json` I did not include all the dynamic text. This was my mistake, I apologize.
I see two options:
- I create a new `en/r_instat_not_menus.json` file, you do an auto-translate, and I make a new database
- We live with the incomplete translation for 0.7.1

Please let me know your preference.

image

**Comment by dannyparsons** [comment]
Yes please on the first option

> - I create a new en/r_instat_not_menus.json file, you do an auto-translate, and I make a new database

**Pull request merged**
