### PR TITLE
Fixing condition for setdefaults

### PR DESCRIPTION
**Pull request by Lunalo**

### CODE REVIEW

**Comment by Lunalo** [comment]
Still in progress

**Comment by Lunalo** [comment]
@dannyparsons 

I have fixed this but the dialog is doing automatic resseting on reopening . If it takes long to fix it, we can do a temprary fix in the set defaults. thanks.

**Comment by dannyparsons** [comment]
ok do that for now, if I can I will try to fix it as well.

**Comment by Lunalo** [comment]
I think I have now implemented that

**Pull request merged**
