### PR TITLE
Added template option to the Structure > Circular > Define dialog

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes issues #6932
Adding an option to the Structure > Circular > Define dialog

could you take a look? 

thanks

### CODE REVIEW

**Comment by lloyddewit** [comment]
@rdstern Please could you test? thanks

**Review by rdstern — APPROVED** [review]
Looks good in that it seems to work.  Looks messy in that the options are not lined up and they are unequally spaced.  Please could that aspect be corrected.  Then I am happy to approve.

**Review by rdstern — CHANGES_REQUESTED** [review]
See comment on lining of controls

**Comment by derekagorhom** [comment]
Hello @rdstern 
good day 
i have resolved the comment on  options are not lined up and they are unequally spaced, please can you have a look 
Thanks

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom sorry to be "picky" and perhaps get one of the others to line the controls better?  It is now almost ok, but the clock24 is still unequally spaced and not aligned. If you make this small change, then please get one of the others to check, and I'll approve without seeing the change.  Thanks

**Comment by derekagorhom** [comment]
Hello @rdstern 
I fixed the issue of clock24 being unequally spaced and not aligned.

**Review by rdstern — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@derekagorhom so that the issue closes when the PR is merged, you should reference the issue as follows;
fixes #6932

**Comment by derekagorhom** [comment]
@shadrackkibet thank you and duly noted

**Pull request merged**
