### PR TITLE
Prepare clear up

### LINKED ISSUE #5942: Some "Prepare" Menu dialogs that need clearing up.
I came across a couple of dialogs in the Prepare menu which need some minor changes.

1. Prepare > Check Data > Non-numeric cases
a) Usually the first letter of each word is capitalised in the title of the dialog. Further, the main form before clicking on this has a hyphen between "non" and "numeric"
b) The checkbox is too small so the words are cut out
c) The data frame selector is lower than the usual (10,10)
d) Usually a new column name would have both words capitalised
e) There is a bit more space than usually seen in other dialogs between the controls.

image

2. Prepare > Column: Factor > Combine Factors
a) ucrReceiver is too high compare to the rest
b) The "Separator" label from it's respective control is too far and not aligned.
c) Tab order needs fixing

image

3. Prepare > Column: Calculate > Polynomials
a) Just the ucrSave size needs sorting since it currently covers the input box

image

4. Prepare > Column: Calculate > Permute
a) As before, the ucrSave size needs sorting (when more than two columns are given)
image

### PR DESCRIPTION
**Pull request by lilyclements**
Fixes #5942 

@africanmathsinitiative/developers this is ready for review.

Just a quick clear up of four dialog designs. "Before" screenshots are given in #5942 

1. Prepare > Check Data > Non-numeric cases
a) First letter of each word in the title of the dialog is now capitalised, with a hyphen added between "non" and "numeric"
b) The checkbox is made larger so the words can all be read
c) The data frame selector is at the usual (10,10)
d) Both words capitalised in new column name
e) Space between controls neatened up

Should the first letter for the words in the checkboxes here be capitalised? They are in most other dialogs (however, not in all. For example, the Import dialog).

image

2. Prepare > Column: Factor > Combine Factors
a) The ucrReceiver is moved down slightly
b) The "Separator" label and it's control are aligned and closer.
c) Tab order fixed

image

3 and 4. Prepare > Column: Calculate > Polynomials and . > Permute
a) The ucrSaves are resized so that the label does not cover the input box

image

image

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review? thanks

**Comment by lloyddewit** [comment]
@Ivanluv did you get a chance to review this? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  am looking at this

**Comment by Ivanluv** [comment]
@lloyddewit  this looks okay

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Comment by lilyclements** [comment]
The only changes made are to the design rather than the code itself, so this should not require testing beyond viewing the dialog design (although if you do test and find a bug I am happy to fix it).

**Comment by lloyddewit** [comment]
@rdstern please could you test? thanks

**Review by rdstern — APPROVED** [review]
I am approving now.  In the first dialogue (non-numeric cases) there is a very minor change on capitalization still to make - it affects nothing.  There is a larger improvement needed to add the Position control to the saved variable, which will be a new (small) issue for @Patowhiz after it is merged.  Then I would like @lilyclements to make the small change in this dialogue and also include Patrick's new code in further dialogues.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
