### PR TITLE
Updated Merge Additional Data dialog

### LINKED ISSUE #7029: Update Merge Additional Data dialog
This dialog: Options by Context > Prepare > Merge Additional Data
is a simplified merge that does a left join and saves the result back into the same data frame.

This is useful when you just want to merge additional columns from another data frame which has matching values to join by so won't change the structure of your data. It's convenient for this to be saved as the same data frame to avoid producing multiple copies of your data. The merge dialog doesn't do this as it often produces something new or goes wrong.

The dialog currently looks for a key and if it exists it uses that as the join options. Otherwise you can define them. You have the choice of selecting columns from the second data frame but the first is fixed to have all the columns.

This dialog could be used generally, not just in this menu. Before that, there could be some improvements:

- It should check that the result will not add any extra rows i.e. all values in the join columns in the second data frame must appear in the first, otherwise it should give an error.
- It currently doesn't save over the first data frame but produces a new one
- I couldn't seem to get it to work when I defined the join columns manually - maybe this wasn't implemented yet
- The data frame labels should be something like "Main Data Frame" and "Additional Data Frame"

This might need some more specification and view from @rdstern

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7029
This PR replaces PR #7309 due to the conflicts.
@rdstern I made the changes here from your review in PR #7309 https://github.com/africanmathsinitiative/R-Instat/pull/7309#pullrequestreview-912676623, Please take a look.
@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
Looks nice, but:
I used the survey data (2 copies) and deleted 3 variables from one of them.  Then made a row variable in each data frame, called row.  Then tried the merge
a) There was a variable of the same name in each data frame.  I wonder why it didn't find it.  I was easily able to add it though.
b) I could not get Ok to be enabled.  So could not check if it works.

**Comment by N-thony** [comment]
> Looks nice, but: I used the survey data (2 copies) and deleted 3 variables from one of them. Then made a row variable in each data frame, called row. Then tried the merge a) There was a variable of the same name in each data frame. I wonder why it didn't find it. I was easily able to add it though. b) I could not get Ok to be enabled. So could not check if it works.

@rdstern please could you re-test? For item a) I need a support from @dannyparsons on checking the link or updating the link when we add the same column in the two dataframes.

**Comment by N-thony** [comment]
> 

@rdstern could you try this for item a)?
1. Load survey dataset two times you will have `survey` and `survey1`,
2. and then from `survey` delete some columns that you will like to add back from `survey1`,
3. go to `Prepare > Data Frame > Row Numbers/Names` then add row in both datasets,
4. use `Prepare > Keys and Links > Add Key` to define `row as key` for both datasets,
5. use `Prepare > Keys and Links > Add Link` to define `row as link` between the two datasets
6. then go to Options by `Context > Prepare > Merge Additional Data...` it will automatically detect `row` as link between the two datasets.
**Note**. it was not detecting row when you did before because row was now defined first `key` in both datasets and the as `link` between the two datasets

**Comment by rdstern** [comment]
Discussed why the making of key variables above should not be necessary.  The code to detect linking should be identical to what is used in the general merge dialogue.  That compares on names.

**Comment by N-thony** [comment]
> Discussed why the making of key variables above should not be necessary. The code to detect linking should be identical to what is used in the general merge dialogue. That compares on names.

@rdstern of course, I got the point now. Thanks.

**Pull request closed without merging**
