### PR TITLE
Updating R-Instat library

### LINKED ISSUE #5121: Add Statistical Problem Solving directory to the R-Instat library
In the longer term we may need a re-think of the R-Instat library.
In the short term it would be useful to have some of the data sets in the R-Instat library for further AIMS courses to make more use the same problems as in our recent course in Cameroon.  And also for James in his course in Maseno.

One data set would be the R file for the survey that is sort of there already.  But change the names of the variables that currently say "Village.", i.e. have a full-stop at the end of the name.

[Tomato.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/2663458/Tomato.xlsx)

Here is tomato.

It would be good to have some sets from the Fuma game.  Perhaps 1 with the game (24 observations), 1 with 1 sample 144 cases.  Perhaps 5 with 10 - 1440 cases and 1 with 100?  Ask Danny.

Then also some (as many as possible) of the data sets from the week 3 assignments.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5121 

@africanmathsinitiative/developers  this is ready for review.

### CODE REVIEW

**Comment by dannyparsons** [comment]
It looks like this has just removed all the files without adding any. Please check the commits carefully.

**Comment by Wycklife** [comment]
@dannyparsons This is because the last commit was  missing by the time I created the pull request. It's already there and this can now be merged.

**Comment by dannyparsons** [comment]
Great, and what about the new Rwanda datasets that Roger sent last week?

**Comment by Wycklife** [comment]
@rdstern Could you please upload the new Rwanda datasets here?

**Comment by dannyparsons** [comment]
You can find them here https://github.com/africanmathsinitiative/R-Instat/issues/5265

**Comment by Wycklife** [comment]
@dannyparsons The Rwanda_Workshop_data has been added to the library.

**Comment by Wycklife** [comment]
@Ivanluv Could you please review this

**Pull request merged**
