### PR TITLE
Rewriting One Variable Model fit

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great that this is getting updated. See the changes I made to one variable compare model in the latest to see how to handle multiple additional functions and link to sub dialogs - particularly how to add additional codes running after the base code.

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers this is ready for review...

**Comment by AlexSananka** [comment]
Testing this now

**Comment by AlexSananka** [comment]
Sort out the issues we have discussed together,also the designer needs some edits so that it can look nit(currently it is somehow wide).
Both ucrSaves in the subdialogs are not working,can we make them working?If not then can we disable them until we can make them working?
I also understand that some four distributions have an `error 100`.I don't know how you're planning to sort out this.
Once this issues are sorted out then this will be ready for @dannyparsons .

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers  this is ready for re-review..
Note: 
there is one bug which was there  in the previous installer though had not been identified yet.
If i choose for example negative binomial distribution, this error is given
image

the `error code 100 ` is given which i guess is an issue with the `fitdist` function.
-One var fit Model in the latest version 0.3.1 is not working (has a no of bugs)

**Comment by stevenndungu** [comment]
the error above occurs with  Hypergometric Distribution,Negative Binomial,Binomial,extreme value and von mises only. Others are working quite well.

**Comment by AlexSananka** [comment]
@dannyparsons I have tested this and it's working fine and more better than what we have currently.
I think it can go in.

**Pull request merged**
