### PR TITLE
Added three Replace options in the Find/Replace dialog

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
Fixes (partially) #7304 
This is still in progress. I am researching the function for the third option, replacing entire cell contents like it's done in Excel.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
I assume you have yet to implement the replace cell.  The radio buttons look fine.
Perhaps check the code to update the default name of the replace cell option.  If I go to the replace options it seems ok.  Then if I go to the cell option, then back to detect (radio button at the top) and then back to replace, then it still has the name detect.

**Comment by anastasia-mbithe** [comment]
@rdstern, I found a function to replace the cell, you can test it now. I also fixed the bug you referred to in your earlier comment.
It is ready for review.

**Review by rdstern — DISMISSED** [review]
Looks good.  I hope the code is also ok so it can be merged soon?

**Review by lloyddewit — APPROVED** [review]
@anastasia-mbithe Looks great, thank you.
I just renamed one of the variables.

**Pull request merged**
