### PR TITLE
dlgMakeDate design

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready for review

Changes:

- design amendments to decrease the depth of the dialog from 613x516 to 533x516

One of the dialogs discussed in #5835 (see point (c))

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Please add the previous and the new designer here, I think it will be quicker to review designer changes that way rather than pulling branches.

**Comment by lilyclements** [comment]
@shadrackkibet noted! This one has a few tabs but nothings changed within the tabs

Before:
image


Now:
image

**Comment by shadrackkibet** [comment]
Looks better now. Can we decrease the spacing between **Specify Format** label and the corresponding Combobox? What do you think?

**Comment by lilyclements** [comment]
Agreed, and done:

image

**Comment by shadrackkibet** [comment]
Looks good to me. @rdstern @lloyddewit ready for you to review and approve for merging.

**Comment by lilyclements** [comment]
@rdstern the help option should hopefully now be visible (or it is for me anyway!)

**Pull request merged**
