### PR TITLE
Adding Geom_smooth

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers  I have put up some parameters for the geom_smooth here which can be tested. Just one issue to be addressed here though, layer parameters reset on reopening

**Comment by rdstern** [comment]
What is the state of this now?  It would be great to be able to include this geom soon.

**Comment by maxwellfundi** [comment]
The current pull request on this is working with a couple of parameters not
all. It has an issue with resetting too but I will have it fixed by end of
week hopefully.
Thanks

**Comment by rdstern** [comment]
Great that geom smooth is there.  

Is there re strong reason why the **formula** parameter is missing?  That is what makes it really powerful.  I realise it has to be given in terms of y and x, rather than our own column names.

**Comment by maxwellfundi** [comment]
The formula, as indicated on the comments on the code, is missing because we currently do not show textboxes that the user would type into for the layer parameters. This will be possible when we will be able to do that.

**Pull request merged**
