### PR TITLE
Climatic Summaries

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Can someone review this when its ready and check the issue that Roger found before, with sometimes the year/within year variables still being included in the code even when the correct radio button was selected?

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is ready for review.

**Comment by rdstern** [comment]
A nice feature:   have been using climatic summaries a lot.  Not by month, so I have not hit the problem above.
I have also noticed this nice feature, which may be there by accident, namely that it does the summaries by year whether the year is a factor, or not.  The ordinary summaries insist on just factors, but it is convenient in the climatic summaries that the year remains a variate.  So I am happy with this feature!

**Comment by shadrackkibet** [comment]
@dannyparsons  this is ready for you to review.

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers can someone test this out?

**Comment by Muthenya** [comment]
I'm testing this now.

**Comment by Patowhiz** [comment]
@Muthenya @shadrackkibet this is okay from my end. Checked for the bug above, its fixed.
@dannyparsons this is ready for you.

**Comment by Muthenya** [comment]
This looks good.

**Comment by shadrackkibet** [comment]
@dannyparsons  this is ready for you to review.

**Pull request merged**
