### PR TITLE
Adding the climatic extremes value dialogue 

### LINKED ISSUE #5887: Adding an extreme value dialogue
This is already provided under Climatic > Model > Extremes.

But that dialogue is simply copied from the old Instat and almost certainly the code and dialogue need to be very different.  

This will almost certainly use the fevd function from the extRemes package.  It allows trends etc and so may be "Interesting" to construct.  
We may also call other functions to use the resulting object, in the same dialogue, or have another new dialogue to Use Extreme Model.  Then this one would become Fit Extreme Model.

We need to ensure that the structure of this (or these) dialogues is consistent with other dialogues in R-Instat.  We may also find that the structure of the equivalent dialogues in the front-end to the extRemes package is helpful?

### PR DESCRIPTION
**Pull request by Ivanluv**
fixes #5887

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv Is this ready for review? thanks

**Comment by Ivanluv** [comment]
@lloyddewit no,I've just started working on this

**Comment by Ivanluv** [comment]
@shadrackkibet any ideas on how to implement @rdstern  first suggestion

**Comment by rdstern** [comment]
@Ivanluv could you look at what is done in the Model > Fit Model > General dialogue?

**Comment by Ivanluv** [comment]
@rdstern  could you look at this

**Comment by Ivanluv** [comment]
@rdstern  could you look at this again

**Comment by rdstern** [comment]
@Ivanluv sorry to mess you up with this, but it will be simpler in the long run!  Delete the second receiver for the formula and change the label to become "... for Location or Scale".  Then it is the location argument in the formula for GEV and Gumbel and scale in PP,GP and exponential.

**Comment by lloyddewit** [comment]
@shadrackkibet please could you peer review this PR?

**Comment by shadrackkibet** [comment]
Not easy to review this at the moment because of many files changes. Can we separate them? Anything that touches `frmMain` or `vb.proj` should be done separately and merged as soon as possible.

**Comment by lloyddewit** [comment]
@Ivanluv I think that the 4 conflicting files have all been merged/committed via other PRs. Please could you resolve these conflicts so that @shadrackkibet can start the peer review? thanks

**Comment by Ivanluv** [comment]
Am working on this

**Comment by Ivanluv** [comment]
I have moved the changes here to PR #5933

**Comment by lloyddewit** [comment]
@Ivanluv Thank you for opening PR #5933. Can we close this PR now?

**Comment by Ivanluv** [comment]
@lloyddewit  Yes .This can be closed

**Pull request closed without merging**
