### PR TITLE
Added "Fixed End Limit" and "Fixed Start Limit" options into Fill Date Gaps  dialog

### LINKED ISSUE #6327: Adding a further option to the Climatic > Dates > Fill Date Gaps dialogue
This is for @dannyparsons to check that it is sensible, and then I hope it is a very quick job for @shadrackkibet who has already worked on this dialogue.  It is to support the new data entry.

We will sometimes want to extend the climatic data frame to enable data entry for a new year at the end - sometimes even at the start.  One way is to use the Fill Date Gaps dialogue.  

I assume (usually) an initially tidy (climatic) data frame.  Extending in one direction (or the other) would be easier if we extend the options in the limits pull-down.

We currently have Data Limits and Fixed limits.  Could we also have `Fixed End Limit `and `Fixed Start Limit`  They would open just a single copy of the calendar control.  That would make life easier.

I assume, and hope this is a pretty trivial addition?

### PR DESCRIPTION
**Pull request by shadrackkibet**
fixes #6327

@rdstern this is not yet ready for the full review. Please do some initial testing just to check that I am on the right path.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
I also thinking of fixing #5523 here and that is why I have this as a draft PR.

**Comment by shadrackkibet** [comment]
Yes, Please approve. We already have an open issue with setting the minimum and maximum dates.

**Comment by shadrackkibet** [comment]
@rdstern the output message is now also modified as requested. Thanks

**Review by rdstern — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet You set this PR to 'ready for review', does this mean we can go ahead and merge? thanks

**Comment by shadrackkibet** [comment]
Yes @lloyddewit

**Pull request merged**
