### PR TITLE
Design change to bar chart dialogue

### PR DESCRIPTION
**Pull request by Ivanluv**
This fixes  the design  issue in PR #5689

### CODE REVIEW

**Comment by Ivanluv** [comment]
@rdstern  could you look at this

**Comment by lloyddewit** [comment]
@Ivanluv may I merge this or do you still want to make extra changes (e.g. add bodies to the callback subroutines)?
I understand also that if I merge this then PR #5689 will also merge automatically.

**Comment by Ivanluv** [comment]
I have removed the empty subs because they are not needed.So this can be merged.Am not sure about  the issue on merging, @maxwellfundi  is more familiar with that

**Comment by lloyddewit** [comment]
@Ivanluv  Thank you for the changes. The merging I mentioned isn't an issue it's just the way Git works. Git merges the commits. When all of a PR's commits have been merged then the PR is considered merged. This PR contains all PR #5689 's commits so when this PR is merged then PR #5689 will also be merged.

@rdstern The only thing that changed since your previous approval is that 2 unused subroutines were removed. Please could you approve again? thanks

**Pull request merged**
