### PR TITLE
One variable Fit model

### LINKED ISSUE #5323: the one-variable fit no longer works
I am looking at fitting extreme value models.

I started with the one variable, which used to work quite well.  

Now it doesn't.  Here is an example of the code generated to fit a normal distribution - just the first 3 lines for now:

**max <- data_book$get_columns_from_data(data_name="ghana_by_year_station", col_names="max")
max <- data_book$get_columns_from_data(data_name="ghana_by_year_station", col_names="max")
last_model <- fitdistrplus::fitdist(method="mle", distr="norm", start=base::mean(x=max), data=base::as.vector(x=max))**

It is quite a complicated package, but getting the initial fit) command to work again could be easy.
a) I notice - the initial line is repeated twice.
b) In the main command the data argument is given last.  That's not a problem, but it is first in the documentation.
c) It is given with the initial base::, which is not needed
d) If I get rid of the start argument in the code, then it works without error.  
e) In fact then the whole code works without error, so I get a picture at the end.

So, I propose that initially the code be examined and simplified.
Also initially try to get it working without the start argument.  (I think it isn't needed for most distributions.
However it IS needed for the extreme value distribution.  (Which is an important one) So, eventually it will have to be given, at least for that distribution.
That may need a bit of Danny help.

### PR DESCRIPTION
**Pull request by stevenndungu**
Bugs fixed:
1 - Could  not work with data containing missing values - test with a data like Dodoma.
2 - Fitting a moment and goodness of fit (fitting options sub dialogue) with MLE (display sub dialogue)
3- fixes #5323

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@stevenndungu  is this ready for review?

**Comment by stevenndungu** [comment]
Not yet @maxwellfundi . Trying to sort out `start` parameter for various distributions. Quite confusing since different distributions require different start values...

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers someone can review this..
I have fixed several issues mentioned in the issue and more not mentioned. 
NB: I expect it to have some bugs - kindly report - though some I found are unsolvable since they are not implemented in the respective packages.

**Comment by stevenndungu** [comment]
Note that for `start` parameter  we need a  list with names that correspond to the parameter names. This was actually the reason we had problem with the start parameter initially used.
I have used arbitrary values for start values for the optimisation process. If anyone has better suggestion, I would be happy to adjust.

**Comment by Wycklife** [comment]
@stevenndungu  reviewing it

**Comment by stevenndungu** [comment]
Ok great! I will explain to you some of the things to test.

**Comment by Carolnikie** [comment]
- I have tested this one but found the following errors.
image' 
- this happens when i do F distribution - moments
image; 
- this happens when i do negative binomial - maximum likelihood
image; bernoulli - 
- this happens when i do maximum likelihood 
image; 
- this happens when i do weibull - moments

**Comment by stevenndungu** [comment]
Thanks @Carolnikie .

For the `moments` .  A parameter called `order ` is required. However, adding it results to other errors which solving gets more complicated - looking for a way out.

- Error code 100, does not always happen. The error is given if the optimum parameter is not obtained (convergence not attained) after 100 runs. [ref:](https://rdrr.io/rforge/fitdistrplus/src/R/fitdist.R).

- Start parameter for binomial - I have  handled that in my last commit.
Addressing the other  errors

**Comment by shadrackkibet** [comment]
@Wycklife did you test this?

**Comment by shadrackkibet** [comment]
@Wycklife anything to report on this based on your review above? anything to take over?

**Comment by Ivanluv** [comment]
@shadrackkibet Am currently looking at this

**Comment by shadrackkibet** [comment]
This can now be closed since we have another pull request open on the same.

**Comment by lloyddewit** [comment]
@maxwellfundi Thank you for the short chat. I understand that:
- This PR should be closed but not merged (because it's from June 2019 and replaced by PR #5795). 
- Due to a misunderstanding this PR was merged and it is no longer possible to easily reverse the merge. 
- You will ask @Ivanluv to review this PR to check that it only contains a subset of the PR #5795 changes and does not cause any side-effects.

Please let me know if I misunderstood anything.

@rdstern This PR was mistakenly merged. Please could you test the main branch to ensure that this PR and PR #5795 both work correctly after the merge, and that no regression was introduced? Thanks

**Comment by shadrackkibet** [comment]
@lloyddewit I understand why this pull request was merged automatically via #5795. This is because @Ivanluv pulled this branch and continued with it (Check #5795 commits, you should see commits here at the beginning). Since @Ivanluv  pull request contains all these changes then this is automatically merged. This is just a GitHub feature therefore, I think it should not be a problem.

**Comment by lloyddewit** [comment]
@shadrackkibet, @maxwellfundi Thank you for the explanations and short discussions. I still have a lot to learn about GitHub!

I understand from our conversation that GitHub automatically marked PR #5370 as merged when PR #5795 was merged. Github did this completely automatically without any intervention from @maxwellfundi. GitHub was able to do this automatically because it detected that all of the commits in PR #5370 are also included in PR #5795. Therefore PR #5370 is just a subset of PR #5795. So if PR #5795 is merged then PR #5370 is automatically merged also.  

@rdstern, @Ivanluv Please ignore my previous request to review/test this PR.

**Pull request merged**
