### PR TITLE
Inline documentation for RCodeStructure class family partially fixes Issue #3577

### PR DESCRIPTION
**Pull request by lloyddewit**
Added/improved comments to the RCodeStructure family of classes (RCodeStructure, RFunction, ROperator, RParameter and RSyntax). 

I only changed the comments. I also commented potential code issues that I noticed, but I did not change the code functionality in any way. 

This PR partially fixes Issue #3577. 

The XML comments can already be used by Intellisense. E.g. if the developer hovers the mouse cursor over the name of an RCodeStructure functions then summary information is now automatically displayed.

The XML comments can also be used to generate technical documentation. See PR #5735 for an example.

@volloholic This PR is ready for review. Please could we review verbally together? I'll contact you via WhatsApp, thanks.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@volloholic @dannyparsons I finished my code comments. Please could you review?

There are many changes. As stated above, I didn't change any code, so if you're short of time the changes can be safely merged with minimal review.

Feel free to ignore the 'TODO' comments. There are 2 types. 

The 'Legacy' comments were in the code already. I left them in (even if I didn't understand them) in case they were important to others.

The 'SJL' comments are things I noticed when I read the code. They are notes for if/when we ever refactor. If you'd like me to remove these comments then let me know. Thanks

**Comment by lloyddewit** [comment]
In case it's more readable, here are the same comments as a static website. To access the new comments, double-click on `_site\api\toc.html` and then select 1 of the 5 changed classes (e.g. RFunction).

[_site.zip](https://github.com/africanmathsinitiative/R-Instat/files/4492329/_site.zip)

**Comment by lloyddewit** [comment]
@dannyparsons This has been ready for review/merge for a while. This PR only changes comments. There are no functional code changes so even if you're too busy to review I think it's safe to merge. I'd appreciate a quick merge to avoid issues later. Thanks if this is possible.

**Comment by shadrackkibet** [comment]
To avoid this kind of conflicts I would suggest merging documentation changes so long as there are no functionality changes. It will be easier for us to review and critique it while using the documentation.

**Comment by lloyddewit** [comment]
@shadrackkibet I agree with you. A PR that only contains documentation changes should still be peer reviewed if possible. But if the peer review is blocked for some reason then the changes should still be merged without delay.

@maxwellfundi Please could you merge this PR? The merge conflicts are trivial. Please could you resolve the conflicts by using the comments from this PR, thank you

**Pull request merged**
