### PR TITLE
Implemented the Prepare > Column: Calculate > Transform (Rank) dialog

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
This fixes issue #6791 
@rdstern and @shadrackkibet I have added the Numeric, sort and Non- negative buttons in the Transform (Rank) dialog.
In Numeric, the scale radio button is not yet functional. Also, I have disabled the Non- negative for now. 
Am not sure of the prefix set in the save control for each function, you can suggest the Prefix to be used and any other change to be implemented.

I am yet to implement the naming to Transform dialogue.

### CODE REVIEW

**Comment by mmulahvictor** [comment]
@anastasia-mbithe I have already made the changes on the Transform(Rank) dialog in PR #6836.

**Comment by rdstern** [comment]
@anastasia-mbithe this is coming on well.
a) The sort now appears to work fine.
b) The numeric is now also working, though there are many cosmetic changes that will be useful
1) In Round you say `Round Of to:`  I suggest just `Round:`  I have chosen to keep the colon because you have to say to how many decimals.  Which you have as Digits: below.  I suggest changing Digits to Decimals for this option.
2) Also the up-down correctly has 0 as the default, but it can be a negative number.  (Then it gives to the nearest 10 or 100 etc.)
3) Significant Figures seems fine.  If you choose to keep the colon (:) in Round, then you need it here too.  I am happy with Digits as the labels> Make the default 4.  
4) Scale this is ok as a label.  No colon here, because this is complete as it is.  But you should change the name of the new variable
5) Diff doesn't work.  Have a look at what we have done in the calculator.  And notice that only works for first order differences.  So I would not bother with the second control.  Just have the Lag.  And notice that you will have to add in as many NA as you have for the value of the lag.  (Once it is working, then if you want to give 2nd order differences you just use the dialogue twice!

**Comment by rdstern** [comment]
I think that the earlier code was probably closer to "proper" sorting, i.e. when the sorted variable carries the other variables in the data frame.  This was intended for the simple sort, i.e. where just that variable is sorted.  And it is sorted (usually) into a new variable 

As you raise the point, I wonder whether we also allow both options on this dialogue?  What we have should be the default, but we could have an option perhaps Carry the Whole Data Frame.  Then there is no new variable, so it is different!  And the general sort is for multiple variables.  I was wondering whether to give information in the dialogue to this effect?

**Comment by anastasia-mbithe** [comment]
@rdstern and @shadrackkibet, the diff function works fine now. You can have a look at it.

**Comment by shadrackkibet** [comment]
We need to discuss sort as well before inviting Roger to look into it.

**Pull request merged**
