### PR TITLE
Improving wakefield keyboard in the calculator.

### LINKED ISSUE #7618: Improve the wakefield keyboard in Prepare > Calculator
When using the wakefield keyboard, when there is a data frame, the first argument for each key is always (n = length...) where length is the length of the data frame.  Currently the command is given, for example, as 

wakefield::age(n = , x = 20:35 , prob = NULL, name = "Age")

or 

wakefield::age()
if the arguments are not shown.  
I would like it to be wakefield::age(n = 36).  I suppose it could be wakefield::age(n = nrow(survey)) if that is easier to do?

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
Fixes #7618 

This changes the wakefield::age() function as requested to wakefield::age(nrow(survey))

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@anastasia-mbithe that's perfect, except it applies to most (if not all) the keys in the wakefield keyboad - not just age

**Comment by anastasia-mbithe** [comment]
I made the change to all wakefield keys apart from the coin function that does not use parameter n in the function.

**Comment by rdstern** [comment]
@anastasia-mbithe many thanks.  That's great

**Comment by rdstern** [comment]
@anastasia-mbithe I may have been asking for the impossible here.  I hope not.  It now works well, but we have lost quite a lot too.  Here is the current age key when I have ticked to give the arguments in the command.
image

That is including a lot of useful information that the user may want to change.  I was hoping we could include the n = 36, or calculate it as a formula and still provide the other arguments when they were needed?

**Comment by N-thony** [comment]
> @N-thony, yeah that's what am working on. I am adding all the parameters for all functions/buttons manually. I'll resolve the conflict as well.

Sounds good, thanks.

**Comment by anastasia-mbithe** [comment]
@N-thony and @rdstern, this is complete. Kindly have a look at it.

**Comment by N-thony** [comment]
> @N-thony and @rdstern, this is complete. Kindly have a look at it.

@anastasia-mbithe great, check my message on Skype.

**Comment by N-thony** [comment]
@rdstern please test?

**Review by rdstern — CHANGES_REQUESTED** [review]
@anastasia-mbithe that has been very impressive and all seem to work except for coin, which I assume you missed.  Once that is done I will be very happy to approve.
For reference, once this is merged I wish to report a small problem with the OK and keep option that is different to the OK and close.  And the difference becomes very evident with this dialogue, so I want to wait till it is merged.

**Review by rdstern — APPROVED** [review]
@anastasia-mbithe excellent.  Many thanks.

**Review by lloyddewit — CHANGES_REQUESTED** [review]
@anastasia-mbithe Thank you for the PR.
This PR should not include the ScintillaNet packages. The new master requires these packages to build the script window control. However, the new master also has new lines in the `.gitignore` file specifying that these files should be ignored by Git.
I suspect that Visual Studio downloaded the Scintilla files automatically; you checked out a branch that had the old `.gitignore` file and then Git assumed these new files should be part of the next commit.
There are probably several ways to fix this. The easiest is probably to make a new PR. Please could you try to make a new branch from the latest master and copy the `ucrCalculator.vb` from this branch to the new branch?
If you need any help, then please let me know. Thanks

**Comment by lloyddewit** [comment]
Replaced by PR #7904

**Pull request closed without merging**
