### PR TITLE
Fixed presentation issues in Save Controls for String Distance, Make Date and Recode Factor dialogues

### LINKED ISSUE #6372: Improve the string distance dialogue
This is a trivial change.  The save control needs to be moved over.  The Position control has messed it up a bit.

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #6372
@africanmathsinitiative/developers @rdstern @shadrackkibet This is ready for review

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Include the following as well. There might be other dialogs with this problem.
- random samples 
image
- Find/ replace (Locate option)
image

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi that's small but useful.  Could you just change the default new name on the distance dialogue to dist, rather than Dist.  
At the same time I have added another tiny issue on the Use Data dialogue.  It is also ust to change Date to date.  Perhaps you could do this at the same time.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern am done, I however can't locate the issue with the Use Date dialogue, did you mean Use date or Make date? if it is Make Date the issue seems to have been fixed already.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi sorry, yes it was Make Date.  And in Version 0.7.0 (and the current master) in the Control `Save Date`, the default name is still `Date`, rather than `date`.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern Kindly take a look again I have changed the SaveDate prefix in the Make Date dialogue from Date to date

**Review by rdstern — APPROVED** [review]
@haward - great

**Review by lloyddewit — DISMISSED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet Please could you confirm that your comments above are resolved (and you haven't since come across any similar issues in other dialogs)? If you're happy, then please could you merge? Thanks

**Comment by shadrackkibet** [comment]
> Include the following as well. There might be other dialogs with this problem.
> 
> * random samples
>   image
> * Find/ replace (Locate option)
>   image

@HawardKetoyoMsatsi I didn't see any changes on these two dialogs.

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet great let me fix the two dialogues prior to merging this PR

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet please take a look at the changes made...

**Review by shadrackkibet — APPROVED** [review]

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
