### PR TITLE
Import Dialog Refactoring

### PR DESCRIPTION
**Pull request by Patowhiz**
This PR fixes no issue.
It's meant to refactor current import dialog code. Removes redundant code, improves code clarity.

@africanmathsinitiative/developers this is ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
@Patowhiz is this a suitable place to mention the proposed improvement to this dialogue to be able to cope with different types of station?  This will then be used in the forthcoming Climsoft video.

**Comment by Patowhiz** [comment]
@lloyddewit this is still pending your review.

**Comment by lloyddewit** [comment]
@shadrackkibet please could you review, thanks

**Comment by shadrackkibet** [comment]
@Patowhiz is this ready for review now? I see more changes after @lloyddewit request for review.

**Comment by lloyddewit** [comment]
@shadrackkibet I just spoke with @Patowhiz. He confirmed that this PR is ready for your review.

**Comment by lloyddewit** [comment]
@Patowhiz Sorry that this got PR held up at the review stage. I asked @shadrackkibet to review but he's currently sick. In the meantime some merge conflicts have appeared. There may also be overlap with PR #6145 and PR #6222.

If you resolve the merge conflicts (or make a new PR), then I'll review this PR directly myself as a top priority.
Thanks

**Comment by rdstern** [comment]
@Patowhiz I was able to go into this branch.  I assume that means there are no merge conflicts now?  So this can be reviewed?

**Comment by Patowhiz** [comment]
@rdstern this PR still has conflicts. And will still have more conflicts when importing from multiple files is done.

**Comment by rdstern** [comment]
@Patowhiz so you are saying we should wait with this until the other improvements are done and merged?

**Comment by Patowhiz** [comment]
@rdstern yes. After which I will have to do the refactoring again because different developers have already worked in this dialog

**Comment by lloyddewit** [comment]
@Patowhiz I understand that this was on hold, waiting for a number of other PRs to be merged. The PRs mentioned above are all merged. Is it a good time to try and close this PR? Or are there currently other dependencies or priorities?
thanks

**Comment by Patowhiz** [comment]
I'll open another pr that addresses the same

**Comment by Patowhiz** [comment]
This PR has now been replaced by PR #6625

**Pull request closed without merging**
