### PR TITLE
Homogenization using multiple stations 

### PR DESCRIPTION
**Pull request by shadrackkibet**
@rdstern I am putting up this for testing particularly the results and if it works well with multiple stations. I have added the station receiver into this dialog but now disabled some functionalities (saving, plotting and summary) which are not yet working for multiple stations. That is coming soon!

### CODE REVIEW

**Comment by lloyddewit** [comment]
@shadrackkibet is this PR ready for review? thanks

**Comment by lloyddewit** [comment]
@shadrackkibet is this PR ready for review? thanks

**Comment by shadrackkibet** [comment]
I am yet to find a way to annotate graphs and the output from `summary()` function for multiple stations. Once that is done this will be ready for review.

**Comment by lloyddewit** [comment]
@shadrackkibet Undersood. Thanks for the feedback.

**Comment by lloyddewit** [comment]
@shadrackkibet is the status still the same as 25 Oct (i.e. ongoing)? thanks

**Comment by shadrackkibet** [comment]
Homogenization for multiple stations at a time is already working. The only challenge which I am yet to solve is on annotating graphs with a specific station name so that the user can easily identify it on the output window. The only way I can think of solving this is by writing a custom  R function with a loop. I wish to discuss first with @dannyparsons before I proceed.

**Review by rdstern — APPROVED** [review]
Lots to improve in the future in this area.  But good to get this merged as it stands

**Comment by lloyddewit** [comment]
@Ivanluv please could you review? thanks

**Comment by Ivanluv** [comment]
@lloyddewit  the code looks good from my end

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
