### PR TITLE
Rewrting Sdgcanonical

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@shadrackkibet  how is this going?

**Comment by shadrackkibet** [comment]
This is has one issue with ucrsave.  I am yet to solve that then it will be ready for review.

**Comment by maxwellfundi** [comment]
Do you need help to get fixed?

**Comment by shadrackkibet** [comment]
yes, i am happy if you can help me fix this.

**Comment by shadrackkibet** [comment]
This has an issue with pushing more comits . I have to close this and open another pullrequest.

**Pull request closed without merging**
