### PR TITLE
Combined the last dialog and last 10 dialogs tool bars into one

### LINKED ISSUE #7431: Combining the Open last dialogue button from the Toolstrip bar
In the toolstrip bar we have two buttons that simplify the opening of the dialogues, the first one open directly the recent dialogue opened and the second has a small arrow which gives the lit of the top 10 recent dialogue opened. 
Now, we would like to combining the two button functionalities to one. We will get rid of the first button that only reopen the recent dialogue and then add it implementation to the second button containing the arrow.
When button is clicked it will just reopen the recent dialogue opened but when we click on the arrow it shows the list of 10 recent dialogues opened as it does now.
image

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes #7431 
Combining the last dialog button to the last ten dialog button. 
@Patowhiz and i removed the `start and end ``separator` for the code and would like to ask @rdstern if the `start and end ``separator` should be shown in the list just to make sure its Documented.

### CODE REVIEW

**Comment by derekagorhom** [comment]
@Patowhiz here is the PR

**Comment by Patowhiz** [comment]
@rdstern I have circled the 2 separator lines that @derekagorhom and I are asking about in the screenshot below.

165923810-aa34a73a-e613-4d5d-8355-1bd80c80e067

**Comment by Patowhiz** [comment]
@rdstern will be very useful if you could review this PR for our next week's workshop. Thanks.

**Comment by Patowhiz** [comment]
@lloyddewit @rdstern @N-thony if this PR can be reviewed and merged, it would be very useful for our next workshop. We usually find it confusing to the users to have to use the 2 buttons instead of just 1.

**Review by rdstern — CHANGES_REQUESTED** [review]
This works fine now and is a good simplification.
But it currently now has the tooltip "View Last Graph" It could say `View/Edit Last Dialogue`.
While correcting that I notice the 2 preceding buttons also say View Last Graph!  (That's also in the released version!)  Change them (back?) to Copy and Paste.

**Comment by derekagorhom** [comment]
Hello @rdstern please i have made the changes, can you test them again

**Comment by Patowhiz** [comment]
@derekagorhom you may have to resolve the conflicts then @rdstern you may have to retest and approve before more conflicts. This PR has changes in  `frmMain` designer and code files.

Thanks.

**Comment by derekagorhom** [comment]
> @derekagorhom you may have to resolve the conflicts then @rdstern you may have to retest and approve before more conflicts. This PR has changes in `frmMain` designer and code files.
> 
> Thanks.

Done

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
