### PR TITLE
Minor changes to the Insert Column/Rows dialog

### LINKED ISSUE #8262: Minor Changes to Insert Column/Rows
Hello @lloyddewit and @Patowhiz, 

Please could you change (or ask someone to change) the text on here to say "Value:" (Instead of "Default Value:") and "Column(s) Name/Prefix:" (Instead of Prefix for Inserted Column(s):).

I am sending this to you, because - although this is pretty trivial - I assume labels must be changed carefully, because of the implications for different languages.  I could make these changes myself, if I knew more about this complication.

Thank you, 

Rachel

### PR DESCRIPTION
**Pull request by anastasia-mbithe**
This fixes #8262
 @rdstern I hope the changes will reflect in this branch.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@anastasia-mbithe I generated the current translation database automatically and if there are manual fixes needed, then I need to correct the process. Therefore, please could you provide a screen dump of the rows you changed. 
Thanks

**Comment by anastasia-mbithe** [comment]
> @anastasia-mbithe I generated the current translation database automatically and if there are manual fixes needed, then I need to correct the process. Therefore, please could you provide a screen dump of the rows you changed. Thanks

@lloyddewit , I made filter for dlgInsertColumn then changed rows 18 and 19. I have attached a screenshot, I hope it helps.
image

**Review by rdstern — APPROVED** [review]
Looks fine now.  Back to you @lloyddewit

**Review by lloyddewit — APPROVED** [review]
@anastasia-mbithe thanks, looks good

**Pull request merged**
