### PR TITLE
Add label options to the Mapping dialog

### PR DESCRIPTION
**Pull request by MeSophie**
Fixes partially #7695 

@rdstern I corrected the error on label maping Dialog.

For the Label and Legend option can we add a check box Add Legend and Add Label? And please more information about the filter part will be very helpful. Thank you.

### CODE REVIEW

**Comment by rdstern** [comment]
@MeSophie I can now edit the labels, as you say.
But - oddly I can't change their size (or I think colour either).

**Comment by MeSophie** [comment]
@rdstern I'm done with improvements. Please can you check.
`max.overlaps = Inf` is working well I try it with this code in r.

**- Without** `max.overlaps = Inf`

image



**- With** `max.overlaps = Inf`

image

**Review by rdstern — CHANGES_REQUESTED** [review]
@MeSophie this is exciting. And looking great. 
a) Change the Label Rectangle to Text and have it unchecked by default.  It also doesn't remember the setting, so make it do that.
b) Have a checkbox, default unchecked for the Size option - as it is in the sub-dialogue.  When checked make the default 5, (as for the nlabel and text geoms, in both the dialogue and the sub-dialogue.)
c) The Label All doesn't remember the previous setting.  Make it do this.
d) The R-text calls the geom_label_repel twice.  I think that may be resulting in the text option not working (ot always gives a label).  And the size doesn't seem to work, from the main dialogue.  It does work from the sub-dialogue.
e) Could you move the box up so it starts just below the data selector.  That will give space for a 4th checkbox, with a copy of the Colour option from the sub-dialogue!

**Review by rdstern — CHANGES_REQUESTED** [review]
@MeSophie This is looking excellent now.
There are just some option settings to tweal a bit and then you are through!
a) The default is correctly with the Text unchecked, and therefore it should be a label - so with the box round the names.  Currently the default (when it is unchecked) is now Text.  I would like the user to have to check to get the text.
b) Then sometimes the Colour and size reset to their default of Black and 5.  And sometimes they remember the previous setting.  I think they may remember for text and not for label, but I am not sure?

**Comment by MeSophie** [comment]
@rdstern Please can you check the new changes? Thank you.

**Review by rdstern — APPROVED** [review]
@MeSophie very nice now.  Many thanks.  I hope @lloyddewit will like the code.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
