### PR TITLE
Import From Climsoft wizard menu

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes partly #4915

This PR adds a menu item to the Climate menu. The menu item gives access to the import from climsoft wizard dialog. The dialog  functionality has been added in PR #5694. 

@africanmathsinitiative/developers this is ready for review.
@lloyddewit only 3 lines of code was added in this PR, the rest are designer changes as discussed with @rdstern .

### CODE REVIEW

**Comment by Patowhiz** [comment]
Screenshot of menu changes

import climsoft menu

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern the code changes are small so I approved them (no developer review needed). Please could you test? thanks

**Review by rdstern — APPROVED** [review]

**Comment by mhabimana** [comment]
@Patowhiz : I can see some small issues of labeling under the "import from Climsoft Wizard " in the released R-Instat V0.2.7(see below) dialog:
image

**Comment by Patowhiz** [comment]
@mhabimana thanks for mentioning this.
@Gioche6 can you have a look at this? You can have the PR directed to this comment. Thanks.

**Pull request merged**
