### PR TITLE
Added Rhelp To  Model Menu Dialogues

### LINKED ISSUE #8160: Improve the calls to R help
@derekagorhom I think this one has your name on it.
a) The R-help on the Model > Use Model > Use Model keyboard dialogue doesn't work well.
Could you label the help button as `R Help` as you have done in the calculator, and also make it the same drop-down control.
Then for General the packages are stats and car, with the stats first and default.
For Prediction it is prediction
For extRemes it is just extRemes (and thisa is working now.
For segmented it is segmented.
b) For Model > Fit Model > Hypothesis Tests and Fit Model, label as R-Help with new control agaIn.  I think they all work here, and each goes to a single package.
c) Add an R Help key below the extended keyboard in the Prepare > Column: Numeric > Enter dialogue, below the extended keyboard, on the right.  It goes to just the base package.

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes #8160 
I have added the `Rhelp` `dropdown` to the `Use Model keyboard`, `Hypothesis Tests`, `Fit Model` and `Prepare > Column: Numeric > Enter dialogue`. 

@rdstern this PR is ready for review.

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@derekagorhom well done, and a veryu clear message too about the changes you made.  That makes the testing very easy.  You are advancing well.
Just one small change - the stats1 and stats2 in the pull-down should just be called `stats`.  They correctly call the right package, it is just the label that is wrong.

And please check, once the change by @N-thony is merged, that these options each go to the maximised window, and not to the browser.  I hope you won't then have a conflict to resolve.

**Comment by derekagorhom** [comment]
I changed the name of the dropdowns for the Rhelp in `stats1` and `stats2` to just `stats`

**Review by rdstern — DISMISSED** [review]
Looks good.
I assume it will be merged after #8159 .  Should then check that there are no conflicts and that those changes apply.  If not - not serious, but sending it to the output window, rather than the browser may have to be done again - perhaps in March release.

**Comment by lloyddewit** [comment]
@derekagorhom I'm afraid that some merge conflicts have apeared, probably triggered by the merge of PR #8159 .
If you can resolve the conflicts, then I can review.
thanks

**Comment by rdstern** [comment]
@derekagorhom just reporting I am still getting build errors.  These were expected from @N-thony work on the same dialogues.  I hope you will be able to resolve them and also check that this help now goes to the output window and not to the browser.  Thanks

**Comment by derekagorhom** [comment]
@rdstern PR #8181 will replace this PR

**Comment by lloyddewit** [comment]
replaced by PR #8181

**Pull request closed without merging**
