### PR TITLE
Corrected consecutive wet days calculation on rainfall quality control

### PR DESCRIPTION
**Pull request by shadrackkibet**
@rdstern this fixes the problem with the calculation of consecutive wet days when there are missing values in the data as reported in #6115. Please check if this works as expected. I will fix the second problem i.e detection of dry months in another PR.

Notes.
- Corrected consecutive wet days calculation.
- Code refactor.
-  Allowing change of threshold of values to ignore when calculating same values

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@shadrackkibet great - it works for the same example that I used in a video that went wrong before.  I would very much like this to be included in the next version.

**Comment by shadrackkibet** [comment]
@rdstern I have implemented the third point (allowing change of threshold for the same option) you requested here. Please check again.

**Review by rdstern — APPROVED** [review]
@shadrackkibet - great

**Comment by shadrackkibet** [comment]
I would like to get this merged soon so that I can fix the second problem i.e Dry months calculation. I will be very happy if this is reviewed and merged ASAP.

**Review by dannyparsons — APPROVED** [review]
Looks good, I have a suggestion for the dialog but as an improvement further to this so will comment on the related issue.

**Comment by shadrackkibet** [comment]
@dannyparsons thanks for the merging this. I am now going to fix the second problem.

**Pull request merged**
