### PR TITLE
Added Scale/Distance & Random Split dialogs to the database

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes Partly #7749 
@lloyddewit , @N-thony , this PR adds Scale/Distance dialog and Random split dialog to the database

### CODE REVIEW

**Comment by Vitalis95** [comment]
Here are the screenshots of the changes.

image

image

image

image

image

**Comment by Vitalis95** [comment]
@MeSophie , I have changed the label in the database to `Save As:` to be consistent with the label in the designer

image

**Review by N-thony — DISMISSED** [review]
@lloyddewit over to you

**Comment by lloyddewit** [comment]
@Vitalis95 Thank you for the updates.
Please see my comment in issue #7749. I think all of these should be resolved when PR #7908 and PR #7927 are merged, apart from:
- Number of Preview Rows:
- Scale/Distance
- Selected Variables
- New Data Frame Name:

Please could you investigate whether these strings also need to be added to the database?
If you need any help, then please let me know.
Thanks

**Comment by N-thony** [comment]
> @Vitalis95 Thank you for the updates. Please see my comment in issue #7749. I think all of these should be resolved when PR #7908 and PR #7927 are merged, apart from:
> 
> * Number of Preview Rows:
> * Scale/Distance
> * Selected Variables
> * New Data Frame Name:
> 
> Please could you investigate whether these strings also need to be added to the database? If you need any help, then please let me know. Thanks

@Vitalis95 this PR contains database changes, it will be good to make the changes requested if possible quickly to avoid conflicts which will lead you to create another PR.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@Vitalis95 Thank you all the well-documented changes. I'm happy to merge. 
When PR #7908 is also merged, then we can retest issue #7749 and identify any remaining missing translations.

**Pull request merged**
