### PR TITLE
One wayfreq

### PR DESCRIPTION
**Pull request by stevenndungu**
Fixed a bug of doing frequency tables for character columns using sjtab

### CODE REVIEW

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers this is ready for review

**Comment by shadrackkibet** [comment]
I am going to review this.

**Comment by shadrackkibet** [comment]
I have tested this and it is working fine.It is now ready for @dannyparsons

**Comment by lilyclements** [comment]
I wish to make minor changes to this dialog before @dannyparsons reviews if that's okay!

**Comment by lilyclements** [comment]
@dannyparsons this is ready to review!
@shadrackkibet Apologies, I thought this was a different branch - I didn't realise it was a minor fix.

**Pull request merged**
