### PR TITLE
Added peaks and valleys to line plot

### LINKED ISSUE #5037: Using broom and adding text to graphs
**Is your feature request related to a problem? Please describe.**
I have wanted to be able to add results to graphs for a long time, e.g. the correlation coefficient to our scatter-plots or the regression equation when using a line plot and adding the fitted line.

From stack-overflow this was a somewhat tricky problem in the past.  Now there seems to be an excellent solution.  And I suggest it fits very well with our ideas in R-Instat.

**Describe the solution you'd like**into graphs warrants 
The **broom** package is important for us in general I think, i.e. for the modelling menu.  It is part of adding the tidy ideas also to modelling.  There are essentially just 3 functions, namely augment, glimpse and tidy and they can be used on many, many models.  They operate on all these model objects - could even be interesting for Prepare > R Objects > View!

The tidy results from broom are then used by **ggpmisc** which shows how far this type of solution can go.  Examples are [here](https://cran.r-project.org/web/packages/ggpmisc/vignettes/user-guide.html). 

We may also want to include ggpubr for the stat_cor and stat_regline_equation.  They may be much simpler to include with the current ggplot system in R-Instat.  And we may want different options for this?  However, it is possible that adding text/labels/tables to graphs warrants a more detailed discussion on the possible structure.  How can we make it simple!

### PR DESCRIPTION
**Pull request by Ogik99**
fixes #5037 
@maxwellfundi kindly review.

### CODE REVIEW

**Comment by Muthenya** [comment]
@maxwellfundi were you able to review this?

**Comment by dannyparsons** [comment]
I suggest @Ivanluv reviews this since Maxwell is now away.

**Comment by Ivanluv** [comment]
From my review everything is working correctly

**Comment by Ogik99** [comment]
@maxwellfundi kindly review

**Comment by maxwellfundi** [comment]
@Ogik99 I have had a look at this earlier and looks good. However there are some conflicts here with something that has been merged before. Please update your master, create a new branch and copy paste the changes there.

**Comment by Ogik99** [comment]
> @Ogik99 I have had a look at this earlier and looks good. However there are some conflicts here with something that has been merged before. Please update your master, create a new branch and copy paste the changes there.

Please see issue #5335.

**Pull request closed without merging**
