### PR TITLE
Hypothesis Tests calculator

### PR DESCRIPTION
**Pull request by shadrackkibet**
In progress!

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is ready for review.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers ?

**Comment by Patowhiz** [comment]
Testing this

**Comment by Patowhiz** [comment]
The changes fixed work fine on my side. Though shouldn't the Show Arguments checkbox  toggle between showing the arguments and removing them of the already shown test? Currently I have to click on the button that calls test function again. 
@dannyparsons this is ready for you.

**Comment by dannyparsons** [comment]
That would be a nice feature but it only applies to future functions. I think changing "Show" to "Include" or something may avoid some confusion.

**Comment by shadrackkibet** [comment]
can someone test this?

**Comment by shadrackkibet** [comment]
@Muthenya  did you finish testing this?

**Pull request merged**
