### PR TITLE
Adding controls to dlgPolarAnnulus

### LINKED ISSUE #5966: More circular plots from openair package
There are 6 more circular plots provided by the Openair package.
Percentile Rose
Frequency Rose
Polar Plot
Polar Cluster
Polar Annulus
Polar Frequency
These may become 6 dialogues or (say) 2 dialogues with 3 radio buttons in each or...?  From a quick look I fail to see the connections that would help in structuring the dialogues.  Once decided they should be easy to construct and code, because they have similar options to the Wind/Pollution Rose function.

This is work initially for @HawardKetoyoMsatsi with @Wycklife probably doing the coding then.

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #5966
Added controls to dlgPolarAnnulus and implemented R code.
@africanmathsinitiative/developers, this is ready for review.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review? thanks

**Comment by Wycklife** [comment]
@HawardKetoyoMsatsi The pollutant checkbox is checked, but when you return to the dialog it's unchecked.

I have selected a single variable, when I check on the multiple pollutant check the variable on the single receiver still appears on the multiple receiver.

**Comment by lloyddewit** [comment]
@Ivanluv Please could you review? thanks

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit , I would like @Ivanluv to hold on a little bit a suggestion was made for the functions of this dialog to be included in the one dialog together with four other dialogs created earlier, once the change is made then it can be reviewed.

**Comment by HawardKetoyoMsatsi** [comment]
I am closing this so that I can reimplement and open it in another PR

**Pull request closed without merging**
