### PR TITLE
Changed the Summary Table Percentages multiple factor to a single factor in Describe > Specific Tables/Graphs > Summary Tables Dialog

### PR DESCRIPTION
**Pull request by Ivanluv**
> c) It would be simpler perhaps if (at least from the dialogue) we only allowed a single factor as the basis for the percentages. I suggest it will be rare that want more. If so, then we could perhaps instruct on how the script would change, rather than trying to be too general in the dialogue.

This fixes part c) of issue #7621

### CODE REVIEW

**Review by lloyddewit — DISMISSED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge, thanks

**Review by rdstern — CHANGES_REQUESTED** [review]
@Ivanluv it works fine.  Just some cosmetic changes.
a) It says `Factors as percentage`  Of course now there is a single factor only.  Change the header to `Of Factor (Optional)`
b) While changing that, could you also change the dialogue header to `Frequency/Summary Tables`  (There used to be 2 dialogues and you have adapted the Summary one.)
c) Ideally the menu item would also change?

**Comment by Ivanluv** [comment]
> a) A simple change is that the menu item should now say Frequency/Summary Table - not just Summary Table. And the title at the top of the dialogue should also say Frequency/Summary Table.

Changing this menu item name in the translations  causes conflicts from my end. @vitalis could you kindly make this change

**Comment by Vitalis95** [comment]
> > a) A simple change is that the menu item should now say Frequency/Summary Table - not just Summary Table. And the title at the top of the dialogue should also say Frequency/Summary Table.
> 
> Changing this menu item name in the translations causes conflicts from my end. @vitalis could you kindly make this change

@Ivanluv , I will do it

**Comment by lloyddewit** [comment]
> > > a) A simple change is that the menu item should now say Frequency/Summary Table - not just Summary Table. And the title at the top of the dialogue should also say Frequency/Summary Table.
> > 
> > 
> > Changing this menu item name in the translations causes conflicts from my end. @vitalis could you kindly make this change
> 
> @Ivanluv , I will do it

done in PR #7716

**Comment by lloyddewit** [comment]
@Ivanluv Thank you for the updates. If you change the translations database, please could you normally provide screenshots of what you changed (there's no diff for binary files)?
Was it just the change of title now done in PR #7716 or were there additional database changes?
I suggest that you remove the database file from this PR (let me know if you're not sure how) and then we can merge.
There's frequent changes to the database this week, so to avoid conflicts, it's probably easiest just to tell me what you want changed, and I'll implement in a separate PR.
Thanks

**Comment by Ivanluv** [comment]
@lloyddewit I don't know how to remove the database file changes, you could help me with that

**Comment by lloyddewit** [comment]
> @lloyddewit I don't know how to remove the database file changes, you could help me with that

@N-thony Please see instructions [here](https://github.com/africanmathsinitiative/R-Instat/wiki/GitHub-notes). If you have problems, then let me know.
Thanks

**Comment by Ivanluv** [comment]
@lloyddewit could you look at this

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@rdstern if you can test/approve, then we can merge, thanks

**Review by rdstern — APPROVED** [review]

**Pull request merged**
