### PR TITLE
Weighted Summaries Rcode.

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by shadrackkibet** [comment]
Weighted summaries have been implemented for the following summaries:
**Mean,Standard deviation, Variance, Median, Quantiles, Skewness, Kurtosis, Coefficient of Variation, Median Absolute deviation,Correlation and Covariance.**

From my quick check on google haven't found functions to implement for the following functions. 
**Minimum, Maximum, n_distinct, Percentiles, Proportions, counts, Trimmed mean, Qn , Sn, mc, first, last, nth and standard error of mean.**

In discussion with @volloholic  he claims that he can implement this in many ways but he needs to discuss this with @rdstern first before we do it.

**Comment by maxwellfundi** [comment]
@shadrackkibet  how is this getting on?

**Comment by shadrackkibet** [comment]
There is still more to be done here. This will not be ready for .23

**Comment by Muthenya** [comment]
There is another conflict here @maxwellfundi.

**Comment by dannyparsons** [comment]
This may need to be checked carefully and copied into a new branch. @maxwellfundi can you have a look at this?

**Comment by shadrackkibet** [comment]
@dannyparsons @rdstern we need to discuss this again. Is this still a priority?

**Comment by dannyparsons** [comment]
Not sure how much of a priority but would be very nice to have.
It would be good to get the R code in place even if we don't change dialogs yet.
I see you looked into packages before as well. If they're common packages we're using already then good to use it but we should avoid adding a package for a single function if we can.

**Comment by shadrackkibet** [comment]
Moved this here #5683

**Pull request closed without merging**
