### PR TITLE
Enabling dlgPolarCluster

### LINKED ISSUE #5966: More circular plots from openair package
There are 6 more circular plots provided by the Openair package.
Percentile Rose
Frequency Rose
Polar Plot
Polar Cluster
Polar Annulus
Polar Frequency
These may become 6 dialogues or (say) 2 dialogues with 3 radio buttons in each or...?  From a quick look I fail to see the connections that would help in structuring the dialogues.  Once decided they should be easy to construct and code, because they have similar options to the Wind/Pollution Rose function.

This is work initially for @HawardKetoyoMsatsi with @Wycklife probably doing the coding then.

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Fixes #5966
Enabled dlgPolarCluster so that I could go ahead with code implementation.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi is this ready for review or are you still working on it? thanks

**Comment by HawardKetoyoMsatsi** [comment]
Yes it is ready for review.

**Comment by shadrackkibet** [comment]
@HawardKetoyoMsatsi since you are editing frmmain here, could you also add ellipsis i.e `...` into Three variables Frequencies.

image

**Comment by shadrackkibet** [comment]
Also, Prepare>Check Data> Visualise Data

image

**Comment by shadrackkibet** [comment]
Also 
**Tools > Install R package...
Help > R packages and commands...**

image
image

**Comment by HawardKetoyoMsatsi** [comment]
@shadrackkibet I am done fixing issues related to this pull request.

**Comment by HawardKetoyoMsatsi** [comment]
I enabled four more dialogs which needs to be merged quickly to allow further code implementation.
Enabled dlgPolarAnnulus
Enabled dlgPolarPlot
Enabled dlgPercentileRose
Enabled dlgPolarFrequecy

**Comment by shadrackkibet** [comment]
Looks good. Over to @lloyddewit and @rdstern to review.

**Review by rdstern — APPROVED** [review]
This is still blank - fine.

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
