### PR TITLE
Dlg unstack fix

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready to review.
fixing #3775 and also sorted updating changes for dlgUnstack

### CODE REVIEW

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is still waiting for review

**Comment by shadrackkibet** [comment]
Reviewing this now.

**Comment by shadrackkibet** [comment]
You should change the selector header on different receivers otherwise this is ready for @dannyparsons

**Comment by lilyclements** [comment]
Good point! Sorted that now.

**Comment by shadrackkibet** [comment]
fixes #3775. @dannyparsons this is ready for you.

**Comment by lilyclements** [comment]
@dannyparsons i've fixed this set assign to problem we discussed

**Pull request merged**
