### PR TITLE
Rainfall Quality Control at Month level- Checking of dry month

### LINKED ISSUE #4607: Rainfall quality control at month level
In the **Climatic > Check Data > Rainfall QC** dialogue the one item that hasn't been implemented is the check that the total rainfall for the month is totally zero.  (This is important, because sometimes it may really be zero for the whole month, or it could be that the data were missing and mistakenly replaced by zero.  Excel makes that sort of thing easy!)

I suggest a simple way this could be implemented on the dialogue.  The item is already there as Dry Month. 
 It has < with a numeric field having a default of 0.05mm.  Then a button with Omit Months.  Or it is a control on the main dialogue.  But it opens a control like the filter, when there is a factor and you can tick, which months to omit.

These are the months when having totally zero isn't a surprise.  For example, in Niger stations that would be November to April. 

Now the calculation.  My breakthrough in thinking is that this would be easy if it gives the results in a monthly data frame, rather than the daily data of the other QC checks.  So that first.

There is the filter if the Omit months is there.  Then the monthly rainfall summary, giving the total and then a filter on that monthly data frame to just show the months with zero total.

Of course this is a different data frame to the other QC checks.  I don't see that as a problem.  Indeed I now see this as an opportunity, because the paper records are usually also at a monthly level.

So, as a further step I wonder (perhaps later) whether the other QC checks might have an option to also output summary results to the monthly data frame.  They might be the sum of the logical columns (at the daily level), which would therefore give the number of times that check has failed in the month.  That could be really useful in the checking process back to the paper records - and even more useful if we could sometimes have images of the paper records linked to our data.

### PR DESCRIPTION
**Pull request by shadrackkibet**
In progress Fixes #4607

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@rdstern Here is a screenshot of this option. What are your views in this?

image

**Comment by dannyparsons** [comment]
It's a bit confusing that the button is **Omit Months** and the sub dialog is **Months to select** (the opposite). Maybe the button could be **Choose Months**?

**Comment by shadrackkibet** [comment]
The point is that we need to select months to omit from the filter. So i suggest the label to be **Select Month(s) to Omit** for the subdialog.

**Comment by rdstern** [comment]
Instead of Select Level could it be Omit Level?  The default for the Missing Value (not Values) Threshold should be 0.05 and the after the field it could say mm.  (Is that the value of the monthly total, or for any day?)  Can we make it so any positive number can be typed there?

**Comment by shadrackkibet** [comment]
I think i misunderstood what this is meant for, i thought this is the sum of missing values in a month so Threshold will be something like 5.

 So, this is to check that the amount( Preferably Monthly total) is less than 0.05.
 If this is what you want then i can change this and also change this to an input so that you can easily type in any +ve value.

**Comment by rdstern** [comment]
That's right.  It is the idea that if the total is really zero, then perhaps the month should be recorded as missing.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers  this is now ready for review.

**Comment by shadrackkibet** [comment]
@dannyparsons  i suggest you merge this for @rdstern to test.

**Pull request merged**
