### PR TITLE
Fixed minor bug in Climatic>Tidy and Examine>Data daily Dialog

### PR DESCRIPTION
**Pull request by EstherNjeriLiberatta**
Fixes (partially) #7279 
@rdstern Fixed item (a.)  It is now possible to add a comment without changing a day/more and test ok will be enabled.

### CODE REVIEW

**Review by lloyddewit — DISMISSED** [review]

**Comment by rdstern** [comment]
It seemed to allow ok, but then gave the error below:
image

**Comment by N-thony** [comment]
> 

@rdstern I think this need to be solved on the R side, the `add_new_comment` function is executed inside `save_data_entry_data` function where they are some check that doesn't the functions to execute if there is nothing changed, I think @dannyparsons is the right person to advice on this.

**Comment by EstherNjeriLiberatta** [comment]
@lilyclements I'll give you a call on skype.

**Comment by N-thony** [comment]
@EstherNjeriLiberatta any progress?

**Comment by EstherNjeriLiberatta** [comment]
@N-thony Thanks for checking, but I'm still waiting for @lilyclements response to the last comment you made.

**Comment by lilyclements** [comment]
> @lilyclements we still need the `data changed` i.e `new_data` to pass this check on line 4287. What do you think? image

@N-thony I don't think I follow. Can you explain the problem here, and why we need the `new_data` to pass this check? Thanks.

**Comment by N-thony** [comment]
> > @lilyclements we still need the `data changed` i.e `new_data` to pass this check on line 4287. What do you think? image
> 
> @N-thony I don't think I follow. Can you explain the problem here, and why we need the `new_data` to pass this check? Thanks.

@lilyclements could we have a quick call?

**Comment by N-thony** [comment]
> @EstherNjeriLiberatta to sort this, you need to read in the `rows_changed` parameter (as well as the `row` option in the `comments_list`) and take the value of the row that has a comment associated with it.

@lilyclements looking at the code and trying to implement your idea, I find a difficulty that is when we only add a comment from where we read the `row` to pass it to `row_changed` it is fine but there is this check on line `4287` when the data change but in our case we didn't change the data, only added the comment.

**Comment by N-thony** [comment]
> @N-thony @EstherNjeriLiberatta I suggest we have a call together and talk this through

@lilyclements let have a call.

**Comment by EstherNjeriLiberatta** [comment]
@lilyclements @N-thony Thanks for your input the dialogue works okay now. 
@africanmathsinitiative/developers This is ready for review.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony Please could you test/approve? thanks

**Review by N-thony — APPROVED** [review]
Good, @rdstern could you test too? thanks

**Review by rdstern — APPROVED** [review]
@EstherNjeriLiberatta that's great.  I should have checked this earleir, because we could have used the feature on the Rwanda workshop this week.

**Pull request merged**
