### PR TITLE
Adding Coordflip to the sdgplots

### LINKED ISSUE #4251: How do I do coord_flip?
This may be a silly question, but I couldn't find it.

I can do coord_flip on some of the graphs, because it is on the main dialogue.  

I don't mind that it is missing on some, (e.g. Line Plots, Scatterplots)  because they have enough on the main dialogue.  And I haven't yet missed it for those graphs - but where is it?

I assumed it might be on the Coordinates Tab, but there is nothing there.  If I am right, then could it go there? The only complication would be that it should automatically be the same as on the main dialogue, for those plots that now have it in 2 places.

I can now do it, by editing the command in the script window.  Great we have this at last.  But there should be an easier way for this feature.

### PR DESCRIPTION
**Pull request by maxwellfundi**
@africanmathsinitiative/developers  this is ready for review. 

I have moved the horizontal plot check boxes from main dialog to the sdgplots under coordinates tab. So to test this, run any graphics dialog and check how it works. 

Fixes #4251

### CODE REVIEW

**Comment by dannyparsons** [comment]
I don't think we want to remove it from the main dialogs that we already have it on, but just add it to the subdialog so any graph can do this.

**Comment by maxwellfundi** [comment]
Okay.

**Comment by shadrackkibet** [comment]
Testing and reviewing this now.

**Comment by maxwellfundi** [comment]
This actually needs to be redone @shadrackkibet  because there is a commit that i removed the coordflips for main dialogs that we need to keep.

**Comment by shadrackkibet** [comment]
This is working fine. One point to note ` theme_grey() ` has no package name.

**Comment by maxwellfundi** [comment]
@shadrackkibet  thanks for your review. I think that must have been an ommision. will add that too.

**Comment by maxwellfundi** [comment]
Will open a new one with coord flips only on the sdgplots.

**Comment by maxwellfundi** [comment]
Opening a new pull request on this

**Pull request closed without merging**
