### PR TITLE
Allow R script key words to be used in Log/Script window

### LINKED ISSUE #8308: Example code that fails in script
@lloyddewit First you install the climaemet package - easily done with the tools > install dialogue.

Then one example in this package is as follows: (I added the second library line, otherwise it is copied from the manual.)

```
library(ggplot2)
library(climaemet)
wl <- ggclimat_walter_lieth(
climaemet::climaemet_9434_climatogram,
alt = "249",
per = "1981-2010",
est = "Zaragoza Airport"
)
wl
# As it is a ggplot object we can modify it
wl + theme(
plot.background = element_rect(fill = "grey80"),
panel.background = element_rect(fill = "grey70"),
axis.text.y.left = element_text(
colour = "black",
face = "italic"
),
axis.text.y.right = element_text(
colour = "black",
face = "bold"
)
)
```
If you try the first half, doen to wl, it should give a graph.  But it says comma (,) is an unknown symbol.

If I put them on one line, so:

```
library(ggplot2)
library(climaemet)
wl <- ggclimat_walter_lieth(climaemet::climaemet_9434_climatogram,alt = "249",per = "1981-2010",est = "Zaragoza Airport")

wl
```
Now it runs fine.

Same with the second half, so 

```
# As it is a ggplot object we can modify it
wl + theme(plot.background = element_rect(fill = "grey80"),panel.background = element_rect(fill = "grey70"),axis.text.y.left = element_text(colour = "black",face = "italic"),axis.text.y.right = element_text(colour= "black",face = "bold"))

```
runs fine

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes part a of #8285 
Fixes #8308

### CODE REVIEW

**Comment by lloyddewit** [comment]
@rdstern This PR fixes the specific script window problems described in issue #8285. Please could you test?
Thanks

**Review by rdstern — COMMENTED** [review]
@lloyddewit all I did was to try the 2 examples from Wezzie.
Great - that they both work.  Are there more features to add or is this now getting to running most things?  

But there is a curious extra feature in the way the scripts and presented in the window. It doesn't seem to have anything to do with running the code:

image

**Comment by lloyddewit** [comment]
@rdstern The strange display is just because the example code in the issue is incorrectly formatted (it starts in the middle of the screen and has lots of whitespace preceeding each line). The RScript window shows vertical lines to help align indents. This is intentional and looks OK with normal code.

**Comment by lloyddewit** [comment]
@rdstern This PR should now also fix issue #8308, please could you test?

**Review by rdstern — APPROVED** [review]
@lloyddewit it is so nice that this is now working easily:

image

This example is also "for real".  It is a recent climatic package, produced by the Spanish Met Service.  I am not so enthusiastic about the display that I would yet want to produce a dialog.  But it is so nice that I don't have to.  For a user who is keen on this type of graph, and is willing to use the script window, they can now modify this code for their own station.

One reason for not doing the dialog is that (from memory) the required shape of the data is very odd, at least compared to our recommended shape.  However, I am happy to fit in with their graph, a user could reshape the data interactively and then use this code to get the graph. 

I would be happy to merge now and then to wait for the rest as another pull request?  Or you may wish to continue?

There doesn't seem to be anything dangerous about what you have done here, to delay merging?

**Comment by rdstern** [comment]
@lloyddewit you said you still have to make use of Rscript in your work.

One big failing in R-Instat is that when running a command from a dialog there is no way of stopping it without ctrl alt delete, which is drastic!

Might we be able to stop when running from a script?  This is [discussed here](https://stackoverflow.com/questions/69358524/what-function-to-interrupt-the-running-r-script)

Maybe I am dreaming too much!.

**Pull request merged**
