### PR TITLE
Rewriting dlgCorrelations in climatic

### PR DESCRIPTION
**Pull request by shadrackkibet**
@africanmathsinitiative/developers in progress.

### CODE REVIEW

**Comment by shadrackkibet** [comment]
I have two issues on the sdgcorrplot here:
1. Radiobuttons moving out of bounds of the panel.To get this error run the dialog and then reset then click on options the go to the subdialog .
2.I can't set the default as radiobutton -"None" on the panel because it is not passing any function so i can't set the Rcode for it.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is ready for review.

**Comment by AlexSananka** [comment]
Issues with this
1)when I click on rdotwocolumn and then then fill the recivers and save the results it does't save and when it does it bugs(it says x is missing with no default).
2)The ucrsave in the subdialog isn't saving as well.
3)Both of the above ucrsaves aren't reseting.

**Comment by lilyclements** [comment]
@shadrackkibet I am going to review this. Not sure how long the internet will last however! Can I make changes to this while I review?

**Comment by shadrackkibet** [comment]
i have fixed this issues now, i am going to push my comits now.

**Comment by lilyclements** [comment]
Great, push the commits. There are a few layout/designer/colon changes I need to make but I don't have long. If I don't make them in time I'll outline what needs to be done

**Comment by shadrackkibet** [comment]
@lilyclements  you can go on now.

**Comment by lilyclements** [comment]
made my changes which are waiting to be merged. Other changes I've just noticed:
* On the sub dialog, the contents in the second groupbox need to be aligned
* The checkbox "label" should have a capital "L"

Other than that and the resetting problem on the sub dialog, this is good. Once that's sorted this should be ready for Danny

**Comment by shadrackkibet** [comment]
@dannyparsons i have addressed the issues above by the reviewers. This is now ready for you.

**Comment by AlexSananka** [comment]
I have tested this dialog and it's working fine just two minor issues
1)the nud for label alpha isn't resetting
2)We do not need to save a plot when it's no plot since we do not have a plot hence I think we can hide ucrSave when you click on No Plot option

Just this two issues and it will be ready for @dannyparsons

**Comment by AlexSananka** [comment]
@dannyparsons This is ready for you to review

**Pull request merged**
