### PR TITLE
sdgComment

### PR DESCRIPTION
**Pull request by Patowhiz**
@maxwellfundi @dannyparsons can you merge this subdialog so that I can start work on it. It's meant to be part of the solution to issue #4825 Simple possible improvement to Comments field in dialogues.

@dannyparsons I have called it sdgComment, I hope that's okay with you. If not let me change it on this pull request.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
Please add controls on this so that we get the resource files generated then we get it merged

**Comment by Patowhiz** [comment]
I have added the comments but the resource file is not being created. The Localizable property of the form is also set as true

**Comment by maxwellfundi** [comment]
Great, now this looks good

**Comment by Patowhiz** [comment]
Great. Thanks

**Pull request merged**
