### PR TITLE
Improvements and tooltips for the calculator transform keyboard

### LINKED ISSUE #5554: Improvements and tooltips for the calculator transform keyboard
I think a reshape will be useful partly because there are 5 new keys to add.
1. There are currently 19 keys.  They all stay, but change the label on the key called **_ecdf to cumdist_**

2. A small edit is that when arguments are enabled the commands for movmax, movsum, movmean, movmed from the zoo package are incomplete.  There is a fill=NA, and align argument that should be added.   See the examples from the tooltips below.

3. Here is my proposed new layout (it has 24 keys, 2 a 4 by 6 array:
lag, lead, pmax, pmin
cummax, cumsum, cummean, cummin
movmax, movsum, movmean, movmed
movmin, diff,  ntile, cumdist
rrank, %rank, drank, mrank
nafill, naest, naapprox, naspline

4. There are 5 new keys, all from the zoo package.  The first is called movmin, but it is actually the zoo::movapply function (because there isn't a min.  (See the tooltip below).  I suggest you include the FUN=min in the command.  

5. I also propose you include the fill=NA argument, by default in all the commands from the **_movmax, movsum, movmean, movmed, and movmin_** keys.  (Unless this is there the resulting variables are shorter than the original variables.)  

6. The othernew keys are the na keys (nafill, etc above)  The corresponding functions zoo::na.fill, zoo::na.aggregate, (that's what I have called naest in the proposed keyboard layout) zoo::na.approx and zoo::na.spline.  (I had not noticed them before and they are potentially very useful and exciting for infilling missing values in the climatic data.  I will describe them in Chapter 8 of the climatic guide.)  

**_Tooltips_**
**_lag:_** Shift a variable down. For example lag(1:5) = (NA,1,2,3,4); lag(1:5,3) = (NA,NA,NA, 1,2)
**_lead_**: Shift a variable up.  For example lead(1:5) = (2,3,4,5,NA); lead(1:5;3) = (4,5, NA,NA,NA)
**_diff_**: difference between successive elements. For example diff(c(1,4,3,7)) = (NA 3,-1,4) 
**_pmax_**: maximum of a set of variables.  For examples pmax(c(1,3,5),c(6,4,2)) = (6,4,5)
**_pmin_**: minimum of a set of variables.  For examples pmin(c(1,3,5),c(6,4,2)) = (1,3,2)

**_cummax_**: cumulative maxima. For example cummax(c(3,2,1,4,0)) = (3,3,3,4,4)
**_movmax_**: moving (or rolling) maxima. For example rollmax(x=c(3,2,1,4,0) ,3,fill=NA, align="right") = (NA,NA, 3,4,4)
**_cumsum_**: cumulative sums. For example cumsum(c(3,2,1,4,0)) = (3,5,6,10,10)
**_cummean_**: cumulative means. For example cummean(c(3,2,1,4,0)) = (3,2.5,2,2.5,2)
**_cummin_**: cumulative minima. For example cummin(c(3,2,1,4,0)) = (3,2.,1,1,0)

**_movsum_**: moving (or rolling) totals. For example rollsum(c(3,2,1,4,0) ,3,fill=NA, align="left") = (6,7,5,NA,NA)
**_movmean_**: moving (or rolling) mean. For example rollmean(c(3,2,1,6,2) ,3,fill=NA) = (NA,2,3,3,NA)
**_movmed_**: moving (or rolling) medians. For example rollmedian(c(3,2,1,6,2) ,3,fill=NA) = (NA,2,2,2,NA)
**_movmin_**: moving (or rolling) minima. For example rollapply(c(3,2,1,6,2),width=3,fill=NA, FUN=min) = (NA,1,1,1,NA)
**_ntile_**: Use ranks to divide into (almost) equal sized groups.  For example ntile(c(15,11,13,12,NA,12),2) = (2,1,2,1,NA,1)
**_cumdist_**: Proportion of values less than or equal to the current rank. For example cume_dist(c(2,4,6,8,3)) = (0.2, 0.6, 0.8, 1.0, 0.4)
**_rrank_**: row numbers as ranks.  For example :row_number(c(15,11,13,12,NA,12)) = (5,1,3,2,NA,3)
**_%rank_**: rescale of minimum ranks to [0,1].  For example percent_rank(c(15,11,13,12,NA,12)) = (1,0,0.75,0.25,NA,0.25)
**_drank_**: dense ranks.  For example d_rank(c(15,11,13,12,NA,12)) = (4,1,3,2,NA,2)
**_mrank_** minimum ranks. For example m_rank(c(15,11,13,12,NA,12)) = (5,1,4,2,NA,2)
**_nafill_**: fills missing values at the start, middle and end. For example na.fill(c(NA,2,NA,4,5,NA),fill="extend") = (2,2,3,4,5,5); while fill=c(15,"extend",NA) = (15,2,3,4,5,NA)
**_na.approx_**: Linear interpolation of missing values.  For example na.approx(c(5,NA,NA,2,2,NA,4,7,NA),maxgap=1,na.rm=FALSE) = (5,NA,NA,2,2,3,4,7,NA)
**_na.spline_**: Spline interpolation of missing values.  For example na.spline(c(NA,NA,NA,2,2,NA,4,7,NA),maxgap=2,na.rm=FALSE) = (NA,NA,NA,2,2,2.5,4,7,12)
**_na.aggregate_**: Missing values as the mean (usually) overall or with a factor.  For example na.aggregate(c(NA,NA,NA,2,2,NA,4,7,NA),maxgap=2,na.rm=FALSE) = (NA,NA,NA,2,2,3.75,4,7,3.75)

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5554

@africanmathsinitiative/developers Someone to review this.

### CODE REVIEW

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers could someone review this, the designer doesn't look good from my  side. Some controls are hidden. Someone to review and see if this is true, so that I can work on them.

**Comment by rdstern** [comment]
@Wycklife I tried to look at your branch, but I can't get the calculator to work.  It crashes out of the programme when you use the calculate dialogue.  So I am afraid is is currently "above my pay grade".  I can't get as far as seeing the new keyboard.

**Comment by Wycklife** [comment]
@rdstern There are some inbuild errors that I am not able to fix, so I have to work on this again.

**Comment by Wycklife** [comment]
There are some inbuild errors that I am not able to fix, which affected the design, so I have to work on this again.
I'm therefore closing this pull request.

**Pull request closed without merging**
