### PR TITLE
Swapping sdgWindrose tabs

### PR DESCRIPTION
**Pull request by maxwellfundi**
@africanmathsinitiative/developers  This is ready for review

### CODE REVIEW

**Comment by dannyparsons** [comment]
is it ready for review then?

**Comment by maxwellfundi** [comment]
Yeah, its ready for review.
Regards
Maxwell Fundi
|| Phone :+254728508241||


Powered By  SalesHandy
<https://www.saleshandy.com/signup/?utm_source=gmail&utm_medium=emailfooter&utm_campaign=branding>

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers can someone quickly confirm this is okay, i need to merge it.

**Comment by maxwellfundi** [comment]
@dannyparsons  Am merging this because more work needs to go in to it. Thanks.

**Comment by rdstern** [comment]
That's great, because I am getting to that section in the guide.

**Pull request merged**
