### PR TITLE
Removed the bug in ucrSave and Made requested Changes

### PR DESCRIPTION
**Pull request by Patowhiz**
@africanmathsinitiative/developers @shadrackkibet @rdstern this is ready for review.
Addresses @shadrackkibet  [comment](https://github.com/africanmathsinitiative/R-Instat/pull/6230#discussion_r591590704)  and [comment](https://github.com/africanmathsinitiative/R-Instat/pull/6230#issuecomment-795612717)

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
This now seems ok.
@Patowhiz I also want to check that when I now fit a model I have available the last models.  When I fit a graph, the combo box also provides a list of the last graphs.
Has this always been there, or is it just added in your combo-box changes?  If it is just added, I note that it is very nice and we need to record this enhancement in the list of recent changes.

**Comment by Patowhiz** [comment]
@rdstern the code that is responsible for that feature is certainly not changed in this PR. I think the feature has always been there.

**Comment by lloyddewit** [comment]
@Patowhiz In PR #6230, @shadrackkibet wrote:

> Other two points in the calculator.
> 
>     * We do not need the colons in the save control?
> 
>     * The save control should reset properly i.e if the checkbox is unchecked then on reset it should be checked because that is the default state?

Did you also implement these requests?

**Comment by Patowhiz** [comment]
Yes

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
