### PR TITLE
Implemented A Wind/Pollution Rose dialog

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
Started a new dialog for Wind/Pollution Rose, added controls and implemented R Code for controls.
Added a wrapper for functions openair::windRose and openair::pollutionRose in stand_alone_functions.R

### CODE REVIEW

**Comment by HawardKetoyoMsatsi** [comment]
@africanmathsinitiative/developers @rdstern This is ready for review.
I have finished the dialog that Windrose/Pollution Rose.

Below is the data I used to test the dialog, the data should have the date coded in Climatic type "date" using the menu
Climatic> Dates>Make Date.

[notmydata.zip](https://github.com/africanmathsinitiative/R-Instat/files/5710050/notmydata.zip)

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi  was this wind/pollution rose from the structured > circular menu.  Because that isn't enabled for me.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern yes this is the dialog that had initially been worked on by @Ivanluv it is found under Structured > Circular > Wind/pollution Rose.
I was advised advised not to set the menu item properties (enabled and visible) to "True".
You could enable it from your end or  @dannyparsons @lloyddewit kindly advise me here, should I set the enabled and visible properties to True and include the frmMain changes for  in the same PR?

**Comment by lloyddewit** [comment]
> I was advised advised not to set the menu item properties (enabled and visible) to "True".
> You could enable it from your end or @dannyparsons @lloyddewit kindly advise me here, should I set the enabled and visible properties to True and include the frmMain changes for in the same PR?

@HawardKetoyoMsatsi Thank you for the changes and the question. You acted professionally and correctly in this PR. As you say, a menu item should not be enabled and visible until the functionality for that menu item is implemented. For this PR, please could you set the set the enabled and visible properties to True, so that this PR is ready for testing by @rdstern? 

In the longer term, we also need to minimise the risks of conflicts in frmMain. When, and in which PR, should we make the `frmMain` changes? It would be good to have a clear, consistent and well-communicated policy on this. I will ask @dannyparsons' advice.

**Comment by HawardKetoyoMsatsi** [comment]
Conflicts that were here have been resolved.
@rdstern Could you please have a look at this.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi Please could you resolve the current file conflict so that @rdstern can test? thanks

**Comment by HawardKetoyoMsatsi** [comment]
@lloyddewit , @rdstern suggested a few changes to be made to create only one dialog for this and four other pull requests submitter earlier. I am working on it, once done I will get this pull request closed.

**Comment by lloyddewit** [comment]
@HawardKetoyoMsatsi thanks for the updates. Are you still working on this PR or is it ready for review/test?

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi the main change I see is the use of facets.

I would prefer the control to be on the other side and called Facet (Optional): .  And it mainly is for us to include a facet variable ourselves, rather than to (only) use one of the inbuilt variables.

There is a question for @shadrackkibet  and @dannyparsons , because the dialogue permits up to 2 variables, e.g. station and season.  Good to either have space for 2 single controls or a multiple control.  But if multiple, then should b=we have a new control that permits up to 2 variables and no more?

Then I would like this to be merged, so it can be used and evaluated.  I am pretty sure there will be more and the need for a sub-dialogue at some stage?

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern I have made the requested changes. I made the dialog such that one can do crate facets using the Station variable or using built-in facet options.

wind_pollution_rose

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi many thanks. I'll check.  From looking at your picture, one small change is to put `Facet (Optional):` above the control and not next it.  Then the control could be wider and not so crammed at the side of the dialogue.

**Comment by rdstern** [comment]
@HawardKetoyoMsatsi this is progressing.  But I still have some puzzles and I have the feeling that you could usefully have been puzzling about these points, before asking others to look.  First the 2 changes I would like:
a) Can you allow any variable to be given in the date field, and not just the defined Date variable.  You see why below.
b) I can't enter my own variable in the Facet field.  I need to be able to do that.
c) It allows up to 2 facet variables.  As you now have plenty of space can you add `2nd Facet (Optional):` as well.  That would just have the variables to be entered, so not the drop-down list..  Again allow any variables for now.

Now my puzzle and one you could usefully also have considered.  I used the openair data, where I added my own variables and changed all the names.  I used a Date variable and then used the facet by Hour.  And it worked!  Now the puzzle - how did it work, i.e. how did it know the hours?

Well I had derived a variable called hour and I think it used that.  It looked for it in the data frame.  At least it didn't work when I deleted that variable.
I also tried (in the script file) changing the date variable to a date time variable - because the data are hourly.  Now it works again, even without the separate hour variable.
So, there is some nifty programming in openair "behind the scenes", but also dangerous for us, because it gives slightly unpredictable results depending on other variables that may be in the data frame, but not in the dialogue.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern @maxwellfundi @lloyddewit I have fixed issues raised by @rdstern concerning this PR. Kindly take a look.

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi this is looking promisisng, except I can test the facets.  The 2 controls are there.  I can go into them, but when I add a data column it goes instead into the station field.  This was empty.  
I am now not quite sure how the Station field will be used except to be a facet variable.
So I wonder if you could add the code that has recently been added to the PICSA rainfall graphs?  This assumes Station is likely to be a facet variable.  So I now suggest you treat the Station like that, and then have  your pull-down as the second faceting variable.  This could be as it is now, i.e. with the pull down options, but so it can have the focus and you can therefore type into it.

**Comment by rdstern** [comment]
Here is the current dialogue:
image

After discussions with @HawardKetoyoMsatsi I suggest the following:
a) The Station field is as now.  By default, if a Station field is declared (in the climatic menu), then the Station is included there.  But any other variable can be included instead from the data selector.
b) Under the Station control add a pull-down control similar to that for the Station field in the Climatic boxplots.  It is smaller, and perhaps aligned so the right of the station is lined  with it.  It has 3 options, namely None, Facet1 and Facet2.
c) Under that is the existing Facet 1 control. The label is changed to become Facet (Optional):  It is as now, except you can also include a variable there from the data selector.
d)  In the function call you can give up to 2 facet variables.  So, there are different cases.  1) If Station is None and Facet (Optional) is default, there are no facets.  2) If Station is None and the Facet is given, then that is the one facet variable  3) If Station is Facet 1 or Facet 2 and Facet Optional is Default, then  the Station is the one Facet variable.  4) If Station is Facet1 and Facet Optional is a facet, then then that is the first facet variable, and the Facet Optional variable is second.  5) Finally, if Station is Facet2 and Facet Optional is a facet, then it is first and the Station variable is second.     
e) The third filed, i.e. Facet 2 (Optional) label and control are deleted.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern I have fixed the above issues, please take a look.

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi this is looking promising.  But:
1) Could you change NONE, FACET 1, FACET 2, into None, Facet 1, Facet 2.
2) I still can't get the focus into the Facet optional control.  It should go turquise to signify I can put a variable into it.
3) Please check the clearing as well.  I put a variable into the Station  field and it nicely used it for facets.  Then I took it out, so that field was empty.  It still gave me those facets.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern the above issues have been fixed, kindly take a look at it.
On issue number 2. the control having turquise color to signify one can input a value: from my inquiry, I find out that it is available only for receivers. we may not be able to fix that by changing the color.

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi ok I understand.  
If possible, in the pull-down, the problem is that we usually use our own factors, not those provided by openair.  But it is nice to keep those options.  
a) Could you therefore add our factors from the data frame into the pull-down.  There is no problem if that includes station again.  Then a line and then the list there.
b) Could you delete site and dst from the current list in the pull-down.
If doing a) above is not trivial for you, then you could check with @shadrackkibet .  He may, at the same time, have comments about this suggestion.

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern Kindly have a look at the changes done. Faceting here resembles the other dialog from openair package.

**Review by rdstern — CHANGES_REQUESTED** [review]
@HawardKetoyoMsatsi this had build errors

**Comment by HawardKetoyoMsatsi** [comment]
@rdstern @lloyddewit This is an old PR that has frmMain changes in it. I will have to close this and open two PRs one with frmMain changes for enabling the menu and setting it to visible and another with Wind/Pollution Rose dialogue implementation.

**Pull request closed without merging**
