### PR TITLE
Added a method to a selector when data frame changes to Climatic>Check Data>QC Temperature

### LINKED ISSUE #5947: Problem with the quality contol for temperature dialogue
This is the first time I have used this dialogue with multiple data frames.  My example is not so easy to reproduce, but @dannyparsons says there must be an obvious error.  Here is the R-code:

```
grouping <- instat_calculation$new(type="by", calculated_from=list("lic"="station"))
largest_jump_tmax <- instat_calculation$new(type="calculation", function_exp="pmax(abs(Tmax - dplyr::lag(Tmax)), abs(Tmax - dplyr::lead(Tmax)), na.rm=TRUE)", calculated_from=list("ang"="Tmax","ang"="Tmin"), result_name="Jump_tmax")
largest_test_jump_tmax <- instat_calculation$new(type="calculation", function_exp="Jump_tmax > 12.0", sub_calculations=list(largest_jump_tmax), result_name="jump_tmax")
largest_jump_tmin <- instat_calculation$new(type="calculation", function_exp="pmax(abs(Tmin - dplyr::lag(Tmin)), abs(Tmin - dplyr::lead(Tmin)), na.rm=TRUE)", calculated_from=list("ang"="Tmax","ang"="Tmin"), result_name="Jump_tmin")
largest_test_jump_tmin <- instat_calculation$new(type="calculation", function_exp="Jump_tmin > 12.0", sub_calculations=list(largest_jump_tmin), result_name="jump_tmin")
filter_calculation <- instat_calculation$new(type="calculation", function_exp="jump_tmax | jump_tmin", calculated_from=list("ang"="Tmax","ang"="Tmin"), manipulations=list(grouping), sub_calculations=list(largest_test_jump_tmax , largest_jump_tmax , largest_test_jump_tmin , largest_jump_tmin), result_name="QC")
filtered_data <- instat_calculation$new(type="filter", function_exp="QC", calculated_from=list("ang"="Tmax","ang"="Tmin"), manipulations=list(grouping), sub_calculations=list(filter_calculation), save=2, result_data_frame="qcTemp")
data_book$run_instat_calculation(calc=filtered_data, display=FALSE)

rm(list=c("filtered_data", "grouping", "filter_calculation", "largest_test_jump_tmax", "largest_jump_tmax", "largest_test_jump_tmin", "largest_jump_tmin"))
```
The dialogue was as follows, and please notice that the data frame was for the station called `ang`.  I had earleir used the dialogue with another sheet called `lic`  and the first line of the code above is for lic.
image

I then did a reset on the dialogue and then made it again the same as above:  Then the code changed, but still gave the wrong results.   The new code was as follows, below.  When I pressed reset it defaulted to the data frame qcTemp7.  I changed the data frame to the correct one, but it still picked up the original one in the first line of the code below.  So is that line of code (or the station field, not recognising a change of data frame?

```
grouping <- instat_calculation$new(type="by", calculated_from=list("qcTemp7"="station"))
largest_jump_tmax <- instat_calculation$new(type="calculation", function_exp="pmax(abs(Tmax - dplyr::lag(Tmax)), abs(Tmax - dplyr::lead(Tmax)), na.rm=TRUE)", calculated_from=list("ang"="Tmax","ang"="Tmin"), result_name="Jump_tmax")
largest_test_jump_tmax <- instat_calculation$new(type="calculation", function_exp="Jump_tmax > 12.0", sub_calculations=list(largest_jump_tmax), result_name="jump_tmax")
largest_jump_tmin <- instat_calculation$new(type="calculation", function_exp="pmax(abs(Tmin - dplyr::lag(Tmin)), abs(Tmin - dplyr::lead(Tmin)), na.rm=TRUE)", calculated_from=list("ang"="Tmax","ang"="Tmin"), result_name="Jump_tmin")
largest_test_jump_tmin <- instat_calculation$new(type="calculation", function_exp="Jump_tmin > 12.0", sub_calculations=list(largest_jump_tmin), result_name="jump_tmin")
filter_calculation <- instat_calculation$new(type="calculation", function_exp="jump_tmax | jump_tmin", calculated_from=list("ang"="Tmax","ang"="Tmin"), manipulations=list(grouping), sub_calculations=list(largest_test_jump_tmax , largest_jump_tmax , largest_test_jump_tmin , largest_jump_tmin), result_name="QC")
filtered_data <- instat_calculation$new(type="filter", function_exp="QC", calculated_from=list("ang"="Tmax","ang"="Tmin"), sub_calculations=list(filter_calculation), manipulations=list(grouping), save=2, result_data_frame="qcTemp")
data_book$run_instat_calculation(calc=filtered_data, display=FALSE)

rm(list=c("filtered_data", "filter_calculation", "grouping", "largest_test_jump_tmax", "largest_jump_tmax", "largest_test_jump_tmin", "largest_jump_tmin"))
```
That field looks like the cause of the problem, because the data frame actually has only one station.  When I clear the Station field in the dialogue, then I get the right answers.

(By the way, this is an example where I suggest you may find (and correct) an obvious error in the code, but you won't be able to test it so easily).  Just tell me and I'll do the testing.

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5947 

@africanmathsinitiative/developers This is ready for review.

### CODE REVIEW

**Comment by Wycklife** [comment]
@rdstern Could you please check if this is now working.

**Comment by rdstern** [comment]
@Wycklife  there is still a problem here.  I give you my method of testing, so you can try to fix.  I think you may have fixed the one located earlier, but the general issue is still there.
This is how I am testing.
a) I open the Dodoma data from the Instat library - Climatic > Tanzania.  It is ready to use this dialogue.  It is defined as climatic, so the dialogue can be used directly.
b) I open the Ghana climatic data from 2 stations.  Not yet defined as climatic, so first use Climatic > Date > Fill Date Gaps and then Climatic > Date > Use Date, to get the year, month, day-in year, day in month
c) then define the Ghana data as climatic.
d) Now both are ready to the dialogue.
e) I think it doesn't matter which one you start with.  I started with Dodoma and used the Same checkbox.  Works fine.
f) Now moved to the ghana dataset which filled automatically.  Then did the same.  Gave an error, see below:

image

You notice there is a lot of Dodoma still in this set of command, and there should only be refewrence to the Ghana data set.

(I tried the same with the rainfall and it seems to work fine.)

**Comment by Wycklife** [comment]
@rdstern This is now fixed, could you please confirm?

**Review by rdstern — APPROVED** [review]
Excellent.  I tried switching between 2 files and this now seems to work fine.

**Review by rdstern — APPROVED** [review]
This dialogue had problems when a data frame was changed.  It now seems to work fine.  Over to @lloyddewit

**Review by lloyddewit — APPROVED** [review]

**Pull request merged**
