### PR TITLE
updating packages

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@africanmathsinitiative/developers Can someone test this? I'm getting a loader lock error every time I start but I can click continue and seems to work fine.

**Comment by dannyparsons** [comment]
@volloholic

**Comment by Lunalo** [comment]
Is this tested already ?

**Comment by lilyclements** [comment]
I'm not getting this error. Can someone else check on their computer as well?

**Comment by Lunalo** [comment]
@dannyparsons 

I have not come across that error . I have tried possible ways  to get the error but it has proved to be futile

**Comment by dannyparsons** [comment]
I'm still getting this issue but will merge it now and continue testing.

**Pull request merged**
