### PR TITLE
One Way Frequencies dialog.

### LINKED ISSUE #4946: Frequencies no longer works
I open our diamonds dataset from the library.  I am using the latest merged R-Instat.

I try Describe > Frequencies with any variable.  I now get:

**Error running R command(s)
Error in .subset2(x, i, exact = exact) : subscript out of bounds
The error occurred in attempting to run the following R command(s):
.temp_val <- capture.output(sjPlot::sjtab(data=data_book$get_columns_from_data(data_name="diamonds", col_names="table", force_as_data_frame=TRUE, remove_labels=TRUE, drop_unused_filter_levels=TRUE), show.summary=FALSE, digits=0, ignore.strings=FALSE, auto.grp.strings =FALSE))
OK**

### PR DESCRIPTION
**Pull request by shadrackkibet**
In Progress Fixes #4946

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@rdstern @dannyparsons  here is a screenshot of the current design.
image

**Comment by dannyparsons** [comment]
Let's have **Output** as the title for the groupbox. Then just **Text (Output Window)** and **HTML (Browser)** as options if both HTML options are the same.
I assume you tried call type = 4 and that didn't work?

**Comment by rdstern** [comment]
I would omit "to a viewer".  The idea is that the output window would be the viewer!

**Comment by dannyparsons** [comment]
ok that's a shame it doesn't work.

**Comment by shadrackkibet** [comment]
I now have only two additional options in the sub dialog as shown below.Is there any other option you would like added?

image

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers this is now ready for review.

**Comment by dannyparsons** [comment]
The main dialog has quite a lot of options already, so the sub dialog is ok I think.

**Comment by rdstern** [comment]
There is a package called **htmltools**.  Is there a chance that this could help putting the html output into our output window?

**Comment by shadrackkibet** [comment]
> There is a package called htmltools. Is there a chance that this could help putting the html output into our output window?

I am not sure if this can help. @dannyparsons  can confirm.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers ?

**Comment by maxwellfundi** [comment]
@Muthenya @Patowhiz @dannyparsons @jackykemboi  can you help test this.

**Comment by Muthenya** [comment]
This is looking and is working well.

**Pull request merged**
