### PR TITLE
Removed TopMost property

### LINKED ISSUE #4567: Setting for the Filter sub-dialogue
Is the setting for the filter sub-dialogue correct?
I am busy capturing screens and find that the Filter sub-dialogue insists on being on top whatever other application I move to, e.g. Powerpoint.  The other R-Instat dialogues seem more polite!

Is this a feature of all sub-dialogues or is this one just being too insistent?

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #4567 Setting for the Filter sub-dialogue .
@africanmathsinitiative/developers this is ready for review

### CODE REVIEW

**Comment by dannyparsons** [comment]
This isn't sufficient because we need to ensure that the sub dialog stays above the main dialog.

**Comment by maxwellfundi** [comment]
@Patowhiz  You can look at other properties of other sub dialogs and see how they work.

**Comment by Patowhiz** [comment]
They work in a similar way. That's all what is needed to achieve that
functionality

**Comment by dannyparsons** [comment]
What about the Date Options subdialog similar issue?

**Comment by Patowhiz** [comment]
I have removed also fixed the other subdialogs that also had this issue.
@africanmathsinitiative/developers  this is ready for review

**Comment by Muthenya** [comment]
This works fine. @dannyparsons this is ready for you.

**Pull request merged**
