### PR TITLE
Transform split bug fix

### PR DESCRIPTION
**Pull request by lilyclements**
@dannyparsons this is ready to review
I've addressed the issue of the developer error when reopening when a ucrInput has a different value inputted from specified in Initialise()

### CODE REVIEW

**Comment by AlexSananka** [comment]
Do we have changes for `dlgSplitText` here?
I can't see them.

**Comment by dannyparsons** [comment]
I worked on this and merged my branch directly. There were no changes on SplitText.

**Comment by AlexSananka** [comment]
working on this now

**Comment by AlexSananka** [comment]
I hope this was not merged in with this changes,some corrections need to be done with this.

**Comment by dannyparsons** [comment]
On which dialog? I thought you were working on Split? There were no changes to Split here.

**Comment by AlexSananka** [comment]
I mean changes on dlgtransformtext.

are they correct from this changes am seeing here?

**Comment by dannyparsons** [comment]
What do you mean are they correct?

**Comment by AlexSananka** [comment]
Sorry I just realised you made some changes before merging,everything is Ok now.

**Pull request merged**
