### PR TITLE
Execute Script window statement by statement rather than line by line

### PR DESCRIPTION
**Pull request by lloyddewit**
Fixes partially #7989.
Fixes partially #8533 (show R code comments in output window, new pipe operator and multi-line statement).
This change will make 'ctrl-enter' execute the R statement at the cursor (rather than just the line), this should fix the current bugs with multi-line statements.
I will first need to develop/release a new version of the RScript library that handles R key words (`if` statements, `for` loops etc.). This will not be trivial and may take a few weeks.
Ongoing, not yet ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
@lloyddewit I tried and it said there were build errors.  I synched the master, tried to load your branch again and got these messages:

image

You said it needed testing, so I was trying to do that.  Am I still too early, or doing something wrong here?

**Comment by lloyddewit** [comment]
@rdstern The commit message was just a personal reminder for me to test, it's not yet ready for you to test. Sorry for the confusion.
As you discovered, you can't build the changes in this PR yet because there are some merge conflicts and it needs a new version of the RScript library which I haven't released yet. I'll resolve these before I ask you to test.
When this PR is ready to test, then I'll take it out of draft status and ask you to test in a comment.
Thanks

**Comment by rdstern** [comment]
@lloyddewit that's an exciting addition!

**Comment by lloyddewit** [comment]
Replaced by PR #8551

**Pull request closed without merging**
