### PR TITLE
dlgCalculator & ucrCalculator.

### LINKED ISSUE #4125: Calculations - mainly Statistics keyboard
There are going to be a series of issues concerned with the calculator.  Perhaps Maxwell could propose one person who might concentrate on it.  Perhaps the work can start on this dialogue in 0.4.7 - which I have given as the current milestone.  But it is unlikely to finish then.  It also depends on the other tasks for AMI staff.

The first set - in this issue concerns the current Statistics keyboard.

1. Please could it be called **Summary** instead, both in the pull-down and also above the keyboard.
2. The keyboard is currently 3 columns of 4 rows.  Others are larger.  I now suggest **5 columns by 4 rows**.
3. **All the existing 12 items remain**, though I suggest in a different order.
4. Most of them use the default argument na.rm=FALSE.  So when there are any missing values the result is missing.  I suggest this should be changed to **na.rm=TRUE**.  
5. I think they all work, except quantile.  This has an additional argument names=TRUE.  It should change to **names=FALSE**.
6. The width of the buttons could change, so the full names can be on a single line.  This is currently not the case for **quantile**.
7. The button called count should change to say **length**.  The word count is perhaps clearer, but length is the command in R and we might as well use that when we can. 
8.  The common feature of this keyboard is that each button here produces a single summary value.  If it displays in the output window, or with the helpful Try feature in the dialogue we can see this.  When writing to a column it produces a column with this single value repeated.
9. It is a good time to add tool-tips.  I'll give them below.
10. The first column is then length (old count), non-miss (that's new and in our summary), miss (already there) and distinct (also new, it is the n_distinct function from dplyr.)
11. The second column is sum, mean, var, sd (all there now).
12. 11. The third column is max, median, min, range  (all there now).
13. The 4th column is cv, iqr, skew, anyDup, (iqr is there now, cv, and skew are all now part of the Summarise dialogue.  anyDup is short for anyDuplicated in the Data Table package and can be typed now.)
14. The fifth column is mad, mc, propn, quantile  (mad and mc are part of the summarise, quantile is there now and propn is new.)

So propn (proportion) is new.  It is the inverse of quantile.  For quantile you supply a value, e.g. 0.5 and it gives the corresponding value.  For example with 0.5 it gives the median.  For proportion you give the value, e.g. 10 and it gives the proportion.

It is described in the R discussions as coming from the ecdf function.  Calculated directly it is (I think) just mean(x= **column** <= **value**, na.rm = TRUE).  Put the default as 1 as the value, just as 0.5 is the default for the quantile.

The only other new one is the number of unique values in a column.  This is given by length(unique(x = **column**)).

### PR DESCRIPTION
**Pull request by shadrackkibet**
@africanmathsinitiative/developers I have make improvements to the calculator here. This fixes #4125,#4128 and #4126.

This is ready for review and testing.

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great, can you post screenshots? Then Roger can check them too

**Comment by shadrackkibet** [comment]
Here are the screenshots;

image

image
image
image
image
image
image

**Comment by rdstern** [comment]
They look great.  This is a big improvement.  Well done.
1. Maths: sign is higher than the rest in the key.  It should be sign.  Is it currently that and not sigin?
2. Logical and symbols.  I had not thought of having more keys below, but quite like the arrangement?  Interesting what others think.
3. In Logical have **between**, not Between.  Also (if you can keep the size, perhaps you can have **duplicated** in full, rather than duplic? 
4. In transform swap movsum and movmax.

**Comment by shadrackkibet** [comment]
@africanmathsinitiative/developers  this is still ready for review.

**Comment by shadrackkibet** [comment]
@dannyparsons this is ready for you to review.

**Comment by dannyparsons** [comment]
Can someone review and test all the new buttons add the correct commands?

**Comment by Patowhiz** [comment]
I'll test this

**Comment by Patowhiz** [comment]
@shadrackkibet how do I run something like sin(90 degrees) ? I have realised the sin,cos and tan function operate on radians

**Comment by shadrackkibet** [comment]
> @shadrackkibet how do I run something like sin(90 degrees) ? I have realised the sin,cos and tan function operate on radians

By default R give this in Radians .Mathematically, `1 degree =0.0174532925 radians`
so, just do this in the calculator; `sin(90*0.0174532925)` e.tc.

**Comment by Patowhiz** [comment]
@shadrackkibet  well my suggestion is, if possible a functionality that allows you to operate on degree directly. Such that internally you convert it to radians before passing it to R. This could be by checking for something like sin(90 degrees). The presence of degrees prompting the conversion even for columns.
Though this can be left as it is since the user can decide to have a column  that has degrees converted to radians then get a sin of that column.

**Comment by Patowhiz** [comment]
@shadrackkibet when I click on button IQR of the summary calculator the focus doesn't head to "x=<here>" in the expression IQR(x=, na.rm = TRUE, type =7). So in a case where I have column Size instead of the generated expression to be IQR(x=Size, na.rm = TRUE, type =7) , its IQR(xSize=, na.rm = TRUE, type =7). Seems like there is a problem with the next character to put cursor on

**Comment by dannyparsons** [comment]
There does seem to be a few R packages which have these conversion functions. But the conversion is so simple, `(deg * pi) / (180)`, I don't think we want to add a new package just for that. I hope we have `pi` in the calculator already? Then it's very easy.
If users are seriously using angle columns then we should encourage them to use radians since a lot of mathematical operations on angles only work when using radians. I don't think this will be very common for a stats package though.

**Comment by Patowhiz** [comment]
Yeah ,True. A tooltip or a help  explanation that explains your **(deg * pi) / (180)** conversion in performing the trigonometric functions will help the users

**Comment by Patowhiz** [comment]
@shadrackkibet when I click on button Try to run this command `stringr::str_locate(string= Village., pattern= 'SAB')` For caculator Strings. It gives me start end... as the output in the try textbox. Is this the expected behaviour or should it give me a concrete value like 1    3 . Not this works as expected when I click on Ok . 2 columns are generated, one with the start value and another with the end value.

**Comment by Patowhiz** [comment]
@shadrackkibet there is some inconsistency in the command generated for the following commands on the part of pattern=

- Button **Replace** generates - ` stringr::str_replace(string= ,pattern= ,replacement= )`

- Button **Locate** generates   -  `stringr::str_locate(string= , pattern= )`

- Button

 **Count** generates    -  `stringr::str_count(string= , pattern ='')`

- Button

 **Combine** generates -  `stringr::str_c(string= , pattern='')`

- Button **Detect** generates -  `stringr::str_detect(string= , pattern= )`

- Button **Split** generates - `stringr::str_split_fixed(string= , pattern='', n= )`

- Button **Extract** generates - `stringr::str_extract(string= , pattern= )`

Am not sure which is the best option between generating the commands with pattern='' or just pattern=
But I think it will be good UX to maintain consistency. 
However when applied with the right input the commands execute as expected.

**Comment by rdstern** [comment]
I am enjoying the discussions on this checking.  And this reminds me that we could spend some time next week on adding tooltips.

**Comment by Patowhiz** [comment]
@shadrackkibet Is the label **Strings (Character column)** meant to tell the user that the calculator is for columns **with** strings or is for columns of **type** character? Am curious to know why the extension "Character column"

Nevertheless I think all the commands generated in this calculator can operate even on factors and even numeric columns. I have tested this.

**Comment by Patowhiz** [comment]
@shadrackkibet I have only found the above issues. The rest appears to be okay to me.

**Comment by shadrackkibet** [comment]
ok. Will address some of this issues.Thanks .

**Comment by shadrackkibet** [comment]
> @shadrackkibet when I click on button IQR of the calculator Summary the focus doesn't head to "x=" in the expression IQR(x=, na.rm = TRUE, type =7). So in a case where I have column Size instead of the generated expression to be IQR(x=Size, na.rm = TRUE, type =7) , its IQR(xSize=, na.rm = TRUE, type =7). Seems like there is a problem with the next character to put cursor on.

@shadrackkibet there is also a similar problem when I click on button Propn

@shadrackkibet the button pad of calculator Strings seems to have a similar problem

@shadrackkibet the button pnom of calculator Probability seems to have a similar problem. Check also if the it gives the expected result when executed, am not sure about it.

@shadrackkibet the button movmax ntile movesum movmed movmean of calculator Transform seems to have a similar problem.

All this are working for me.... I noticed that the comma is close to the equal sign which makes it hard for the user to  insert the cursor after the equal sign. However i have moved the comma away so that at least it is clear to the user.

**Comment by Patowhiz** [comment]
Yeah that should sort out the focus issue

**Comment by shadrackkibet** [comment]
@Patowhiz i have sorted out some of the of the issues you raised above. This is ready for re-review.

**Comment by Patowhiz** [comment]
Will check

**Comment by shadrackkibet** [comment]
@Patowhiz  is this ready for @dannyparsons ?

**Comment by Patowhiz** [comment]
@dannyparsons The above issues have been addressed. @shadrackkibet I think this is ready

**Pull request merged**
