### PR TITLE
Designdlg column structures

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready to review.

Here I:
* Sorted the code layout
* Sorted the designer layout
* Increased functionality: If you uncheck "Colour Columns", your columns will uncolour

### CODE REVIEW

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is still waiting for review

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers I need someone to review this as soon as possible.

Presumably we want this in for Friday's release. If changes are needed here, I might not be able to make them in time if it's reviewed later in the week when I'm working on SSD stuff and also later in the week I imagine there will be more pull requests to get into the next beta release - so I'd like to review these! Earlier in the week, I'd have more time to make amendments to my current pull requests.

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is waiting for review.

**Comment by stevenndungu** [comment]
Reviewing this.

**Comment by lilyclements** [comment]
@dannyparsons this is ready to review.
@stevenndungu has made some useful changes which have now been merged in. Neither of us can see any further problems with this dialog

**Comment by stevenndungu** [comment]
Yap, It is working fine.

**Pull request merged**
