### PR TITLE
Added new humidity elements into the Define Climatic Dialog

### LINKED ISSUE #7971: Add new humidity elements into the Define Climatic Dialogue
[bohicon.zip](https://github.com/africanmathsinitiative/R-Instat/files/10058352/bohicon.zip)

I am adding a climatic dataset from Bohicon in Benin.  Just one year!
In the Define climatic data it would be useful if 2 more elements could be included, namely `Minimum RH (%)` and `Maximum RH (%)`.
Here is the current dialogue:
image
I suggest there is just room for these 2 elements is you start the Elements from right at the top of the existing dialogue, and then add the Humidity receivers at the bottom.

Then we would be able to define all the elements used in the Evapotranspiration dialogue.  The existing elements are added into that dialogue automatically and it will be good, when these are also included.

@N-thony I think you might quickly be able to do this?

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #7971 
@rdstern could you test? Thanks

### CODE REVIEW

**Review by rdstern — CHANGES_REQUESTED** [review]
@N-thony that's great.  I could approve now.
I just wonder if you could arrange for the receivers to be more lined up - perhaps move the station and dates down a little, so the 3 rows look well lined.  (Could be done differently perhaps - you are better than me on these design questions.)
Then I hope it might even get merged today if @lloyddewit is ok with the code.  Then @MeSophie could include the small change in the evapotranspiration dialogue, when she does the other small edits.

**Comment by N-thony** [comment]
> @N-thony that's great. I could approve now. I just wonder if you could arrange for the receivers to be more lined up - perhaps move the station and dates down a little, so the 3 rows look well lined. (Could be done differently perhaps - you are better than me on these design questions.) Then I hope it might even get merged today if @lloyddewit is ok with the code. Then @MeSophie could include the small change in the evapotranspiration dialogue, when she does the other small edits.

@rdstern have a look

**Review by rdstern — APPROVED** [review]
@N-thony perfect now.  I am not quite sure what you did, but it is neater than I expected.  @lloyddewit I hope this will be easy to check, so it can be merged.

**Comment by N-thony** [comment]
> @N-thony perfect now. I am not quite sure what you did, but it is neater than I expected. @lloyddewit I hope this will be easy to check, so it can be merged.

@rdstern with the data you have shared in the issue I have added year and month columns before defining it climatic and when you tried to define as climatic, you get the following bug from the R side. I have fixed it. Sorry I didn't run the dialogue before.
image

**Comment by N-thony** [comment]
@rdstern could you check again? :)

**Review by rdstern — APPROVED** [review]
@N-thony still fine, so @lloyddewit over to you.

**Pull request merged**
