### PR TITLE
Transform Climatic

### PR DESCRIPTION
**Pull request by lilyclements**
Update: @africanmathsinitiative/developers this is ready to review

### CODE REVIEW

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is ready to review

Here I have removed `bUserTyped = False` for two climatic dialogs

**Comment by maxwellfundi** [comment]
@shadrackkibet  could you please help review this?

**Comment by shadrackkibet** [comment]
Reviewing this.

**Comment by shadrackkibet** [comment]
When i type  my name in the ucrInput  and then reopen the dialog my name is lost. Do you want this dialog to behave that way?

**Comment by lilyclements** [comment]
No that is not intentional, which dialog is that on?

**Comment by shadrackkibet** [comment]
Both dialogs.

**Comment by lilyclements** [comment]
Okay I see. It is because the ucrInput name updates when the ucrReceiverElement changes and when we reopen the dialog, the ucrReceiverElement changes. Fixed it now so you can continue your review

**Comment by shadrackkibet** [comment]
@dannyparsons  this is ready for you to review.

**Pull request merged**
