### PR TITLE
Added a few keys to the circular keyboard and made the proposed changes 

### LINKED ISSUE #5332: Adding the circular mean, etc into R-Instat
I write this issue in detail.  I have added it (temporarily) to the first milestone to ensure a quick discussion on the strategy proposed below - rather than the programming.  And the results may be useful for a current MSc essay, which is one reason for the urgency.

I start with the circular mean - which is useful in its own right - later there should be a Circular keyboard for the calculator and a Circular tab for the **Prepare > Column: Reshape > Column Summaries**.  This could even start with the single calculation of the mean.

One question is whether we use a package, or write our own functions.  There are 2 packages for circular statistics, namely **circular** and **CircStats**.  They have lots of things, but neither seem ideal for the simple calculations.  Circular makes you define a new data type - which might be useful - that's a point for discussion.  CircStats is much simpler, but their function for the mean doesn't seem to include the adjustment na.rm=TRUE/FALSE to allow for missing values.

[Here](https://stackoverflow.com/questions/32404222/circular-mean-in-r) is an article on StackOverflow that explains what is happening and usefully discussed (and solves) what happens when the answer is negative!

And Wikipedia has a really simple example to try [here](https://en.wikipedia.org/wiki/Mean_of_circular_quantities). 

If we were to write our own functions, then I am sure we could get Sam to write them for us.

The example I have is in degrees, while the R functions work in radians.  The examples in Wikipedia are 10, 20, 30 degrees, with a mean of 20 degrees.  Then subtract 15 to give 355, 5, 15 and a mean of 5 degrees.

Here is the formula:

a) sinpart <- mean(sin(wd*2*pi/360),na.rm=TRUE)
b) cospart <- mean(cos(wd*2*pi/360),na.rm=TRUE)
Then: c) circmean=atan2(sinpart,cospart)*360/(2*pi)

We could presumably assume the data are in radians only?  We shouldn't fix on degrees, because the circle could also be 360 degrees, or 366 days, or 12 months, or 24 hours.  Perhaps our function could include a Units argument?

So I can now use **Prepare > Column: Calculations > Calculate** to get the circular mean.  Could I also use **Prepare > Column: Reshape > General Summaries** to get the means per day from hourly data, which is what I need now?

What should our strategy be.  I was assuming before that we will probably make good use of the circular (and possibly circstats) packages.  We may do, for the distributions and fitting parts.  But I am now wondering what is for the best for the summary statistics calculations?

### PR DESCRIPTION
**Pull request by Wycklife**
Fixes #5332

@africanmathsinitiative/developers Ready to be reviewed. Someone to review the changes.

### CODE REVIEW

**Comment by rdstern** [comment]
@Wycklife In the calculator, circular keyboard there is a further key to add. 

I wrote before - but well hidden!  
"The first key, circular has default code:
circular::circular( ,modulo= "2pi",units="radians")"

I think it could now become the last key, that just fills the set of 4 by 4.

**Comment by Wycklife** [comment]
@rdstern Should I add more parameters or just these two?

**Comment by Wycklife** [comment]
@rdstern I've made the proposed changes. I think it's now okay.

**Comment by Wycklife** [comment]
@africanmathsinitiative/developers Someone can review this

**Comment by rdstern** [comment]
ok.  I'll check now

**Comment by rdstern** [comment]
1. The first command circular: I think just the 2 arguments I have mentioned would be better.  I am checking it now.
In the first key - circular the default should be 
circular::circular(xxx,modulo="2pi")
Then, when you give the arguments, I think you have missed the quotes, e.g. "degrees".
Perhaps the default command (when arguments isn't ticked) could be given as:
circular::circular(xxx, modulo="2pi",units="radians")
Then it will be clear what a user should change if the data are in degrees or hours.

2. When the arguments are given, then for the mean you have (correctly) made na.rm = TRUE.  This needs to be done for all the other summaries.
3. The bottom row of keys doesn't work when the arguments checkbox is not ticked.  It needs the probs argument anyway so probs = 0 for the min, 0.25 for q1, 0.75 for q3 and 1 for the max.
4. It also needs to be added for the quantile key.
5. Lastly - the medianHL key needs to move down so it is in line with the others

**Comment by Wycklife** [comment]
@rdstern Thanks for the observation, I'm making the changes.

**Comment by Wycklife** [comment]
@rdstern I've implemented the changes, could you please have a look at them.

**Comment by rdstern** [comment]
They all look fine.  Can you just align the medianHL key label, so it is the same position as the other keys.  It is the top-right key.
Then it is ready for @dannyparsons to merge.
It looks very good.  Very well done for your work on this and also on the summaries tab.  I will now complete the chapter in the climatic guide.

**Comment by Wycklife** [comment]
@dannyparsons @rdstern Should I change na.rm =TRUE to default state?

**Comment by dannyparsons** [comment]
I've just commented here https://github.com/africanmathsinitiative/R-Instat/issues/5332#issuecomment-525840241. Sorry we're changing back again! 
Yes, please, we want the R default so we want `na.rm = FALSE`. Both for circular and summary keyboards.

**Comment by Wycklife** [comment]
@dannyparsons This has been implemented. Kindly have a look

**Comment by dannyparsons** [comment]
Great, can you also check the `na.rm` default in the normal summary keyboard? For example, Roger noticed mean had `na.rm = TRUE` which we now want as `FALSE`.

**Comment by Wycklife** [comment]
Okay

**Comment by Wycklife** [comment]
@dannyparsons This is now consistent, have a look

**Comment by maxwellfundi** [comment]
@dannyparsons  this seems ready for you.

**Pull request merged**
