### PR TITLE
Start of Rains

### PR DESCRIPTION
**Pull request by shadrackkibet**

### CODE REVIEW

**Comment by bethanclarke** [comment]
Is this ready for testing?

**Comment by shadrackkibet** [comment]
Yes you could review this.

One issue still remains, When Start day is missing , Date should be missing which i am yet to fix. Otherwise other issues are now sorted.

**Comment by bethanclarke** [comment]
Hi @shadrackkibet I was testing Dry Spell and I got this error

image

**Comment by bethanclarke** [comment]
I think you may need to add some additional code parameter pairs for the nud associated with check boxes: Number of rainy days, dray spell and dry period.

**Comment by shadrackkibet** [comment]
Thanks for testing this. I think `roll_sum_rain` calculation should not be there when you have Dry Spell  condition  only.

**Comment by shadrackkibet** [comment]
@bethanclarke above bug is now fixed. Please test it again.

**Comment by bethanclarke** [comment]
This dialog is working well now. Well done for fixing that issue. @dannyparsons this is ready for testing

**Pull request merged**
