### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by lloyddewit** [comment]
@N-thony If you (or your delegate) can do the French translations for this new text, then I can update the database, thanks

**Comment by lloyddewit** [comment]
@N-thony There are 23 new strings that need translation. I did the Russian translations (machine translation) because these are very useful for testing.
Please could you (or your delegate) do the French translations?
Thanks for all your help.

image

**Comment by N-thony** [comment]
> @N-thony There are 23 new strings that need translation. I did the Russian translations (machine translation) because these are very useful for testing. Please could you (or your delegate) do the French translations? Thanks for all your help.
> 
> image

@lloyddewit sure. @MeSophie can you do the French translations?

**Comment by lloyddewit** [comment]
@N-thony There are also some QA errors that may need checking.

image

image

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@N-thony Thank you for the translations. There were some translations waiting for approval. I approved these. The French QA issues also seem to be resolved.
When the new approvals appear in the JSON files, then I will merge this PR and update the database.

**Pull request merged**
