### PR TITLE
Script dialog menu item

### PR DESCRIPTION
**Pull request by Patowhiz**
Partly fixes issue #5986.
This PR adds a new menu item under the edit in the main form.
@shadrackkibet @lloyddewit please merge this so that @rdstern can test PR #6752.

### CODE REVIEW

**Comment by lloyddewit** [comment]
@Patowhiz I understand that if we merge this, then we will have a menu item that opens an empty dialog. This is not ideal on the master branch.
Is it possible to make the menu item invisible or at least disabled?
You could then pull these changes into PR #6752, and just make the menu item visible/enabled.
Is that practical?

**Review by rdstern — COMMENTED** [review]
@Patowhiz now I understand about the script being on the right.  That looks very neat.  I really like it, so far.

**Comment by Patowhiz** [comment]
@lloyddewit what if someone else adds another menu item on the main form? I think the designer and resource files may have conflicts.

With @rdstern we do intend to have a basic version of this dialog done and merged by end of this sprint. And I think we do have a basic version ready for testing in PR #6752.

Still, I can disable the menu item here, have it merged. Then create a separate PR from #6752 that will contain changes that @rdstern wants to test. That way I won't risk redoing PR #6752 afresh should there be conflicts at the form main, and @rdstern will do tests on that new PR. @lloyddewit do you prefer I proceed with this option? I

**Comment by Patowhiz** [comment]
@lloyddewit I have disabled the menu.

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet @rdstern If one of you approves then we can merge. @Patowhiz can then pull this PR's changes from main to PR #6752 and then enable the menu again for testing. This approach should minimise the risk of merge conflicts.
Thanks!

**Comment by Patowhiz** [comment]
@shadrackkibet @rdstern this needs to be reviewed and approved. It may have conflicts if not done early.

**Comment by shadrackkibet** [comment]
After reading through I still don't understand what's happening here. Either way, I approve and merge since @lloyddewit agrees.

**Review by shadrackkibet — APPROVED** [review]

**Review by rdstern — CHANGES_REQUESTED** [review]
@Patowhiz this is now merged, but the menu item is disabled

**Pull request merged**
