### PR TITLE
Improved dialog layouts for French text in dialogs from Describe menu, Model menu and other menus 

### PR DESCRIPTION
**Pull request by rachelkg**
I have been looking through the describe menu. I have checked up to the end of the Specific submenu but will continue working on the rest next week. Unresolved issues have been noted in the attached excel document. 

Thanks, 

Rachel 
[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6756957/R-Instat.translation.changes.xlsx)

### CODE REVIEW

**Comment by rachelkg** [comment]
I have now finished checking the French layout of the Describe menu, except for the Plot Options dialog which we agreed to do at the end as it is very complicated. 

The excel document with comments about the translation
[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6787488/R-Instat.translation.changes.xlsx) is attached. 

Finally I am not sure if this is normal but in Multivariate-Principle Component Analysis-PAC Options dialog the save tab was completely empty. This seemed odd so I thought I should mention it.

**Comment by rachelkg** [comment]
I have also finished the Model menu. I was not able to access the Display Options subdialog, but I am aware this has some layout issues and have created an issue to try to access this. 

I also found that a number of items in the Tidy submenu could not be opened (Other (one variable, Other (two variable...)

Please find the updated excel document attached.

**Comment by lloyddewit** [comment]
@rachelkg Thanks. Is this PR now ready for test/review/merge or do you still expect to make additional changes?

**Comment by rachelkg** [comment]
@lloyddewit I would like for it to be tested/reviewed and merged if possible. I will make changes as I receive comments from the review.

**Comment by lloyddewit** [comment]
@rdstern Please could you test?

@shadrackkibet These are layout changes so in theory only the 'designer' and 'resx' files are changed. In practice, some of the dialog class files are also changed because the Winform editor sometimes adds empty handlers. @rachelkg is changing many dialogs so it will be time consuming to remove these empty handlers again before merging. 
I'm personally willing to accept these empty handlers for now, we can always remove them later if/when we work on this dialog.
What's your view?

**Comment by shadrackkibet** [comment]
@lloyddewit I am volunteering to remove all the empty handlers. Once ready I can pull these changes and work on them and merge them into this PR or branch it through another PR.

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit I am volunteering to remove all the empty handlers. Once ready I can pull these changes and work on it and merge them into this PR or branch it through another PR.

@shadrackkibet Thank you for the offer.  If we remove the handlers form this PR then we should also remove them from PR #6557 and PR #6558. This could be significant work.
We could manually remove the handlers again. Or we could use Git to remove the dialog classes from these PRs (just leaving the 'resx' and 'designer' changes). This would need some research.

**Comment by rachelkg** [comment]
@lloyddewit is this empty handler issue something I am doing wrong in my editing process? Please feel free to correct my process if so.

**Comment by rachelkg** [comment]
@lloyddewit @shadrackkibet Is it something I am doing wrong in my process that is creating all these ‘empty handles’. Please say if I could be doing something differently moving forward.

**Comment by shadrackkibet** [comment]
@rachelkg This has to do with Visual Studio, sometimes it adds handlers automatically when you make designer changes.

I would suggest that you always check your changes in VS before committing. Since you are only doing layout changes then you should ensure that there are no `.vb` files in your commits. Whenever you make changes in VS you will see the changes under the Git changes Tab (See the screenshot)
image

If you see any `.vb` changes you can undo the changes by right-clicking on the file or use the undo arrow on the side.

image

I hope your VS setup looks similar to mine above and hopefully, this sheds some light.

**Comment by lloyddewit** [comment]
@shadrackkibet Thanks for the explanation. 
@rachelkg One small clarification: please don't undo changes to '.designer.vb' files. So in the example above, you should undo the changes to 'dlgCorrelation.vb' but **not** 'dlgCorrelation.designer.vb'.

**Comment by N-thony** [comment]
> @shadrackkibet I just noticed that empty handlers have also been added to PR #6543 .
> @N-thony Please see the discussion about empty handlers above

Thanks, @lloyddewit, I'm going to remove them all.

**Comment by rachelkg** [comment]
@lloyddewit @shadrackkibet Thanks for the explanation. I will look out for these moving forward.  

Sorry to have created extra work for people!

**Comment by lloyddewit** [comment]
> 
> 
> @lloyddewit @shadrackkibet Thanks for the explanation. I will look out for these moving forward.
> 
> Sorry to have created extra work for people!

@rachelkg Nothing to apologize for, you couldn't have known this and we didn't warn you!

**Comment by rachelkg** [comment]
Hi,

I have now finished checking the French layout of the menus, except for the Import dialog, The Calculator dialog  and the Plot Options dialog as they are either complicated and need further input or people are working on them. Please find the related excel document attached.

There are a few outstanding issues but I think it is ready to be checked and merged. 

Thanks, 

Rachel 


[R-Instat translation changes.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6826407/R-Instat.translation.changes.xlsx)

**Comment by lloyddewit** [comment]
@rachelkg Thank you for all your work! Before we merge, @shadrackkibet or I will remove the empty handlers.
Thank you also for the spreadsheet. This describes work we still need to do so I think it should be linked to an issue rather than this PR. I moved it to issue #6512 . If you want to update the spreadsheet further, then please could you ensure that issue #6512 always links to the latest spreadsheet version? thanks

**Comment by rdstern** [comment]
This could become long as I capture the screens sometimes to show a problem:
Describe > One Variable > Summarise - Label with to increase - word `Manquante i`s missing - how ironic!
image

While here I looked also at the summaries.  (The "master copy" is possibly with Prepare > Reshape Data > Column Summaries) 
 The word Missing is Missing again - top left.  And Range is translated as Plage (middle right).  I suggest `étendue`
image
On the next tab: the word `percentage` is missing towards the top.  For trimmed mean `moyenne tronquée `is suggested, and could we have `mesure de position `for location - it is currently Localisation.
And the circular tab should also have `mesure de position `for location.

Describe > One Variable > Graph.  Just 2 trivial points.  
image

Can the` Selected Variables `label be moved over, to line up on the left.  That will work for the English as well.
Ans, on a number of sub-dialogues I am getting the Lan button incomplete.  I don't know if that is a global thing, or has to be changed individually?

Describe > One Variable > Frequencies

image


Minor changes also needed in the English as well.  The label should be `Variables Selected `.  That's in English and then (I hope automatically changed in the French?
The label at the top is the translation for `One-way frequencies.`   I suggest we omit One-way in the English.  (It is in the menu section for a single variable already!  This can also be changed in English and French in the sub-dialogue heading.  
At the same time maybe the options button could be Frequency Options in English and Options de Frequences in French.
Finally the label for Descending Frequencies is incomplete - that's noted by @rachelkg in the Excel file  For Ascending it is `Frequences ascendantes` so could it instead be `Frequences Descendantes`.  Alternatively get rid of the word Frequencies in the English.  (This whole dialogue is about frequences, so just have Ascending and Descending!)

To be continued

**Comment by rachelkg** [comment]
@rdstern thanks for checking through this and all your comments. I am away this week but look forward to reviewing and fixing everything up when I get back. I will try to have a work day early in the week probably the 27th.

**Comment by rachelkg** [comment]
Hi @N-thony, 

Would you be able to look into resolving these conflicts please? @rdstern is going to discuss merging these with @shadrackkibet but if this could be done first that would be great. 

Thanks, 

Rachel

**Review by rdstern — APPROVED** [review]
@shadrackkibet approved as explained on @rachelkg other pull requests

**Comment by shadrackkibet** [comment]
I am afraid this PR now has conflicts in many files. Fixing conflicts in `.resx` and `designer.vb` is a bit tricky. We can try to resolve but I can't guarantee everything will be okay. Sorry, if it won't work then it means it has to be redone on a new branch. @lloyddewit what's your opinion on this?

**Comment by lloyddewit** [comment]
@rachelkg @shadrackkibet I removed the unecessary handler subs that were accidentally added to this PR. I used the commands below. For more explanation, please see PR #6557
```
git merge-base master pr/6580-french-layout-checked-for-the-describe-menu-onwards
git checkout b291378a89d0b0b251d890a8a0f18d0d40fd440c -- dlgBarAndPieChart.vb dlgColumnStats.vb dlgCorrelation.vb dlgGeneralForGraphics.vb dlgOneVarFitModel.vb dlgPrincipalComponentAnalysis.vb dlgScatterPlot.vb dlgSummaryTables.vb sdgMissingOptions.vb sdgOneWayFrequencies.vb sdgTwoWayFrequencies.vb
```
Note: I also had to undo some other changes in order to fix compilation errors:
```
git checkout b291378a89d0b0b251d890a8a0f18d0d40fd440c -- dlgOneWayFrequencies.Designer.vb
git checkout b291378a89d0b0b251d890a8a0f18d0d40fd440c -- sdgOneWayFrequencies.Designer.vb
```

**Review by rdstern — APPROVED** [review]

**Comment by lloyddewit** [comment]
> 
> 
> I am afraid this PR now has conflicts in many files. Fixing conflicts in `.resx` and `designer.vb` is a bit tricky. We can try to resolve but I can't guarantee everything will be okay. Sorry, if it won't work then it means it has to be redone on a new branch. @lloyddewit what's your opinion on this?

@shadrackkibet I agree. The only way to resolve the conflicts would be to manually edit the conflicting files. However, the conflicting files are automatically generated and editing them would be dangerous. I don't think we should do this. 

@rachelkg I'm afraid that you'll have to implement your changes to the conflicting dialogs and subdialogs again.
I suggest that you first review the changes you made to the affected dialogs in this PR. You may want to take some screenshots. When you've done this, please let me know. I will then remove the conflicting files from this PR and merge this PR.
Please make a new PR for your new updates.
If you have any questions, then please let me know.
Thanks and sorry for the extra work.

Future considerations:
I understand that you mainly work on Fridays. If possible, each Friday, you could try and make a new PR, that's ready for review. We could then merge it very quickly. This would reduce the risk of merge conflicts.

The (sub)dialogs affected are:

- dlgBoxPlot
- dlgCircular
- dlgHistogram
- dlgMerge
- dlgOptions
- dlgSummaryTables
- sdgCorrPlot
- sdgMissingOptions
- sdgPlots

**Comment by rachelkg** [comment]
Hi @lloyddewit and @shadrackkibet, 

Thanks for all your work on this.. Sorry it have got so messy. I have made a note of the dialogs and subdialogs that need to be redone and will do those this week. Please feel free to go ahead with the merge. 

re: "Future considerations: I understand that you mainly work on Fridays. If possible, each Friday, you could try and make a new PR, that's ready for review. We could then merge it very quickly. This would reduce the risk of merge conflicts." Thanks for this suggestion I will do this moving forward. I am going to try to work on Tuesdays and Wednesdays over the summer so will make PRs on Wednesdays. 

Thanks, 

Rachel

**Comment by N-thony** [comment]
> > I am afraid this PR now has conflicts in many files. Fixing conflicts in `.resx` and `designer.vb` is a bit tricky. We can try to resolve but I can't guarantee everything will be okay. Sorry, if it won't work then it means it has to be redone on a new branch. @lloyddewit what's your opinion on this?
> 
> @shadrackkibet I agree. The only way to resolve the conflicts would be to manually edit the conflicting files. However, the conflicting files are automatically generated and editing them would be dangerous. I don't think we should do this.
> 
> @rachelkg I'm afraid that you'll have to implement your changes to the conflicting dialogs and subdialogs again.
> I suggest that you first review the changes you made to the affected dialogs in this PR. You may want to take some screenshots. When you've done this, please let me know. I will then remove the conflicting files from this PR and merge this PR.
> Please make a new PR for your new updates.
> If you have any questions, then please let me know.
> Thanks and sorry for the extra work.
> 
> Future considerations:
> I understand that you mainly work on Fridays. If possible, each Friday, you could try and make a new PR, that's ready for review. We could then merge it very quickly. This would reduce the risk of merge conflicts.
> 
> The (sub)dialogs affected are:
> 
> * dlgBoxPlot
> * dlgCircular
> * dlgHistogram
> * dlgMerge
> * dlgOptions
> * dlgSummaryTables
> * sdgCorrPlot
> * sdgMissingOptions
> * sdgPlots

@lloyddewit just a question, I'm not sure and want your view. This PR has the changes up to 125 files, so it is a lot of work. I followed what you have done on PR #6557 about rolling back the affected files to the state they were in when PR #6557 was first branched. This effectively removes the changed files from PR #6557. So, is it possible to do the same here so that the files creating conflicts will be removed in this PR? Thanks.

**Review by rdstern — APPROVED** [review]
@lloyddewit can this now be merged, before the latest one-way frequencies one? (#6657)

**Comment by rachelkg** [comment]
I have now redone the changed to the conflicting dialogs in a new pull request, which I will put up at the end of the day. Please let me know if there is anything else you need from me to get this merged. 

Thanks, 

Rachel

**Comment by rachelkg** [comment]
I have now redone the changed to the conflicting dialogs in a new pull request, which I will put up at the end of the day. Please let me know if there is anything else you need from me to get this merged. 

Thanks, 

Rachel

**Comment by lloyddewit** [comment]
I removed the conflicting files from this PR with the following git commands:

$ git merge-base master pr/6580-french-layout-checked-for-the-describe-menu-onwards
$ git checkout b291378a89d0b0b251d890a8a0f18d0d40fd440c -- dlgBarAndPieChart.Designer.vb dlgBarAndPieChart.resx dlgBoxPlot.designer.vb dlgCircular.Designer.vb dlgColumnStats.Designer.vb dlgColumnStats.resx dlgHistogram.designer.vb dlgHistogram.resx dlgHistogram.vb dlgMerge.resx dlgOneVariableGraph.resx dlgOneWayFrequencies.resx dlgOptions.resx dlgRandomSample.resx dlgRestrict.resx dlgSummaryTables.Designer.vb dlgSummaryTables.resx sdgCorrPlot.resx sdgMissingOptions.Designer.vb sdgPlots.resx

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet Please could you approve and merge? thanks

**Review by shadrackkibet — APPROVED** [review]

**Pull request merged**
