### PR TITLE
Climatic sum#5698

### PR DESCRIPTION
**Pull request by Ivanluv**
@Patowhiz  would you kindly look at this.Related to issue #5698

### CODE REVIEW

**Comment by Patowhiz** [comment]
Checking this @Ivanluv

**Comment by maxwellfundi** [comment]
@Ivanluv  Are these the same changes on the #5697 ?

**Comment by Ivanluv** [comment]
@maxwellfundi No they are different

**Comment by maxwellfundi** [comment]
@Ivanluv  am closing this PR. It has lots of other changes. Please pen a new PR with the changes for the climatic summary only.

**Comment by Patowhiz** [comment]
Checking this

**Pull request closed without merging**
