### PR TITLE
Mainly improving the transform keyboard

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes issue #8958, 
@rdstern this is ready for review.

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@Fidel365 this looks really good.
Just one point: In rank with the arguments could it start with x=  and then the cursor before the comma, so the column can be entered.  This is where I entered fert below.

image

**Comment by Fidel365** [comment]
@rdstern I have made the changes requested.

**Review by rdstern — COMMENTED** [review]
@Fidel365 this looks really good.
Just one point: In rank with the arguments could it start with x=  and then the cursor before the comma, so the column can be entered.  This is where I entered fert below.

image

**Comment by Fidel365** [comment]
@rdstern I have made the changes requested and this is ready for review.

**Review by rdstern — APPROVED** [review]
@Fidel365 this now seems to work fine.  Thanks.  @N-thony pver to you.

**Pull request merged**
