### PR TITLE
Added translations for (sub)dialog tool tips

### PR DESCRIPTION
**Pull request by lloyddewit**
Partially fixes issue #3721
Translates tool tips associated with (sub)dialog controls. I still need to investigate tool bar tool tips.
@rdstern Please could you test? thanks
Please note that this PR includes a test database that 'translates' tool tips into French by adding 'fr'. I will create a separate PR for the real French CrowdIn translations.

@shadrackkibet Almost all the changes are in the [TranslateWinform Nuget package](https://github.com/lloyddewit/TranslateWinForm) so there is not much to review in this PR. You'll get an opportunity to review the Nuget package code in the coming weeks.

### CODE REVIEW

**Comment by rdstern** [comment]
This looks good.  I saw you solved your remaining issue of being able to add the translation to the calculation keyboard, which is where I started.
This showed (possibly) a potential problem for those translations.  The first is sqrt that is translated as racine.  The tooltip is `frsquare root.  For example sqrt(3) = 3 ^ 0.5 = 1.732`.

Another example is ceiling, translated as plafond.  The tooltip is `frInteger above the given value.  For example ceiling(3.5)=4, ceiling-3.5 = -3`  

In each case we want to translate the first part, but we don't want to translate the formulae.  So `ceiling` can be translated, but not `ceiling(` .  Or perhap[s nothing when the sentence has an = sign.

I then looked at the column summaries.  Here there isn't the fr and instead the translation is implemented - fine.

image

I like it.  Now the task is to use the tooltips more!

**Comment by lloyddewit** [comment]
@rdstern Thank you for the test. If you are happy with the mechanism, then please could you approve?

I think that all your comments above can be solved by the CrowdIn translations. So  moved these comments to issue #6512

**Review by rdstern — APPROVED** [review]

**Comment by lloyddewit** [comment]
@shadrackkibet please could you approve and merge? thanks

**Review by shadrackkibet — APPROVED** [review]

**Comment by shadrackkibet** [comment]
@lloyddewit **Translation (mechanism)** is part of the labels to be used in PRs? I thought we only use it for issues. This is the first PR with such a label.

**Pull request merged**
