### PR TITLE
Clean up for Column Summaries sdgs

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers this is ready to review

### CODE REVIEW

**Comment by shadrackkibet** [comment]
I don't think that is possible for our ucrInputtextboxes as at now . We might want to change this to an Nud for now?

**Comment by lilyclements** [comment]
Found a way to fix it by `SetValidationTypeAsNumericList(dcmMin:=0, dcmMax:=1)`

So the remaining bug is having two checkboxes controlling one input means that there is an issue in the inputs visibility when you check/uncheck the boxes. Can you think of an instance where we have one input being controlled by two checkboxes elsewhere or is this the first that this issue has come up?

**Comment by dannyparsons** [comment]
The percentile textbox is ok, the min/max values were needed
@shadrackkibet anything else?

**Comment by shadrackkibet** [comment]
checking this again.

**Pull request merged**
