### PR TITLE
Summary

### PR DESCRIPTION
**Pull request by shadrackkibet**
In progress!

### CODE REVIEW

**Comment by shadrackkibet** [comment]
@dannyparsons did you discuss with @rdstern the issue of mean function here? Do we need to have a separate function for Trimmed mean?

**Comment by dannyparsons** [comment]
I think what we need is to modify the column summaries function so that we can pass the trim argument to the correct mean function.

**Comment by shadrackkibet** [comment]
@dannyparsons  i think this can go in then we can come into the issue of trimmed mean later since we have an issue open at  #3845

**Comment by dannyparsons** [comment]
Yes that sounds good. I don't see any changes in the R code for the new `summary_skewness_mc` function. Or is it already a function there?

**Comment by shadrackkibet** [comment]
yep,`summary_skewness_mc` is already a function.

**Pull request merged**
