### PR TITLE
Random split dialog

### PR DESCRIPTION
**Pull request by mmulahvictor**
I have added the new Random Split dialog to the form main.
@shadrackkibet and @lloyddewit can you merge this for @rdstern to review PR #7272.

### CODE REVIEW

**Review by lloyddewit — APPROVED** [review]

**Comment by lloyddewit** [comment]
@mmulahvictor Thank you for this. I assume that 'my changes' means PR #7272, so I changed your comment to reference this PR (I suggest that we always specifically state which PR we're referring to).

@rdstern If you can approve, then we can merge. @mmulahvictor will then pull theses changes into PR #7272 and you can then test PR #7272.

Thanks!

**Comment by rdstern** [comment]
I get build errors

**Comment by lloyddewit** [comment]
@mmulahvictor Please could you resolve the merge conflicts?

@rdstern I can build this PR without any problems. 
Did you try 'Build/Rebuild Solution'?
If that doesn't solve it, then we could wait until @mmulahvictor has fixed the merge errors, and then look at the build problem in more detail.

**Comment by mmulahvictor** [comment]
@rdstern can you approve this so that I can look at the dialog.

**Comment by lloyddewit** [comment]
> @rdstern can you approve this so that I can look at the dialog.

@mmulahvictor This PR has merge conflicts. I suggest that you close this PR and make a new PR with these `frmMain` changes. I can merge the new PR quickly and you can pull the `frmMain` changes into PR #7272. @rdstern can then test the new dialog.
Does this make sense? or do you prefer a different approach?
Thanks

**Comment by mmulahvictor** [comment]
I am closing this PR due to merge conflicts

**Comment by mmulahvictor** [comment]
I am clossing this PR due to merge conflicts

**Pull request closed without merging**
